feat: add native addon to `cphase` API
stdlib-js/stdlib pull request #1004
Opened 2023-04-21 05:20 UTC by steff456

Part of https://github.com/stdlib-js/todo/issues/1454

## Description

> What is the purpose of this pull request?

This pull request:

-   Adds support for Complex128 dtype
-   Adds C implementation
-   Adds native addon with benchmark, tests, examples and readme update

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   Part of https://github.com/stdlib-js/todo/issues/1454

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2023-07-07 19:29 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cphase/README.md
> +#include "stdlib/math/base/special/cphase.h"
This example is not correct, as `cphase` returns a scalar value.

2023-07-07 19:29 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cphase/README.md
> +Computes the [argument][complex-number-argument] of a double-precision complex floating-point number.
Can you also update the main README description to use the `double-precision` language.

2023-07-07 19:31 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cphase/docs/repl.txt
>      Computes the argument of a complex number in radians.
Can you update the description here? Thanks!

2023-07-07 19:31 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cphase/docs/types/index.d.ts
>  * Computes the argument of a complex number in radians.
Can you update the description here? Thanks!

2023-07-07 19:32 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cphase/README.md
> +#include "stdlib/math/base/special/cphase.h"
See `example.c`.

2023-07-07 19:33 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cphase/README.md
>      re = round( randu()*100.0 ) - 50.0;
Can you replace with `random/base/uniform`?

2023-07-07 19:33 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cphase/examples/index.js
>  var round = require( '@stdlib/math/base/special/round' );
See comment in README.

2023-07-07 19:34 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cphase/include/stdlib/math/base/special/cphase.h
> +* Computes the argument of a complex number in radians.
Description.

2023-07-07 19:34 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cphase/lib/index.js
>  * @module @stdlib/math/base/special/cphase
Can you update the description here? Thanks!

2023-07-07 19:35 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cphase/lib/main.js
>  * Computes the argument of a complex number in radians.
Desc.

2023-07-07 19:35 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cphase/lib/main.js
> +* var phi = cphase( new Complex128( 5.0, 3.0 ) );
```suggestion
*
* var phi = cphase( new Complex128( 5.0, 3.0 ) );
```

2023-07-07 19:35 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cphase/lib/native.js
> +* Computes the argument of a complex number in radians.
Desc.

2023-07-07 19:35 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cphase/lib/native.js
> +* var phi = cphase( new Complex128( 5.0, 3.0 ) );
```suggestion
*
* var phi = cphase( new Complex128( 5.0, 3.0 ) );
```

2023-07-07 19:36 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cphase/lib/native.js
> +* var phi = cphase( new Complex128( 5.0, 3.0 ) );
cc @Planeshifter We should be able to create a lint rule for this, correct?

@steff456 Would you mind opening an internal todo for this? Thanks!

2023-07-07 19:37 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cphase/src/main.c
> +* Computes the argument of a complex number in radians.
Desc.

2023-07-07 19:37 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cphase/src/main.c
> +	return atan2( im, re );
```suggestion
	return atan2( im, re ); // TODO: replace with stdlib function once available
```

2023-07-07 19:39 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cpolar/lib/cpolar.js
> +	out[ 1 ] = cphase( new Complex128( re, im ) );
You can avoid duplicate creation of the complex number.

2023-07-07 19:40 UTC, kgryte requested changes
Thanks! Left a few comments.

2023-07-11 15:26 UTC, steff456 commented on lib/node_modules/@stdlib/math/base/special/cphase/lib/native.js
> +* var phi = cphase( new Complex128( 5.0, 3.0 ) );
For reference: https://github.com/stdlib-js/todo/issues/1657

2023-07-14 19:09 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cphase/README.md
>  # phase
```suggestion
# cphase
```

2023-07-14 19:10 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cphase/README.md
> +        printf( "fcphase(%lf + %lfi) = %lf\n", re, im, y );
```suggestion
        printf( "cphase(%lf + %lfi) = %lf\n", re, im, y );
```

2023-07-14 19:11 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cphase/docs/types/test.ts
> +// The function returns a double-precision complex floating-point number...
```suggestion
// The function returns a number...
```

2023-07-14 19:13 UTC, kgryte approved these changes
LGTM. Thanks, @steff456!

2023-07-14 19:21 UTC, merged