Added strided interface to fill a strided array with pseudorandom numbers drawn from a Laplace distribution.
stdlib-js/stdlib pull request #1008
Opened 2023-05-16 13:00 UTC by ShivangRawat30

…r of laplace

Resolves # .

## Description

> What is the purpose of this pull request?
Added strided interface to fill a strided array with pseudorandom numbers drawn from a Laplace distribution.

This pull request:

-   a
-   b
-   c

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #940
-   fixes #940

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [ ] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2023-05-16 16:30 UTC, Planeshifter requested changes
Thank you for your contribution!

There are a few documentation and copy-paste errors that need to be resolved before merging.

2023-05-16 16:30 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/laplace/README.md
> +# Beta Random Numbers
```suggestion
# Laplace Random Numbers
```

2023-05-16 16:30 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/laplace/README.md
> +> Fill a strided array with pseudorandom numbers drawn from a [laplace][@stdlib/random/base/laplace] distribution.
```suggestion
> Fill a strided array with pseudorandom numbers drawn from a [Laplace (double exponential)][@stdlib/random/base/laplace] distribution.
```

2023-05-16 16:30 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/laplace/README.md
> +Fills a strided array with pseudorandom numbers drawn from a [laplace][@stdlib/random/base/laplace] distribution.
```suggestion
Fills a strided array with pseudorandom numbers drawn from a [Laplace (double exponential)][@stdlib/random/base/laplace] distribution.
```

2023-05-16 16:30 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/laplace/package.json
> +  "description": "Fill a strided array with pseudorandom numbers drawn from a beta distribution.",
```suggestion
  "description": "Fill a strided array with pseudorandom numbers drawn from a Laplace (double exponential) distribution.",
```

2023-05-16 16:30 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/laplace/package.json
> +    "beta",
```suggestion
    "laplace",
```

2023-05-16 16:30 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/laplace/README.md
> +#### laplace( N, alpha, sa, beta, sb, out, so\[, options] )
Copy-paste error: Need to update distribution parameters here and elsewhere in the `README.md` from `alpha` and `beta` to `mu` (mean) and `b` (scale parameter) as in implementation.

2023-05-17 14:13 UTC, ShivangRawat30 commented
@Planeshifter Thanks for the input, I'll change them asap

2023-05-23 21:50 UTC, Planeshifter commented
Closing again as superseded by https://github.com/stdlib-js/stdlib/pull/1011.

2023-05-23 21:50 UTC, closed without merging