Strided interface for weibull distrbution #946
stdlib-js/stdlib pull request #1012
Opened 2023-05-21 06:56 UTC by amitjimiwal

Resolves #946 

## Adding support for filling a strided array with pseudorandom numbers drawn from a Weibull distribution. This is the strided interface analog of @stdlib/random/base/weibull.

## Related Issues
None

This pull request:

-   resolves #946 

## Questions

> Any questions for reviewers of this pull request?

Do lemme know if i interpreted wrong implementation

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2023-05-23 21:28 UTC, Planeshifter requested changes
Thanks for your PR!

Flagged a bunch of copy-paste and minor naming issues. Once these are addressed (easiest may be to batch commit the suggestions from the files tab), should be able to merge in.

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/package.json
> +  "description": "Fill a strided array with pseudorandom numbers drawn from a weibull distribution.",
```suggestion
  "description": "Fill a strided array with pseudorandom numbers drawn from a Weibull distribution.",
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/README.md
> +> Fill a strided array with pseudorandom numbers drawn from a [weibull][@stdlib/random/base/weibull] distribution.
```suggestion
> Fill a strided array with pseudorandom numbers drawn from a [Weibull][@stdlib/random/base/weibull] distribution.
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/README.md
> +Fills a strided array with pseudorandom numbers drawn from a [weibull][@stdlib/random/base/weibull] distribution.
```suggestion
Fills a strided array with pseudorandom numbers drawn from a [Weibull][@stdlib/random/base/weibull] distribution.
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/README.md
> +-   **sa**: index increment for `alpha`.
```suggestion
-   **sk**: index increment for `k`.
```

Let's make sure to rename the `sa` parameter everywhere to `sk`.

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/README.md
> +-   **sb**: index increment for `beta`.
```suggestion
-   **sl**: index increment for `lambda`.
```

Let's make sure to rename the `sb` parameter everywhere to `sl`.

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/README.md
> +-   **ob**: starting index for `alpha`.
```suggestion
-   **ol**: starting index for `lambda`.
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/README.md
> +-   **oa**: starting index for `k`.
```suggestion
-   **ok**: starting index for `k`.
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/lib/ndarray.js
> +* @param {integer} sa - `k` stride length
```suggestion
* @param {integer} sk - `k` stride length
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/lib/ndarray.js
> +* @param {NonNegativeInteger} oa - starting `k` index
```suggestion
* @param {NonNegativeInteger} ok - starting `k` index
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/lib/ndarray.js
> +* @param {integer} sb - `lambda` stride length
```suggestion
* @param {integer} sl - `lambda` stride length
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/lib/ndarray.js
> +* @param {NonNegativeInteger} ob - starting `lambda` index
```suggestion
* @param {NonNegativeInteger} ol - starting `lambda` index
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/lib/main.js
> +* @param {integer} sa - `k` stride length
```suggestion
* @param {integer} sk - `k` stride length
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/lib/main.js
> +* @param {integer} sb - `lambda` stride length
```suggestion
* @param {integer} sk - `lambda` stride length
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/docs/types/index.d.ts
> +	* @param sa - `alpha` stride length
```suggestion
	* @param sk - `k` stride length
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/docs/types/index.d.ts
> +	* Fills a strided array with pseudorandom numbers drawn from a weibull distribution.
```suggestion
	* Fills a strided array with pseudorandom numbers drawn from a weibull distribution.
```
```suggestion
	* Fills a strided array with pseudorandom numbers drawn from a Weibull distribution.
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/docs/types/index.d.ts
> +	* @param sb - `weibull` stride length
```suggestion
	* @param sl - `lambda` stride length
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/docs/types/index.d.ts
> +	* Fills a strided array with pseudorandom numbers drawn from a weibull distribution using alternative indexing semantics.
```suggestion
	* Fills a strided array with pseudorandom numbers drawn from a Weibull distribution using alternative indexing semantics.
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/docs/types/index.d.ts
> +	* @param sa - `k` stride length
```suggestion
	* @param sk - `k` stride length
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/docs/types/index.d.ts
> +	* @param oa - starting index for `k`
```suggestion
	* @param ok - starting index for `k`
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/docs/types/index.d.ts
> +	* @param sb - `lambda` stride length
```suggestion
	* @param sl - `lambda` stride length
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/docs/types/index.d.ts
> +	* @param ob - starting index for `lambda`
```suggestion
	* @param ol - starting index for `lambda`
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/docs/types/index.d.ts
> +	ndarray( N: number, k: Collection, sa: number, oa: number, lambda: Collection, sb: number, ob: number, out: Collection, so: number, oo: number, options?: Options ): Collection; // tslint:disable-lin
```suggestion
	ndarray( N: number, k: Collection, sk: number, ok: number, lambda: Collection, sl: number, ol: number, out: Collection, so: number, oo: number, options?: Options ): Collection; // tslint:disable-line:max-line-length
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/docs/types/index.d.ts
> +* Fills a strided array with pseudorandom numbers drawn from a weibull distribution.
```suggestion
* Fills a strided array with pseudorandom numbers drawn from a Weibull distribution.
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/docs/types/index.d.ts
> +* @param sa - `k` stride length
```suggestion
* @param sk - `k` stride length
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/docs/types/index.d.ts
> +* @param sb - `lambda` stride length
```suggestion
* @param sl - `lambda` stride length
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/docs/types/index.d.ts
> +	( N: number, k: Collection, sa: number, lambda: Collection, sb: number, out: Collection, so: number, options?: Options ): Collection; // tslint:disable-line:max-line-length
```suggestion
	( N: number, k: Collection, sk: number, lambda: Collection, sl: number, out: Collection, so: number, options?: Options ): Collection; // tslint:disable-line:max-line-length
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/docs/repl.txt
> +    Fills a strided array with pseudorandom numbers drawn from a weibull
```suggestion
    Fills a strided array with pseudorandom numbers drawn from a Weibull
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/docs/repl.txt
> +{{alias}}( N, k, sa, lambda, sb, out, so[, options] )
```suggestion
{{alias}}( N, k, sk, lambda, sl, out, so[, options] )
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/docs/repl.txt
> +    sa: integer
```suggestion
    sk: integer
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/docs/repl.txt
> +        Index increment for `alpha`.
```suggestion
        Index increment for `k`.
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/docs/repl.txt
> +    sb: integer
```suggestion
    sl: integer
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/docs/repl.txt
> +        Index increment for `beta`.
```suggestion
        Index increment for `lambda`.
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/docs/repl.txt
> +{{alias}}.ndarray( N, k, sa, oa, lambda, sb, ob, out, so, oo[, options] )
```suggestion
{{alias}}.ndarray( N, k, sk, ok, lambda, sl, ol, out, so, oo[, options] )
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/docs/repl.txt
> +    sa: integer
```suggestion
    sk: integer
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/docs/repl.txt
> +        Index increment for `alpha`.
```suggestion
        Index increment for `k`.
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/docs/repl.txt
> +    oa: integer
```suggestion
    ok: integer
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/docs/repl.txt
> +        Starting index for `alpha`.
```suggestion
        Starting index for `k`.
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/docs/repl.txt
> +    sb: integer
```suggestion
    sl: integer
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/docs/repl.txt
> +        Index increment for `beta`.
```suggestion
        Index increment for `lambda`.
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/docs/repl.txt
> +    ob: integer
```suggestion
    ol: integer
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/docs/repl.txt
> +        Starting index for `beta`.
```suggestion
        Starting index for `lambda`.
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/lib/index.js
> +* Fill a strided array with pseudorandom numbers drawn from a weibull distribution.
```suggestion
* Fill a strided array with pseudorandom numbers drawn from a Weibull distribution.
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/lib/main.js
> +* Fills a strided array with pseudorandom numbers drawn from a beta distribution.
```suggestion
* Fills a strided array with pseudorandom numbers drawn from a Weibull distribution.
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/lib/ndarray.js
> +function weibull( N, k, sa, oa, lambda, sb, ob, out, so, oo, options ) { // eslint-disable-line max-params
```suggestion
function weibull( N, k, sk, ok, lambda, sl, ol, out, so, oo, options ) { // eslint-disable-line max-params
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/lib/ndarray.js
> +	var rand = prng( k, sa, oa, lambda, sb, ob, arguments.length > 10, options ); // eslint-disable-line max-len
```suggestion
	var rand = prng( k, sk, ok, lambda, sl, ol, arguments.length > 10, options ); // eslint-disable-line max-len
```

2023-05-23 21:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/lib/ndarray.js
> +	binary( [ k, lambda, out ], [ N ], [ sa, sb, so ], [ oa, ob, oo ], rand.fcn ); // eslint-disable-line max-len
```suggestion
	binary( [ k, lambda, out ], [ N ], [ sk, sl, so ], [ ok, ol, oo ], rand.fcn ); // eslint-disable-line max-len
```

2023-05-23 21:31 UTC, Planeshifter requested changes

2023-05-23 21:31 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/README.md
> +#### beta( N, k, sa, lambda, sb, out, so\[, options] )
```suggestion
#### weibull( N, k, sk, lambda, sl, out, so\[, options] )
```

2023-05-23 21:31 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/README.md
> +#### weibull.ndarray( N, k, sa, oa, lambda, sb, ob, out, so, oo\[, options] )
```suggestion
#### weibull.ndarray( N, k, sk, ok, lambda, sl, ol, out, so, oo\[, options] )
```

2023-05-23 21:31 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/README.md
> +Fills a strided array with pseudorandom numbers drawn from a [weibull][@stdlib/random/base/weibull] distribution using alternative indexing semantics.
```suggestion
Fills a strided array with pseudorandom numbers drawn from a [Weibull][@stdlib/random/base/weibull] distribution using alternative indexing semantics.
```

2023-05-23 21:31 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/lib/main.js
> +function weibull( N, k, sa, lambda, sb, out, so, options ) {
```suggestion
function weibull( N, k, sk, lambda, sl, out, so, options ) {
```

2023-05-23 21:31 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/lib/main.js
> +	var rand = prng( k, sa, 0, lambda, sb, 0, arguments.length > 7, options );
```suggestion
	var rand = prng( k, sk, 0, lambda, sl, 0, arguments.length > 7, options );
```

2023-05-23 21:31 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/lib/main.js
> +	binary( [ k, lambda, out ], [ N ], [ sa, sb, so ], rand.fcn );
```suggestion
	binary( [ k, lambda, out ], [ N ], [ sk, sl, so ], rand.fcn );
```

2023-05-23 21:31 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/lib/ndarray.js
> +* Fills a strided array with pseudorandom numbers drawn from a weibull distribution.
```suggestion
* Fills a strided array with pseudorandom numbers drawn from a Weibull distribution.
```

2023-05-23 21:33 UTC, Planeshifter requested changes

2023-05-23 21:33 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/docs/repl.txt
> +        shape parameter.
```suggestion
        Shape parameter.
```

2023-05-23 21:33 UTC, Planeshifter commented on lib/node_modules/@stdlib/random/strided/weibull/docs/repl.txt
> +        scale parameter.
```suggestion
        Scale parameter.
```

2023-05-24 09:18 UTC, amitjimiwal commented
> Thanks for your PR!
> 
> Flagged a bunch of copy-paste and minor naming issues. Once these are addressed (easiest may be to batch commit the suggestions from the files tab), should be able to merge in.

Will do the required changes. Thanks for the review @Planeshifter

2023-05-28 10:44 UTC, amitjimiwal commented
@Planeshifter   Requested Chnages are resolved.
Pls review

2023-05-29 02:13 UTC, merged

2023-05-29 02:14 UTC, Planeshifter commented
Thank you. There were a few more copy-paste errors to be resolve (see above commits), but your PR has now landed!

2023-05-29 06:01 UTC, amitjimiwal commented
Thanks @Planeshifter .