feat: add string/base/distances/levenshtein
stdlib-js/stdlib pull request #1030
Opened 2023-06-03 10:20 UTC by Infinage

Resolves #835.

## Description

> What is the purpose of this pull request?

This pull request:

-   Implements the RFC proposal for implementing function to calculate the Levenshtein (edit) distance between two strings.

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #835 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2023-06-03 10:47 UTC, Planeshifter requested changes
Thanks for the PR! Only a few minor things need to be addressed.

2023-06-03 10:47 UTC, Planeshifter commented on lib/node_modules/@stdlib/string/base/distances/README.md
> +var string = require( '@stdlib/string/base/distances' );
Let's name the variable distances here and below in the namespace `README.md`.

2023-06-03 10:47 UTC, Planeshifter commented on lib/node_modules/@stdlib/string/base/distances/docs/types/index.d.ts
> +    * @returns levenshtein distance
```suggestion
    * @returns Levenshtein distance
```

2023-06-03 10:47 UTC, Planeshifter commented on lib/node_modules/@stdlib/string/base/distances/examples/index.js
> +// Calculates the levenshtein (edit) distance between two input strings...
```suggestion
// Calculates the Levenshtein (edit) distance between two input strings...
```

2023-06-03 10:47 UTC, Planeshifter commented on lib/node_modules/@stdlib/string/base/distances/levenshtein/docs/types/index.d.ts
> +* @returns levenshtein distance
```suggestion
* @returns Levenshtein distance
```

2023-06-03 10:47 UTC, Planeshifter commented on lib/node_modules/@stdlib/string/base/distances/levenshtein/lib/main.js
> +* @throws {TypeError} both arguments provided must be a string
```suggestion
* @throws {TypeError} first argument must be a string
* @throws {TypeError} second argument must be a string
```

2023-06-03 10:47 UTC, Planeshifter commented on lib/node_modules/@stdlib/string/base/distances/levenshtein/lib/main.js
> +* @returns {number} levenshtein distance
```suggestion
* @returns {number} Levenshtein distance
```

2023-06-03 10:47 UTC, Planeshifter commented on lib/node_modules/@stdlib/string/base/distances/levenshtein/lib/main.js
> +	// If either of the string is empty, insert the characters
```suggestion
	// If either of the strings is empty, insert the characters:
```

2023-06-03 10:47 UTC, Planeshifter commented on lib/node_modules/@stdlib/string/base/distances/levenshtein/test/test.js
> +
A few unit tests are missing for full code coverage. Should add tests for invalid inputs (see e.g. `@stdlib/string/substring-after` for a function with two string parameters).

2023-06-03 10:59 UTC, Infinage commented
Thanks for the quick review! Had a minor query - post making these changes, should I do a squash and force push these changes or do you want me to retain the commit history?

2023-06-03 11:38 UTC, Infinage commented
@Planeshifter - I have force pushed with the requested changes. Could you please approve it if everything looks good? Thanks!

2023-06-03 19:56 UTC, Planeshifter requested changes

2023-06-03 19:56 UTC, Planeshifter commented on lib/node_modules/@stdlib/string/base/distances/levenshtein/docs/types/index.d.ts
> +* Copyright (c) 2022 The Stdlib Authors.
```suggestion
* Copyright (c) 2023 The Stdlib Authors.
```

2023-06-03 19:56 UTC, Planeshifter commented on lib/node_modules/@stdlib/string/base/distances/levenshtein/docs/types/test.ts
> +* Copyright (c) 2022 The Stdlib Authors.
```suggestion
* Copyright (c) 2023 The Stdlib Authors.
```

2023-06-03 19:56 UTC, Planeshifter commented on lib/node_modules/@stdlib/string/base/distances/levenshtein/examples/index.js
> +* Copyright (c) 2022 The Stdlib Authors.
```suggestion
* Copyright (c) 2023 The Stdlib Authors.
```

2023-06-03 19:56 UTC, Planeshifter commented on lib/node_modules/@stdlib/string/base/distances/test/test.js
> +* Copyright (c) 2022 The Stdlib Authors.
```suggestion
* Copyright (c) 2023 The Stdlib Authors.
```

2023-06-03 19:56 UTC, Planeshifter commented on lib/node_modules/@stdlib/string/base/distances/lib/index.js
> +* Copyright (c) 2022 The Stdlib Authors.
```suggestion
* Copyright (c) 2023 The Stdlib Authors.
```

2023-06-03 19:56 UTC, Planeshifter commented on lib/node_modules/@stdlib/string/base/distances/levenshtein/lib/index.js
> +* Copyright (c) 2022 The Stdlib Authors.
```suggestion
* Copyright (c) 2023 The Stdlib Authors.
```

2023-06-03 19:56 UTC, Planeshifter commented on lib/node_modules/@stdlib/string/base/distances/levenshtein/lib/main.js
> +* Copyright (c) 2018 The Stdlib Authors.
```suggestion
* Copyright (c) 2023 The Stdlib Authors.
```

2023-06-03 19:56 UTC, Planeshifter commented on lib/node_modules/@stdlib/string/base/distances/examples/index.js
> +* Copyright (c) 2022 The Stdlib Authors.
```suggestion
* Copyright (c) 2023 The Stdlib Authors.
```

2023-06-03 19:56 UTC, Planeshifter commented on lib/node_modules/@stdlib/string/base/distances/docs/types/test.ts
> +* Copyright (c) 2022 The Stdlib Authors.
```suggestion
* Copyright (c) 2023 The Stdlib Authors.
```

2023-06-03 19:56 UTC, Planeshifter commented on lib/node_modules/@stdlib/string/base/distances/docs/types/index.d.ts
> +* Copyright (c) 2022 The Stdlib Authors.
```suggestion
* Copyright (c) 2023 The Stdlib Authors.
```

2023-06-03 19:56 UTC, Planeshifter commented on lib/node_modules/@stdlib/string/base/distances/README.md
> +Copyright (c) 2022 The Stdlib Authors.
```suggestion
* Copyright (c) 2023 The Stdlib Authors.
```

2023-06-03 20:00 UTC, Planeshifter approved these changes

2023-06-03 20:06 UTC, Planeshifter approved these changes

2023-06-03 20:08 UTC, merged

2023-06-03 20:08 UTC, Planeshifter commented
Package has landed!

2023-06-04 00:04 UTC, Infinage commented
Truly elated I could help! Thank you!