feat: add iter/while-each
stdlib-js/stdlib pull request #1180
Opened 2023-12-13 12:18 UTC by Jaysukh-409

Resolves #810.

## Description

> What is the purpose of this pull request?

This pull request:

-   Create an iterator which, while a test condition is true, invokes a function for each iterated value before returning the iterated value.

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #810 

## Questions

> Any questions for reviewers of this pull request?

I have added lib and examples for the whileEach iterator. Please review and provide feedback accordingly.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2023-12-15 04:33 UTC, kgryte commented on lib/node_modules/@stdlib/iter/while-each/README.md
> +# whileEach Iterator
```suggestion
# iterWhileEach
```

2023-12-15 04:35 UTC, kgryte commented on lib/node_modules/@stdlib/iter/while-each/README.md
> +Returns an iterator which invokes a `function` for each iterated value untill either a `predicate` returns `false` or the function has iterated over all value **before** returning the iterated value.
```suggestion
Returns an iterator which invokes a function for each iterated value **before** returning the iterated value until either a `predicate` function returns `false` or the iterator has iterated over all values.
```

2023-12-15 04:36 UTC, kgryte commented on lib/node_modules/@stdlib/iter/while-each/README.md
> +-   **next**: function which returns an iterator protocol-compliant object containing the next iterated value (if one exists) assigned to a `value` property and a `done` property having a `boolean` v
```suggestion
-   **next**: function which returns an iterator protocol-compliant object containing the next iterated value (if one exists) assigned to a `value` property and a `done` property having a boolean value indicating whether the iterator is finished.
```

2023-12-15 04:36 UTC, kgryte commented on lib/node_modules/@stdlib/iter/while-each/README.md
> +The invoked `function` is provided two arguments:
```suggestion
The invoked function is provided two arguments:
```

2023-12-15 04:36 UTC, kgryte commented on lib/node_modules/@stdlib/iter/while-each/README.md
> +-   `index`: iteration index (zero-based)
```suggestion
-   **value**: iterated value
-   **index**: iteration index (zero-based)
```

2023-12-15 04:42 UTC, kgryte commented on lib/node_modules/@stdlib/iter/while-each/README.md
> +}
```suggestion
function assert( v, i ) {
    if ( i > 1 ) {
        throw new Error( 'unexpected error' );
    }
}
```

I see that `iter/for-each` has a similar example, which does not actually illustrate anything new. Here, we at least want to show that provided functions are invoked with multiple arguments.

2023-12-15 04:43 UTC, kgryte commented on lib/node_modules/@stdlib/iter/while-each/README.md
> +}
Once this PR is merged, feel free to submit a PR against `iter/for-each` which updates the respective example to be more illustrative.

2023-12-15 04:44 UTC, kgryte commented on lib/node_modules/@stdlib/iter/while-each/README.md
> +To set the function execution context, provide a `thisArg`.
```suggestion
To set the execution context for `fcn`, provide a `thisArg`.
```

2023-12-15 04:45 UTC, kgryte commented on lib/node_modules/@stdlib/iter/while-each/README.md
> +```javascript
```suggestion
<!-- eslint-disable no-undefined-this -->

```javascript
```

I believe we need to disable this lint rule here, as I believe we should be getting a lint error.

2023-12-15 04:46 UTC, kgryte commented on lib/node_modules/@stdlib/iter/while-each/README.md
> +var iterForEach = require( '@stdlib/iter/for-each' );
```suggestion
var iterWhileEach = require( '@stdlib/iter/while-each' );
```

2023-12-15 04:47 UTC, kgryte commented on lib/node_modules/@stdlib/iter/while-each/README.md
> +var it = iterForEach( rand, predicate, assert );
```suggestion
var it = iterWhileEach( rand, predicate, assert );
```

2023-12-15 04:48 UTC, kgryte commented on lib/node_modules/@stdlib/iter/while-each/README.md
> +-   <span class="package-name">[`@stdlib/iter/map`][@stdlib/iter/map]</span><span class="delimiter">: </span><span class="description">create an iterator which invokes a function for each iterated va
```suggestion
```

We handle "See Also" sections in a separate build process which draws from a central project database.

2023-12-15 04:48 UTC, kgryte commented on lib/node_modules/@stdlib/iter/while-each/README.md
> +
```suggestion
```

2023-12-15 04:48 UTC, kgryte commented on lib/node_modules/@stdlib/iter/while-each/docs/repl.txt
> +    Returns an iterator which invokes a function for each iterated value before
This description needs to be updated to match the README.

2023-12-15 04:49 UTC, kgryte commented on lib/node_modules/@stdlib/iter/while-each/docs/repl.txt
> +    When invoked, the input function is provided two arguments:
```suggestion
    When invoked, both input functions are provided two arguments:
```

2023-12-15 04:49 UTC, kgryte commented on lib/node_modules/@stdlib/iter/while-each/docs/repl.txt
> +        Function which indicates whether to continue iterating or not.
```suggestion
        Function which indicates whether to continue iterating.
```

2023-12-15 04:49 UTC, kgryte commented on lib/node_modules/@stdlib/iter/while-each/docs/repl.txt
> +    > function predicate( v ) { return v === v};
```suggestion
    > function predicate( v ) { return v === v };
```

2023-12-15 04:50 UTC, kgryte commented on lib/node_modules/@stdlib/iter/while-each/README.md
> +    return v < 0.5;
```suggestion
    return v <= 0.75;
```

Updating to match `examples/index.js`.

2023-12-15 04:52 UTC, kgryte commented on lib/node_modules/@stdlib/iter/while-each/lib/main.js
> +* Returns an iterator which invokes a function for each iterated value before returning the iterated value.
This description needs to be updated.

2023-12-15 04:55 UTC, kgryte commented on lib/node_modules/@stdlib/iter/while-each/lib/main.js
> +		};
```suggestion
		if ( v.done || !predicate( v, i ) {
			FLG = true;
			return v;
		}
		v = v.value;
		fcn.call( thisArg, v, i );
		return {
			'value': v,
			'done': false
		};
```

As currently implemented, `fcn` is being called **before** `predicate` which is not what should happen (see [`@stdlib/utils/while-each`](https://github.com/stdlib-js/stdlib/blob/30cf48578491d545c528a28ccc031545c8e7bbf9/lib/node_modules/%40stdlib/utils/while-each/lib/main.js#L71)). We want to stop calling `fcn` as soon as `predicate` returns `false`; at which point, the iterator is considered "done".

Additionally, as stated in the docs, `predicate` should be provided both the value and index.

2023-12-15 05:00 UTC, kgryte commented on lib/node_modules/@stdlib/iter/while-each/lib/main.js
> +		return iterWhileEach( iterator[ iteratorSymbol ](), predicate, fcn, thisArg );
```suggestion
		return iterWhileEach( iterator[ iteratorSymbol ](), predicate, fcn, thisArg ); // eslint-disable-line max-len
```

2023-12-15 05:04 UTC, kgryte requested changes
@Jaysukh-409 Thanks for working on this! A few descriptions need to be updated, and this package still needs tests. For the latter, you can consult `iter/for-each` while borrowing some ideas from `utils/while-each`. Once resolved, this PR should be ready for merge.

2023-12-15 05:05 UTC, kgryte commented on lib/node_modules/@stdlib/iter/while-each/README.md
> +<!-- eslint-disable no-undefined-this -->
```suggestion
<!-- eslint-disable no-invalid-this -->
```

2023-12-15 05:07 UTC, kgryte commented on lib/node_modules/@stdlib/iter/while-each/lib/main.js
> +* var iter = iterWhileEach( randu(), predicate, assert );
@Jaysukh-409 I suggest not using `randu()` here, as the doctests (i.e., `returns <number>`) will randomly fail. I suggest using the example from the README which uses `array2iterator` and a static array `[ 1, 2, 3, 4 ]` with the `predicate` function updated accordingly.

2023-12-15 05:07 UTC, kgryte commented on lib/node_modules/@stdlib/iter/while-each/lib/index.js
> +* var iter = iterWhileEach( randu(), predicate, assert );
@Jaysukh-409 Same comment as https://github.com/stdlib-js/stdlib/pull/1180/files#r1427553714.

2023-12-15 10:05 UTC, kgryte commented on lib/node_modules/@stdlib/iter/while-each/docs/repl.txt
> +    returning the iterated value until either a predicate function
Just checking: do these lines wrap at 80 characters?

2023-12-15 10:05 UTC, kgryte commented on lib/node_modules/@stdlib/iter/while-each/docs/repl.txt
> +    returning the iterated value until either a predicate function
Line 4 looks like it wraps prematurely.

2023-12-15 10:06 UTC, kgryte commented on lib/node_modules/@stdlib/iter/while-each/lib/index.js
> +* // returns <number>
```suggestion
* // returns 1
*
* r = iter.next().value;
* // returns 2
```

2023-12-15 10:08 UTC, kgryte commented on lib/node_modules/@stdlib/iter/while-each/lib/main.js
> +* // throws <ReferenceError>
@Planeshifter Looks like we are still getting ESLint auto-fixes in doctest comments. Would you mind ensuring that this gets resolved?

@Jaysukh-409 In the meantime, it looks like we have error. Namely, Lines 45-46 are incorrect. You need to import `array2iterator`.

2023-12-15 10:09 UTC, kgryte commented on lib/node_modules/@stdlib/iter/while-each/lib/index.js
> +* var isnan = require( '@stdlib/math/base/assert/is-nan' );
These imports are no longer necessary. And we need to import `array2iterator`.

2023-12-15 11:03 UTC, Jaysukh-409 commented
Please ignore changes made above. Due to some issues I got this trouble.

2023-12-15 20:57 UTC, kgryte commented on lib/node_modules/@stdlib/iter/while-each/lib/main.js
> +* Returns an iterator which invokes a function for each iterated value before returning the iterated value until either a predicate function returns false or the iterator has iterated over all values
```suggestion
* Returns an iterator which invokes a function for each iterated value before returning the iterated value until either a predicate function returns `false` or the iterator has iterated over all values.
```

2023-12-15 21:03 UTC, kgryte commented on lib/node_modules/@stdlib/iter/while-each/test/test.js
> +		if ( r.value ) {
```suggestion
		if ( typeof r.value !== 'undefined' ) {
```

`r.value` can be `0`.

2023-12-15 21:06 UTC, kgryte commented on lib/node_modules/@stdlib/iter/while-each/test/test.js
> +		if ( r.value ) {
```suggestion
		if ( typeof r.value !== 'undefined' ) {
```

`r.value` can be `0`.

2023-12-15 21:10 UTC, kgryte requested changes
@Jaysukh-409 This is looking good! I think the only thing missing is benchmarks.

2023-12-15 21:11 UTC, kgryte commented
...and TypeScript declarations.

2023-12-16 07:25 UTC, kgryte commented on lib/node_modules/@stdlib/iter/while-each/docs/types/index.d.ts
> +* -   When invoked, both callback and `predicate` function are provided two arguments:
```suggestion
* -   When invoked, both the `predicate` and callback functions are provided two arguments:
```

2023-12-16 07:26 UTC, kgryte commented on lib/node_modules/@stdlib/iter/while-each/docs/types/index.d.ts
> +declare function iterWhileEach( iterator: Iterator, predicate: Predicate ,fcn: Callback, thisArg?: any ): Iterator;
```suggestion
declare function iterWhileEach( iterator: Iterator, predicate: Predicate, fcn: Callback, thisArg?: any ): Iterator;
```

2023-12-16 07:29 UTC, kgryte commented on lib/node_modules/@stdlib/iter/while-each/docs/types/index.d.ts
> +declare function iterWhileEach( iterator: Iterator, predicate: Predicate, fcn: Callback, thisArg?: any ): Iterator;
We can improve this type declaration, but we need to do this more generally for packages in `iter/*`, where we are not good about preserving type information. We can leave as is, for now, and address in a subsequent PR/commit.

2023-12-16 07:29 UTC, kgryte commented on lib/node_modules/@stdlib/iter/while-each/docs/types/test.ts
> +
```suggestion
```

2023-12-16 07:31 UTC, kgryte approved these changes
LGTM. Thanks, @Jaysukh-409!

2023-12-16 07:37 UTC, merged