feat: added iterCartesianSquare
stdlib-js/stdlib pull request #1371
Opened 2024-02-24 15:50 UTC by vinayak-00017

Resolves # 1334.

## Description

> What is the purpose of this pull request?
implements the package @stdlib/iter/cartesian-square.

This pull request:

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #1334 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-02-25 05:08 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cartesian-square/lib/main.js
> +* @private
Indentation is off here.

2024-02-25 05:11 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cartesian-square/lib/main.js
> +* @private
Indentation here and below.

2024-02-25 05:14 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cartesian-square/lib/main.js
> +		if ( i >= arr.length * arr.length ) {
A compiler might optimize this, but probably better to just cache it as `N = arr.length * arr.length` in the parent scope.

2024-02-25 05:16 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cartesian-square/lib/main.js
> +	if ( !Array.isArray( arr ) ) {
Use the more general `isCollection`. And actually, we should support accessor arrays. See https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/array/base/cartesian-square/lib/main.js#L48

2024-02-25 05:16 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cartesian-square/lib/main.js
> +* @param {ArrayLike} arr - input array
```suggestion
* @param {Collection} arr - input array
```

2024-02-25 05:17 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cartesian-square/test/test.js
> +	t.ok( iter.next().done, 'returns expected value' );
```suggestion
	t.strictEqual( iter.next().done, true, 'returns expected value' );
```

We should explicitly verify that the value of `true` is returned to ensure accordance with the iterator protocol.

2024-02-25 05:19 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cartesian-square/test/test.js
> +// TESTS //
This tests do not have full coverage support. You can run

```bash
make test-cov TESTS_FILTER=".*/iter/cartesian-square/.*"
make view-cov
```

to view a coverage report. See other iterator packages for how we ensure that tests can run in older environments lacking Symbols.

2024-02-25 05:20 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cartesian-square/docs/types/index.d.ts
> +declare function iterCartesianSquare<T>( x: ArrayLike<T> | Iterable<T> ): Iterator;
This API is not intended to support iterables.

2024-02-25 05:20 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cartesian-square/docs/types/index.d.ts
> +// EXPORTS //
```suggestion

// EXPORTS //
```

2024-02-25 05:21 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cartesian-square/docs/repl.txt
> +     x : collection
```suggestion
     x : ArrayLikeObject
```

2024-02-25 05:21 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cartesian-square/docs/repl.txt
> +    iterator is iterable.
```suggestion
    array-like object.
    
    If an environment supports Symbol.iterator, the returned iterator is iterable.
```

This needs to be rewrapped.

2024-02-25 05:21 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cartesian-square/benchmark/benchmark.js
> +	// Run the benchmark...
```suggestion
```

2024-02-25 05:23 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cartesian-square/benchmark/benchmark.js
> +		}
This not what we are looking for in a benchmark. We are not interested in measuring how long it takes to exhaust an iterator. We should be more interested in the performance of returning a single iterated value.

You can measure iteration without exhausting the iterator by ensuring that the input array has one more element than the square root of `b.iterations`.

2024-02-25 05:24 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cartesian-square/README.md
> +for ( pair of cartesianSquare ) {
We author everything in ES5. Perform manual iteration using a `while` loop. See other iterator packages.

2024-02-25 05:24 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cartesian-square/README.md
> +The returned iterator will generate all possible combinations from the input array x.
```suggestion
```

2024-02-25 05:25 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cartesian-square/README.md
> +for ( pair of cartesianSquare ) {
ES5. Just demonstrate manually returning the first few values. See other iterator packages.

2024-03-02 10:50 UTC, vinayak-00017 commented
I have made the changes you mentioned. Thanks for the review.

2024-03-17 20:15 UTC, Planeshifter requested changes
The tests currently won't run in environments lacking `Symbol.iterator` support. See the tests for other iterator packages such as https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/iter/head/test/test.js for how to ensure that tests can run in older environments lacking Symbols. This is currently blocking merging this PR.

2024-06-11 08:30 UTC, kgryte commented
@vinayak-00017 Are you still interested in working on this PR?

2024-06-11 09:31 UTC, vinayak-00017 commented
> @vinayak-00017 Are you still interested in working on this PR?

I apologise, I might not be able to complete it.

2026-05-20 19:06 UTC, closed without merging