Added Test Cases to adjacency-matrix
stdlib-js/stdlib pull request #1373
Opened 2024-02-24 20:18 UTC by uchiha-vivek

Resolves # .

## Description 
Test Cases for adjacency matrix

> What is the purpose of this pull request?

This pull request:

-   a Added more test cases for adjacency matrix.
-   b Checking whether the matrix is null, updation of matrix, and checking for edges between the vertices.
-   c They have been implemented in form of test cases.

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves # 
-   fixes # adding more test-cases

## Questions

> Any questions for reviewers of this pull request?

Please review the features and suggest changes if required.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [ ] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-02-25 16:41 UTC, uchiha-vivek commented
Please review it.

2024-03-17 08:57 UTC, kgryte commented on lib/node_modules/@stdlib/utils/compact-adjacency-matrix/test/test.js
> +var tape = require('tape');
All of these style changes should not have been made. Please revert and ensure that you follow project conventions.

2024-03-17 09:00 UTC, kgryte commented on lib/node_modules/@stdlib/utils/compact-adjacency-matrix/test/test.js
> +	t.deepEqual(mat.matrix, [
@uchiha-vivek Did you run these tests?

Based on what you have here, it does not appear so. There is no `matrix` attribute, and these tests are not written correctly.

2024-03-17 09:01 UTC, kgryte requested changes
This PR needs significant changes in order to be merged. I encourage you to see the tests for other packages (e.g., [`@stdlib/array/complex64`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/array/complex64/test)) for what we expect in terms of rigor and level of detail.

2024-10-13 20:44 UTC, closed without merging