refactor: improve type declarations for group function using generics
stdlib-js/stdlib pull request #1375
Opened 2024-02-25 00:30 UTC by rajutkarsh07

Resolves  #1086

## Description

> What is the purpose of this pull request?

This pull request:
    * Adds generics for improved type safety for the group function.

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves stdlib-js/stdlib/issues/1086

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-02-25 01:07 UTC, kgryte commented
@Planeshifter Would you mind reviewing? You might have additional ideas regarding the keys of the output object.

2024-02-25 20:08 UTC, Planeshifter requested changes
The type of the `collection` elements does not have to match the types of the group elements. For example, we could have a numeric array and a group array of strings.

In fact, I suggest we enforce that the `groups` collection groups should contain only values that are [valid property keys](https://www.totaltypescript.com/concepts/propertykey-type)

2024-02-27 22:01 UTC, rajutkarsh07 commented
@Planeshifter I have updated the code

2024-03-01 02:38 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/group/docs/types/index.d.ts
> +): { [key: string]: Collection<T> };
Let's use built-in `PropertyKey` instead (which also encompasses symbols, which are valid property keys):

```suggestion
declare function group<T, K extends PropertyKey>(
	collection: Collection<T>,
	groups: Collection<K>
): { [key: PropertyKey]: Collection<T> };
```

2024-03-01 02:44 UTC, Planeshifter requested changes
Two suggestions, then this should be ready to land; thanks!

2024-03-01 02:44 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/group/docs/types/index.d.ts
> +): { [key: string]: Collection<T> };
```suggestion
declare function group<T, K extends PropertyKey>(
	collection: Collection<T>,
	options: Options,
	groups: Collection<K>
): { [key in K]: Collection<T> };
```

2024-03-01 21:14 UTC, rajutkarsh07 commented
@Planeshifter I have made the required changes

2024-03-01 23:44 UTC, Planeshifter approved these changes

2024-03-01 23:44 UTC, Planeshifter commented
@rajutkarsh07 Great, thanks! Will merge after CI has passed.

2024-03-01 23:48 UTC, merged