feat: add `@stdlib/iter/cartesian-product`
stdlib-js/stdlib pull request #1399
Opened 2024-02-27 14:27 UTC by shubhexists

Resolves #1335 
## Description

> What is the purpose of this pull request?

This pull request:

-   Adds implementation of iterator equivalent of cartesian-product

## Related Issues

> Does this pull request have any related issues?

#1335 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

TESTS

![Screenshot from 2024-02-27 19-25-03](https://github.com/stdlib-js/stdlib/assets/110319892/c526500e-95a1-48de-aa26-e26f872057f0)

BENCHMARKS
![Screenshot from 2024-02-27 19-24-47](https://github.com/stdlib-js/stdlib/assets/110319892/e2207112-0ba0-430b-ab9d-25fd3ec1aac5)

EXAMPLES
![Screenshot from 2024-02-27 19-24-36](https://github.com/stdlib-js/stdlib/assets/110319892/9b89dbb9-4b5d-439d-af5d-5078bcba8b18)

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-02-27 18:59 UTC, maniksharma17 commented
@shubhexists hey, I cannot seem to run benchmark.js on the feat I added (@stdlib/utils/parse-ndjson). I'm getting this error. Did you encounter it too? 
![image](https://github.com/stdlib-js/stdlib/assets/130829163/8fa21a7c-7f0b-4772-8e30-ea6fe5fc45ed)

2024-02-28 19:19 UTC, steff456 requested changes
Hi @shubhexists, thanks for opening this PR!

I left some comments in this PR to get this approved, please let me know if you have any further question about any of them :)

2024-02-28 19:19 UTC, steff456 commented on lib/node_modules/@stdlib/iter/cartesian-product/README.md
> +}
Instead of using a `while` loop here can you please base this example like the other packages, e.g [counter package](https://github.com/stdlib-js/stdlib/blob/ce5ea47aad2effe3f956dde2ae01843f6b014d77/lib/node_modules/%40stdlib/iter/counter/README.md?plain=1#L53)

2024-02-28 19:19 UTC, steff456 commented on lib/node_modules/@stdlib/iter/cartesian-product/README.md
> +
```suggestion

The returned [iterator][mdn-iterator-protocol] protocol-compliant object has the following properties:

-   **next**: function which returns an [iterator][mdn-iterator-protocol] protocol-compliant object containing the next iterated value (if one exists) assigned to a `value` property and a `done` property having a `boolean` value indicating whether the [iterator][mdn-iterator-protocol] is finished.
-   **return**: function which closes an [iterator][mdn-iterator-protocol] and returns a single (optional) argument in an [iterator][mdn-iterator-protocol] protocol-compliant object.

```

Please also add the references to the new links at the bottom of the file

2024-02-28 19:19 UTC, steff456 commented on lib/node_modules/@stdlib/iter/cartesian-product/README.md
> +
```suggestion
<section class="notes">

## Notes

-   If an environment supports `Symbol.iterator` **and** a provided [iterator][mdn-iterator-protocol] is iterable, the returned [iterator][mdn-iterator-protocol] is iterable.

</section>

```

2024-02-28 19:19 UTC, steff456 commented on lib/node_modules/@stdlib/iter/cartesian-product/README.md
> +var x2 = linspace(10, 15, 6);
Can you please update this example to use `randu` package instead of `linspace`? Please guide yourself with the other packages.

2024-02-28 19:19 UTC, steff456 commented on lib/node_modules/@stdlib/iter/cartesian-product/README.md
> +
Add the new links here

2024-02-28 19:19 UTC, steff456 commented on lib/node_modules/@stdlib/iter/cartesian-product/benchmark/benchmark.js
> +bench( pkg+':len=100', function benchmark( b ) {
```suggestion
bench( pkg, function benchmark( b ) {
```

2024-02-28 19:19 UTC, steff456 commented on lib/node_modules/@stdlib/iter/cartesian-product/benchmark/benchmark.js
> +	x = zeroTo( 100 );
Please change this to use `rand` as the other `iter` packages

2024-02-28 19:19 UTC, steff456 commented on lib/node_modules/@stdlib/iter/cartesian-product/benchmark/benchmark.js
> +});
Add the benchmark `bench( pkg+'::iteration', function benchmark( b )` to this file as well

2024-02-28 19:19 UTC, steff456 commented on lib/node_modules/@stdlib/iter/cartesian-product/benchmark/benchmark.length.js
we don't need this file

2024-02-28 19:19 UTC, steff456 commented on lib/node_modules/@stdlib/iter/cartesian-product/docs/types/test.ts
> +// The compiler throws an error if the function is provided a first argument which is not array-like...
Please add a case for `string`, `boolean`, `null` and `undefined` to both arguments.

2024-02-28 19:19 UTC, steff456 commented on lib/node_modules/@stdlib/iter/cartesian-product/examples/index.js
> +var iter = iterCartesianProduct(x1, x2);
Same comment as in the readme, please use `rand` here

2024-02-28 19:19 UTC, steff456 commented on lib/node_modules/@stdlib/iter/cartesian-product/lib/main.js
> +function iterCartesianProduct(x1, x2) {
```suggestion
function iterCartesianProduct( x1, x2 ) {
```

We add a space when brackets are present, please change this in all the instances of this file

2024-02-28 19:19 UTC, steff456 commented on lib/node_modules/@stdlib/iter/cartesian-product/test/test.js
> +	values = ['5', 5, NaN, true, false, null, void 0, {}, function noop() {}];
```suggestion
	values = [
	    '5', 
	    5, 
	    NaN, 
	    true, 
	    false, 
	    null, 
	    void 0, 
	    {}, 
	    function noop() {}
	];
```
Please format lines that are long

2024-02-28 19:19 UTC, steff456 commented on lib/node_modules/@stdlib/iter/cartesian-product/test/test.js
> +	values = ['5', 5, NaN, true, false, null, void 0, {}, function noop() {}];
Same comment as above

2024-02-28 21:52 UTC, shubhexists commented
Hi @steff456 , my idea of using `linspace` and `zeroTo` was that the `iterCartesianProduct` function takes in an Array instead of an `Iterator`, as mentioned in the Issue. 
Since, `randu` returns an `Iterator` object, I would eventually have to run a while loop to collect all it's values into an `Array`.

What are your opinions?

2024-03-06 19:28 UTC, steff456 commented
@shubhexists you are right, let's leave the examples with `linspace`

2024-03-06 19:35 UTC, steff456 requested changes
Thanks for the changes @shubhexists, there are still a couple of tiny fixes before this PR is ready!

2024-03-06 19:35 UTC, steff456 commented on lib/node_modules/@stdlib/iter/cartesian-product/docs/types/test.ts
> +// The compiler throws an error if the function is provided a first argument which is not array-like...
This is not resolved yet, I meant we need to add the case for these dtypes for the error cases rather than the correct case

2024-03-06 19:35 UTC, steff456 commented on lib/node_modules/@stdlib/iter/cartesian-product/test/test.js
> +	values = ['5', 5, NaN, true, false, null, void 0, {}, function noop() {}];
This is still not resolved

2024-03-06 20:39 UTC, shubhexists commented
@steff456 Kindly have a look now

2024-03-12 20:17 UTC, steff456 requested changes
There's still a minor change for this PR to be ready.

2024-03-12 20:17 UTC, steff456 commented on lib/node_modules/@stdlib/iter/cartesian-product/docs/types/test.ts
> +// The compiler throws an error if the function is provided a first argument which is not array-like...
This is still not resolved

2024-03-12 20:17 UTC, steff456 commented on lib/node_modules/@stdlib/iter/cartesian-product/docs/types/test.ts
> +	iterCartesianProduct( {}, [ 4, 5, 6 ] ); // $ExpectError
The previous comment meant to add cases where the first argument is `string`, `boolean`, `null` and `undefined`
```suggestion
	iterCartesianProduct( {}, [ 4, 5, 6 ] ); // $ExpectError
	iterCartesianProduct( 'a', [ 4, 5, 6 ] ); // $ExpectError
	iterCartesianProduct( null, [ 4, 5, 6 ] ); // $ExpectError
	iterCartesianProduct( undefined, [ 4, 5, 6 ] ); // $ExpectError
```

Please do the same for the other test cases.

2024-08-31 09:04 UTC, closed without merging