Add fresnels function
stdlib-js/stdlib pull request #140
Opened 2017-09-26 06:30 UTC by rreusser

Resolves #136 .

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing], including the relevant style guides.
-   [x] Read and understand the [Code of Conduct][code-of-conduct].
-   [x] Read and understood the [licensing terms][license].
-   [x] Searched for existing issues and pull requests **before** submitting this pull request.
-   [x] Filed an issue (or an issue already existed) **prior to** submitting this pull request.
-   [x] Rebased onto latest `develop`.
-   [x] Submitted against `develop` branch.

## Description

> What is the purpose of this pull request?

This PR adds `fresnels` for computing the S(x) term of the Fresnel integral.

## Related Issues

> Does this pull request have any related issues?

See also: #135.

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

`fresnel` could use both this and `fresnelc` for computing the separate expansions for small x. There's no overlap so that it would reduce duplication of the code, though that's a refactoring that would require the separate versions to be merged first.

It's also possible that the large-x expansion could probably be streamlined to more efficiently compute the separate expansions, though I think that's secondary to an effective, accurate computation.

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

[license]: https://github.com/stdlib-js/stdlib/blob/develop/LICENSE

2017-09-26 06:41 UTC, kgryte commented
@rreusser If there is no overlap or perf gains to be attained by computing, e.g., simultaneously, I am fine with merging the separate implementations prior to a combined API.

2017-09-26 06:46 UTC, rreusser commented
There is overlap, but only for some ranges. Small numbers use separate expansions. Large numbers use a coupled expansion that makes it natural to compute both together. There's probably a large number expansion that is slightly more efficient by only using `sine` *or* `cosine` (not both for the sake of the phase change), but I don't know it.

2017-09-26 06:50 UTC, kgryte commented
Up to you. In general, I am fine with code duplication where it makes sense. Use your best judgment.

2017-09-26 07:06 UTC, rreusser commented
I think the small amount of duplication makes it more reasonable to just have all three entirely separate. Really getting it _perfect_ would require additional high-precision re-derivation.

2017-09-26 07:08 UTC, kgryte commented
Sounds good to me. :)

2017-09-27 01:22 UTC, kgryte requested changes

2017-09-27 01:22 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/fresnels/lib/fresnels.js
> +/* S(x) for small x */
Comment style.

2017-09-27 01:22 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/fresnels/lib/fresnels.js
> +/* Auxiliary function f(x) */
Comment style.

2017-09-27 01:22 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/fresnels/lib/fresnels.js
> +/* Auxiliary function g(x) */
Comment style.

2017-09-27 01:27 UTC, rreusser commented on lib/node_modules/@stdlib/math/base/special/fresnels/lib/fresnels.js
> +/* S(x) for small x */
✅

2017-09-27 01:27 UTC, rreusser commented on lib/node_modules/@stdlib/math/base/special/fresnels/lib/fresnels.js
> +/* Auxiliary function f(x) */
✅

2017-09-27 01:27 UTC, rreusser commented on lib/node_modules/@stdlib/math/base/special/fresnels/lib/fresnels.js
> +/* Auxiliary function g(x) */
✅

2017-09-27 01:28 UTC, kgryte approved these changes

2017-09-27 01:28 UTC, kgryte commented
@rreusser Thanks for your work on this! Will merge once CircleCI finishes. :)

2017-09-27 02:28 UTC, merged