feat: added utils/every-in-by
stdlib-js/stdlib pull request #1409
Opened 2024-02-28 18:16 UTC by the-r3aper7

Resolves #822 

## Description

> What is the purpose of this pull request?

This pull request:

-   a
-   b
-   c

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #
-   fixes #

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [ ] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-02-29 02:45 UTC, Planeshifter commented
@the-r3aper7 This package is currently missing a `README.md` file. Would you mind adding it, please?

2024-02-29 09:51 UTC, the-r3aper7 commented
@Planeshifter i have added `README.md` file.

2024-03-01 02:32 UTC, Planeshifter requested changes

2024-03-01 02:32 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/every-in-by/README.md
> +# every in by
```suggestion
# everyInBy
```

2024-03-01 02:32 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/every-in-by/README.md
> +> Test whether all elements in a object are truthy.
```suggestion
> Test whether all properties (own and inherited) of an object pass a test implemented by a predicate function.
```

2024-03-01 02:32 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/every-in-by/README.md
> +Tests whether all elements in a `object` pass a test implemented by a `predicate` function.
```suggestion
Tests whether all properties (own and inherited) of an `object` pass a test implemented by a `predicate` function.
```

2024-03-01 02:32 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/every-in-by/README.md
> +-   <span class="package-name">[`@stdlib/utils/some`][@stdlib/utils/some]</span><span class="delimiter">: </span><span class="description">test whether a object contains at least `n` elements which a
We auto-populate this section, no reason to fill in manually.

```suggestion
```

2024-03-01 02:32 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/every-in-by/README.md
> +[@stdlib/utils/some]: https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/utils/some
```suggestion
```

2024-03-01 02:32 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/every-in-by/lib/index.js
> +* Test whether all elements in a collection pass a test implemented by a predicate function, iterating from left to right.
```suggestion
* Test whether all elements in an object pass a test implemented by a predicate function.
```

2024-03-01 02:32 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/every-in-by/lib/main.js
> +* Tests whether all elements in a object pass a test implemented by a predicate function.
```suggestion
* Tests whether all properties (own and inherited) of an object pass a test implemented by a predicate function.
```

2024-03-01 02:32 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/every-in-by/lib/main.js
> +* @throws {TypeError} first argument must be a object
```suggestion
* @throws {TypeError} first argument must be an object
```

2024-03-01 02:32 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/every-in-by/package.json
> +  "description": "Test whether all elements in a object pass a test implemented by a predicate function, iterating from left to right.",
```suggestion
  "description": "Test whether all properties (own and inherited) of an object pass a test implemented by a predicate function.",
```

2024-03-01 02:32 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/every-in-by/docs/repl.txt
> +    predicate function, iterating from right to left.
```suggestion
    Test whether all properties (own and inherited) of an object pass a 
    test implemented by a predicate function.
```

2024-03-01 02:32 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/every-in-by/package.json
> +    "array-like",
```suggestion
    "object",
    "iterate",
```

2024-03-01 02:32 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/every-in-by/test/test.js
> +var everyInBy = require( './../lib' ); // Replace './lib' with the actual path to your function
```suggestion
var everyInBy = require( './../lib' );
```

2024-03-01 02:32 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/every-in-by/test/test.js
> +var noop = require('@stdlib/utils/noop');
Should insert spaces here and below around parentheses to match project conventions:

```suggestion
var tape = require( 'tape' );
var noop = require( '@stdlib/utils/noop' );
```

2024-03-01 02:32 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/every-in-by/lib/main.js
> +	}
```suggestion
	for ( key in obj ) { // eslint-disable-line guard-for-in
		if ( !predicate.call( thisArg, obj[ key ], key, obj ) ) {
			return false;
		}
	}
```

2024-03-01 02:32 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/every-in-by/docs/types/index.d.ts
> +type Predicate<T> = ( value: T, key: string, obj: object ) => boolean;
Please have a look at the type definitions for the predicate function in say `every-by`, which, even though for collections / arrays, should give some indication of how we want to type the `Predicate` function as well as `everyInBy`

2024-03-01 10:48 UTC, the-r3aper7 commented
@Planeshifter i have made the changes as you suggested.

2024-03-02 00:19 UTC, Planeshifter approved these changes
Made a few changes to get this over the finish line; will merge once CI passes.

Thanks for your contribution!

2024-03-02 00:19 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/every-by/docs/types/index.d.ts
> +import { Collection } from '@stdlib/types/object';
Need to revert this change:

```suggestion
import { Collection } from '@stdlib/types/array';
```

2024-03-02 00:19 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/every-in-by/docs/repl.txt
> +        The test function.
```suggestion
        Test function.
```

2024-03-02 00:19 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/every-in-by/docs/types/index.d.ts
> +// Export the function
```suggestion

// EXPORTS //

```

2024-03-02 00:19 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/every-in-by/docs/types/index.d.ts
> +
```suggestion
```

2024-03-02 00:26 UTC, merged