Add fresnelc
stdlib-js/stdlib pull request #141
Opened 2017-09-26 07:28 UTC by rreusser

Resolves #137.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing], including the relevant style guides.
-   [x] Read and understand the [Code of Conduct][code-of-conduct].
-   [x] Read and understood the [licensing terms][license].
-   [x] Searched for existing issues and pull requests **before** submitting this pull request.
-   [x] Filed an issue (or an issue already existed) **prior to** submitting this pull request.
-   [x] Rebased onto latest `develop`.
-   [x] Submitted against `develop` branch.

## Description

> What is the purpose of this pull request?

This pull request adds `fresnelc`.

## Related Issues

> Does this pull request have any related issues?

#137, #140, #135.

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

Once fully merged, I'm considering submitting a small refactor in which `fresnel` uses `fresnels` and `fresnelc` for separate evaluation of S(x) and C(x) for small x. That will remove some redundant coefficients from `fresnel` at the cost of maybe one extra absolute value evaluation. Otherwise the duplicate coefficients aren't a big deal. I have no strong preference. Honestly I'd hazard a guess that the presence and ease of access of obscure functions greatly greatly outweighs a 20ns difference in evaluation speed.

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

[license]: https://github.com/stdlib-js/stdlib/blob/develop/LICENSE

2017-09-26 07:32 UTC, rreusser commented
I guess what I'm trying to say is that the *only* reason for `fresnels` and `fresnelc` to exist is to avoid the extra line of code it takes to to calculate both S(x) *and* C(x) and throw one away when you just want one of two.

2017-09-26 07:34 UTC, kgryte commented
@rreusser Sounds reasonable. Will do the reviews later tonight/tomorrow. You have a preference for review order?

2017-09-26 07:42 UTC, rreusser commented
No strong preference. Probably `fresnel`, then `fresnels`, then `fresnelc`. They're *very* similar.

2017-09-27 01:35 UTC, kgryte requested changes

2017-09-27 01:35 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/fresnelc/README.md
> +> Compute the C(x) term of the [Fresnel integral][fresnel-integral].
For consistency with `S(x)`

> Compute the Fresnel integral C(x).

2017-09-27 01:35 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/fresnelc/docs/repl.txt
> +    Computes Fresnel integral C(x).
Computes the Fresnel...

2017-09-27 01:35 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/fresnelc/docs/repl.txt
> +        S(x).
C(x).

2017-09-27 01:35 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/fresnelc/test/fixtures/c/cephes/runner.c
> +	double *C;
Move to line above.

2017-09-27 01:36 UTC, rreusser commented on lib/node_modules/@stdlib/math/base/special/fresnelc/README.md
> +> Compute the C(x) term of the [Fresnel integral][fresnel-integral].
✅

2017-09-27 01:37 UTC, rreusser commented on lib/node_modules/@stdlib/math/base/special/fresnelc/test/fixtures/c/cephes/runner.c
> +	double *C;
✅

2017-09-27 01:37 UTC, rreusser commented on lib/node_modules/@stdlib/math/base/special/fresnelc/docs/repl.txt
> +        S(x).
Good catch. ✅

2017-09-27 01:40 UTC, kgryte approved these changes

2017-09-27 01:40 UTC, kgryte commented
@rreusser Thanks yet again! Will merge once CircleCI finishes. :)

2017-09-27 03:01 UTC, merged