feat: add `utils/any-in-by`
stdlib-js/stdlib pull request #1411
Opened 2024-02-28 20:12 UTC by itsspriyansh

Resolves #823 

## Description

> What is the purpose of this pull request?

This pull request:

-   a adds utils/any-in-by package
-   b tests whether any "own" and inherited property of a provided object satisfies a predicate function.

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #
-   fixes #

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [ ] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-03-02 01:48 UTC, Planeshifter requested changes
Thanks for this PR! Left some comments that will need to be addressed before this can be merged.

2024-03-02 01:48 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/any-in-by/README.md
> +#### anyInBy( collection, predicate\[, thisArg ] )
```suggestion
#### anyInBy( object, predicate\[, thisArg ] )
```

2024-03-02 01:48 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/any-in-by/README.md
> +-   <span class="package-name">[`@stdlib/utils/some-by`][@stdlib/utils/some-by]</span><span class="delimiter">: </span><span class="description">test whether a collection contains at least `n` elemen
We have tooling to auto-populate this section, so no reason to fill in manually.

```suggestion
```

2024-03-02 01:48 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/any-in-by/README.md
> +[@stdlib/utils/some-by]: https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/utils/some-by
We have tooling to auto-populate these links, so no reason to fill in manually.

```suggestion
```

2024-03-02 01:48 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/any-in-by/README.md
> +-   `collection`: input collection
```suggestion
-   `value`: property value
-   `key`: property key
-   `object`: input object
```

2024-03-02 01:48 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/any-in-by/README.md
> +-   If provided an empty collection, the function returns `false`.
```suggestion
-   If provided an empty object, the function returns `false`.
```

2024-03-02 01:48 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/any-in-by/README.md
> +    -   The function provides limited support for dynamic collections (i.e., collections whose `length` changes during execution).
Let's remove these notes as specifically about arrays.

```suggestion
```

2024-03-02 01:48 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/any-in-by/docs/repl.txt
> +{{alias}}( collection, predicate[, thisArg ] )
REPL documentation here needs to be updates as it currently is written for `collection` / `array` inputs, but the function is for `object`s.

2024-03-02 01:48 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/any-in-by/test/test.js
> +});
Can remove as duplicate of test in L36-63.

```suggestion
```

However, we need a test for ensuring that function throws an error if provided a predicate argument that is not a function.

2024-03-02 01:48 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/any-in-by/package.json
> +      "array-like",
```suggestion
      "object",
      "obj",
      "iterate",
```

2024-03-02 01:48 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/any-in-by/lib/main.js
> +		if ( hasOwnProp( obj, key ) && predicate.call( thisArg, obj[key], key, obj ) ) {
We should remove the `hasOwnProp( obj, key )` property check as the function is for "own _and inherited_" properties.

2024-03-02 01:48 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/any-in-by/docs/types/index.d.ts
> +// EXPORTS //
Two empty lines before section header comments:

```suggestion


// EXPORTS //
```

2024-03-02 01:48 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/any-in-by/docs/types/index.d.ts
> +* Checks whether an element in a collection passes a test.
```suggestion
* Checks whether an object property passes a test.
```

2024-03-02 01:48 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/any-in-by/docs/types/index.d.ts
> +* @returns boolean indicating whether an element in a collection passes a test
```suggestion
* @returns boolean indicating whether an object property passes a test
```

2024-03-02 01:48 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/any-in-by/docs/types/index.d.ts
> +* Checks whether an element in a collection passes a test.
```suggestion
* Checks whether an object property passes a test.
```

2024-03-02 01:48 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/any-in-by/docs/types/index.d.ts
> +* @returns boolean indicating whether an element in a collection passes a test
```suggestion
* @returns boolean indicating whether an object property passes a test
```

2024-03-02 01:48 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/any-in-by/docs/types/index.d.ts
> +* Checks whether an element in a collection passes a test.
```suggestion
* Checks whether an object property passes a test.
```

2024-03-02 01:48 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/any-in-by/docs/types/index.d.ts
> +* @param value - collection value
```suggestion
* @param value - property value
```

2024-03-02 01:48 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/any-in-by/docs/types/index.d.ts
> +* @param value - collection value
```suggestion
* @param value - property value
```

2024-03-02 01:48 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/any-in-by/docs/types/index.d.ts
> +* @param index - collection index
```suggestion
* @param key - property key
```

2024-03-02 01:48 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/any-in-by/docs/types/index.d.ts
> +* @returns boolean indicating whether an element in a collection passes a test
```suggestion
* @returns boolean indicating whether an object property passes a test
```

2024-03-02 01:48 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/any-in-by/docs/types/index.d.ts
> +type Ternary<T, U> = ( this: U, value: T, index: number, collection: Collection<T> ) => boolean;
```suggestion
* Checks whether an object property passes a test.
*
* @param value - property value
* @param key - property key
* @param obj - input object
* @returns boolean indicating whether an object property passes a test
*/
type Ternary<T, U> = ( this: U, value: T, key: string, obj:{ [key: string]: T } ) => boolean;
```

2024-03-02 01:48 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/any-in-by/docs/types/index.d.ts
> +type Predicate<T, U> = Nullary<U> | Unary<T, U> | Binary<T, U> | Ternary<T, U>;
```suggestion
* Checks whether an object property passes a test.
*
* @param value - property value
* @param key - property key
* @param obj - input object
* @returns boolean indicating whether an object property passes a test
*/
type Predicate<T, U> = Nullary<U> | Unary<T, U> | Binary<T, U> | Ternary<T, U>;
```

2024-03-03 15:11 UTC, itsspriyansh commented
@Planeshifter I have resolved all the problems.

2024-03-03 23:09 UTC, Planeshifter reviewed
It's coming along well, but I noticed we are still missing some tests. Would you be able to please add these?

2024-03-03 23:09 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/any-in-by/test/test.js
> +tape( 'the function throws an error if not provided a object', function test( t ) {
```suggestion
tape( 'the function throws an error if not provided an object', function test( t ) {
```

2024-03-03 23:09 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/any-in-by/test/test.js
> +
Needs a test for when `predicate` is not a function.

2024-03-03 23:09 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/any-in-by/test/test.js
> +});
We should have a test for when the function returns `false`. Our goal is to achieve 100% code coverage, so we should make sure that tests cover all code paths.

2024-03-04 10:11 UTC, itsspriyansh commented
@Planeshifter I have fixed the typo and I have added 3 tests where:
1. predicate is not a function
2. predicate is not provided
3. function returns false

2024-03-05 02:05 UTC, Planeshifter approved these changes
LGTM! Thanks for this contribution!

2024-03-05 02:08 UTC, merged