feat: added utils/none-in-by
stdlib-js/stdlib pull request #1416
Opened 2024-02-29 06:58 UTC by AgPriyanshu18

Check whether every property of object does not satisfy predicate function

Fixes #824

Resolves #824 .

## Description

> What is the purpose of this pull request?

This pull request:

-   a add utils/none-in-by
-   b Check whether every property of object does not satisfy predicate function
-   c

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #824 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [ ] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-02-29 10:09 UTC, Jaysukh-409 commented on lib/node_modules/@stdlib/utils/none-in-by/benchmark/julia/benchmark.jl
> +# Copyright (c) 2018 The Stdlib Authors.
```suggestion
# Copyright (c) 2024 The Stdlib Authors.
```

2024-02-29 10:10 UTC, Jaysukh-409 reviewed
Change Copyright years wherever it is necessary.

2024-02-29 10:25 UTC, Jaysukh-409 commented on lib/node_modules/@stdlib/utils/none-in-by/test/test.js
> +});
Needs to add test for providing an execution context.

2024-02-29 10:25 UTC, Jaysukh-409 commented on lib/node_modules/@stdlib/utils/none-in-by/README.md
> +
Add example of the function execution context and what predicate function receives as an argument.

2024-02-29 16:31 UTC, AgPriyanshu18 commented
@Jaysukh-409 I have made all suggested changes.

2024-03-02 05:41 UTC, Pranavchiku requested changes
This PR needs a few changes, I have requested changes and ask you to iterate over entire package comparing against `stdlib/utils/none-by`. Thank you!

2024-03-02 05:41 UTC, Pranavchiku commented on lib/node_modules/@stdlib/utils/none-in-by/README.md
> +> Tests whether every property of an object fails a test implemented by a predicate function.
```suggestion
> Test whether every property of an object fails a test implemented by a predicate function.
```

2024-03-02 05:41 UTC, Pranavchiku commented on lib/node_modules/@stdlib/utils/none-in-by/README.md
> +```
```suggestion
    ```javascript
    function truthy() {
        return true;
    }
    var bool = noneInBy( {}, truthy );
    // returns true
    ```
```

2024-03-02 05:41 UTC, Pranavchiku commented on lib/node_modules/@stdlib/utils/none-in-by/README.md
> +
mIssing ``The function does **not** skip `undefined` elements.``

2024-03-03 10:32 UTC, AgPriyanshu18 commented
@Pranavchiku I have completed the suggested changes and have reviewed the whole package.

2024-03-05 01:31 UTC, Planeshifter approved these changes
Looks good; just made a few code style and documentation fixes, but otherwise this PR should be ready to land once CI clears.

2024-03-05 01:31 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/none-in-by/docs/repl.txt
> +    Tests whether every property in a collection fail a test implemented by a
```suggestion
    Tests whether every property in an object fails a test implemented by a
```

2024-03-05 01:31 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/none-in-by/docs/types/test.ts
> +};
```suggestion
const obj = {
	'a': 1,
	'b': 2,
	'c': 4
};
```

2024-03-05 01:31 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/none-in-by/lib/index.js
> +* Test whether every property of a object fail a test implemented by a predicate function.
```suggestion
* Test whether every property of an object fails a test implemented by a predicate function.
```

2024-03-05 01:31 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/none-in-by/lib/index.js
> +* var obj = { 'a' : -1, 'b' : -2, 'c' : -3, 'd' : -4};
```suggestion
* var obj = { 'a' : -1, 'b' : -2, 'c' : -3, 'd' : -4 };
```

2024-03-05 01:31 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/none-in-by/lib/main.js
> +* @throws {TypeError} first argument must be a object
```suggestion
* @throws {TypeError} first argument must be an object
```

2024-03-05 01:31 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/none-in-by/lib/main.js
> +		throw new TypeError( format( 'invalid argument. First argument must be a object. Value: `%s`.', obj ) );
```suggestion
		throw new TypeError( format( 'invalid argument. First argument must be an object. Value: `%s`.', obj ) );
```

2024-03-05 01:31 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/none-in-by/package.json
> +    "description": "Test whether every property in a collection fail a test implemented by a predicate function.",
```suggestion
    "description": "Test whether every property in an object fails a test implemented by a predicate function.",
```

2024-03-05 01:31 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/none-in-by/package.json
> +      "array-like",
```suggestion
      "every",
      "iterate",
      "object",
```

2024-03-05 01:31 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/none-in-by/test/test.js
> +tape('the function returns `true` if every property fail a test ', function test(t) {
```suggestion
tape('the function returns `true` if every property fails a test ', function test(t) {
```

2024-03-05 01:31 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/none-in-by/test/test.js
> +tape('the function throws an error if not provided an object', function test(t) {
```suggestion
tape( 'the function throws an error if not provided an object', function test( t ) {
```

2024-03-05 01:31 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/none-in-by/test/test.js
> +tape('if provided an empty object, the function returns `true`', function test(t) {
```suggestion
tape( 'if provided an empty object, the function returns `true`', function test( t ) {
```

2024-03-05 01:31 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/none-in-by/test/test.js
> +tape('the function returns `false` if one or more properties pass a test ', function test(t) {
```suggestion
tape( 'the function returns `false` if one or more properties pass a test ', function test( t ) {
```

2024-03-05 01:31 UTC, Planeshifter commented on lib/node_modules/@stdlib/utils/none-in-by/test/test.js
> +});
Should update spacing around parentheses per our code style:

```suggestion
tape( 'the function supports providing an execution context', function test( t ) {
	var bool;
	var ctx;
	var obj;

	function sum( value ) {
		/* eslint-disable no-invalid-this */
		if ( value < 0 ) {
			return false;
		}
		this.sum += value;
		this.count += 1;
		return false;
	}

	ctx = {
		'sum': 0,
		'count': 0
	};
	obj = {
		'0': 1.0,
		'1': 2.0,
		'2': 3.0
	};

	bool = noneInBy( obj, sum, ctx );

	t.strictEqual( bool, true, 'returns true' );
	t.strictEqual( ctx.sum / ctx.count, 2.0, 'expected result' );

	t.end();
});
```

2024-03-05 01:38 UTC, merged