Add C implementation for `@stdlib/math/base/special/acoversin`
stdlib-js/stdlib pull request #1429
Opened 2024-03-01 07:40 UTC by aman-095

Resolves #776.

## Description

> What is the purpose of this pull request?

This pull request adds native C implementation for
`@stdlib/math/base/special/acoversin`

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #776 
-   fixes #

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-03-01 13:58 UTC, Pranavchiku requested changes
Looks good to me, nice work! Left few comments, apply those and this PR will be good to merge.

2024-03-01 13:58 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/acoversin/lib/native.js
> +*/
```suggestion
* var v = acoversin( NaN );
* // returns NaN
*/
```

2024-03-01 13:58 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/acoversin/manifest.json
> +
```suggestion
}
```

Remove extra end of file line

2024-03-01 13:58 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/acoversin/test/test.native.js
> +var tryRequire = require( '@stdlib/utils/try-require' );
```suggestion
var tryRequire = require( '@stdlib/utils/try-require' );
var EPS = require( '@stdlib/constants/float64/eps' );
var abs = require( '@stdlib/math/base/special/abs' );
```

2024-03-01 13:58 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/acoversin/test/test.native.js
> +var tryRequire = require( '@stdlib/utils/try-require' );
This is weird, try this, if it throws linting error you may avoid it.

2024-03-01 14:16 UTC, aman-095 commented on lib/node_modules/@stdlib/math/base/special/acoversin/test/test.native.js
> +var tryRequire = require( '@stdlib/utils/try-require' );
It works. Done

2024-03-01 14:28 UTC, Pranavchiku approved these changes
Thanks for this! Looks good to me.

2024-03-01 16:34 UTC, merged

2024-03-03 09:25 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/acoversin/manifest.json
> +}
@Planeshifter This is probably another thing we can automate. Ensuring trailing newlines for most file types.