feat: add complex/parse-float32
stdlib-js/stdlib pull request #1430
Opened 2024-03-01 08:17 UTC by Rejoan-Sardar

Resolves # 1332.

## Description

> What is the purpose of this pull request?

This pull request:
Adds the package @stdlib/complex/parse-float32.

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #1332 

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

Tests:
![Screenshot 2024-02-29 230900](https://github.com/stdlib-js/stdlib/assets/119718513/089685fc-aba9-4995-a0a2-e69443e4c51c)

Benchmarks
![Screenshot 2024-02-29 230841](https://github.com/stdlib-js/stdlib/assets/119718513/45e911af-abaf-43ed-b8f8-86bedab7ef3c)

Examples
![Screenshot 2024-02-29 230624](https://github.com/stdlib-js/stdlib/assets/119718513/247c9229-7ebf-4ab8-b4cc-b2b96fe8dba7)

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [X] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

2024-03-01 13:41 UTC, Pranavchiku commented on .gitignore
> -#/
can you please revert this

2024-03-02 09:00 UTC, Userf1995 commented on .gitignore
> -#/
Hi Pranav I reverted this and also What are the changes I have to do, I changed it now please check

2024-03-02 09:08 UTC, Pranavchiku requested changes
Looks good to me! I didn't went much into `lib/main.js` overall it is good. Requested few changes, once addressed this will be ready to merge.

2024-03-02 09:08 UTC, Pranavchiku commented on lib/node_modules/@stdlib/complex/parse-float32/README.md
> +var imag = require( '@stdlib/complex/imag' );
```suggestion
var parseComplex64 = require( '@stdlib/complex/parse-float32' );
var real = require( '@stdlib/complex/real' );
var imag = require( '@stdlib/complex/imag' );
```

2024-03-02 09:08 UTC, Pranavchiku commented on lib/node_modules/@stdlib/complex/parse-float32/docs/repl.txt
> +
```suggestion
```

2024-03-02 09:08 UTC, Pranavchiku commented on lib/node_modules/@stdlib/complex/parse-float32/lib/main.js
> +var isString = require( '@stdlib/assert/is-string' ).isPrimitive;
```suggestion
var isString = require( '@stdlib/assert/is-string' ).isPrimitive;
var Complex64 = require( '@stdlib/complex/float32' );
```

2024-03-02 10:02 UTC, Rejoan-Sardar commented on lib/node_modules/@stdlib/complex/parse-float32/lib/main.js
> +var isString = require( '@stdlib/assert/is-string' ).isPrimitive;
I've made all the changes you mentioned

2024-03-02 12:26 UTC, Pranavchiku approved these changes
Looks good to me. Thanks @Rejoan-Sardar !

2024-03-02 17:04 UTC, merged