feat: added @stdlib/string/to-well-formed
stdlib-js/stdlib pull request #1675
Opened 2024-03-03 20:21 UTC by Pratik772846

Returns a well-formed string by replacing all lone surrogates

Fixes #1066

Resolves # 1066

## Description

> What is the purpose of this pull request?

This pull request:

-   Replaces all lone surrogates in a string and returns a well-formed string
-   If the string is already well formed then return a shallow copy of the string

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves # 
-   fixes #

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [ ] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-03-04 10:22 UTC, Pranavchiku requested changes
Thanks @Pratik772846 for working on this. Requested changes.

2024-03-04 10:22 UTC, Pranavchiku commented on lib/node_modules/@stdlib/string/to-well-formed/README.md
> +> Creates a new well-formed string.
```suggestion
> Create a new well-formed string.
```

2024-03-04 10:22 UTC, Pranavchiku commented on lib/node_modules/@stdlib/string/to-well-formed/README.md
> +</section>
We can put some related packages here.

2024-03-04 10:22 UTC, Pranavchiku commented on lib/node_modules/@stdlib/string/to-well-formed/benchmark/benchmark.js
> +bench( pkg+'::str2wellformed', function benchmark( b ) {
```suggestion
bench( pkg, function benchmark( b ) {
```
We don't need this here, any specific reason for having this?

2024-03-04 10:22 UTC, Pranavchiku commented on lib/node_modules/@stdlib/string/to-well-formed/docs/types/index.d.ts
> +* Tests if a string is well-formed.
Incorrect description

2024-03-04 10:22 UTC, Pranavchiku commented on lib/node_modules/@stdlib/string/to-well-formed/docs/types/test.ts
> +// TESTS //
```suggestion


// TESTS //
```

2024-03-04 10:22 UTC, Pranavchiku commented on lib/node_modules/@stdlib/string/to-well-formed/docs/types/test.ts
> +// TESTS //
Mek sure you have correct dev env setup

2024-03-04 10:22 UTC, Pranavchiku commented on lib/node_modules/@stdlib/string/to-well-formed/examples/index.js
> +
```suggestion
console.log( str2wellformed( '' ) );
// => ''

```

I will prefer to do it for all console.log here

2024-03-04 10:22 UTC, Pranavchiku commented on lib/node_modules/@stdlib/string/to-well-formed/lib/index.js
> +*
```suggestion
```

2024-03-04 10:22 UTC, Pranavchiku commented on lib/node_modules/@stdlib/string/to-well-formed/lib/main.js
> +	var i;
```suggestion
	var modifiedString;
	var i;
	modifiedString = '';
```

2024-03-04 10:22 UTC, Pranavchiku commented on lib/node_modules/@stdlib/string/to-well-formed/lib/main.js
> +	for ( i =0; i < str.length; i++ ) {
```suggestion
	for ( i = 0; i < str.length; i++ ) {
```

2024-03-04 10:22 UTC, Pranavchiku commented on lib/node_modules/@stdlib/string/to-well-formed/lib/main.js
> +			modifiedString += str[i];
```suggestion
			modifiedString += str[ i ];
```

2024-03-04 10:22 UTC, Pranavchiku commented on lib/node_modules/@stdlib/string/to-well-formed/package.json
> +  }
incorrect indentation

2024-03-04 12:42 UTC, Pranavchiku commented on lib/node_modules/@stdlib/string/to-well-formed/package.json
> +
```suggestion
```

2024-03-04 12:43 UTC, Pranavchiku approved these changes
LGTM.

2024-03-04 12:44 UTC, Pranavchiku commented
I am not so great in reviewing this kind of PRs, I let Athan or Phillip review this.

2024-03-05 09:51 UTC, Pratik772846 commented
@Planeshifter Can you please review these changes?

2024-03-10 00:58 UTC, Planeshifter commented on lib/node_modules/@stdlib/string/to-well-formed/docs/repl.txt
> +        String to test.
```suggestion
        Input string.
```

2024-03-10 01:01 UTC, Planeshifter commented on lib/node_modules/@stdlib/string/to-well-formed/package.json
> +    "object"
```suggestion
  "stdlib",
  "string",
  "well-formed",
  "surrogate",
  "lone-surrogate",
  "utf-16",
  "unicode",
  "replacement",
  "character",
  "validation",
  "sanitization",
  "conversion",
  "transform",
  "utility",
  "utils"
```

2024-03-10 01:03 UTC, Planeshifter commented on lib/node_modules/@stdlib/string/to-well-formed/test/test.js
> +	t.equal(str2wellformed('5\uDBFF'), '5�', 'replaces lone high surrogate with Unicode replacement character');
```suggestion
	t.equal( str2wellformed(''), '', 'returns an empty string for an empty input' );
	t.equal( str2wellformed('\uDBFF'), '�', 'replaces lone high surrogate with Unicode replacement character' );
	t.equal( str2wellformed('\uDBFFFF\uDBFF'), '�FF�', 'replaces multiple lone surrogates with Unicode replacement characters' );
	t.equal( str2wellformed('Hello \uDBFFWorld'), 'Hello �World', 'replaces lone high surrogate in a string with Unicode replacement character' );
	t.equal( str2wellformed('\uDBFF'), '�', 'replaces lone high surrogate with Unicode replacement character' );
	t.equal( str2wellformed('\uDBFFFFF'), '�FFF', 'replaces lone high surrogate with Unicode replacement character' );
	t.equal( str2wellformed('\uDC00\uDC00'), '��', 'replaces lone low surrogate with Unicode replacement character' );
	t.equal( str2wellformed('5\uDBFF'), '5�', 'replaces lone high surrogate with Unicode replacement character' );
```

2024-03-10 01:04 UTC, Planeshifter commented on lib/node_modules/@stdlib/string/to-well-formed/package.json
> +  "description": "Convert a string to a well formed string",
```suggestion
  "description": "Convert a string to a well formed string.",
```

2024-03-10 01:04 UTC, Planeshifter commented on lib/node_modules/@stdlib/string/to-well-formed/lib/index.js
> +* Return a well formed string.
```suggestion
* Convert a string to a well formed string.
```

2024-03-10 01:05 UTC, Planeshifter commented on lib/node_modules/@stdlib/string/to-well-formed/docs/types/index.d.ts
> +* Returns a well formed string.
```suggestion
* Replaces all lone surrogates in order to create a new string which is well formed.
```

2024-03-10 01:06 UTC, Planeshifter commented on lib/node_modules/@stdlib/string/to-well-formed/docs/types/index.d.ts
> +* @returns returns a well formed string
```suggestion
* @returns new string which does not contain any lone surrogates
```

2024-03-10 01:07 UTC, Planeshifter commented on lib/node_modules/@stdlib/string/to-well-formed/README.md
> +Creates a new well-formed string.
```suggestion
Creates a new well-formed string by replacing all lone surrogates with the replacement character `\uFFFD`.
```

2024-03-10 01:08 UTC, Planeshifter commented
@Pratik772846 Implementation looks fine; will merge after CI has passed. Thank you!

2024-03-10 01:10 UTC, merged