feat: Add napi for binary int32_t to double and int32_t to int32_t
stdlib-js/stdlib pull request #1687
Opened 2024-03-04 09:17 UTC by aman-095

Resolves # .

## Description

> What is the purpose of this pull request?

This pull request adds napi for ii_i and ii_d `@stdlib/math/base/napi/binary`. 

## Related Issues

> Does this pull request have any related issues?

It is a blocker for the C implementation for GCD. 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-03-04 09:54 UTC, Pranavchiku approved these changes
This looks good to me as per my knowledge. Thanks @aman-095!

If you wish to read more about `Node-API`: https://nodejs.org/api/n-api.html

2024-03-04 09:54 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/napi/binary/README.md
> +Invokes a binary function accepting a signed 32-bit integer and a signed 32-bit integer and returning a signed 32-bit integer.
```suggestion
Invokes a binary function accepting and returning signed 32-bit integers.
```

2024-03-04 09:54 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/napi/binary/README.md
> +Invokes a binary function accepting a signed 32-bit integer and a signed 32-bit integer and returning a double-precision floating-point number.
```suggestion
Invokes a binary function accepting signed 32-bit integers and returning a double-precision floating-point number.
```

2024-03-04 09:54 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/napi/binary/include/stdlib/math/base/napi/binary.h
> +* Invokes a binary function accepting signed 32-bit integers and returning a signed 32-bit integer.
```suggestion
* Invokes a binary function accepting and returning signed 32-bit integers.
```

2024-03-04 09:54 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/napi/binary/src/main.c
> +* Invokes a binary function accepting signed 32-bit integers and returning a signed 32-bit integer.
```suggestion
* Invokes a binary function accepting and returning signed 32-bit integers.
```

2024-03-04 10:39 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/README.md
> +#### stdlib_math_base_napi_ii_d( env, info, fcn )
You need to document the associated macros below.

2024-03-04 10:39 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/include/stdlib/math/base/napi/binary.h
> +* Macro for registering a Node-API module exporting an interface invoking a binary function accepting and returning signed 32-bit integer.
```suggestion
* Macro for registering a Node-API module exporting an interface invoking a binary function accepting and returning signed 32-bit integers.
```

2024-03-04 10:40 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/include/stdlib/math/base/napi/binary.h
> +* Macro for registering a Node-API module exporting an interface invoking a binary function accepting signed 32-bit integer and returning double-precision floating-point number.
```suggestion
* Macro for registering a Node-API module exporting an interface invoking a binary function accepting signed 32-bit integers and returning a double-precision floating-point number.
```

2024-03-04 10:42 UTC, kgryte requested changes
The README is missing the new macro defns. Once added, this should be ready for merge.

2024-03-04 13:54 UTC, aman-095 commented
@kgryte @Pranavchiku I have applied changes please review.

2024-03-05 02:16 UTC, Planeshifter approved these changes
LGTM! Thanks for your contribution!

2024-03-05 02:20 UTC, merged