feat:Add C implementation for @stdlib/math/base/special/asec
stdlib-js/stdlib pull request #1720
Opened 2024-03-05 20:57 UTC by Rejoan-Sardar

Resolves #861 .

## Description

> What is the purpose of this pull request?

This pull request:Add C implementation for @stdlib/math/base/special/asec

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #861 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [X] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

2024-03-06 05:16 UTC, Pranavchiku requested changes
Requested changes, once addressed this can be ready.

2024-03-06 05:16 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/asec/README.md
> +Copyright (c) 2024 The Stdlib Authors.
```suggestion
Copyright (c) 2022 The Stdlib Authors.
```

2024-03-06 05:16 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/asec/benchmark/benchmark.native.js
> +* Copyright (c) 2022 The Stdlib Authors.
```suggestion
* Copyright (c) 2024 The Stdlib Authors.
```

2024-03-06 05:16 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/asec/benchmark/benchmark.native.js
> +		y = asec( ( randu()*1000.0 ) + 1.0 );
I will recommend to introduce new variable x and then do 
```javascript
x = ( randu()*1000.0 ) + 1.0;
y = asec( x );
```

2024-03-06 05:16 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/asec/benchmark/c/Makefile
> +# Copyright (c) 2020 The Stdlib Authors.
```suggestion
# Copyright (c) 2024 The Stdlib Authors.
```

2024-03-06 05:16 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/asec/benchmark/c/benchmark.c
> +/**
we don't need this file, as `math.h` do not have `asec` registered.

2024-03-06 05:16 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/asec/include/stdlib/math/base/special/asec.h
> +* Copyright (c) 2022 The Stdlib Authors.
```suggestion
* Copyright (c) 2024 The Stdlib Authors.
```

2024-03-06 05:16 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/asec/lib/native.js
> +* Copyright (c) 2022 The Stdlib Authors.
```suggestion
* Copyright (c) 2024 The Stdlib Authors.
```

2024-03-06 05:16 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/asec/lib/native.js
> +var acos = require( '@stdlib/math/base/special/acos' );
```suggestion
var addon = require( './../src/addon.node' );
```

2024-03-06 05:16 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/asec/lib/native.js
> +	return acos( 1.0 / x );
```suggestion
	return addon( x );
```

2024-03-06 05:16 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/asec/src/addon.c
> +* Copyright (c) 2022 The Stdlib Authors.
```suggestion
* Copyright (c) 2024 The Stdlib Authors.
```

2024-03-06 05:16 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/asec/test/test.native.js
> +* Copyright (c) 2022 The Stdlib Authors.
```suggestion
* Copyright (c) 2024 The Stdlib Authors.
```

2024-03-06 05:16 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/asec/test/test.native.js
> +tape( 'the function computes the inverse (arc) secant on the interval `[-3.0,-1.0]`', function test( t ) {
```suggestion
tape( 'the function computes the inverse (arc) secant on the interval `[-3.0,-1.0]`', opts, function test( t ) {
```

2024-03-06 05:16 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/asec/test/test.native.js
> +tape( 'the function computes the inverse (arc) secant on the interval `[1.0,3.0]`', function test( t ) {
```suggestion
tape( 'the function computes the inverse (arc) secant on the interval `[1.0,3.0]`', opts, function test( t ) {
```

2024-03-06 05:16 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/asec/test/test.native.js
> +tape( 'the function computes the inverse (arc) secant on the interval `[3.0,100.0]`', function test( t ) {
```suggestion
tape( 'the function computes the inverse (arc) secant on the interval `[3.0,100.0]`', opts, function test( t ) {
```

2024-03-06 05:16 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/asec/test/test.native.js
> +tape( 'the function computes the inverse (arc) secant on the interval `[-100.0,-3.0]`', function test( t ) {
```suggestion
tape( 'the function computes the inverse (arc) secant on the interval `[-100.0,-3.0]`', opts, function test( t ) {
```

2024-03-06 05:16 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/asec/test/test.native.js
> +tape( 'the function computes the inverse (arc) secant on the interval `[100.0,1000.0]`', function test( t ) {
```suggestion
tape( 'the function computes the inverse (arc) secant on the interval `[100.0,1000.0]`', opts, function test( t ) {
```

2024-03-06 05:16 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/asec/test/test.native.js
> +tape( 'the function computes the inverse (arc) secant on the interval `[-1000.0,-100.0]`', function test( t ) {
```suggestion
tape( 'the function computes the inverse (arc) secant on the interval `[-1000.0,-100.0]`', opts, function test( t ) {
```

2024-03-06 05:16 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/asec/test/test.native.js
> +tape( 'the function computes the inverse (arc) secant on the interval `[-1e200,-1e208]`', function test( t ) {
```suggestion
tape( 'the function computes the inverse (arc) secant on the interval `[-1e200,-1e208]`', opts, function test( t ) {
```

2024-03-06 05:16 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/asec/test/test.native.js
> +tape( 'the function computes the inverse (arc) secant on the interval `[1e300,1e308]`', function test( t ) {
```suggestion
tape( 'the function computes the inverse (arc) secant on the interval `[1e300,1e308]`', opts, function test( t ) {
```

2024-03-06 05:16 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/asec/test/test.native.js
> +tape( 'the function returns `NaN` if provided `NaN`', function test( t ) {
```suggestion
tape( 'the function returns `NaN` if provided `NaN`', opts, function test( t ) {
```

2024-03-06 05:16 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/asec/test/test.native.js
> +tape( 'the function returns `NaN` if provided `+0`', function test( t ) {
```suggestion
tape( 'the function returns `NaN` if provided `+0`', opts, function test( t ) {
```

2024-03-06 05:16 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/asec/test/test.native.js
> +tape( 'the function returns `NaN` if provided `-0`', function test( t ) {
```suggestion
tape( 'the function returns `NaN` if provided `-0`', opts, function test( t ) {
```

2024-03-06 05:16 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/asec/test/test.native.js
> +tape( 'the function returns `NaN` on the interval `(-1, 1)`', function test( t ) {
```suggestion
tape( 'the function returns `NaN` on the interval `(-1, 1)`', opts, function test( t ) {
```

2024-03-06 20:33 UTC, Rejoan-Sardar commented
I have addressed all the issues you mentioned in your review. Please take a look at the changes

2024-03-08 11:45 UTC, Rejoan-Sardar commented
> Requested changes, once addressed this can be ready.

@Pranavchiku I have addressed all the issues you mentioned in your review.please check.

2024-03-09 04:12 UTC, Planeshifter approved these changes
Looks good; let's get this in! Thank you!

2024-03-09 04:18 UTC, merged