I have make the necessary changes to refactor sdssum to follow curren…
stdlib-js/stdlib pull request #1727
Opened 2024-03-06 05:21 UTC by kunal-511

…t project convention

Resolves # .1525

## Description

> What is the purpose of this pull request?
I have make the necessary changes to refactor sdssum to follow current project convention

This pull request:

-   a
-   b
-   c

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #1525
-   fixes #

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [ ] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-03-06 09:09 UTC, kunal-511 commented
@Planeshifter Please review my PR?

2024-03-06 09:15 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sdssum/benchmark/benchmark.js
> +	var x = filledarrayBy( len, 'float64', rand );
This is incorrect. The dtype should be `float32` here and everywhere else in this PR.

2024-03-06 09:15 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sdssum/benchmark/benchmark.js
> +
```suggestion


```

2024-03-06 09:15 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sdssum/benchmark/benchmark.ndarray.native.js
> +var rand = uniform( -100.0, 100.0 );
```suggestion
var rand = uniform( -100.0, 100.0 );

```

2024-03-06 09:16 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sdssum/examples/index.js
> +console.log( y );
```suggestion
var v = sdssum( x.length, x, 1 );
console.log( v );

```

No need to change the variable name here.

2024-03-06 09:18 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sdssum/lib/ndarray.native.js
> +	view = offsetView( x, offset );
This is the relevant file you want to emulate: https://github.com/stdlib-js/stdlib/blob/58c9a5053430b55c974e9ecccfc45c51c3fefc9e/lib/node_modules/%40stdlib/blas/base/sasum/lib/ndarray.native.js

2024-03-06 09:18 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sdssum/manifest.json
> +	"options": {
Please convert this file to 2-space indentation.

2024-03-06 09:19 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sdssum/manifest.json
> +				"@stdlib/napi/argv-strided-float64array"
This is incorrect. The input array should be a float32 array.

2024-03-06 09:19 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sdssum/manifest.json
> +}
Trailing newline. Please ensure you have installed EditorConfig, as mentioned in the development guide.

2024-03-06 09:20 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sdssum/src/addon.c
> +    return v;
This should be TAB indentation. As mentioned above, input array should be float32, not float64. L43 should be `(float *)X`.

2024-03-06 09:20 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sdssum/src/addon.c
> +static napi_value addon(napi_env env, napi_callback_info info)
Please adhere to project spacing conventions.

2024-03-06 09:20 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sdssum/src/addon.c
> +STDLIB_NAPI_MODULE_EXPORT_FCN(addon)
Trailing newline.

2024-03-06 09:21 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sdssum/test/test.ndarray.native.js
> +	t.strictEqual( sdssum.length, 4, 'returns expected value' );
The changes in this file are incomplete. You should refactor to avoid the use of `floor`. See reference PRs linked to in the OP.

2024-03-06 09:22 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sdssum/test/test.sdssum.js
> +
```suggestion
```

2024-03-06 09:22 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sdssum/test/test.sdssum.native.js
> +
```suggestion
```

2024-03-06 09:22 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sdssum/test/test.ndarray.js
> +	t.strictEqual( sdssum.length, 4, 'returns expected value' );
Refactoring is incomplete. Remove the use of `floor`.

2024-03-06 09:23 UTC, kgryte requested changes
Left various comments. Please pay particular attention to similar PRs and commits and match changes and conventions in those changesets as closely as possible.

2024-03-06 09:25 UTC, kgryte commented
Please also check the box in the OP indicating that you have read and understood the contribution guidelines.

2024-03-06 09:27 UTC, kunal-511 commented
@kgryte Thanks for your review, I will implement these ass soon as possible

2024-03-07 02:29 UTC, kunal-511 commented
@kgryte 
The requested changes have been addressed. Please take a look

2024-03-07 03:04 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sdssum/manifest.json
> +				"@stdlib/napi/argv-int32",
This is incorrect. Should be `int64`.

2024-03-07 03:04 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sdssum/src/addon.c
> +#include "stdlib/napi/argv_int32.h"
This should be `int64`.

2024-03-07 03:05 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sdssum/test/test.ndarray.js
> +//var floor = require( '@stdlib/math/base/special/floor' );
Don't comment out. Remove.

2024-03-07 03:06 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sdssum/benchmark/benchmark.native.js
> +
```suggestion
```

2024-03-07 03:06 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sdssum/benchmark/benchmark.native.js
> +	var x = filledarrayBy( len, 'float64', rand );
float32

2024-03-07 03:06 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sdssum/benchmark/benchmark.ndarray.js
> +
```suggestion
```

2024-03-07 03:06 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sdssum/benchmark/benchmark.ndarray.js
> +
```suggestion
```

2024-03-07 03:07 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sdssum/benchmark/benchmark.ndarray.js
> +
Please ensure you have your local dev environment setup, including running `make init`. Your PR contains various lint errors which project automated tooling can catch, but only if you have properly set things up locally.

2024-03-07 03:07 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sdssum/benchmark/benchmark.ndarray.js
> +	var x = filledarrayBy( len, 'float64', rand );
float32

2024-03-07 03:08 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sdssum/benchmark/benchmark.ndarray.native.js
> +
```suggestion
```

2024-03-07 03:08 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sdssum/benchmark/benchmark.ndarray.native.js
> +	var x = filledarrayBy( len, 'float64', rand );
float32

2024-03-07 03:08 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sdssum/manifest.json
> +        "@stdlib/napi/argv-int32",
int64 here and elsewhere

2024-03-07 03:09 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sdssum/manifest.json
> +        "./src/sdssum_f.c"
Why are these files here? The implementation does not have Fortran files.

2024-03-07 03:10 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sdssum/manifest.json
> +      "blas": "openblas",
There are no OpenBLAS bindings. This `manifest.json` is entirely incorrect. Use the former `manifest.json` file and just change the indentation.

2024-03-07 03:12 UTC, kgryte requested changes
This PR currently has a number of issues. Please consult other packages in `blas/ext/base` and try to adhere as closely as possible. For example, see https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/blas/ext/base/ssumors. But don't just copy-paste. Consider what is appropriate to emulate and where to deviate based on the needs of `sdssum`. I suggested consulting `sasum`, but only for how ndarray views are handled.

2024-03-07 12:09 UTC, kunal-511 commented
@kgryte
The requested changes have been addressed. Please take a look

2024-03-10 07:26 UTC, kunal-511 commented
@kgryte @Planeshifter  Please see this

2024-04-20 23:52 UTC, Planeshifter commented
Closing as this refactoring was meanwhile merged per https://github.com/stdlib-js/stdlib/pull/2080. Thanks either way for your contribution even though it didn't make it in this time!

2024-04-20 23:52 UTC, closed without merging