docs: improve README examples of `stats/iter` namespace .
stdlib-js/stdlib pull request #1738
Opened 2024-03-06 16:25 UTC by kumarsuraj212003

Resolves #1652.

## Description

> What is the purpose of this pull request?

This pull request:

-   a
-   b
-   c

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #1652
-   fixes #

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-03-06 19:43 UTC, steff456 requested changes
Thanks @kumarsuraj212003 for opening this PR!

I left two comments and please check the failing CI for the example you added.

Also, please add the requested information in the description of this PR, specially the first section describing what this PR is doing.

2024-03-06 19:43 UTC, steff456 commented on lib/node_modules/@stdlib/stats/iter/README.md
> +Copyright (c) 2024 The Stdlib Authors.
```suggestion
Copyright (c) 2018 The Stdlib Authors.
```

We only define the copyright year when we create the file

2024-03-06 19:43 UTC, steff456 commented on lib/node_modules/@stdlib/stats/iter/README.md
> +
```suggestion
```

2024-03-07 14:06 UTC, kumarsuraj212003 reviewed
i follow stuggested changes

2024-03-07 14:26 UTC, kumarsuraj212003 commented
![Screenshot (12)](https://github.com/stdlib-js/stdlib/assets/125961509/064f6578-5e57-4ac1-84a5-a5fc0af914d2)
can u please tell me why am i getting this error.
i have setup stdlib locally i also varified by running benchmarks and tests ,it woks smoothly

2024-03-07 17:19 UTC, kumarsuraj212003 commented
I think i should update index.js file too in `stats/iter/examples` to pass all CI

2024-03-12 20:21 UTC, steff456 commented
Hi @kumarsuraj212003, that error indicate that when the example is running, it is returning `null` instead of the expected value. Can you please check if everything is running smoothly locally by running the lint command `make lint-markdown-files FILES="<Type here the path to the readme file>"`? You can double check if everything is importing correctly as part of the package.

2024-05-19 16:23 UTC, closed without merging