feat: Add C implementation for `math/base/special/pow`
stdlib-js/stdlib pull request #1739
Opened 2024-03-06 19:19 UTC by aman-095

Resolves #1656.

## Description

> What is the purpose of this pull request?

This RFC proposes adding native C implementation for [`@stdlib/math/base/special/pow`](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/pow/)

```c
double stdlib_base_pow( const double b, const double x )
```

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #1656 
-   fixes #

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-03-06 19:21 UTC, aman-095 commented
There is some minor error that is leading to test failure. Can you please check the implementation? CC @kgryte @Pranavchiku @Planeshifter

2024-03-07 01:57 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/README.md
> +-   **x**: `[in] double` input value.
```suggestion
-   **base**: `[in] double` base.
-   **exponent**: `[in] double` exponent.
```

2024-03-07 01:58 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/README.md
> +double stdlib_base_pow( const double b, const double x );
```suggestion
double stdlib_base_pow( const double base, const double exponent );
```

2024-03-07 01:59 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/README.md
> +    double out;
```suggestion
    double out;
    double b;
    double x;
```

Order based on line length.

2024-03-07 02:00 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/benchmark/c/native/benchmark.c
> +* Benchmark `ellipk`.
```suggestion
* Benchmark `pow`.
```

2024-03-07 02:01 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/binding.gyp
> +}
Trailing newline.

```suggestion
}

```

2024-03-07 02:02 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/include.gypi
> +}
Trailing newline.

```suggestion
}

```

2024-03-07 02:03 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/include/stdlib/math/base/special/pow.h
> +double stdlib_base_pow( const double b, const double x );
```suggestion
double stdlib_base_pow( const double b, const double exponent );
```

2024-03-07 02:03 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/include/stdlib/math/base/special/pow.h
> +#endif // !STDLIB_MATH_BASE_SPECIAL_POW_H
```suggestion
#endif // !STDLIB_MATH_BASE_SPECIAL_POW_H

```

2024-03-07 02:06 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/lib/native.js
> +* @param {number} x - input value
```suggestion
* @param {number} x - base
* @param {number} y - exponent
```

Match the `main.js` file.

2024-03-07 02:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/lib/native.js
> +* // returns NaN
```suggestion
* v = pow( 4.0, 0.5 );
* // returns 2.0
*
* v = pow( 100.0, 0.0 );
* // returns 1.0
*
* v = pow( 3.141592653589793, -0.2 );
* // returns ~0.7954
*
* v = pow( NaN, 3.0 );
* // returns NaN
*
* v = pow( 5.0, NaN );
* // returns NaN
```

Copy-paste errors.

2024-03-07 02:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/lib/native.js
> +	return addon( b, x );
```suggestion
function pow( x, y ) {
	return addon( x, y );
```

2024-03-07 02:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/lib/native.js
> +Evaluates the exponential function.
```suggestion
* Evaluates the exponential function.
```

2024-03-07 02:08 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/lib/native.js
> +* @returns {number} exponential value
```suggestion
* @returns {number} function value
```

2024-03-07 02:09 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/lib/native.js
> +* // returns NaN
```suggestion
* @example
* var v = pow( 2.0, 3.0 );
* // returns 8.0
*
* @example
* var v = pow( 4.0, 0.5 );
* // returns 2.0
*
* @example
* var v = pow( 100.0, 0.0 );
* // returns 1.0
*
* @example
* var v = pow( 3.141592653589793, 5.0 );
* // returns ~306.0197
*
* @example
* var v = pow( 3.141592653589793, -0.2 );
* // returns ~0.7954
*
* @example
* var v = pow( NaN, 3.0 );
* // returns NaN
*
* @example
* var v = pow( 5.0, NaN );
* // returns NaN
*
* @example
* var v = pow( NaN, NaN );
```

For future reference, just copy the docs from the `main.js` file and add `@private` annotation.

2024-03-07 02:12 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/src/Makefile
> +.PHONY: clean
```suggestion
.PHONY: clean

```

2024-03-07 02:14 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/src/main.c
> +
```suggestion
```

2024-03-07 02:15 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/src/main.c
> +double LOG_WORKSPACE[2] = { 0.0, 0.0 };
We shouldn't use workspaces in C, as it is not thread safe.

2024-03-07 02:17 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/src/main.c
> +static const uint32_t HIGH_MAX_NEAR_UNITY = 0x3fefffff;
```suggestion
static const int32_t HIGH_MAX_NEAR_UNITY = 0x3fefffff;
```

You've made a number of these constants unsigned integers, when the JS implementation has them as signed integers. What is the rationale for doing that?

2024-03-07 02:17 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/src/main.c
> +static const double TINY = 1.0e-300;
```suggestion
static const double HUGE_VALUE = 1.0e300;

static const double TINY_VALUE = 1.0e-300;
```

These need to be renamed due to conflicts with built-in C macros.

2024-03-07 02:18 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/src/main.c
> +static const uint32_t HIGH_MIN_NORMAL_EXP = 0x00100000;
```suggestion
static const int32_t HIGH_MIN_NORMAL_EXP = 0x00100000;
```

2024-03-07 02:22 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/src/main.c
> +static const uint32_t HIGH_BIASED_EXP_NEG_1 = 0x3fe00000;
```suggestion
static const int32_t HIGH_BIASED_EXP_NEG_1 = 0x3fe00000;
```

For reference, the asm type annotation in JS for signed 32-bit integers is `|0` and the type annotation for unsigned 32-bit integers is `>>>0`.

Would you mind updating all the constants accordingly?

2024-03-07 02:24 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/src/main.c
> +double BP [2] = { 1.0, 1.5 };
Why is this and the following not `static const`?

2024-03-07 02:25 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/src/main.c
> +double BP [2] = { 1.0, 1.5 };
Otherwise, the variables are visible outside this translation unit.

2024-03-07 02:26 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/src/main.c
> +double LOG_WORKSPACE[2] = { 0.0, 0.0 };
Instead of a log workspace, provide two output argument pointers to `log2ax`.

2024-03-07 02:27 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/src/main.c
> +double y_is_infinite( const double x, const double y ) {
```suggestion
static double y_is_infinite( const double x, const double y ) {
```

Internal functions need to be local to this file. Update here and elsewhere.

2024-03-07 02:27 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/src/main.c
> +    if ( x == -1.0 ) {
TAB indentation.

2024-03-07 02:28 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/src/main.c
> +* double out = y_is_infinite( 1.5, -Infinity );
```suggestion
* double out = y_is_infinite( -1.0, 1.0/0.0 );
* // returns NaN
*
* @example
* double out = y_is_infinite( 1.5, -1.0/0.0 );
```

`Infinity` is a JavaScript global, not a C global.

2024-03-07 02:32 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/src/main.c
> +    stdlib_base_float64_get_high_word( xc, &hx );
TAB indentation here and elsewhere.

2024-03-07 02:33 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/src/main.c
> +	double ahx;
This should not be a double.

2024-03-07 02:36 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/src/main.c
> +    stdlib_base_float64_get_high_word( xc, &hx );
Okay. I see your rationale for `uint32_t` above, as that is the expected output pointer dtype for `get_high_word`. 

I think you at least want to go back and check whether you've typed the various variables correctly and with fidelity with the JS implementation. You can also reference the original source implementation linked to in the license comment in the JS implementation.

2024-03-07 02:36 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/src/main.c
> +            return HUGE * HUGE;
```suggestion
            return HUGE_VALUE * HUGE_VALUE;
```

2024-03-07 02:37 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/src/main.c
> +        return TINY * TINY;
```suggestion
        return TINY_VALUE * TINY_VALUE;
```

2024-03-07 02:37 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/src/main.c
> +        return HUGE * HUGE;
```suggestion
        return HUGE_VALUE * HUGE_VALUE;
```

2024-03-07 02:38 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/src/main.c
> +	return TINY * TINY;
```suggestion
	return TINY_VALUE * TINY_VALUE;
```

2024-03-07 02:38 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/src/main.c
> +* @param y    input value
```suggestion
* @param x    base
* @param y    exponent
```

Here and elsewhere.

2024-03-07 02:39 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/src/main.c
> +* @param y    input value
Same comment as above.

2024-03-07 02:39 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/src/main.c
> +* @return	  output value
```suggestion
* @return	  output value
```

You've mixed tabs and spaces here.

2024-03-07 02:41 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/src/main.c
> +* @return	  function value
```suggestion
* @param j    high word of hp + lp
* @param hp    first power summand
* @param lp    second power summand
* @return	  function value
```

Align descriptions. You've also mixed tabs and spaces.

2024-03-07 02:41 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/src/main.c
> +	double hpc;
Order by length.

2024-03-07 02:44 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/src/main.c
> +		n = ( j + ( HIGH_MIN_NORMAL_EXP >> ( k + 1 ) ) ) >> 0; // asm type annotation
You don't need `>> 0` asm type annotations. That is a JS concept to signal typed integer values to supporting compilers. Remove here and elsewhere, as the variables in C are explicitly typed.

2024-03-07 02:45 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/src/main.c
> +		n = ( ( ( n & HIGH_SIGNIFICAND_MASK ) | HIGH_MIN_NORMAL_EXP ) >> ( HIGH_NUM_SIGNIFICAND_BITS - k ) ) >> 0; // eslint-disable-line max-len
Remove ESLint comments. ESLint is not used to lint C.

2024-03-07 02:45 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/src/main.c
> +	jc = jcc|0;
```suggestion
	jc = (int32_t)jcc;
```

Perform an explicit cast.

2024-03-07 02:47 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/src/main.c
> +void logx( double *out, const double ax ) {
Rather than a pointer to a two-element array, provide pointers to two output argument values.

2024-03-07 02:49 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/src/main.c
> +	uint32_t ahx; // absolute value high word `x`
Align the comments as in JS.

2024-03-07 02:50 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/src/main.c
> +				return sx * HUGE * HUGE;
Update variable names.

2024-03-07 02:52 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/src/main.c
> +		t[0] = LOG_WORKSPACE[0];
We don't want the log workspace, but, even if we did, this does not do what you are wanting. This assigns the value, and does not set the pointer to `t[0]` to point to the start of the workspace.

2024-03-07 02:53 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/src/main.c
> +	ic = i;
Should we be casting to `int32_t` as in JS?

2024-03-07 02:53 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/pow/src/main.c
> +			return sx * HUGE * HUGE;
Update variable names here and below.

2024-03-07 02:54 UTC, kgryte requested changes
Thanks for working on this, @aman-095. Everything but the implementation looks fine to me. I recommend doing another deep pass across the implementation to ensure that the port matches the JS implementation. I highly recommend also taking a look at the original source implementation from which we wrote the JS variant.

2024-03-07 13:26 UTC, aman-095 commented
The original source implementation is this https://svnweb.freebsd.org/base/release/9.3.0/lib/msun/src/s_pow.c but it throws 404 not found. @kgryte

2024-03-07 18:38 UTC, aman-095 commented
When I run `make install-node-addons .....`, it gives me the following line:

`  CC(target) Release/obj.target/addon/../../../../number/float32/base/to-word/src/to_word.o`, why does it have `float32` in there?

2024-03-07 18:44 UTC, aman-095 commented
The pushed changes are not for review, will clean this PR soon. @Pranavchiku can you please check why I am getting divergence in `stdlib_base_float64_to_words( x, &hx, &lx )` for javascript and C implementation.

2024-03-07 19:55 UTC, Pranavchiku commented
Let me check locally.

2024-03-07 19:58 UTC, Pranavchiku commented
```console
% make examples-c EXAMPLES_FILTER=".*/math/base/special/pow/.*"

Running example: /Users/pranavchiku/repos/stdlib-js/stdlib/lib/node_modules/@stdlib/math/base/special/pow/examples/c/example.c
Resolving package path...
Package path: /Users/pranavchiku/repos/stdlib-js/stdlib/lib/node_modules/@stdlib/math/base/special/pow
Resolving package manifest...
Successfully resolved package manifest.
Resolving include directories...
Resolving source files...
Resolving libraries...
Resolving library paths...
Compiling example...
example.c:27:9: warning: unused variable 'i' [-Wunused-variable]
    int i;
        ^
1 warning generated.
ld: warning: ignoring duplicate libraries: '-lm'
Successfully compiled example.
Success!

x: 1.689838e-52
y: 5.964124
inside
hy: 1075305283, ly: 1485800128
xc here: 1.689838e-52
x here: 1.689838e-52
hx: 892350328, lx: -1859706867 ------------------------ Here is incorrect value
ax: 1.689838e-52
ahx: 892350328, ahy: 1075305283
sx: 0, sy: 0
0
9
19
ax: 1.689838e-52
, ahx: 892350328
27
z: inf
sx: 1
28
pow(1.689838e-52, 5.964124) = inf
```

2024-03-08 07:53 UTC, Pranavchiku commented
You'll have to use: `printf("hx: %u, lx: %u\n", hx, lx);`

2024-03-08 09:58 UTC, aman-095 commented
@kgryte @Pranavchiku all tests, examples, and benchmarks work well locally. Don't know why CI is failing. Please review.

2024-03-13 12:48 UTC, aman-095 commented
CC @kgryte @Pranavchiku all tests work well locally. Don't know why tests are failing here.

2024-06-19 20:41 UTC, Planeshifter approved these changes
The discrepancy in test cases arise from floating-point operation fusing (see [clang.llvm.org/docs/UsersManual.html#cmdoption-ffp-contract](https://clang.llvm.org/docs/UsersManual.html#cmdoption-ffp-contract)), where multiple floating-point operations are combined into a single operation.

See prior discussion here: https://github.com/stdlib-js/stdlib/pull/2298#discussion_r1624765205

When compiling the add-on with this optimization disabled via

```
CFLAGS="-ffp-contract=off" NODE_GYP_FLAGS="" make install-node-addons NODE_ADDONS_PATTERN="math/base/special/pow"
```

all test cases match the results from the test fixtures.

2024-06-19 21:12 UTC, merged

2024-06-20 05:46 UTC, Pranavchiku commented
Woah! we finally got `pow` knocked out!