refactor: update blas/ext/base/ssumkbn2 to follow current project conventions
stdlib-js/stdlib pull request #1749
Opened 2024-03-07 10:56 UTC by vr-varad

…ventions

Resolves # .

## Description

> What is the purpose of this pull request?

This pull request refactors the ```@stdlib/blas/ext/ssumkbn2``` to follow current project conventions
> ## Checklist
> * [x]  update readme.md
> * [x]  docs
> * [x]  src
> * [x]  include.gypi
> * [x]  manifest.json
> * [x]  package.json
> * [x]  lib
> * [x]  examples
> * [x]  benchmark
> * [x]  test

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #1542 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [ ] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-03-07 11:27 UTC, vr-varad commented
Hello @Planeshifter and @kgryte, I'd appreciate your review of my pull request (#1749) whenever you have a moment. Thank you!

2024-03-09 14:47 UTC, vr-varad commented
Hi @Planeshifter @Pranavchiku  and @kgryte, just checking in on my pull request (#1749). Would you mind reviewing it when you get a chance?

2024-03-11 05:33 UTC, vr-varad commented
@Pranavchiku @Planeshifter @kgryte Any reviews updates?

2024-03-12 13:22 UTC, vr-varad commented
@Planeshifter any updates of reviews?

2024-03-12 13:24 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/ssumkbn2/README.md
> +var x = filledarrayBy( 10, 'float64', discreteUniform( -100, 100 ) );
```suggestion
var x = filledarrayBy( 10, 'float32', discreteUniform( -100, 100 ) );
```

2024-03-12 13:26 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/ssumkbn2/examples/index.js
> +var x = filledarrayBy( 10, 'float64', discreteUniform( 0, 100 ) );
```suggestion
var x = filledarrayBy( 10, 'float32', discreteUniform( 0, 100 ) );
```

2024-03-12 13:27 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/ssumkbn2/lib/ndarray.native.js
>  * var floor = require( '@stdlib/math/base/special/floor' );
```suggestion
```

2024-03-12 13:29 UTC, Pranavchiku requested changes
Missing changes in `docs/types`, requested few changes.

2024-03-12 13:29 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/ssumkbn2/lib/ndarray.native.js
> +	view = offsetView( x, offset );
```suggestion

	offset = minViewBufferIndex( N, stride, offset );

	view = offsetView( x, offset );

```

2024-03-12 13:29 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/ssumkbn2/manifest.json
> +	  }
Use spacing instead of tabs, incorrect indentation.

2024-03-12 15:32 UTC, vr-varad commented
@Pranavchiku I don't see any changes in docs/types to be made. Could u please review it?

2024-03-13 06:43 UTC, vr-varad commented
@kgryte @Planeshifter @Pranavchiku Could u review it for any other issues or changes?

2024-03-13 10:14 UTC, kgryte commented on lib/node_modules/@stdlib/bench/harness/package.json
> +    "test": "tape ./test/test.benchmark.js"
Remove this. There is no need for this change and this is unrelated to this PR.

2024-03-13 12:07 UTC, vr-varad commented
@kgryte @Pranavchiku I have made the required changes.

2024-03-13 21:03 UTC, vr-varad commented
hey @kgryte Would you mind taking a moment to review this? Your feedback would be greatly appreciated. Thank you very much!

2024-03-13 21:20 UTC, vr-varad commented
@kgryte I am closing this pr as there is an issue in my forked repository and will make a new pr soon.

2024-03-13 21:20 UTC, closed without merging