Hamming distance between two strings (Compares Unicode code points)
stdlib-js/stdlib pull request #1759
Opened 2024-03-07 17:39 UTC by JayPokale

Resolves #836 

## Description
Calculates the Hamming Code Points Distance distance between two equal-length unicode code points.

> Does this pull request have any related issues?

This pull request:

-   resolves #836

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-03-08 10:25 UTC, Pranavchiku commented
@JayPokale can you please ensure linters are set correctly in your device. I think those are not.

2024-03-08 10:34 UTC, Pranavchiku requested changes
Please go through development guide and iterate through the PR you referred. Setup dev environment and then this PR can be reviewed.

2024-03-08 10:34 UTC, Pranavchiku commented on CONTRIBUTORS
> +Jay Pokale <jay.pokale.35@gmail.com>
This is automated, please revert this commit.

2024-03-08 10:34 UTC, Pranavchiku commented on lib/node_modules/@stdlib/string/base/distances/hamming-code-points/benchmark/benchmark.js
> +});
This file should be TAB indented.

2024-03-08 10:34 UTC, Pranavchiku commented on lib/node_modules/@stdlib/string/base/distances/hamming-code-points/docs/types/test.ts
> +  hammingCodePointsDistance("", ""); // $ExpectType number
```suggestion
  hammingCodePointsDistance( "", "" ); // $ExpectType number
```

2024-03-08 10:34 UTC, Pranavchiku commented on lib/node_modules/@stdlib/string/base/distances/hamming-code-points/docs/types/test.ts
> +  hammingCodePointsDistance((x: number): number => x, ""); // $ExpectError
same comment here

2024-03-08 10:34 UTC, Pranavchiku commented on lib/node_modules/@stdlib/string/base/distances/hamming-code-points/docs/types/test.ts
> +  hammingCodePointsDistance("", (x: number): number => x); // $ExpectError
here as well

2024-03-08 10:34 UTC, Pranavchiku commented on lib/node_modules/@stdlib/string/base/distances/hamming-code-points/docs/types/test.ts
> +  hammingCodePointsDistance("", "", 3); // $ExpectError
sme comment

2024-03-08 10:34 UTC, Pranavchiku commented on lib/node_modules/@stdlib/string/base/distances/hamming-code-points/docs/types/test.ts
> + * @license Apache-2.0
this file shall be TAB indented

2024-03-08 10:34 UTC, Pranavchiku commented on lib/node_modules/@stdlib/string/base/distances/hamming-code-points/lib/index.js
> +// MODULES //
```suggestion
 */


// MODULES //
```

2024-03-08 10:34 UTC, Pranavchiku commented on lib/node_modules/@stdlib/string/base/distances/hamming-code-points/lib/index.js
> +// EXPORTS //
```suggestion
var main = require("./main.js");


// EXPORTS //
```

2024-03-08 10:34 UTC, Pranavchiku commented on lib/node_modules/@stdlib/string/base/distances/hamming-code-points/lib/main.js
> +// MAIN //
```suggestion
var format = require("@stdlib/string/format");


// MAIN //
```

2024-03-08 10:34 UTC, Pranavchiku commented on lib/node_modules/@stdlib/string/base/distances/hamming-code-points/lib/main.js
> +// EXPORTS //
Tab indentation required

2024-03-08 10:34 UTC, Pranavchiku commented on lib/node_modules/@stdlib/string/base/distances/hamming-code-points/lib/main.js
> +  if (!isString(s1)) {
Please declare variables at beginning of file

2024-03-08 10:34 UTC, Pranavchiku commented on lib/node_modules/@stdlib/string/base/distances/hamming-code-points/test/test.js
> +  }
Tab indentation, bracket spacing, etc.

2024-03-11 10:19 UTC, JayPokale commented
@Pranavchiku I converted code in required format as mentioned above.

2024-03-17 12:06 UTC, kgryte commented
This PR is currently failing CI and needs to be updated before we can review.

2024-03-18 19:21 UTC, closed without merging