refactor: updated addon.cpp to addon.c
stdlib-js/stdlib pull request #1770
Opened 2024-03-08 07:59 UTC by naveen1m

Resolves #1537

## Description

> What is the purpose of this pull request?

This pull request:

-   Refactors `@stdlib/blas/ext/base/ssorthp` to follow current project conventions.

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #1537 
-   progress #1152 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-03-08 10:05 UTC, Pranavchiku requested changes
This PR needs more changes, please follow https://github.com/stdlib-js/stdlib/commit/d66d80cfcbab1da95cb5ae8cfae4a1fc4c5129d1 and add required files.

2024-03-22 01:45 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/ssorthp/README.md
> +
```suggestion
```

2024-03-22 01:45 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/ssorthp/README.md
> +var x = filledarrayBy( 10, 'float32', rand);
```suggestion
var x = filledarrayBy( 10, 'float32', rand );
```

2024-03-22 01:46 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/ssorthp/include.gypi
> +# Copyright (c) 2024 The Stdlib Authors.
```suggestion
# Copyright (c) 2020 The Stdlib Authors.
```

2024-03-22 01:52 UTC, Planeshifter requested changes
Please have a look at the failing CI job for linting of the C files.

Also, the PR currently took the instruction to "remove the use of floor everywhere" as replacing it via a a right shift operation. This will have to be changed; please consult the linked packages for the changes we are looking for.

Thanks for your efforts!

2024-03-22 05:37 UTC, naveen1m commented
Got it! thanks for the clarification. I will make the necessary changes.

2024-04-07 04:54 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/ssorthp/benchmark/benchmark.mostly_sorted_few_uniques.js
> +			tmp[ j ] = 2*( uniform( a+sa, b+sb ) )>>1;
This isn't where you should be removing "floor". You are only supposed to remove from documentation and tests. E.g.,

```
N = floor( x.length / 2 );
```

Those are the only instances. Not here in the benchmarks.

2024-04-09 15:11 UTC, naveen1m commented
@kgryte @Planeshifter can you please review it? 
 
this test is failing, while other file has included same directory [see](https://github.com/stdlib-js/stdlib/commit/d66d80cfcbab1da95cb5ae8cfae4a1fc4c5129d1#diff-af83a9a228abf78533a2b199ce69ed7b06bece7905eebc62ca899fe9ab1c032f)

![Screenshot 2024-04-09 at 6 13 13 AM](https://github.com/stdlib-js/stdlib/assets/94122792/e8fd373c-7d66-44b0-812c-068ed6613551)
run_affected_tests

2024-04-27 22:21 UTC, Planeshifter commented
Tests should now pass; will merge once CI has passed. Thanks!

2024-04-27 22:21 UTC, Planeshifter approved these changes

2024-04-27 22:27 UTC, merged