feat: add math/base/special/cotd
stdlib-js/stdlib pull request #1772
Opened 2024-03-08 10:13 UTC by the-r3aper7

Resolves #40 

## Description

> What is the purpose of this pull request?

This pull request:

-   a
-   b
-   c

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #
-   fixes #

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [ ] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-03-09 20:53 UTC, the-r3aper7 commented
@Planeshifter should I add checks for when input is `-180` it should return `-Infinity` because I saw in `julia` when passed `-180` it is returning `-Inf`

2024-03-12 16:41 UTC, saisrikardumpeti commented
@Planeshifter this PR is ready for review.

2024-03-13 00:22 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/cotd/README.md
> +> Computes the [cotangent][trigonometric-functions] of an angle measured in degrees..
```suggestion
> Computes the [cotangent][trigonometric-functions] of an angle measured in degrees.
```

2024-03-13 00:22 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/cotd/README.md
> +v = cotd( 90 );
```suggestion
v = cotd( 60.0 );
// returns ~0.58

v = cotd( 90.0 );
```

2024-03-13 00:22 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/cotd/docs/repl.txt
> +    Computes the cotangent of a degrees.
```suggestion
    Computes the cotangent of an angle measured in degrees.
```

2024-03-13 00:23 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/cotd/docs/repl.txt
> +    ~0.58
```suggestion
    > y = {{alias}}( 90.0 )
    0.0
    > y = {{alias}}( 60.0 )
    ~0.58
```

2024-03-13 00:23 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/cotd/docs/types/index.d.ts
> + * var v = cotd( 90 );
```suggestion
 * var v = cotd( 60.0 );
 * // returns ~0.58
 *
 * @example
 * var v = cotd( 90.0 );
```

2024-03-13 00:24 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/cotd/lib/index.js
> +* // returns ~0.58
```suggestion
* v = cotd( 45.0 );
* // returns 1.0
*
* v = cotd( 90.0 );
* // returns 0.0
*
* v = cotd( 60.0 );
* // returns ~0.58
```

2024-03-13 00:26 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/cotd/lib/main.js
> +	if ( x === Infinity || x === -Infinity ) {
Could you please replace this check with usage of `var isInfinite = require( '@stdlib/math/base/assert/is-infinite' );`?

2024-03-13 00:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/cotd/lib/main.js
> +	}
```suggestion
	if ( isInteger( ( ( x / 90.0 ) - 1.0 ) / 2.0 ) ) {
		return 0.0;
	}
```

2024-03-13 00:29 UTC, Planeshifter requested changes
Left some small change requests that hopefully will be easy to resolve.

Ready for merging otherwise, I think.

2024-03-13 02:55 UTC, the-r3aper7 commented
@Planeshifter i have made the changes to this PR and others too.

2024-03-15 01:58 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/cotd/README.md
> +> Computes the [cotangent][trigonometric-functions] of an angle measured in degrees.
```suggestion
> Compute the [cotangent][trigonometric-functions] of an angle measured in degrees.
```

2024-03-15 01:59 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/cotd/package.json
> +  "description": "Computes the cotangent of an angle measured in degrees",
```suggestion
  "description": "Compute the cotangent of an angle measured in degrees",
```

2024-03-15 01:59 UTC, Planeshifter approved these changes
Let's get this one in as well; thanks!

2024-03-15 02:02 UTC, merged

2024-03-15 09:54 UTC, kgryte commented
@the-r3aper7 Same comment. Can you tick the box in the OP indicating that you've read the contributing guidelines? Thanks!