feat: add math/base/special/acscd
stdlib-js/stdlib pull request #1789
Opened 2024-03-08 18:56 UTC by the-r3aper7

Resolves #42 .

## Description

> What is the purpose of this pull request?

This pull request:

-   a
-   b
-   c

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #
-   fixes #

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [ ] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-03-08 20:42 UTC, Pranavchiku commented
@the-r3aper7 we appreciate your contribution but opening 10 PRs in a span of 10 hour just don't makes any sense. Also, it unnecessarily blocks other people to work on those. Neither of PR seems perfect to me, even description is not filled correctly. Reiterating we prefer quality of contribution over number of PRs.

2024-03-09 01:39 UTC, the-r3aper7 commented
yep, i will refactor them today. don't worry.

2024-03-09 03:59 UTC, Planeshifter reviewed
@the-r3aper7 Left a few comments here upon cursory look through the package. 

One important thing that should be added (here and in your other PRs) are tests showing that the function returns the correct values for valid inputs. You can generate a set of test value and add a test with description `the function computes the arccosecant (in degrees)` to `test.js`. Please have a look at other packages on how these are typically authored.

2024-03-09 03:59 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/acscd/README.md
> +-   <span class="package-name">[`@stdlib/math/base/special/atan`][@stdlib/math/base/special/atan]</span><span class="delimiter">: </span><span class="description">compute the arccosecant of a double-
This section is auto-populated, can remove:

```suggestion
```

2024-03-09 03:59 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/acscd/README.md
> +[@stdlib/math/base/special/atan]: https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/atan
This related links are auto-populated, can remove:

```suggestion
```

2024-03-09 03:59 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/acscd/README.md
> +// returns 60.00000000000001
We usually around to up to three digits after the decimal point and use `~` for approximate values in return annotations:

```suggestion
// returns ~60.0
```

2024-03-09 03:59 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/acscd/README.md
> +// returns 44.99999999999999
```suggestion
// returns ~45.0
```

2024-03-09 03:59 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/acscd/README.md
> +v = acscd( sqrt(2) );
```suggestion
v = acscd( sqrt( 2 ) );
```

2024-03-09 03:59 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/acscd/README.md
> +// returns 30.000000000000004
```suggestion
// returns ~30.0
```

2024-03-09 03:59 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/acscd/docs/repl.txt
> +    If input does not satisfies `x >= 1` or `x <= -1` the function returns NaN.
```suggestion
    If `x` does not satisfy `x >= 1` or `x <= -1`, the function returns NaN.
```

2024-03-09 03:59 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/acscd/lib/main.js
> +	return rad2deg(rad);
When all variable declarations can be immediately assigned values, can collapse:

```suggestion
	var rad = acsc( x );
	return rad2deg( rad );
```

(notice also the added spaces around the function parentheses)

2024-03-09 03:59 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/acscd/package.json
> +    "test": "./test"
Directories need to be fixed here and potentially in the other PRs:

```suggestion
    "benchmark": "./benchmark",
    "doc": "./docs",
    "example": "./examples",
    "lib": "./lib",
    "test": "./test"
```

2024-03-09 04:02 UTC, the-r3aper7 commented
cool i will make changes to other PRs.

2024-03-09 07:46 UTC, the-r3aper7 commented
@Planeshifter i have made those changes!

2024-03-09 20:27 UTC, the-r3aper7 commented
@Planeshifter i have made changes all the other PRs too. can you review those.

2024-03-11 23:47 UTC, Planeshifter requested changes
This should be almost ready to merge now. Thanks for updating!

2024-03-11 23:47 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/acscd/docs/types/index.d.ts
> +* @returns arcocsecant (in degree)
```suggestion
* @returns arccosecant (in degree)
```

2024-03-11 23:47 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/acscd/lib/main.js
> +var acsc = require('@stdlib/math/base/special/acsc');
Missing spaces around `require` parentheses:

```suggestion
var rad2deg = require( '@stdlib/math/base/special/rad2deg' );
var acsc = require( '@stdlib/math/base/special/acsc' );
```

2024-03-11 23:47 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/acscd/package.json
> +  "description": "Compute the arccosecant(degree) of a double-precision floating-point number.",
```suggestion
  "description": "Compute the arccosecant (in degrees) of a double-precision floating-point number.",
```

2024-03-11 23:47 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/acscd/package.json
> +    "ponyfill"
```suggestion
    "angle"
```

2024-03-11 23:47 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/acscd/lib/index.js
> +* Compute the arccosecant of a double-precision floating-point number.
```suggestion
* Compute the arccosecant (in degrees) of a double-precision floating-point number.
```

2024-03-11 23:47 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/acscd/README.md
> +> Compute the [arccosecant][arccosecant] in degree of a double-precision floating-point number.
```suggestion
> Compute the [arccosecant][arccosecant] (in degrees) of a double-precision floating-point number.
```

2024-03-11 23:47 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/acscd/README.md
> +Computes the [arccosecant][arccosecant] (in degree) of a double-precision floating-point number.
```suggestion
Computes the [arccosecant][arccosecant] (in degrees) of a double-precision floating-point number.
```

2024-03-11 23:56 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/acscd/docs/repl.txt
> +    Computes the arccosecant of a double-precision floating-point number.
```suggestion
    Computes the arccosecant (in degrees) of a double-precision floating-point
    number.
```

2024-03-11 23:56 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/acscd/docs/repl.txt
> +        Arccosecant (in degree).
```suggestion
        Arccosecant (in degrees).
```

2024-03-11 23:57 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/acscd/lib/main.js
> +* Computes the arccosecant (in degree) of a double-precision floating-point number.
```suggestion
* Computes the arccosecant (in degrees) of a double-precision floating-point number.
```

2024-03-11 23:57 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/acscd/lib/main.js
> +* @returns {number} arccosecant (in degree)
```suggestion
* @returns {number} arccosecant (in degrees)
```

2024-03-11 23:57 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/acscd/docs/types/index.d.ts
> +* Computes the arccosecant (in degree) of a double-precision floating-point number.
```suggestion
* Computes the arccosecant (in degrees) of a double-precision floating-point number.
```

2024-03-12 01:35 UTC, the-r3aper7 commented
cool i will make changes to other PRs. too

2024-03-12 14:00 UTC, Planeshifter approved these changes
Did one more look over the package; looks all good to me!

Will merge shortly.

2024-03-12 14:01 UTC, merged