refactor: update blas/ext/base/ssum to follow current project convent…
stdlib-js/stdlib pull request #1802
Opened 2024-03-09 10:26 UTC by raunak-dev-edu

Resolves #1540.

## Description

> What is the purpose of this pull request?

This pull request:

-   refactors `blas/ext/base/ssum` to follow current project conventions.

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #1540 
-   progresses #1152

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-03-10 13:28 UTC, Pranavchiku requested changes
Heading good, requested changes. Once done this PR will be ready to merge.

2024-03-10 13:28 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/ssum/README.md
> +Copyright (c) 2024 The Stdlib Authors.
```suggestion
Copyright (c) 2020 The Stdlib Authors.
```

Let us not update copyright year unless you add new file.

2024-03-10 13:28 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/ssum/README.md
> +var x = filledarrayBy(10, 'float32', discreteUniform(0, 100));
```suggestion
var x = filledarrayBy( 10, 'float32', discreteUniform(0, 100) );
```

2024-03-10 13:28 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/ssum/benchmark/benchmark.js
> +* Copyright (c) 2024 The Stdlib Authors.
same comment

2024-03-10 13:28 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/ssum/docs/repl.txt
> +
```suggestion
```

2024-03-10 13:28 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/ssum/lib/ndarray.native.js
> +	view = offsetView( x, offset );
```suggestion
	offset = minViewBufferIndex( N, stride, offset );

	view = offsetView( x, offset );

```

2024-03-10 13:28 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/ssum/manifest.json
> +	  {
we use spaces for `manifest.json` instead of TABs

2024-03-10 13:28 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/ssum/manifest.json
> +
trailing new line

2024-03-10 13:28 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/ssum/test/test.ndarray.js
>  	v = ssum( N, x, 2, 0 );
```suggestion
	v = ssum( 4, x, 2, 0 );
```

2024-03-10 13:28 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/ssum/test/test.ndarray.js
> +	N = 4;
same here

2024-03-10 13:28 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/ssum/test/test.ndarray.js
> +	N = 4;
same here

2024-03-10 13:28 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/ssum/test/test.ndarray.native.js
> +	N = 4;
same comments

2024-03-10 13:28 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/ssum/test/test.ssum.js
> -	N = floor(x1.length / 2);
same comments

2024-03-10 13:28 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/ssum/test/test.ssum.native.js
> +	N = 4;
same comments

2024-03-10 14:44 UTC, raunak-dev-edu commented
@Pranavchiku I have applied the chnges as per requested. Please re-review it.

2024-03-20 20:43 UTC, kgryte commented
@raunak-dev-edu Looks like we're getting lint failures on this PR. Those should be addressed before we review.

2024-04-20 17:31 UTC, Planeshifter approved these changes
Thank you, @raunak-dev-edu!

2024-04-20 17:42 UTC, merged