refactor: update blas/ext/base/sfill to follow current projects conve…
stdlib-js/stdlib pull request #1809
Opened 2024-03-09 19:30 UTC by AgPriyanshu18

Resolves #1527 .

## Description

> What is the purpose of this pull request?

This pull request:

-   a refactor blas/ext/base/sfill to follow current projects convention
-   b
-   c

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #1527 
-   fixes #

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [ ] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-03-10 09:52 UTC, kgryte commented
@AgPriyanshu18 Would you mind checking the box in the OP that you've read the contributing guidelines? We require this as an acknowledgment of licensing terms and attribution.

2024-03-10 13:14 UTC, Pranavchiku requested changes
Minor changes requested. Please avoid updating copyright year. Thanks @AgPriyanshu18 !

2024-03-10 13:14 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/sfill/README.md
> +The `N` and `stride` parameters determine which elements in the strided array are accessed at runtime. For example, to fill every other element
```suggestion
The `N` and stride parameters determine which elements in the strided array are accessed at runtime. For example, to fill every other element
```

2024-03-10 13:14 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/sfill/README.md
> +While [`typed array`][mdn-typed-array] views mandate a view offset based on the underlying `buffer`, the `offset` parameter supports indexing semantics based on a starting index. For example, to acce
```suggestion
While [`typed array`][mdn-typed-array] views mandate a view offset based on the underlying `buffer`, the offset parameter supports indexing semantics based on a starting index. For example, to access only the last three elements of the strided array
```

2024-03-10 13:14 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/sfill/benchmark/benchmark.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-10 13:14 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/sfill/benchmark/benchmark.native.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-10 13:14 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/sfill/benchmark/benchmark.ndarray.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-10 13:14 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/sfill/benchmark/benchmark.ndarray.native.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-10 13:14 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/sfill/benchmark/c/Makefile
> +# Copyright (c) 2024 The Stdlib Authors.
```suggestion
# Copyright (c) 2020 The Stdlib Authors.
```

2024-03-10 13:14 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/sfill/benchmark/c/benchmark.length.c
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-10 13:14 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/sfill/binding.gyp
> +# Copyright (c) 2024 The Stdlib Authors.
```suggestion
# Copyright (c) 2020 The Stdlib Authors.
```

2024-03-10 13:14 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/sfill/docs/repl.txt
> +
```suggestion
```

2024-03-10 13:14 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/sfill/docs/types/index.d.ts
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-10 13:14 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/sfill/docs/types/test.ts
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-10 13:14 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/sfill/lib/ndarray.native.js
> +	view = offsetView( x, offset );
```suggestion
	offset = minViewBufferIndex( N, stride, offset );

	view = offsetView( x, offset );

```

2024-03-20 20:25 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sfill/examples/c/Makefile
> +# Copyright (c) 2024 The Stdlib Authors.
```suggestion
# Copyright (c) 2020 The Stdlib Authors.
```

2024-03-20 20:25 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sfill/examples/c/example.c
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-20 20:26 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sfill/examples/index.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-20 20:26 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sfill/include.gypi
> +# Copyright (c) 2024 The Stdlib Authors.
```suggestion
# Copyright (c) 2020 The Stdlib Authors.
```

2024-03-20 20:27 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sfill/README.md
> +Copyright (c) 2024 The Stdlib Authors.
```suggestion
Copyright (c) 2020 The Stdlib Authors.
```

2024-03-20 20:28 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sfill/include/stdlib/blas/ext/base/sfill.h
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-20 20:28 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sfill/lib/index.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-20 20:28 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sfill/lib/main.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-20 20:28 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sfill/lib/native.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-20 20:29 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sfill/lib/ndarray.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-20 20:29 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sfill/lib/ndarray.native.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-20 20:29 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sfill/lib/sfill.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-20 20:30 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sfill/lib/sfill.native.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-20 20:30 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sfill/src/Makefile
> +# Copyright (c) 2024 The Stdlib Authors.
```suggestion
# Copyright (c) 2020 The Stdlib Authors.
```

2024-03-20 20:30 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sfill/src/addon.c
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-20 20:31 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sfill/src/addon.c
This file needs to be updated and refactored. It is not just a simple renaming.

2024-03-20 20:31 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sfill/src/sfill.c
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-20 20:32 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sfill/test/test.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-20 20:32 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sfill/test/test.ndarray.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-20 20:32 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sfill/test/test.ndarray.native.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-20 20:32 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sfill/test/test.sfill.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-20 20:33 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sfill/test/test.sfill.native.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-20 20:34 UTC, kgryte requested changes
I've gone through and undone all the copyright year changes. This PR still needs further updates. Namely, the `addon.c` file needs to be updated and the `manifest.json` file needs to be updated.

2024-04-17 02:11 UTC, Planeshifter approved these changes

2024-04-17 02:19 UTC, merged