refactor: update `blas/ext/base/dcusum` to follow current project conventions
stdlib-js/stdlib pull request #1867
Opened 2024-03-13 18:39 UTC by AuenKr

Resolves #1471.

## Description

> What is the purpose of this pull request?

This pull request:

-   refactors `@stdlib/blas/ext/base/dcusum` to follow current projects convention

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #1471 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-03-14 02:41 UTC, AuenKr commented
@Pranavchiku, can you review the PR?

2024-03-14 04:13 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/dcusum/README.md
> +The `N` and `stride` parameters determine which elements in the strided input and output array are accessed at runtime. For example, to compute the cumulative sum of every other element in strided in
```suggestion
The `N` and `stride` parameters determine which elements in the strided arrays are accessed at runtime. For example, to compute the cumulative sum of every other element in strided input array,
```

2024-03-14 04:16 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/dcusum/docs/repl.txt
> +    input and output array are accessed at runtime.
```suggestion
    arrays are accessed at runtime.
```

2024-03-14 04:17 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/dcusum/examples/index.js
> +var x = filledarrayBy( 10, 'float64', discreteUniform( 0, 100 ));
```suggestion
var x = filledarrayBy( 10, 'float64', discreteUniform( 0, 100 ) );
```

2024-03-14 04:24 UTC, kgryte requested changes
Thanks @AuenKr for working on this, and thank you for being diligent and paying attention to detail on this. Really makes things easy on reviewers.

I think the only thing which needs to be updated is the `manifest.json` file. For an example, see https://github.com/stdlib-js/stdlib/blob/dc84fce54ee45d590860af4eb36845981342671f/lib/node_modules/%40stdlib/blas/ext/base/dfill/manifest.json. In short, we need to add specific build configurations for the addon vs benchmarks vs examples.

2024-03-14 11:56 UTC, AuenKr commented
@kgryte, applied changes in `manifest.json`

2024-03-19 10:42 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/dcusum/src/addon.c
> +	status = napi_create_double( env, stdlib_strided_dcusum( N, sum, (double *)X, strideX, (double *)Y, strideY ), &v );
```suggestion
	status = napi_create_double( env, stdlib_strided_dcusum( N, sum, X, strideX, Y, strideY ), &v );
```

Same comment as #1864 regarding casting.

2024-03-19 10:45 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/dcusum/manifest.json
> +  "options": {},
```suggestion
  "options": {
    "task": "build"
  },
```

2024-03-19 10:47 UTC, kgryte approved these changes
LGTM. Thanks, @AuenKr.

2024-03-19 11:02 UTC, merged