refactor: update blas/ext/base/ssumkbn2 to follow current project con…
stdlib-js/stdlib pull request #1873
Opened 2024-03-13 22:02 UTC by vr-varad

## Description

> What is the purpose of this pull request?

This pull request refactors the ```@stdlib/blas/ext/ssumkbn2``` to follow current project conventions
> ## Checklist
> * [x]  update readme.md
> * [x]  docs
> * [x]  src
> * [x]  include.gypi
> * [x]  manifest.json
> * [x]  package.json
> * [x]  lib
> * [x]  examples
> * [x]  benchmark
> * [x]  test

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #1542 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> For previous context, please refer to discussion #1749.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-03-14 08:15 UTC, vr-varad commented
@kgryte could u review this for any changes to be made.

2024-03-14 08:21 UTC, kgryte commented
@vr-varad This one is looking good. I'll review within the next 24-48 hours.

2024-03-21 00:54 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/ssumkbn2/benchmark/benchmark.js
> +var rand = uniform( -20.0, -10.0 );
```suggestion
var rand = uniform( -10.0, 10.0 );
```

2024-03-21 00:55 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/ssumkbn2/benchmark/benchmark.native.js
> +var rand = uniform( -20.0, -10.0 );
```suggestion
var rand = uniform( -10.0, 10.0 );
```

2024-03-21 00:55 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/ssumkbn2/benchmark/benchmark.ndarray.js
> +var rand = uniform( -20.0, -10.0 );
```suggestion
var rand = uniform( -10.0, 10.0 );
```

2024-03-21 00:55 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/ssumkbn2/benchmark/benchmark.ndarray.native.js
> +var rand = uniform( -20.0, -10.0 );
```suggestion
var rand = uniform( -10.0, 10.0 );
```

2024-03-21 00:56 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/ssumkbn2/lib/ndarray.native.js
> +
```suggestion
	offset = minViewBufferIndex( N, stride, offset );
	view = offsetView( x, offset );
```

2024-03-21 00:58 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/ssumkbn2/manifest.json
> +  "options": {},
This file has mixed TAB and space indentation. It should be 2-space indentation.

Additionally, it needs additional configuration objects. See, e.g., https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/blas/ext/base/dfill/manifest.json

2024-03-21 00:58 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/ssumkbn2/src/addon.c
> +	napi_status status = napi_create_double( env, (double)stdlib_strided_ssumkbn2( N, (float *)X, stride ), &v );
```suggestion
	napi_status status = napi_create_double( env, (double)stdlib_strided_ssumkbn2( N, X, stride ), &v );
```

2024-03-21 00:59 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/ssumkbn2/src/addon.c
> +STDLIB_NAPI_MODULE_EXPORT_FCN( addon )
```suggestion
STDLIB_NAPI_MODULE_EXPORT_FCN( addon )

```

2024-03-21 01:01 UTC, kgryte requested changes
Thanks for working on this @vr-varad. Looks like the main blocker is just updating the `manifest.json` file. Once that is resolved, should be good to merge.

2024-03-21 14:57 UTC, vr-varad commented
Hello @kgryte, I've addressed the issues. Would you mind reviewing it when you have a moment? Thank you for your time!

2024-03-21 20:09 UTC, vr-varad commented
Hello @kgryte, I've addressed the issues. Would you mind reviewing it when you have a moment? Thank you for your time!

2024-03-22 01:56 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/ssumkbn2/lib/ndarray.native.js
> +
```suggestion
```

2024-03-22 01:56 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/ssumkbn2/manifest.json
> +	"options": {
This file has mixed TAB and space indentation. It should be strictly 2-space indentation.

2024-03-22 01:57 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/ssumkbn2/manifest.json
> +  }
```suggestion
  }

```

2024-03-22 07:35 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/ssumkbn2/manifest.json
> +	},
This file still has mixed space and TAB indentation. :)

2024-03-22 07:49 UTC, kgryte commented
@vr-varad What editor are you using? Can you not inspect the indentation locally? Each commit you've made attempting to address the indentation in that file has not actually fixed the indentation.

2024-03-22 07:52 UTC, vr-varad commented
@kgryte I am using VSCODE as the editor and I am using tab size at 2 space indendation

2024-03-22 07:53 UTC, vr-varad commented
for the last commit I did it manually but don't know why its not working

2024-03-22 07:54 UTC, kgryte commented
You want to indent using spaces, not tabs, for that file. You should be able to run a command in VSCode to convert all tabs to spaces.

2024-03-22 07:57 UTC, vr-varad commented
ya I got it Thanks @kgryte

2024-03-22 07:58 UTC, kgryte approved these changes
LGTM. Thanks, @vr-varad!

2024-03-22 08:05 UTC, merged