feat: add C implementation for math/base/special/asind
stdlib-js/stdlib pull request #1876
Opened 2024-03-14 01:54 UTC by Rejoan-Sardar

Resolves # .

## Description

> What is the purpose of this pull request?

This pull request:

-   add C implementation for math/base/special/asind

## Related Issues

> Does this pull request have any related issues?

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [X] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

2024-03-15 10:33 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/asind/include/stdlib/math/base/special/asind.h
> +#endif // !STDLIB_MATH_BASE_SPECIAL_ASIND_H
Add a trailing new line

2024-03-15 10:34 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/asind/src/main.c
> +* // returns 0.0
please refer other packages, this is javascript one.

2024-03-15 10:34 UTC, Pranavchiku requested changes
Left a few comments above, once addressed this will be good to merge.

2024-03-15 10:44 UTC, Rejoan-Sardar commented
@Pranavchiku I have addressed all the issues you mentioned in your review. Please take a look at the changes

2024-03-16 16:51 UTC, Planeshifter approved these changes
LGTM. Thanks!

2024-03-16 16:52 UTC, merged