refactor: update `blas/ext/base/sdsapxsum` to follow current project conventions
stdlib-js/stdlib pull request #1889
Opened 2024-03-14 16:42 UTC by AuenKr

Resolves #1521 .

## Description

> What is the purpose of this pull request?

This pull request:

-   update `@stdlib/blas/ext/base/sdsapxsum` to follow current project conventions

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #1521 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-03-20 01:02 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/sdsapxsum/docs/repl.txt
>      > var x = new {{alias:@stdlib/array/float32}}( [ 1.0, -2.0, 3.0, 2.0, 5.0, -1.0 ] );
Already defined above (had a mistake already in `repl.txt`) Let's fix it:

```suggestion
    > x = new {{alias:@stdlib/array/float32}}( [ 1.0, -2.0, 3.0, 2.0, 5.0, -1.0 ] );
```

2024-03-20 01:03 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/sdsapxsum/examples/index.js
> +var x = filledarrayBy( 10, 'float32', discreteUniform( 0, 100 ));
```suggestion
var x = filledarrayBy( 10, 'float32', discreteUniform( 0, 100 ) );
```

2024-03-20 01:07 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/sdsapxsum/src/addon.c
> +	status = napi_create_double( env, stdlib_strided_sdsapxsum( N, alpha, X, stride ), &v );
```suggestion
	status = napi_create_double( env, (double)stdlib_strided_sdsapxsum( N, alpha, X, stride ), &v );
```

2024-03-20 01:09 UTC, Planeshifter requested changes
Looks good; just a few changes needed and we can merge your PR. Thanks!

2024-03-20 13:08 UTC, AuenKr commented
@Planeshifter, applied all suggestions.

2024-03-21 01:17 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sdsapxsum/lib/ndarray.native.js
> +
```suggestion
```

2024-03-21 01:18 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sdsapxsum/manifest.json
> +      "dependencies": []
You're missing the `sdsapxsumpw` dependency here and below.

2024-03-21 01:21 UTC, kgryte requested changes
Thanks for working on this, @AuenKr. Need to add the missing dependency in the `manifest.json` configuration objects, and this should be ready for merge.

2024-03-21 12:41 UTC, AuenKr commented
@kgryte, added dependency in `manifest.json` file

2024-03-21 12:57 UTC, Planeshifter approved these changes
LGTM! Thanks.

2024-03-21 12:58 UTC, merged