refactor: update `blas/ext/base/sdsapxsumpw` to follow current project conventions
stdlib-js/stdlib pull request #1925
Opened 2024-03-16 20:07 UTC by Jai0401

Resolves #1522 

## Description
This pull request refactors `blas/ext/base/sdsapxsumpw` to follow current project conventions.

## Related Issues
#1152 
#788 

This pull request:

-   resolves #1522 
-  progresses #1152

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-03-17 13:58 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/sdsapxsumpw/README.md
> +Copyright (c) 2024 The Stdlib Authors.
```suggestion
Copyright (c) 2020 The Stdlib Authors.
```

2024-03-17 13:59 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/sdsapxsumpw/README.md
> +var x = filledarrayBy(10, 'float32', discreteUniform( 0, 100 ));
```suggestion
var x = filledarrayBy( 10, 'float32', discreteUniform( 0, 100 ) );
```

2024-03-17 13:59 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/sdsapxsumpw/benchmark/benchmark.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-17 13:59 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/sdsapxsumpw/benchmark/benchmark.js
> +var rand = uniform( -100.0, 100.0 );
```suggestion
var rand = uniform( -10.0, 10.0 );
```

2024-03-17 13:59 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/sdsapxsumpw/benchmark/benchmark.native.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-17 14:00 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/sdsapxsumpw/benchmark/benchmark.native.js
> +var rand = uniform( -100.0, 100.0 );
```suggestion
var rand = uniform( -10.0, 10.0 );
```

2024-03-17 14:00 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/sdsapxsumpw/benchmark/benchmark.ndarray.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-17 14:00 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/sdsapxsumpw/benchmark/benchmark.ndarray.js
> +var rand = uniform( -100.0, 100.0 );
```suggestion
var rand = uniform( -10.0, 10.0 );
```

2024-03-17 14:00 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/sdsapxsumpw/benchmark/benchmark.ndarray.native.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-17 14:00 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/sdsapxsumpw/benchmark/benchmark.ndarray.native.js
> +var rand = uniform( -100.0, 100.0 );
```suggestion
var rand = uniform( -10.0, 10.0 );
```

2024-03-17 14:01 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/sdsapxsumpw/examples/index.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-17 14:01 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/sdsapxsumpw/lib/index.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-17 14:01 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/sdsapxsumpw/lib/ndarray.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-17 14:01 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/sdsapxsumpw/lib/ndarray.native.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-17 14:02 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/sdsapxsumpw/lib/ndarray.native.js
> +	view = offsetView( x, offset );
```suggestion

	offset = minViewBufferIndex( N, stride, offset );
	view = offsetView( x, offset );

```

2024-03-17 14:02 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/sdsapxsumpw/manifest.json
> +	  }
Incorrect indentation

2024-03-17 14:03 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/sdsapxsumpw/src/addon.c
> +STDLIB_NAPI_MODULE_EXPORT_FCN( addon )
trailing line required.

2024-03-17 14:03 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/sdsapxsumpw/test/test.ndarray.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-17 14:03 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/sdsapxsumpw/test/test.ndarray.js
Please remove N and use 4 directly

2024-03-17 14:03 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/sdsapxsumpw/test/test.ndarray.js
same comment at all places

2024-03-17 14:04 UTC, Pranavchiku requested changes
Left comments, please address those.

2024-03-17 14:18 UTC, Jai0401 commented
@Pranavchiku thanks for the review, working on suggestions.

2024-03-17 15:03 UTC, Jai0401 commented
Hello @Pranavchiku, I have implemented the necessary changes as per our discussion. Please review the updates and let me know if any further adjustments are required. Thank you for your guidance and support.

2024-03-17 15:38 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/sdsapxsumpw/manifest.json
> +	  }
This file has incorrect indentation, you may setup editor config extension in VSCode.

2024-03-17 15:38 UTC, Pranavchiku requested changes
Just fix indentation in `manifest.json` and this will be ready to merge.

2024-03-17 16:06 UTC, Jai0401 commented
Hello @Pranavchiku, I've made the requested changes. Please review and let me know if anything else is needed. Thanks for your help!

2024-03-21 02:25 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/sdsapxsumpw/README.md
> +The `N` and `stride` parameters determine which elements in the strided array are accessed at runtime. For example, to compute the sum of every other element in `x`,
```suggestion
The `N` and stride parameters determine which elements in the strided array are accessed at runtime. For example, to compute the sum of every other element in `x`,
```

2024-03-21 02:44 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sdsapxsumpw/docs/repl.txt
>      > var x = new {{alias:@stdlib/array/float32}}( [ 1.0, -2.0, 3.0, 2.0, 5.0, -1.0 ] );
```suggestion
    > x = new {{alias:@stdlib/array/float32}}( [ 1.0, -2.0, 3.0, 2.0, 5.0, -1.0 ] );
```

2024-03-21 02:46 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sdsapxsumpw/src/addon.c
> +	return v;
```suggestion
	STDLIB_NAPI_ARGV( env, info, argv, argc, 4 );
	STDLIB_NAPI_ARGV_INT64( env, N, argv, 0 );
	STDLIB_NAPI_ARVG_FLOAT( env, alpha, argv, 1 );
	STDLIB_NAPI_ARGV_INT64( env, stride, argv, 3 );
	STDLIB_NAPI_ARGV_STRIDED_FLOAT32ARRAY( env, X, N, stride, argv, 2 );

	napi_value v;
	napi_status status = napi_create_double( env, (double)stdlib_strided_sdsapxsumpw( N, alpha, X, stride ), &v );
	assert( status == napi_ok );

	return v;
```

This is incorrect. You also need to handle the scalar constant `alpha`.

2024-03-21 02:47 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/sdsapxsumpw/src/addon.c
> +#include "stdlib/napi/argv_int64.h"
```suggestion
#include "stdlib/napi/argv_int64.h"
#include "stdlib/napi/argv_float.h"
```

2024-03-21 02:49 UTC, kgryte requested changes
Thanks for working on this, @Jai0401. You're missing changes to the `manifest.json` file, which needs to be updated to include additional build configurations.

2024-03-21 02:53 UTC, kgryte commented
See https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/blas/ext/base/dfill/manifest.json for an example.

2024-03-21 13:52 UTC, Jai0401 commented
@kgryte I've made the requested changes. Please review and let me know if anything else is needed. Thanks for your help!

2024-03-22 01:29 UTC, Planeshifter approved these changes
Thanks for the edits! Took a final look and this is now all looking good. Will merge shortly.

2024-03-22 01:30 UTC, merged