feat: add C implementation for math/base/special/minmax
stdlib-js/stdlib pull request #1939
Opened 2024-03-18 01:11 UTC by Rejoan-Sardar

Resolves a part of #649 .

## Description

> What is the purpose of this pull request?

This pull request:

-   add C implementation for math/base/special/minmax

## Related Issues

> Does this pull request have any related issues?

This pull request:

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [X] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

2024-03-24 19:06 UTC, Planeshifter requested changes
Thanks for this PR! Left some comments that will need to be addressed.

2024-03-24 19:06 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/minmax/README.md
> +// returns [ -0.0, +0.0 ];
Example code needs to be updated as it currently doesn't match function signature above.

2024-03-24 19:06 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/minmax/src/main.c
> +double stdlib_base_minmax( const double x, const double y, double* min, double* max ) {
```suggestion
void stdlib_base_minmax( const double x, const double y, double* min, double* max ) {
```

2024-03-24 19:06 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/minmax/src/main.c
> +* @returns {Array<number>} minimum and maximum values
Need to update the parameter and return annotations here. Notice this is not JSDoc.

2024-03-24 19:06 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/minmax/test/test.native..js
> +/**
File has two periods right now, please change `..js` to `.js`.

2024-03-24 19:06 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/minmax/src/main.c
> +* double v = stdlib_base_minmax( 3.14, 4.2 );
Examples need to be updated to match implementation.

2024-03-24 19:06 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/minmax/src/addon.c
> +static napi_value addon( napi_env env, napi_callback_info info ) {
Should be possible to significantly simplify this file via the utilities in https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/napi.

2024-03-24 19:06 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/minmax/include/stdlib/math/base/special/minmax.h
> +double stdlib_base_minmax( const double x, const double y, double *min, double *max );
```suggestion
void stdlib_base_minmax( const double x, const double y, double *min, double *max );
```

2024-03-24 19:06 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/minmax/benchmark/c/native/benchmark.c
> +	double z;
Would be good to rename `z` to `max` here.

2024-04-01 11:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/minmax/src/main.c
> +    return;
You have mixed tab and space indentation. It should be TAB indentation.

2024-04-12 07:27 UTC, closed without merging