[RFC]: refactor `blas/ext/base/scusumkbn2` to follow current project conventions
stdlib-js/stdlib pull request #1961
Opened 2024-03-20 00:13 UTC by headlessNode

Resolves #1518 

## Description

> What is the purpose of this pull request?

This pull request:

-   refactors `blas/ext/base/scusumkbn2` to follow current project conventions

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #1518 
-   progresses #1152

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-03-22 02:23 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn2/binding.gyp
> +# Copyright (c) 2024 The Stdlib Authors.
```suggestion
# Copyright (c) 2020 The Stdlib Authors.
```

2024-03-22 02:24 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn2/benchmark/c/benchmark.length.c
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-22 02:24 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn2/benchmark/c/Makefile
> +# Copyright (c) 2024 The Stdlib Authors.
```suggestion
# Copyright (c) 2020 The Stdlib Authors.
```

2024-03-22 02:25 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn2/benchmark/benchmark.ndarray.native.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-22 02:25 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn2/benchmark/benchmark.ndarray.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-22 02:25 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn2/benchmark/benchmark.native.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-22 02:26 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn2/benchmark/benchmark.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-22 02:26 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn2/README.md
> +Copyright (c) 2024 The Stdlib Authors.
```suggestion
Copyright (c) 2020 The Stdlib Authors.
```

2024-03-22 02:26 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn2/src/Makefile
> +# Copyright (c) 2024 The Stdlib Authors.
```suggestion
# Copyright (c) 2020 The Stdlib Authors.
```

2024-03-22 02:27 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn2/test/test.ndarray.native.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-22 02:27 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn2/test/test.scusumkbn2.js
>  	scusumkbn2( N, 0.0, x1, -2, y1, 1 );
```suggestion
	N = 3;

	scusumkbn2( 3, 0.0, x1, -2, y1, 1 );
```

2024-03-22 02:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn2/test/test.scusumkbn2.native.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-22 02:28 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn2/test/test.scusumkbn2.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-22 02:29 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn2/examples/index.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-22 02:29 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn2/examples/c/example.c
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-22 02:30 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn2/docs/types/index.d.ts
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-22 02:30 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn2/docs/types/test.ts
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-22 02:30 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn2/examples/c/Makefile
> +# Copyright (c) 2024 The Stdlib Authors.
```suggestion
# Copyright (c) 2020 The Stdlib Authors.
```

2024-03-22 02:31 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn2/include.gypi
> +# Copyright (c) 2024 The Stdlib Authors.
```suggestion
# Copyright (c) 2020 The Stdlib Authors.
```

2024-03-22 02:31 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn2/lib/index.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-22 02:31 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn2/include/stdlib/blas/ext/base/scusumkbn2.h
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-22 02:31 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn2/src/scusumkbn2.c
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-22 02:32 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn2/test/test.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-22 02:32 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn2/test/test.ndarray.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-22 02:33 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn2/lib/scusumkbn2.native.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-22 02:33 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn2/lib/ndarray.native.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-22 02:33 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn2/lib/scusumkbn2.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-22 02:33 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn2/lib/native.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-22 02:34 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn2/lib/main.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-22 02:34 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn2/lib/ndarray.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-22 02:36 UTC, Planeshifter requested changes
This looks overall very good.

Notice I had to revert the copyright year changes: It is our convention to not update them when files are edited, only when they are first committed to the repository.

One thing: Please edit the `manifest.json` file to be 2-space indented and to have `benchmark` and `example` configurations.

2024-03-22 18:05 UTC, headlessNode commented
@Planeshifter could you please elaborate a bit about adding `benchmark` and `example` configurations to `manifest.json`? 
I've looked at various merged PRs for the similar issues but I'm unsure of how to implement. Please guide me in this mattter.

2024-03-22 21:17 UTC, headlessNode commented
@Planeshifter I've added the suggested changes, please check.

2024-03-23 01:58 UTC, Planeshifter approved these changes
Thanks! Checks out, looks all good to me now. Will merge shortly.

2024-03-23 02:03 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn2/src/addon.c
> +	STDLIB_NAPI_ARGV_FLOAT( env, alpha, argv, 1 );
```suggestion
	STDLIB_NAPI_ARGV_FLOAT( env, sum, argv, 1 );
```

2024-03-23 02:08 UTC, merged