refactor: update `blas/ext/base/dapxsumkbn2` to follow current project conventions
stdlib-js/stdlib pull request #1978
Opened 2024-03-21 06:11 UTC by kumarsuraj212003

Resolves #1467 .

## Description

> What is the purpose of this pull request?

refactor `blas/ext/base/dapxsumkbn2` to follow current project conventions

This pull request:

## Related Issues
#788, #1152

> Does this pull request have any related issues?

This pull request:

-   resolves #1467
-   progresses #1152

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-03-23 22:06 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dapxsumkbn2/manifest.json
> +    "options": {},
Can you please change this file to 2-space indentation and add configurations for the examples and benchmarks?

2024-03-23 22:07 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dapxsumkbn2/src/addon.c
> +    napi_status status = napi_create_double( env, stdlib_strided_dapxsumkbn2( N, alpha, (double *)X, stride ), &v );
The cast should not be needed anymore: 

```suggestion
    napi_status status = napi_create_double( env, stdlib_strided_dapxsumkbn2( N, alpha, X, stride ), &v );
```

2024-03-23 22:11 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dapxsumkbn2/manifest.json
> +                "stdlib/napi/argv_strided_float64array.h"
The dependencies should be listed as stdlib packages:

```suggestion
                "@stdlib/napi/export",
                "@stdlib/napi/argv",
                "@stdlib/napi/argv-int64",
                "@stdlib/napi/argv-strided-float64array"
```

2024-03-23 22:13 UTC, Planeshifter requested changes
Thanks for working on this! Left a few comments; mainly the `manifest.json` file has to be updated. Please have a look at how we have been updating it in some of the linked PRs in the RFC.

2024-03-24 06:51 UTC, kumarsuraj212003 commented
@Planeshifter thanks for review, I added suggested changes, can you please tell me why my  `run_affected_tests / Run affected tests (pull_request)` test is failling.

2024-03-24 07:41 UTC, kgryte commented
@kumarsuraj212003 The `manifest.json` file still needs updating.

2024-03-24 08:24 UTC, kumarsuraj212003 commented
@kgryte `run_affected_tests / Run affected tests (pull_request)` is still failing. Could you please investigate the error.It helps me alot. Thank you

2024-03-24 09:26 UTC, kgryte commented
Done. You're missing an include and the `manifest.json` file is missing a dep.

2024-03-24 10:31 UTC, kumarsuraj212003 commented
@kgryte I think I understood what you wanted me to correct, and I have made the necessary adjustments, including adding the missing include and updating the dependencies in the `manifest.json` file. Thank you again for helping me identify and resolve my errors.

2024-03-26 01:30 UTC, Planeshifter approved these changes
Thanks for getting this PR into a good shape! LGTM. I will merge it shortly.

2024-03-26 01:34 UTC, merged