feat: add C implementation for `math/base/special/atan2`
stdlib-js/stdlib pull request #1981
Opened 2024-03-21 20:16 UTC by Pushpendra766

Resolves # .

## Description

> What is the purpose of this pull request?

This pull request:

-   Adds C implementation for [math/base/special/atan2](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/atan2)
     `double out = stdlib_base_atan2( 2.0, 2.0 ); `

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #1923 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-03-22 01:13 UTC, Planeshifter commented
/stdlib update-copyright-years

2024-03-22 01:14 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/atan2/benchmark/benchmark.native.js
> +		z = Math.atan2( x, y ); // eslint-disable-line stdlib/no-builtin-math
```suggestion
		z = atan2( x, y );
```

2024-03-22 01:17 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/atan2/README.md
> +#### stdlib_base_atan2( x )
```suggestion
#### stdlib_base_atan2( y, x )
```

2024-03-22 01:17 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/atan2/README.md
> +-   **x**: `[in] double` input value.
Need to document both parameters here.

2024-03-22 01:17 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/atan2/README.md
> +double stdlib_base_atan2( const double x );
```suggestion
double stdlib_base_atan2( const double y, const double x );
```

2024-03-22 01:22 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/atan2/lib/native.js
> +* Computes the arctangent of a double-precision floating-point number.
```suggestion
* Computes the angle in the plane (in radians) between the positive x-axis and the ray from `(0,0)` to the point `(x,y)`.
```

2024-03-22 01:22 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/atan2/lib/native.js
> +* @param {number} x - input value
```suggestion
* @param {number} y - `y` coordinate
* @param {number} x - `x` coordinate
```

2024-03-22 01:22 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/atan2/lib/native.js
> +* @returns {number} arctangent (in radians)
```suggestion
* @returns {number} angle (in radians)
```

2024-03-22 01:23 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/atan2/src/main.c
> +    if(stdlib_base_is_nan(x) || stdlib_base_is_nan(y)){
Please add spaces around parentheses here and below to match our code style conventions.

2024-03-22 01:24 UTC, Planeshifter requested changes
Thanks for working on this! I left an initial set of comments and suggestions that need to be addressed.

2024-03-22 07:53 UTC, Pushpendra766 commented
> /stdlib update-copyright-years

should I change it to 2024 ?

2024-03-22 13:17 UTC, Planeshifter commented
@Pushpendra766 The `/stdlib update-copyright-years` command automatically has our stdlib-bot update the copyright years for added files, see: https://github.com/stdlib-js/stdlib/pull/1981/commits/5c3356e8164935be474d510421a4b3a56e49bb2b. Just pull down the changes, no reason for you to manually change them.

2024-03-22 18:03 UTC, Pushpendra766 commented
/

> @Pushpendra766 The `/stdlib update-copyright-years` command automatically has our stdlib-bot update the copyright years for added files, see: [5c3356e](https://github.com/stdlib-js/stdlib/commit/5c3356e8164935be474d510421a4b3a56e49bb2b). Just pull down the changes, no reason for you to manually change them.

Okay, thanks.
I have done the suggested changes. I hope it will fix the formatting and documentation issues.

2024-03-23 14:40 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/atan2/src/main.c
> +
```suggestion
```

2024-03-23 14:41 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/atan2/src/main.c
> +* @returns {number} angle (in radians)
```suggestion
* @param y    `y` coordinate
* @param x    `x` coordinate
* @return       angle (in radians)
```

2024-03-23 14:43 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/atan2/src/main.c
> +}
```suggestion
    if ( stdlib_base_is_nan( x ) || stdlib_base_is_nan( y ) ) {
        return 0.0 / 0.0;
    }
    if ( stdlib_base_is_infinite( x ) ) {
        if ( x == STDLIB_CONSTANT_FLOAT64_PI ) {
            if ( stdlib_base_is_infinite( y ) ) {
                return stdlib_base_copysign( STDLIB_CONSTANT_FLOAT64_PI / 4.0, y );
            }
            return stdlib_base_copysign( 0.0, y );
        }
        // Case: x is -Infinity
        if ( stdlib_base_is_infinite( y ) ) {
            return stdlib_base_copysign( 3.0 * STDLIB_CONSTANT_FLOAT64_PI / 4.0, y );
        }
        return stdlib_base_copysign( STDLIB_CONSTANT_FLOAT64_PI, y );
    }
    if ( stdlib_base_is_infinite( y ) ) {
        return stdlib_base_copysign( STDLIB_CONSTANT_FLOAT64_PI / 2.0, y );
    }
    if ( y == 0.0 ) {
        if ( x >= 0.0 && !stdlib_base_float64_signbit( x ) ) {
            return stdlib_base_copysign( 0.0, y );
        }
        return stdlib_base_copysign( STDLIB_CONSTANT_FLOAT64_PI, y );
    }
    if ( x == 0.0 ) {
        return stdlib_base_copysign( STDLIB_CONSTANT_FLOAT64_PI / 2.0, y );
    }
    q = stdlib_base_atan( y / x );
    if ( x < 0.0 ) {
        if ( q <= 0.0 ) {
            return q + STDLIB_CONSTANT_FLOAT64_PI;
        }
        return q - STDLIB_CONSTANT_FLOAT64_PI;
    }
    return q;
}
```

2024-03-23 14:44 UTC, Planeshifter requested changes
CI is currently failing, please take a look. I think the `manifest.json` file is missing used packages in the `examples` and `benchmark` configurations, namely `random/base/randu`, but looks like we also have a problem with the implementation since the tests fail, although at first glance, it looks fine to me and matching the JS implementation.

2024-03-23 18:03 UTC, Pushpendra766 commented
> CI is currently failing, please take a look. I think the `manifest.json` file is missing used packages in the `examples` and `benchmark` configurations, namely `random/base/randu`, but looks like we also have a problem with the implementation since the tests fail, although at first glance, it looks fine to me and matching the JS implementation.

`random/base/randu` is not a dependency for atan2, as far as I know.
Also, I checked the implementation thoroughly. It matches the JavaScript implementation of the function.

2024-03-25 09:52 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/atan2/README.md
> +Compute the angle in the plane (in radians) between the positive x-axis and the ray from `(0,0)` to the point `(x,y)`.
```suggestion
Computes the angle in the plane (in radians) between the positive x-axis and the ray from `(0,0)` to the point `(x,y)`.
```

2024-03-25 09:53 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/atan2/README.md
> +Compute the angle in the plane (in radians) between the positive x-axis and the ray from `(0,0)` to the point `(x,y)`.
Please do not commit it, I'll apply every change in batch.

2024-03-25 09:54 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/atan2/README.md
> +#include "stdlib/random/base/randu"
```suggestion
#include "stdlib/random/base/randu.h"
```

2024-03-25 09:57 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/atan2/README.md
> +}
```suggestion
#include "stdlib/math/base/special/atan2.h"
#include <stdlib.h>
#include <stdio.h>

int main( void ) {
    double y;
    double x;
    double v;
    int i;

    for ( i = 0; i < 100; i++ ) {
        y = ( ( (double)rand() / (double)RAND_MAX ) * 100.0 );
        x = ( ( (double)rand() / (double)RAND_MAX ) * 100.0 );
        v = stdlib_base_atan2( y, x );
        printf( "atan2(%lf, %lf) = %lf\n", y, x, v );
    }
    return 0;
}
```

2024-03-25 09:59 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/atan2/benchmark/c/native/benchmark.c
> +#include <stdlib.h>
```suggestion
#include "stdlib/math/base/special/atan2.h"
#include <stdlib.h>
```

2024-03-25 09:59 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/atan2/benchmark/c/native/benchmark.c
> +		z = atan2( x, y );
```suggestion
		z = stdlib_base_atan2( y, x );
```

2024-03-25 09:59 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/atan2/benchmark/c/native/benchmark.c
> +		printf( "# c::%s\n", NAME );
```suggestion
		printf( "# c::native::%s\n", NAME );
```

2024-03-25 10:00 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/atan2/examples/c/example.c
> +}
```suggestion
#include "stdlib/math/base/special/atan2.h"
#include <stdlib.h>
#include <stdio.h>

int main( void ) {
	double y;
	double x;
	double v;
	int i;
	for ( i = 0; i < 100; i++ ) {
		y = ( ( (double)rand() / (double)RAND_MAX ) * 100.0 );
		x = ( ( (double)rand() / (double)RAND_MAX ) * 100.0 );
		v = stdlib_base_atan2( y, x );
		printf( "atan2(%lf, %lf) = %lf\n", y, x, v );
	}
	return 0;
}
```

2024-03-25 10:01 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/atan2/include/stdlib/math/base/special/atan2.h
> +* Computes the arctangent of a double-precision floating-point number.
```suggestion
* Computes the angle in the plane (in radians) between the positive x-axis and the ray from `(0,0)` to the point `(x,y)`.
```

2024-03-25 10:03 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/atan2/manifest.json
> +        "@stdlib/math/base/napi/unary",
```suggestion
        "@stdlib/math/base/napi/binary",
```

2024-03-25 10:04 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/atan2/src/addon.c
> +#include "stdlib/math/base/napi/unary.h"
```suggestion
#include "stdlib/math/base/napi/binary.h"
```

2024-03-25 10:04 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/atan2/src/addon.c
> +STDLIB_MATH_BASE_NAPI_MODULE_D_D( stdlib_base_atan2 )
```suggestion
STDLIB_MATH_BASE_NAPI_MODULE_DD_D( stdlib_base_atan2 )
```

2024-03-25 10:04 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/atan2/src/main.c
> +* @return       angle (in radians)
```suggestion
* @param x    `x` coordinate
* @return      angle (in radians)
```

2024-03-25 10:07 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/atan2/src/main.c
> +    return q;
```suggestion
	double q;
	if ( stdlib_base_is_nan( x ) |	dlib_base_is_nan( y ) ) {
		return 0.0 / 0.0; // NaN
	}
	if ( stdlib_base_is_infinite( x ) ) {
		if ( x == STDLIB_CONSTANT_FLOAT64_PI ) {
			if ( stdlib_base_is_infinite( y ) ) {
				return stdlib_base_copysign( STDLIB_CONSTANT_FLOAT64_PI / 4.0, y );
			}
			return stdlib_base_copysign( 0.0, y );
		}
		// Case: x is -Infinity
		if ( stdlib_base_is_infinite( y ) ) {
			return stdlib_base_copysign( 3.0 * STDLIB_CONSTANT_FLOAT64_PI / 4.0, y );
		}
		return stdlib_base_copysign( STDLIB_CONSTANT_FLOAT64_PI, y );
	}
	if ( stdlib_base_is_infinite( y ) ) {
		return stdlib_base_copysign( STDLIB_CONSTANT_FLOAT64_PI / 2.0, y );
	}
	if ( y == 0.0 ) {
		if ( x >= 0.0 && !stdlib_base_float64_signbit( x ) ) {
			return stdlib_base_copysign( 0.0, y );
		}
		return stdlib_base_copysign( STDLIB_CONSTANT_FLOAT64_PI, y );
	}
	if ( x == 0.0 ) {
		return stdlib_base_copysign( STDLIB_CONSTANT_FLOAT64_PI / 2.0, y );
	}
	q = stdlib_base_atan( y / x );
	if ( x < 0.0 ) {
		if ( q <= 0.0 ) {
			return q + STDLIB_CONSTANT_FLOAT64_PI;
		}
		return q - STDLIB_CONSTANT_FLOAT64_PI;
	}
	return q;
```

2024-03-25 10:09 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/atan2/src/main.c
> +    return q;
TAB indentation is required

2024-03-25 10:10 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/atan2/src/main.c
> +	if ( stdlib_base_is_nan( x ) |	dlib_base_is_nan( y ) ) {
```suggestion
	if ( stdlib_base_is_nan( x ) |	stdlib_base_is_nan( y ) ) {
```

2024-03-25 10:11 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/atan2/src/main.c
> +	if ( stdlib_base_is_nan( x ) |	stdlib_base_is_nan( y ) ) {
```suggestion
	if ( stdlib_base_is_nan( x ) ||	stdlib_base_is_nan( y ) ) {
```

2024-03-25 10:12 UTC, Pranavchiku approved these changes
Tested locally, everything works well. Thanks @Pushpendra766 !

2024-03-26 01:55 UTC, Planeshifter approved these changes

2024-03-26 01:59 UTC, merged