update blas/ext/base/dapxsumors to follow current project conventions #1468
stdlib-js/stdlib pull request #1993
Opened 2024-03-22 14:23 UTC by ShivamAhir

Resolves # .

## Description
 update blas/ext/base/dapxsumors to follow current project conventions #1468

This pull request:

-   a
-   b
-   c

## Related Issues

> Does this pull request have any related issues? 

This pull request:

-   resolves #1468 
-   fixes #

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-03-23 21:15 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dapxsumors/README.md
> +var x = filledarrayBy(10, 'float32', discreteUniform(0, 100));
```suggestion
var x = filledarrayBy( 10, 'float32', discreteUniform( 0, 100 ) );
```

2024-03-23 21:16 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dapxsumors/docs/repl.txt
>      at runtime.
```suggestion
    The `N` and stride parameters determine which elements in the strided array are 
    accessed at runtime.
```

2024-03-23 21:19 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dapxsumors/manifest.json
>  	]
The indentation in the `manifest.json` file should be changed to 2-spaces and configurations for the examples and benchmarks should be added, see the linked PRs.

2024-03-23 21:19 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dapxsumors/src/addon.c
> +	napi_status status = napi_create_double( env, stdlib_strided_dapxsumors( N, alpha, (double *)X, stride ), &v );
Casting to double is not necessary anymore here:

```suggestion
	napi_status status = napi_create_double( env, stdlib_strided_dapxsumors( N, alpha, X, stride ), &v );
```

2024-03-23 21:20 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dapxsumors/test/test.dapxsumors.js
> +	v = dapxsumors( 4, 5.0, x, 2 );
Please remove `N` variable declarations in this file as they are now unused.

2024-03-23 21:22 UTC, Planeshifter requested changes
Thanks for working on this! Left a bunch of requested changes that should hopefully be easy to resolve.

2024-03-24 18:36 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dapxsumors/benchmark/benchmark.js
```suggestion


```

2024-03-24 18:43 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dapxsumors/benchmark/benchmark.ndarray.js
```suggestion


```

2024-03-24 18:43 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dapxsumors/docs/repl.txt
> +    10
```suggestion
    > {{alias}}( 3, 5.0, x1, 2 )
    14.0
```

2024-03-24 18:49 UTC, Planeshifter approved these changes
Thanks! Will merge shortly after CI has passed.

2024-03-24 18:49 UTC, merged

2024-03-24 19:03 UTC, ShivamAhir commented
@Planeshifter grateful for your ongoing guidance and support. Hard to manage without it.😊