refactor update `blas/ext/base/dsumpw` to follow current project conventions
stdlib-js/stdlib pull request #1994
Opened 2024-03-22 15:25 UTC by rajutkarsh07

Resolves #1508

## Description

> What is the purpose of this pull request?
update `blas/ext/base/dsumpw` to follow current project conventions

This pull request:

-  progresses #1152 
-  fixes #1508 

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #
-   fixes #

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-03-23 22:14 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dsumpw/README.md
> +Copyright (c) 2024 The Stdlib Authors.
```suggestion
Copyright (c) 2020 The Stdlib Authors.
```

2024-03-23 22:14 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dsumpw/README.md
> +var x = filledarrayBy(10, 'float64', discreteUniform(0, 100));
```suggestion
var x = filledarrayBy( 10, 'float64', discreteUniform( 0, 100 ) );
```

2024-03-23 22:15 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dsumpw/benchmark/benchmark.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-23 22:15 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dsumpw/benchmark/benchmark.native.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-23 22:15 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dsumpw/benchmark/benchmark.ndarray.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-23 22:15 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dsumpw/benchmark/benchmark.ndarray.native.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-23 22:16 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dsumpw/examples/index.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-23 22:16 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dsumpw/lib/index.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-23 22:16 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dsumpw/lib/native.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-23 22:17 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dsumpw/test/test.dsumpw.js
> +
```suggestion

```

2024-03-23 22:17 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dsumpw/test/test.dsumpw.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-23 22:18 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dsumpw/test/test.dsumpw.native.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-23 22:18 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dsumpw/test/test.ndarray.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-23 22:18 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dsumpw/test/test.ndarray.native.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-23 22:18 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dsumpw/lib/ndarray.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-23 22:18 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dsumpw/lib/ndarray.native.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-23 22:20 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dsumpw/manifest.json
> +      			"stdlib/napi/argv_strided_float64array.h"
```suggestion
				"@stdlib/napi/export",
      			"@stdlib/napi/argv",
      			"@stdlib/napi/argv-int64",
      			"@stdlib/napi/argv-strided-float64array"
```

2024-03-23 22:22 UTC, Planeshifter requested changes
Thanks for your efforts!

The `manifest.json` file will have to be changed per the new conventions, i.e. using 2-space indentation and containing multiple configurations for examples and benchmarks.

Most importantly, the `addon.c` file should be updated as part of the issue. Would you please look into this? The linked PRs in the RFC issue and recently merged PRs should give guidance for how this has to be done.

2024-03-24 22:21 UTC, rajutkarsh07 commented
@Planeshifter I have made the suggested changes

2024-03-26 01:37 UTC, Planeshifter requested changes
CI is failing; looks like the `addon.c` file is for a different package with both `X` and `Y` arrays.

2024-03-26 11:48 UTC, rajutkarsh07 commented
@Planeshifter Is this correct 
or can you suggest be what should be there?

2024-04-15 00:40 UTC, Planeshifter approved these changes
CI should now pass; will merge shortly. Thanks for your contribution!

2024-04-15 01:24 UTC, merged