Update dapxsumpw
stdlib-js/stdlib pull request #1996
Opened 2024-03-22 16:08 UTC by ShivamAhir

Resolves # .

## Description

> What is the purpose of this pull request?

This pull request:

-   a
-   b
-   c

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #
-   fixes #

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [ ] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-03-23 22:30 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dapxsumpw/README.md
> +var x = filledarrayBy(10, 'float64', discreteUniform(0, 100));
```suggestion
var x = filledarrayBy( 10, 'float64', discreteUniform( 0, 100 ) );
```

2024-03-23 22:30 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dapxsumpw/manifest.json
> +      			"stdlib/napi/argv_strided_float64array.h"
```suggestion
				"@stdlib/napi/export",
				"@stdlib/napi/argv",
				"@stdlib/napi/argv-int64",
      			"@stdlib/napi/argv-strided-float64array"
```

2024-03-23 22:32 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dapxsumpw/manifest.json
>  				"-lm"
Indentation should be changed to two spaces here.

Would you please also update the file to have separate configurations for benchmarks and examples. The linked changes in the RFC or merged PRs should give guidance on how the file has to be updated.

2024-03-23 22:33 UTC, Planeshifter requested changes
Almost ready for merge; just needs updates to the `manifest.json` I believe. Thanks for your efforts!

2024-03-24 12:24 UTC, ShivamAhir commented
@Planeshifter  I think I understood what you wanted me to correct, and I have made the necessary adjustments, including adding the missing include and updating the dependencies in the ```manifest.json``` file. Thank you😊  for helping me identify and resolve my errors.

2024-03-24 18:06 UTC, Planeshifter approved these changes
Thanks for the changes! 

Had to fix the indentation in the manifest file (make sure you have an `.editorconfig` extension for your code editor installed, then the files should be auto-formatted on save), but otherwise looks all good to me now. Will merge shortly after CI has passed.

2024-03-24 18:12 UTC, merged