refactor: update `blas/ext/base/dasumpw` to follow current project conventions
stdlib-js/stdlib pull request #1998
Opened 2024-03-22 16:49 UTC by rajutkarsh07

Resolves #1470 

## Description
update blas/ext/base/dasumpw to follow current project conventions

> What is the purpose of this pull request?

This pull request:

-  progresses #1152 
-  fixes #1470 

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #
-   fixes #

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-03-22 18:41 UTC, rajutkarsh07 commented
@Planeshifter please review this PR

2024-03-23 21:01 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dasumpw/README.md
> +Copyright (c) 2024 The Stdlib Authors.
We don't update the copyright years for existing files.

```suggestion
Copyright (c) 2020 The Stdlib Authors.
```

2024-03-23 21:02 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dasumpw/benchmark/benchmark.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-23 21:02 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dasumpw/benchmark/benchmark.native.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-23 21:02 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dasumpw/lib/ndarray.native.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-23 21:03 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dasumpw/lib/ndarray.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-23 21:03 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dasumpw/lib/index.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-23 21:05 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dasumpw/manifest.json
> +    "options": {},
This file needs 2-space indentation and we should add configurations for examples and benchmarks, see the linked PRs in the RFC.

2024-03-23 21:06 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dasumpw/docs/repl.txt
> -
Removal of this line change should be reverted. 

I believe there may be some updates required for the `repl.txt` file as part of this refactoring, though.

2024-03-23 21:06 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dasumpw/examples/index.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-23 21:06 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dasumpw/benchmark/benchmark.ndarray.native.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-23 21:07 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dasumpw/benchmark/benchmark.ndarray.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-23 21:09 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dasumpw/src/addon.c
> +napi_value node_dasumpw( napi_env env, napi_callback_info info ) {
This file should be simplified as part of this refactoring to make use of the available macros, please consult the linked PRs for how this should look like.

2024-03-23 21:09 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dasumpw/src/addon.c
> +* Computes the sum of absolute values (L1 norm) of double-precision floating-point strided array elements using pairwise summation.
This comment should be replaced as part of the refactoring.

2024-03-23 21:09 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dasumpw/test/test.dasumpw.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-23 21:10 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dasumpw/test/test.dasumpw.native.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-23 21:10 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dasumpw/test/test.ndarray.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-23 21:10 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dasumpw/test/test.ndarray.native.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-23 21:11 UTC, Planeshifter requested changes
Thanks for your PR!

The main changes needed are updating the `addon.c` file and the `manifest.json` in order to get it ready for merging.

2024-03-23 21:30 UTC, rajutkarsh07 commented
@Planeshifter I have made the suggested changes

2024-03-25 01:11 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dasumpw/README.md
> +var x = filledarrayBy(10, 'float64', discreteUniform(0, 100));
```suggestion
var x = filledarrayBy( 10, 'float64', discreteUniform( 0, 100 ) );
```

2024-03-25 01:17 UTC, Planeshifter requested changes
@rajutkarsh07 CI checks are currently failing. Looks like we need an additional empty line at L51 of `repl.txt` and I think `c_dasum` in the `addon.c` file has to be replaced with `stdlib_strided_dasumpw` for tests to pass. I also believe some changes to `manifest.json` are still outstanding. Hopefully fixing up these issues won't be too burdensome.

2024-03-25 04:39 UTC, rajutkarsh07 commented
@Planeshifter made the changes in manifest.json and addon.c

2024-03-26 13:08 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dasumpw/src/addon.c
> +	napi_status status = napi_create_double( env, stdlib_strided_dasumpw( N, (double *)X, strideX ), &v );
```suggestion
	napi_status status = napi_create_double( env, stdlib_strided_dasumpw( N, X, strideX ), &v );
```

2024-03-26 13:18 UTC, Planeshifter approved these changes
After a few additional changes to the `manifest.json`, CI checks are now passing. Will merge shortly. Thank you @rajutkarsh07 for your contribution!

2024-03-26 13:18 UTC, merged