refactor update blas/ext/base/dsnansum to follow current project conventions
stdlib-js/stdlib pull request #2001
Opened 2024-03-22 17:39 UTC by Shubh942

Resolves #1492.

## Description

update blas/ext/base/dsnansum to follow current project conventions
> What is the purpose of this pull request?

This pull request:

progresses #1152 
Fixes #1492 

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #
-   fixes #

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-03-22 17:40 UTC, Shubh942 commented
@Planeshifter @Pranavchiku @kgryte can you please review it

2024-03-25 09:51 UTC, Pranavchiku requested changes
You have to fix `addon.c` file, refer similar PRs. Left few comments, once addressed this will be good to merge.

2024-03-25 09:51 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/dsnansum/README.md
> +Copyright (c) 2024 The Stdlib Authors.
```suggestion
Copyright (c) 2020 The Stdlib Authors.
```

2024-03-25 09:51 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/dsnansum/README.md
> +var x = filledarrayBy(10, 'float32', discreteUniform(0, 100));
```suggestion
var x = filledarrayBy( 10, 'float32', discreteUniform( 0, 100 ) );
```

2024-03-25 09:51 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/dsnansum/benchmark/benchmark.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-25 09:51 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/dsnansum/benchmark/benchmark.js
> +var rand = uniform( -100.0, 100.0 );
```suggestion
var rand = uniform( -10.0, 10.0 );
```

2024-03-25 09:51 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/dsnansum/benchmark/benchmark.native.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-25 09:51 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/dsnansum/benchmark/benchmark.native.js
> +var rand = uniform( -100.0, 100.0 );
```suggestion
var rand = uniform( -10.0, 10.0 );
```

2024-03-25 09:51 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/dsnansum/benchmark/benchmark.ndarray.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-25 09:51 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/dsnansum/benchmark/benchmark.ndarray.js
> +var rand = uniform( -100.0, 100.0 );
```suggestion
var rand = uniform( -10.0, 10.0 );
```

2024-03-25 09:51 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/dsnansum/benchmark/benchmark.ndarray.native.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-25 09:51 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/dsnansum/benchmark/benchmark.ndarray.native.js
> +var rand = uniform( -100.0, 100.0 );
```suggestion
var rand = uniform( -10.0, 10.0 );
```

2024-03-25 09:51 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/dsnansum/docs/repl.txt
> +    > {{alias}}( 3, x, 2 )
```suggestion
    > {{alias}}( 4, x, 2 )
```

2024-03-25 09:51 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/dsnansum/docs/repl.txt
> +    > {{alias}}( 3, x1, 2 )
```suggestion
    > {{alias}}( 4, x1, 2 )
```

2024-03-25 09:51 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/dsnansum/examples/index.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-25 09:51 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/dsnansum/lib/index.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-25 09:51 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/dsnansum/lib/index.js
> +* var v = dsnansum.ndarray( 4, x, 2, 1 );
```suggestion
* var v = dsnansum.ndarray( 5, x, 2, 1 );
```

2024-03-25 09:51 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/dsnansum/lib/ndarray.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-25 09:51 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/dsnansum/lib/ndarray.js
> +* var v = dsnansum( 8, x, 2, 1 );
```suggestion
* var v = dsnansum( 5, x, 2, 1 );
```

2024-03-25 09:51 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/dsnansum/lib/ndarray.native.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-25 09:51 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/dsnansum/lib/ndarray.native.js
> +* var v = dsnansum( 4, x, 2, 1 );
```suggestion
* var v = dsnansum( 5, x, 2, 1 );
```

2024-03-25 09:51 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/dsnansum/manifest.json
> +				"stdlib/napi/argv_strided_float32array.h"
This file has TAB indentation, please fix this.

2024-03-25 09:51 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/dsnansum/test/test.dsnansum.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2024-03-25 09:51 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/dsnansum/test/test.dsnansum.js
>  	v = dsnansum( N, x, 2 );
```suggestion
	v = dsnansum( 4, x, 2 );
```

Apply this in every `test.*` file

2024-03-25 09:51 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/dsnansum/test/test.dsnansum.js
> +	N = 4;
same comment here

2024-03-25 09:51 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/dsnansum/test/test.dsnansum.js
> +	N = 4;
same comment here, also remove declaration of `N`

2024-03-25 23:52 UTC, Shubh942 commented
I will change the code as specified. Thanks for your response

2024-03-26 10:38 UTC, Shubh942 commented
@Pranavchiku I have made the suggested changes.

2024-03-26 11:01 UTC, Pranavchiku requested changes
You will have to update indentation in `manifest.json` and update `addon.c`

2024-03-26 11:01 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/dsnansum/manifest.json
> +	  }
This is still tab indented, please refer similar PRs and update accordingly

2024-03-26 12:21 UTC, Shubh942 commented
@Pranavchiku I have updated the indentation in `manifest.json` and update `addon.c`.

2024-03-27 07:32 UTC, Shubh942 commented
@Planeshifter can you please review my PR

2024-03-27 09:20 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/dsnansum/manifest.json
> +
```suggestion
}

```

2024-03-27 09:24 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/dsnansum/src/addon.c
> +	return NULL;
```suggestion
	STDLIB_NAPI_ARGV( env, info, argv, argc, 3 );
	STDLIB_NAPI_ARGV_INT64( env, N, argv, 0 );
	STDLIB_NAPI_ARGV_INT64( env, strideX, argv, 2 );
	STDLIB_NAPI_ARGV_STRIDED_FLOAT32ARRAY( env, X, N, strideX, argv, 1 );

	napi_value v;
	status = napi_create_double( env, stdlib_strided_dnansum( N, X, stride ), &v );
	assert( status == napi_ok );
	return v;
}
```

2024-03-27 09:25 UTC, Pranavchiku approved these changes
This looks good to me. Thanks @Shubh942 !

2024-03-28 21:42 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dsnansum/src/addon.c
> +	STDLIB_NAPI_ARGV_INT64( env, strideX, argv, 2 );
```suggestion
	STDLIB_NAPI_ARGV_INT64( env, stride, argv, 2 );
```

2024-03-28 21:42 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dsnansum/src/addon.c
> +	STDLIB_NAPI_ARGV_STRIDED_FLOAT32ARRAY( env, X, N, strideX, argv, 1 );
```suggestion
	STDLIB_NAPI_ARGV_STRIDED_FLOAT32ARRAY( env, X, N, stride, argv, 1 );
```

2024-03-28 21:42 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dsnansum/src/addon.c
> +	STDLIB_NAPI_ARGV_INT64( env, strideX, argv, 2 );
```suggestion
	STDLIB_NAPI_ARGV_INT64( env, stride, argv, 2 );
```

2024-03-28 21:42 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dsnansum/src/addon.c
> +	status = napi_create_double( env, stdlib_strided_dnansum( N, X, stride ), &v );
```suggestion
	status = napi_create_double( env, stdlib_strided_dsnansum( N, X, stride ), &v );
```

2024-03-29 04:00 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/dsnansum/manifest.json
> +        "@stdlib/napi/argv-float",
```suggestion
```

This isn't needed.

2024-03-29 04:01 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/dsnansum/src/addon.c
> +#include "stdlib/napi/argv_float.h"
```suggestion
```

This isn't used.

2024-03-29 04:03 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/dsnansum/test/test.ndarray.js
> +	t.strictEqual( dsnansum.length, 4, 'return expected value' );
```suggestion
	t.strictEqual( dsnansum.length, 4, 'returns expected value' );
```

2024-03-29 04:03 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/dsnansum/test/test.dsnansum.js
> +	t.strictEqual( dsnansum.length, 3, 'return expected value' );
```suggestion
	t.strictEqual( dsnansum.length, 3, 'returns expected value' );
```

2024-03-29 04:04 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/dsnansum/test/test.ndarray.native.js
> +	t.strictEqual( dsnansum.length, 4, 'return expected value' );
```suggestion
	t.strictEqual( dsnansum.length, 4, 'returns expected value' );
```

2024-03-29 04:04 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/dsnansum/README.md
> +var x = filledarrayBy( 10, 'float32', discreteUniform( 0, 100 ) );
The changes to this example are not equivalent to the original.

2024-03-29 04:05 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/dsnansum/benchmark/benchmark.native.js
> +	var x = filledarrayBy( len, 'float32', rand );
The changes to this (and the other benchmarks) are not equivalent to the original.

2024-03-29 04:07 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/dsnansum/manifest.json
> -				"@stdlib/blas/ext/base/dsnansumpw"
This dependency has been omitted from the dependencies in each of the configurations. This should be re-added to each of them.

2024-03-29 04:09 UTC, kgryte requested changes
This PR needs changes, as directed in the comments, before it can be merged. Benchmark test data generation should remain similar to the original (namely, `NaNs` should be present; otherwise, compiler optimizations can result in conditionals being removed, resulting in better measured performance than "real-world" usage.

2024-03-29 11:09 UTC, Shubh942 commented
@kgryte @Planeshifter I made the required changes. Can you please review it.

2024-03-30 09:51 UTC, Shubh942 commented
@kgryte  @Planeshifter I made the required changes.

2024-04-08 02:10 UTC, kgryte commented
@Shubh942 Looks like this PR is failing CI, including failing tests and lint errors. Until those are resolved, we won't be able to move this PR forward.

2024-04-14 21:17 UTC, Planeshifter approved these changes

2024-04-14 21:22 UTC, merged