refactor update `blas/ext/base/dsortsh` to follow current project conventions
stdlib-js/stdlib pull request #2007
Opened 2024-03-23 02:39 UTC by liberocks

Resolves https://github.com/stdlib-js/stdlib/issues/1500.

## Description

> What is the purpose of this pull request?

This pull request refactors the existing implementation to follow the current project convention for `blas/ext/base/dsortsh`

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves https://github.com/stdlib-js/stdlib/issues/1500
-   fixes #

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-03-25 09:35 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/dsortsh/benchmark/benchmark.mostly_sorted_few_uniques.js
> +		iter = pow( iter, 3.0/4.0 ) | 0;
I think we do not need this

2024-03-25 09:36 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/dsortsh/benchmark/benchmark.mostly_sorted_few_uniques.native.js
> +var rand = uniform( -100.0, 100.0 );
```suggestion
var rand = uniform( 1.0, 10.0 );
```

2024-03-25 09:36 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/dsortsh/benchmark/benchmark.mostly_sorted_few_uniques.native.js
> +		iter = pow( iter, 3.0/4.0 ) | 0;
same comment here

Same comment follows on each of `benchmark.*`

2024-03-25 09:36 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/dsortsh/manifest.json
> +				"@stdlib/napi/export",
Incorrect indentation

2024-03-25 09:37 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/dsortsh/manifest.json
> +				"@stdlib/napi/argv",
same here

2024-03-25 09:37 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/dsortsh/src/addon.c
> +STDLIB_NAPI_MODULE_EXPORT_FCN( addon )
add a trailing end line

2024-03-25 09:38 UTC, Pranavchiku requested changes
Left comments above, this PR is missing updates in readme, docs, etc. Please refer a similar PR and update accordingly. Thanks for your work!

2024-03-30 06:31 UTC, liberocks commented
Hi @Pranavchiku I have made changes as suggested. However, it turns out we still need this code,
```
iter = pow( iter, 3.0/4.0 ) | 0;
```
I tried removing it and the benchmark goes forever. It causes timeout on the CI pipeline. Thus I put it back.

Anyway, thank you for reviewing my PR!

2024-04-28 14:16 UTC, Planeshifter approved these changes
Did some minor clean-up and will merge once CI passes. Thanks for your PR!

2024-04-28 14:19 UTC, merged