refactor: update blas/ext/base/scusumkbn to follow current project co…
stdlib-js/stdlib pull request #2012
Opened 2024-03-23 19:08 UTC by vr-varad

…nventions

Resolves # .

## Description

refactor: update blas/ext/base/scusumkbn to follow current project conventions

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #1517 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [ ] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-03-23 19:14 UTC, vr-varad commented
Dear @kgryte @Pranavchiku and @Planeshifter. I've implemented the requested changes. Would you be able to take a moment to review them when you have some time? Your feedback would be greatly appreciated. Thank you kindly.

2024-03-23 20:46 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn/docs/repl.txt
> +    The `N` and `stride` parameters determine which elements in the strided
```suggestion
    The `N` and stride parameters determine which elements in the strided
```

2024-03-23 20:48 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn/docs/repl.txt
> +    based on starting indices.
```suggestion
    buffer, the offset parameters support indexing semantics based on
    starting indices.
```

2024-03-23 20:49 UTC, Planeshifter approved these changes
Looks good; thank you for the edits! Will merge your PR shortly.

2024-03-23 20:53 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn/docs/repl.txt
> +    arrays accessed at runtime.
```suggestion
    The `N` and stride parameters determine which elements in the strided arrays
    are accessed at runtime.
```

2024-03-23 20:54 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn/manifest.json
@Planeshifter This file needs to be updated before this can be merged.

2024-03-23 20:55 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn/manifest.json
> +			"dependencies": [
This file should also use 2-space indentation.

2024-03-23 20:55 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn/src/addon.c
> +STDLIB_NAPI_MODULE_EXPORT_FCN( addon )
```suggestion
STDLIB_NAPI_MODULE_EXPORT_FCN( addon )

```

2024-03-23 20:57 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn/test/test.ndarray.js
This file needs to be updated to remove `floor` usage.

2024-03-23 20:57 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn/test/test.ndarray.native.js
This file needs to be updated to remove `floor` usage.

2024-03-23 20:58 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn/manifest.json
> +			"dependencies": [
@vr-varad Can you add separate build configurations, as done elsewhere? Thanks.

2024-03-23 20:59 UTC, kgryte requested changes
@vr-varad Left some comments, which should be addressed before this PR can be merged.

2024-03-24 04:35 UTC, vr-varad commented
Hello @kgryte, I've made the necessary adjustments. Could you please take a moment to review them? Your input would be greatly appreciated. Thank you.

2024-03-24 05:04 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn/manifest.json
> +	{
This file has mixed TABS and spaces.

2024-03-24 05:05 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn/manifest.json
> +	{
It should be 2-space indentation.

2024-03-24 05:05 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn/manifest.json
> +  "options": {},
Missing default `task`.

2024-03-24 05:07 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn/manifest.json
> +		"@stdlib/napi/argv-strided-float32array"
These dependencies are not necessary for compiling benchmarks.

2024-03-24 05:07 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn/manifest.json
> +		"@stdlib/napi/export",
Same comment. These deps are only necessary for compiling `addon.c`, not the examples.

2024-03-24 05:07 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn/manifest.json
> +}
```suggestion
}

```

Missing trailing newline. Have you setup EditorConfig?

2024-03-24 05:09 UTC, kgryte requested changes
@vr-varad This PR is close to ready. Some remaining changes are necessary for the `manifest.json` file.

2024-03-24 05:29 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn/manifest.json
> +    "task":"build"
```suggestion
    "task": "build"
```

2024-03-24 05:29 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn/manifest.json
> +     "relative": true
```suggestion
     "relative": true
```

2024-03-24 05:29 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn/manifest.json
> +     "relative": true
```suggestion
     "relative": true
```

2024-03-24 05:29 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn/manifest.json
> +     "relative": false
```suggestion
     "relative": false
```

2024-03-24 05:29 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn/manifest.json
> +     "relative": false
```suggestion
     "relative": false
```

Not clear to me why, but you have trailing tabs.

2024-03-24 05:30 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn/manifest.json
>  }
You still need the `benchmark` and `examples` configurations. Those need to be re-added. They just don't have dependencies.

2024-03-24 05:40 UTC, vr-varad commented
@kgryte Made the changes as suggested.

2024-03-24 05:48 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn/manifest.json
> +	  "resolve": true,
This file still has mixed TABS and spaces.

2024-03-24 06:35 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/scusumkbn/manifest.json
> +	},
There are still TABS in this file. :)

2024-03-24 06:52 UTC, vr-varad commented
@kgryte are there still tabs?

2024-03-24 07:35 UTC, kgryte approved these changes
LGTM. Thanks for working on this, @vr-varad.

2024-03-24 07:36 UTC, kgryte commented
@vr-varad Would you mind checking the box in the OP indicating that you've read the contributing guidelines? This needs to be checked in order to confirm that you agree to licensing terms and the Developer's Certificate of Origin.

2024-03-24 07:44 UTC, vr-varad commented
@kgryte done.

2024-03-24 07:46 UTC, merged