refactor: update `blas/ext/base/dnannsum` to follow current project conventions
stdlib-js/stdlib pull request #2019
Opened 2024-03-24 14:10 UTC by AuenKr

Resolves #1478 .

## Description

> What is the purpose of this pull request?

This pull request:

-   refactored `@stdlib/blas/ext/base/dnannsum` to follow current project conventions

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #1478 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-03-25 09:28 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/dnannsum/benchmark/benchmark.js
> +	return benchmark;
Please cross check the conventions here, `x` shall be declared and assigned on separate lines.

2024-03-25 09:28 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/dnannsum/benchmark/benchmark.native.js
> +	var x = filledarrayBy( len, 'float64', clbk );
same comment here

2024-03-25 09:28 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/dnannsum/benchmark/benchmark.ndarray.js
> +	var x = filledarrayBy( len, 'float64', clbk );
same here

2024-03-25 09:29 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/ext/base/dnannsum/lib/ndarray.native.js
> +	viewOut = offsetView( out, offsetOut );
```suggestion
	offsetX = minViewBufferIndex( N, strideX, offsetX );
	offsetOut = minViewBufferIndex( N, strideOut, offsetOut );

	viewX = offsetView( x, offsetX );
	viewOut = offsetView( out, offsetOut );

```

2024-03-25 09:31 UTC, Pranavchiku requested changes
Left a few comments, thanks for this PR!

2024-04-08 08:01 UTC, AuenKr commented
@Pranavchiku applied all suggestion and fixed `addon.c` file which causing test case to fail.

2024-04-08 09:31 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dnannsum/manifest.json
> +        "./src/dnansum.c"
```suggestion
        "./src/dnannsum.c"
```

2024-04-08 09:31 UTC, Planeshifter commented on lib/node_modules/@stdlib/blas/ext/base/dnannsum/manifest.json
> +        "./src/dnansum.c"
```suggestion
        "./src/dnannsum.c"
```

2024-04-10 05:58 UTC, AuenKr commented
@kgryte can u review the PR?

2024-04-15 12:54 UTC, Planeshifter approved these changes
Thanks @AuenKr for your PR! Looked great, I just had to add a missing dependency to the `manifest.json` example and benchmarks configurations. Will merge shortly.

2024-04-15 12:57 UTC, merged