Add files via upload
stdlib-js/stdlib pull request #2031
Opened 2024-03-25 07:33 UTC by xaman27x

## Description

> What is the purpose of this pull request?

This pull request:
Adds native C implementation for @stdlib/math/base/special/sin
`double stdlib_base_sin ( const double x );`
## Related Issues
Issue Tracker: https://github.com/stdlib-js/stdlib/issues/2018

This pull request:
1) Adds C Implementation of @stdlib/node_moudles/math/base/special/sin

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [ ] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-03-25 07:38 UTC, xaman27x commented
NOTE:
The sin function contains precision upto 4 floating points. (ie. +-0.00001)
Thanks!

2024-03-25 09:18 UTC, Pranavchiku requested changes
This PR is missing files, please refer similar PRs add those and then this can be reviewed. Also `sin` implementation depends on `rempio2` for which we do not have C implementation atm, so this PR is blocked.

2024-03-25 09:56 UTC, kgryte requested changes
@xaman27x As is, we cannot accept the changes introduced in this PR. Please ensure you study how other packages include C implementations.

E.g., don't write your own `binding.gyp` file, copy it from other packages, comments and all.

You shouldn't be modifying the contents of `package.json`, except for `gypfile` and `directories`. Use project `Makefiles`, copying them from other packages.

We have project tooling for compilation. Learn that tooling.

Your addon interface does not conform to our conventions.

Your C implementation needs considerable work. `sin` depends on `rempio2`: https://svnweb.freebsd.org/base/release/9.3.0/lib/msun/src/s_sin.c?view=markup. Meaning, the prerequisite for adding a C implementation to `sin` has not been satisfied in order to add this implementation.

2024-03-25 10:57 UTC, xaman27x commented
> @xaman27x As is, we cannot accept the changes introduced in this PR. Please ensure you study how other packages include C implementations.
> 
> 
> 
> E.g., don't write your own `binding.gyp` file, copy it from other packages, comments and all.
> 
> 
> 
> You shouldn't be modifying the contents of `package.json`, except for `gypfile` and `directories`. Use project `Makefiles`, copying them from other packages.
> 
> 
> 
> We have project tooling for compilation. Learn that tooling.
> 
> 
> 
> Your addon interface does not conform to our conventions.
> 
> 
> 
> Your C implementation needs considerable work. `sin` depends on `rempio2`: https://svnweb.freebsd.org/base/release/9.3.0/lib/msun/src/s_sin.c?view=markup. Meaning, the prerequisite for adding a C implementation to `sin` has not been satisfied in order to add this implementation.

Alright! I'll copy all necessary files henceforth! And since the Sin implementation requires C implementation of 'rempio2' as well, I'll work upon that first!
Thank you for consideration
Best.

2024-06-11 08:22 UTC, kgryte commented
This PR has been superseded by #2349. Will go ahead and close. Thank you, @xaman27x, for your interest in stdlib.

2024-06-11 08:22 UTC, closed without merging