feat: add `blas/base/zcopy`
stdlib-js/stdlib pull request #2064
Opened 2024-03-27 05:18 UTC by aman-095

## Description

> What is the purpose of this pull request?

This RFC proposes to add a routine to copy values from one complex double-precision floating-point vector to another complex double-precision floating-point vector as defined in [BLAS Level 1](http://www.netlib.org/blas/#_level_1) routines. Specifically adding `@stdlib/blas/base/zcopy` is proposed.

## Related Issues

> Does this pull request have any related issues?
None.

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-03-27 09:11 UTC, kgryte commented on lib/node_modules/@stdlib/blas/base/zcopy/README.md
> +var realf = require( '@stdlib/complex/realf' );
The use of `realf`and `imagf` here and elsewhere in this PR is incorrect. You should be using `@stdlib/complex/real` which is for extracting the real component of a **double-precision floating-point number**.

2024-03-27 09:12 UTC, kgryte commented on lib/node_modules/@stdlib/blas/base/zcopy/README.md
> +var realf = require( '@stdlib/complex/realf' );
The `f` suffix tells you that the API is for single-precision floating-point numbers, not double-precision.

2024-03-27 09:14 UTC, kgryte commented on lib/node_modules/@stdlib/blas/base/zcopy/docs/repl.txt
> +    > var re = {{alias:@stdlib/complex/realf}}( z )
Same comment.

2024-03-27 09:18 UTC, kgryte requested changes
Thanks, @aman-095. This looks good apart from the `realf` and `imagf` usage. Once resolved, this should be ready for merge.

2024-03-27 09:19 UTC, kgryte commented
@aman-095 Are you planning on adding the C and Fortran implementations in a follow-up PR? Or will you be adding them to this PR?

2024-03-27 09:22 UTC, aman-095 commented
@kgryte I'll correct the implementation and yes I will add the C and Fortran implementation in this PR itself.

2024-03-27 09:23 UTC, kgryte commented
@aman-095 Great! Thanks!

2024-04-03 07:52 UTC, kgryte commented on lib/node_modules/@stdlib/blas/base/zcopy/benchmark/benchmark.native.js
> +		bench( pkg+':len='+len, opts, f );
```suggestion
		bench( pkg+'::native:len='+len, opts, f );
```

Missing the benchmark namespace.

2024-04-03 07:52 UTC, kgryte commented on lib/node_modules/@stdlib/blas/base/zcopy/benchmark/benchmark.ndarray.native.js
> +		bench( pkg+':ndarray:len='+len, opts, f );
```suggestion
		bench( pkg+'::native:ndarray:len='+len, opts, f );
```

2024-04-03 07:56 UTC, kgryte commented on lib/node_modules/@stdlib/blas/base/zcopy/benchmark/fortran/benchmark.length.f
> +end program bench
```suggestion
end program bench

```

2024-04-03 08:04 UTC, kgryte commented on lib/node_modules/@stdlib/blas/base/zcopy/benchmark/fortran/benchmark.length.f
> +      x( i ) = cmplx( (real(r1)*10000.0d0)-5000.0d0, (real(r2)*1000.0d0)-5000.0d0, kind=8  )
```suggestion
      x( i ) = cmplx( (real(r1)*10000.0d0)-5000.0d0, (real(r2)*1000.0d0)-5000.0d0, kind=8 )
```

2024-04-03 08:18 UTC, kgryte commented on lib/node_modules/@stdlib/blas/base/zcopy/docs/repl.txt
> +    another complex double-precision floating-point vector.
```suggestion
    Copies values from one double-precision complex floating-point vector to
    another double-precision complex floating-point vector.
```

2024-04-03 08:24 UTC, kgryte commented on lib/node_modules/@stdlib/blas/base/zcopy/lib/ndarray.native.js
> +* Copies values from one complex single-precision floating-point vector to another complex single-precision floating-point vector.
```suggestion
* Copies values from one complex double-precision floating-point vector to another complex double-precision floating-point vector.
```

2024-04-03 08:29 UTC, kgryte commented on lib/node_modules/@stdlib/blas/base/zcopy/src/zcopy.f
> +! * Jack Dongarra, linpack, 3/11/78.
```suggestion
! * Jack Dongarra, linpack, 4/11/78.
```

The extended comment should match what is in netlib: https://github.com/OpenMathLib/OpenBLAS/blob/develop/lapack-netlib/BLAS/SRC/zcopy.f

2024-04-03 08:33 UTC, kgryte commented on lib/node_modules/@stdlib/blas/base/zcopy/src/zcopy.f
> +end subroutine zcopy
```suggestion
end subroutine zcopy

```

2024-04-03 08:41 UTC, kgryte commented on lib/node_modules/@stdlib/blas/base/zcopy/src/zcopy.f
> +  complex(kind=8) :: zx(*), zy(*)
```suggestion
  complex(kind=kind(0.0d0) :: zx(*), zy(*)
```

2024-04-03 08:46 UTC, kgryte commented on lib/node_modules/@stdlib/blas/base/zcopy/src/zcopy.f
> +! @param {Array<complex(kind=8)>} zy - output array
```suggestion
! @param {Array<complex<double>>} zx - input array
! @param {integer} strideX - `zx` stride length
! @param {Array<complex<double>>} zy - output array
```

Fortran is a bit annoying in its parameterization of dtypes.

2024-04-03 08:49 UTC, kgryte approved these changes
LGTM. Thanks, @aman-095!

2024-04-03 08:50 UTC, kgryte commented on lib/node_modules/@stdlib/blas/base/zcopy/src/zcopy.f
> +  complex(kind=kind(0.0d0) :: zx(*), zy(*)
```suggestion
  complex(kind=kind(0.0d0)) :: zx(*), zy(*)
```

2024-04-03 08:50 UTC, kgryte approved these changes

2024-04-03 08:59 UTC, merged