docs: improve README examples of lib/node_modules/@stdlib/constants/u…
stdlib-js/stdlib pull request #2097
Opened 2024-03-31 15:24 UTC by BeastMasterGrinder

Resolves #1566 .

## Description

> improve README examples of constants/unicode namespace

## Related Issues

> No

This pull request:

-   resolves #1566 
-   fixes #1566 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [ ] Read, understood, and followed the [contributing guidelines][contributing].
-   [ ] Searched for existing issues and pull requests.
-   [ ] The issue name begins with RFC:

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-04-02 08:47 UTC, kgryte commented on lib/node_modules/@stdlib/constants/unicode/README.md
> -<section class="usage">
Why is this removed?

2024-04-02 08:47 UTC, kgryte commented on lib/node_modules/@stdlib/constants/unicode/README.md
> -#### constants
Why was this change made? Where else in the project do we make the API heading level 2?

2024-04-02 08:48 UTC, kgryte commented on lib/node_modules/@stdlib/constants/unicode/README.md
> +console.log( 'Maximum BMP code point:', constants.MAX_BMP );
The first code block is always the import. Please see other packages in the project.

2024-04-02 08:49 UTC, kgryte requested changes
This PR makes several changes we don't want and does not conform to existing project conventions/practices. As such, we won't be able to move this forward until changes are made.

2024-09-07 19:17 UTC, closed without merging

2024-09-07 19:17 UTC, Planeshifter commented
Closing due to inactivity.