fix: Bug with skin tone emojis when using prevGraphemeClusterBreak package
stdlib-js/stdlib pull request #2139
Opened 2024-04-07 13:13 UTC by olenkabilonizhka

Resolves #1092 

## Description

> What is the purpose of this pull request?

There's an issue with prevGraphemeClusterBreak package, if I compare the results with nextGraphemeClusterBreak for a single skin tone emoji it doesn't return the same values,

`prevGraphemeClusterBreak( '👉🏿' ) // returns 1
nextGraphemeClusterBreak( '👉🏿' ) // returns -1`

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #1092 
-   fixes #

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-04-07 19:23 UTC, kgryte requested changes
(1) It looks like you are using language features which are beyond ES5. (2) You are performing repeated and unnecessary application of the regular expression. (3) Your PR is not accompanied by any additional tests.

As such, this PR cannot move forward until the above is addressed.

2024-04-14 09:14 UTC, kgryte commented on lib/node_modules/@stdlib/string/prev-grapheme-cluster-break/lib/main.js
> +	var regexEmoji = new RegExp("\\p{Extended_Pictographic}", "ug");
This regular expression is not ES5.

2024-04-14 09:15 UTC, kgryte commented on lib/node_modules/@stdlib/string/prev-grapheme-cluster-break/lib/main.js
> +	var regexEmojiMatching = str.match(regexEmoji)
You assume that `str` is a string here. But that assumption is not verified until L80.

2024-04-14 09:15 UTC, kgryte commented on lib/node_modules/@stdlib/string/prev-grapheme-cluster-break/lib/main.js
> +	if (regexEmoji.test(str) && regexEmojiMatching && regexEmojiMatching.length === 1) {
You're not conforming to our style conventions which can be readily observed in this source file.

2024-05-02 08:37 UTC, olenkabilonizhka commented on lib/node_modules/@stdlib/string/prev-grapheme-cluster-break/lib/main.js
> +	var regexEmoji = new RegExp("\\p{Extended_Pictographic}", "ug");
Thanks, resolved.

2025-04-03 00:05 UTC, closed without merging