Add uimuldw function
stdlib-js/stdlib pull request #219
Opened 2018-10-20 04:18 UTC by rei2hu

Resolves #207  .

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing], including the relevant style guides.
-   [x] Read and understand the [Code of Conduct][code-of-conduct].
-   [x] Read and understood the [licensing terms][license].
-   [x] Searched for existing issues and pull requests **before** submitting this pull request.
-   [x] Filed an issue (or an issue already existed) **prior to** submitting this pull request.
-   [x] Rebased onto latest `develop`.
-   [x] Submitted against `develop` branch.

## Description

> What is the purpose of this pull request?

This pull request:

-   Implements the uimuldw function.

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #207 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

[license]: https://github.com/stdlib-js/stdlib/blob/develop/LICENSE

2018-10-20 21:09 UTC, kgryte commented
@rei2hu This is awesome! Will review later today!

2018-10-20 23:10 UTC, kgryte requested changes
@rei2hu This is really good work! Thanks for working on this! Only minor nitpicks. Once resolved, should be ready for merge!

2018-10-20 23:10 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/uimuldw/README.md
> +> Perform multiplication of two unsigned 32-bit integers and return an array of two unsigned 32-bit integers which represents their 64-bit unsigned integer product.
```suggestion
> Compute the double word product of two unsigned 32-bit integers.
```

The current description is **good**; however, a bit too literal for a top-level package description. It's use below can be left as is.

2018-10-20 23:10 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/uimuldw/README.md
> +> Perform multiplication of two unsigned 32-bit integers and return an array of two unsigned 32-bit integers which represents their 64-bit unsigned integer product.
```suggestion
> Multiplies two unsigned 32-bit integers and returns an array of two unsigned 32-bit integers which represents the 64-bit unsigned integer product.
```

2018-10-20 23:10 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/uimuldw/docs/repl.txt
> +    Perform multiplication of two unsigned 32-bit integers and return an array
```suggestion
    Multiplies two unsigned 32-bit integers and returns an array
```

2018-10-20 23:10 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/uimuldw/docs/repl.txt
> +    of two unsigned 32-bit integers which represents their 64-bit unsigned
```suggestion
    of two unsigned 32-bit integers which represents the 64-bit unsigned
```

2018-10-20 23:10 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/uimuldw/docs/repl.txt
> +    out: Array (optional)
```suggestion
    out: ArrayLikeObject (optional)
```

2018-10-20 23:10 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/uimuldw/docs/repl.txt
> +    out: Array
```suggestion
    out: ArrayLikeObject
```

2018-10-20 23:10 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/uimuldw/examples/index.js
> +		console.log( '%d x %d = 0x%s%s', i, j, y[0].toString( 16 ).padStart( 8, 0 ), y[1].toString( 16 ).padStart( 8, 0 ) );
`padStart` is not supported in older environments. Would you mind updating to use [`@stdlib/string/left-pad`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/string/left-pad)? Thanks!

2018-10-20 23:10 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/uimuldw/lib/index.js
> +* Perform multiplication of two unsigned 32-bit integers and return an array of two unsigned 32-bit integers.
```suggestion
* Perform multiplication of two unsigned 32-bit integers and return an array of two unsigned 32-bit integers which represents the 64-bit unsigned integer product.
```

2018-10-20 23:10 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/uimuldw/lib/main.js
> +* Performs multiplication of two unsigned 32-bit integers and returns an array of two unsigned 32-bit integers.
```suggestion
* Performs multiplication of two unsigned 32-bit integers and returns an array of two unsigned 32-bit integers which represents the 64-bit unsigned integer product.
```

2018-10-20 23:10 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/uimuldw/lib/main.js
> +function uimuldw() { // [out] a, b
```suggestion
function uimuldw() {
```

2018-10-20 23:10 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/uimuldw/package.json
> +  "description": "Perform multiplication of two unsigned 32-bit integers and get their 64-bit product.",
```suggestion
  "description": "Compute the double word product of two unsigned 32-bit integers.",
```

2018-10-20 23:10 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/uimuldw/package.json
> +	"64-bit",
```suggestion
    "64-bit",
```

2018-10-20 23:10 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/uimuldw/package.json
> +	"64bit",
```suggestion
    "64bit",
```

2018-10-20 23:10 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/uimuldw/test/fixtures/c/runner.c
> +void muldwu1(unsigned w[], unsigned u, unsigned v) {
```suggestion
void muldwu1( unsigned w[], unsigned u, unsigned v ) {
```

2018-10-20 23:10 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/uimuldw/test/fixtures/c/runner.c
> +
```suggestion
```

2018-10-20 23:10 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/uimuldw/test/fixtures/c/runner.c
> +
```suggestion
```

2018-10-21 17:45 UTC, rei2hu commented
I'll also pr for the signed version once this passes

2018-10-21 22:10 UTC, kgryte requested changes
@rei2hu I missed a couple nits in documentation files. Sorry about that. Once these are resolved, I'll merge. :)

2018-10-21 22:10 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/uimuldw/README.md
> +<!-- Package usage notes. Make sure to keep an empty line after the `section` element and another before the `/section` close. -->
```suggestion
```

This is a stray comment which has wandered from its original place. You can just go ahead and remove.

2018-10-21 22:10 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/uimuldw/README.md
> +<!-- eslint-disable no-shortcut-reference-link -->
```suggestion
```

2018-10-21 22:10 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/uimuldw/README.md
> +
```suggestion
```

2018-10-21 22:10 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/uimuldw/README.md
> +
```suggestion
```

2018-10-21 22:10 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/uimuldw/README.md
> +
```suggestion
```

2018-10-21 22:10 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/uimuldw/docs/repl.txt
> +    Multiplies two unsigned 32-bit integers and returns an array
This description needs to be re-aligned with 80 char width. I believe `of two` can be moved to this line, which may affect subsequent lines.

2018-10-22 18:57 UTC, kgryte approved these changes
@rei2hu Thanks again for working on this!

2018-10-22 18:57 UTC, merged