feat: add `blas/base/drotm`
stdlib-js/stdlib pull request #2266
Opened 2024-05-25 05:57 UTC by aman-095

## Description

> What is the purpose of this pull request?

This RFC proposes to add a routine to apply a modified Givens plane rotation on double-precision floating-point vectors as defined in [BLAS Level 1](http://www.netlib.org/blas/#_level_1) routines. Specifically adding `@stdlib/blas/base/drotm` is proposed.

## Related Issues

> Does this pull request have any related issues?

None. 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-06-08 12:23 UTC, Pranavchiku requested changes
Minor changes required, then this PR can be reviewed again.

2024-06-08 12:23 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/base/drotm/README.md
> +void c_drotm( const CBLAS_INT N, double *X, const CBLAS_INT strideX, double *Y, const CBLAS_INT strideY, const double param[ 5 ] );
```suggestion
void c_drotm( const CBLAS_INT N, double *X, const CBLAS_INT strideX, double *Y, const CBLAS_INT strideY, const double *param);
```

2024-06-08 12:23 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/base/drotm/benchmark/fortran/benchmark.length.f
> +    param(5) = 0.0d0
```suggestion
    param = 0.0d0
```

Try this, I think this should work.

2024-06-08 12:23 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/base/drotm/examples/c/example.c
> +    }
tab indentation

2024-06-08 12:23 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/base/drotm/include/stdlib/blas/base/drotm.h
> +void API_SUFFIX(c_drotm)( const CBLAS_INT N, double *X, const CBLAS_INT strideX, double *Y, const CBLAS_INT strideY, const double param[ 5 ] );
```suggestion
void API_SUFFIX(c_drotm)( const CBLAS_INT N, double *X, const CBLAS_INT strideX, double *Y, const CBLAS_INT strideY, const double *param );
```

2024-06-08 12:23 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/base/drotm/include/stdlib/blas/base/drotm_cblas.h
> +void API_SUFFIX(cblas_drotm)( const CBLAS_INT N, double *X, const CBLAS_INT strideX, double *Y, const CBLAS_INT strideY, const double param[ 5 ] );
same comment here

2024-06-08 12:23 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/base/drotm/lib/drotm.js
> +	if ( N <= 0 || ( dflag+2.0 ) === 0.0 ) {
```suggestion
	if ( N <= 0 || ( dflag + 2.0 ) === 0.0 ) {
```

2024-06-08 12:23 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/base/drotm/lib/ndarray.js
> +	if ( N <= 0 || ( dflag+2.0 ) === 0.0 ) {
```suggestion
	if ( N <= 0 || ( dflag + 2.0 ) === 0.0 ) {
```

2024-06-08 12:23 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/base/drotm/src/drotm.c
> +	if ( N <= 0 || ( dflag+2.0 ) == 0.0 ) {
```suggestion
	if ( N <= 0 || ( dflag + 2.0 ) == 0.0 ) {
```

2024-06-08 12:23 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/base/drotm/src/drotm.f
> +  if( n <= 0 .OR. (dflag+two == zero)) return
```suggestion
  if( n <= 0 .OR. ( dflag + two == zero ) ) return
```

2024-06-08 12:23 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/base/drotm/src/drotm.f
> +  if(strideX == strideY .AND. strideX > 0) then
```suggestion
  if( strideX == strideY .AND. strideX > 0 ) then
```

2024-06-08 12:23 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/base/drotm/src/drotm.f
> +end subroutine drotm
fix spacing issue in this file.

2024-06-08 12:23 UTC, Pranavchiku commented on lib/node_modules/@stdlib/blas/base/drotm/src/drotm_cblas.c
> +void API_SUFFIX(c_drotm)( const CBLAS_INT N, double *X, const CBLAS_INT strideX, double *Y, const CBLAS_INT strideY, const double param[ 5 ] ) {
change API definition accordingly

2024-06-22 23:03 UTC, kgryte commented
@aman-095 LMK once you've update this PR to match the changes in https://github.com/stdlib-js/stdlib/pull/2267.

2024-06-24 11:26 UTC, aman-095 commented
Hey, @kgryte, I have applied the necessary changes to this PR.

2024-06-25 01:05 UTC, kgryte approved these changes
LGTM. Thanks, @aman-095!

2024-06-25 01:14 UTC, merged