feat: add JavaScript implementation for iter/cusome
stdlib-js/stdlib pull request #2561
Opened 2024-07-11 10:35 UTC by TheNourhan

Resolves #2334

## Description

> What is the purpose of this pull request?

This pull request:

- Implementation of the iterCuSome function in the lib folder.
- Documentation updates in the docs folder:
    - Added REPL usage examples to docs/repl.txt.
    - Created TypeScript type definitions in the docs/types folder.
- Updated README.md.
- Added benchmarks to the benchmark folder.
- Added unit tests to the test folder.

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #2334

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [ ] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-07-12 01:49 UTC, kgryte commented
@TheNourhan I think you misunderstood the RFC. The iterator should never end until the source iterator ends. It should cumulatively test for at least n elements, forever returning true until the source iterator no longer has iterated values. See other cumulative iterators for an example.

Also, please ensure that your source implementation matches the style and conventions of other iterator packages.

2024-07-12 10:28 UTC, TheNourhan commented
@kgryte Sorry for the confusion, I've edited it

2024-07-14 07:01 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cusome/lib/main.js
> +	setReadOnly(iter, 'next', next);
This iterator is missing a `return` method and an iterator symbol check. See https://github.com/stdlib-js/stdlib/blob/903c51c7d0a06d9186a6f2be1b01fa25f770a3eb/lib/node_modules/%40stdlib/iter/cuany/lib/main.js#L76. The implementation should be very similar to what is found in `cuany`.

2024-07-14 07:01 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cusome/test/test.js
> +});
As in `cuany`, you need iterator symbol tests.

2024-07-14 07:02 UTC, kgryte requested changes
Thanks for continuing to work on this, @TheNourhan. This is coming along. Left a couple more comments. I suggest more closely studying `cuany` and updating this PR accordingly.

2024-07-14 07:03 UTC, kgryte commented
Additionally, CI failures also need to be addressed before this PR can be merged.

2024-07-16 18:22 UTC, TheNourhan commented
@kgryte I made all the changes you requested, I hope everything is fine now :)

2024-07-20 18:00 UTC, TheNourhan commented
If there something I can improve to move forward with the merger? @kgryte

2024-07-22 22:25 UTC, kgryte approved these changes
LGTM. Thanks for working on this, @TheNourhan. I made a number of changes which you'll want to keep in mind for future PRs. The main thing is being consistent with code elsewhere in the project.

2024-07-22 22:28 UTC, kgryte approved these changes

2024-07-22 22:32 UTC, merged