Pull Request to [RFC]: add @stdlib/array/base/cunone-by #2325
stdlib-js/stdlib pull request #2615
Opened 2024-07-17 11:02 UTC by Naresh-kumar-Thodupunoori

Resolves #2325 .

## Description

> What is the purpose of this pull request?

This pull request:

-  It adds the package @stdlib/array/base/cunone-by 

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #2325 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-07-17 11:04 UTC, Naresh-kumar-Thodupunoori commented
@kgryte can you please review this !!!!!

2024-07-26 03:16 UTC, kgryte requested changes
Left an initial review. Main comment is that you need to carefully follow project conventions. Please try to ensure consistency with the rest of the project.

2024-07-26 03:16 UTC, kgryte commented on lib/node_modules/@stdlib/array/base/cunone-by/README.md
This README needs to be updated, as it does not match the style and conventions of other similar files in this project. Please update.

2024-07-26 03:16 UTC, kgryte commented on lib/node_modules/@stdlib/array/base/cunone-by/benchmark/benchmark.assign.length.js
The indentation of this file is off.

2024-07-26 03:16 UTC, kgryte commented on lib/node_modules/@stdlib/array/base/cunone-by/benchmark/benchmark.assign.length.js
> +main();
You need to add trailing newlines. Please ensure EditorConfig is installed as discussed in the contributing guidelines.

2024-07-26 03:16 UTC, kgryte commented on lib/node_modules/@stdlib/array/base/cunone-by/benchmark/benchmark.js
> +    for ( i = 0; i < y.length; i++ ) {
This check is unnecessary. Remove.

2024-07-26 03:16 UTC, kgryte commented on lib/node_modules/@stdlib/array/base/cunone-by/docs/repl.txt
> +{{alias}}( x, predicate )
Match the conventions used elsewhere in this project.

2024-07-26 03:16 UTC, kgryte commented on lib/node_modules/@stdlib/array/base/cunone-by/docs/types/index.d.ts
> +    assign<T, U extends Collection<boolean> | AccessorArrayLike<boolean>>(
Don't line break. The predicate should be the last argument.

2024-07-26 03:16 UTC, kgryte commented on lib/node_modules/@stdlib/array/base/cunone-by/docs/types/index.d.ts
> +* var arr = cunoneBy.assign( x, y, function isEven( v ) { return v % 2 === 0; }, 2, 0 );
No inline function declarations. Move out of the invocation.

2024-07-26 03:16 UTC, kgryte commented on lib/node_modules/@stdlib/array/base/cunone-by/lib/assign.js
> +
Missing license.

2024-07-26 03:16 UTC, kgryte commented on lib/node_modules/@stdlib/array/base/cunone-by/lib/assign.js
> +        if ( i === 0 ) {
Why do we need to special case the first argument?

2024-07-26 03:16 UTC, kgryte commented on lib/node_modules/@stdlib/array/base/cunone-by/lib/index.js
> +'use strict';
License headers here and everywhere.

2024-07-26 03:16 UTC, kgryte commented on lib/node_modules/@stdlib/array/base/cunone-by/lib/main.js
> +    out = new Array( x.length );
Do not preallocate arrays like this. You can cause the array to be allocated in object mode. Instead use [] and push.

2024-07-26 03:16 UTC, kgryte commented on lib/node_modules/@stdlib/array/base/cunone-by/package.json
> +}
Trailing newlines here and everywhere.

2024-07-26 03:16 UTC, kgryte commented on lib/node_modules/@stdlib/array/base/cunone-by/test/test.assign.js
> +    var x = [ -1, -2, -3, -4, -5 ];
The order of declarations violates our lint rules. Make sure you have run make init to ensure automation runs on commit and push.

2024-07-26 03:16 UTC, kgryte commented on lib/node_modules/@stdlib/array/base/cunone-by/test/test.assign.js
> +// Add more tests as needed
Why is this comment here?

2024-07-26 03:16 UTC, kgryte commented on lib/node_modules/@stdlib/array/base/cunone-by/test/test.js
> +    t.strictEqual( Array.isArray(out), true, 'returns an array' );
We don't use the builtin isArray. Use our utility package.

2024-07-26 03:16 UTC, kgryte commented on lib/node_modules/@stdlib/array/base/cunone-by/test/test.js
> +// Add more tests as needed for the assign method and other aspects of the main export
Either add tests or remove.

2024-07-26 03:16 UTC, kgryte commented
Additionally all build failures need to be addressed before this PR can be merged or considered for further review.

2024-07-26 20:55 UTC, Naresh-kumar-Thodupunoori commented on lib/node_modules/@stdlib/array/base/cunone-by/README.md
I am working on it, actually having some examinations up my sleeve.So preparing for them.

2024-09-24 00:04 UTC, Planeshifter commented
Closing as another PR with this package has meanwhile been merged. Thanks for your efforts and interest in `stdlib`  either way!

2024-09-24 00:05 UTC, closed without merging