Cusome by
stdlib-js/stdlib pull request #2661
Opened 2024-07-25 14:40 UTC by vivek-anand-singh

Resolves #2338 

## Description

> What is the purpose of this pull request?
The purpose of this pull request is to introduce the `@stdlib/iter/cusome-by` package, which provides a transform iterator to determine if at least `n` values from a source iterator satisfy a given predicate function. This new feature enhances the library by allowing cumulative testing of iterated values.

This pull request:

-   adds the feature of cusome-by function for `stdib`

## Related Issues

> Does this pull request have any related issues? 
- No

This pull request:

-   resolves #2338
-   fixes #2338

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

2024-07-25 14:41 UTC, vivek-anand-singh commented
@kgryte Please review this PR .

2024-07-28 23:56 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cusome-by/README.MD
> +```markdown
This is not how to write README files. Furthermore, the README name is incorrect. We don't uppercase `MD`.

2024-07-28 23:57 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cusome-by/README.MD
> +-   <span class="package-name">[`@stdlib/iter/cusome`][@stdlib/iter/cusome]</span><span class="delimiter">: </span><span class="description">create an iterator which iteratively checks whether at lea
Do not manually edit this section. See the comment at L197. This section should be empty.

2024-07-28 23:57 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cusome-by/README.MD
> +<!-- </related-links> -->
These should be removed.

2024-07-28 23:58 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cusome-by/benchmark/benchmark.js
> +});
You did not setup EditorConfig. Please read our contributing guidelines.

2024-07-28 23:58 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cusome-by/docs/repl.txt
> +The predicate function is provided two arguments:
This file does not adhere to project conventions. See the REPL text guide in `/docs`.

2024-07-28 23:59 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cusome-by/docs/types/index.d.ts
> +interface CuSomeByIterator extends Iterator {
Why are you doing this? Use `TypedIterator` from `@stdlib/types/iter`. Furthermore, if the source iterator is iterable, the returned iterable should also be iterable. See other `@stdlib/iter/*` packages.

2024-07-29 00:00 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cusome-by/docs/types/test.ts
> +import iterCuSomeBy = require( './index' );
Missing license header. Incorrect indentation throughout the file.

2024-07-29 00:00 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cusome-by/docs/types/test.ts
> +
Why do you have multiple trailing lines?

2024-07-29 00:00 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cusome-by/examples/index.js
> +}
EditorConfig.

2024-07-29 00:01 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cusome-by/lib/index.js
> +module.exports = main;
EditorConfig.

2024-07-29 00:01 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cusome-by/lib/main.js
> +				'value': false,
You should be assigning `v.value` here.

2024-07-29 00:02 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cusome-by/lib/main.js
> +			};
```suggestion
			return v;
```

2024-07-29 00:02 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cusome-by/lib/main.js
> +module.exports = iterCuSomeBy;
EditorConfig.

2024-07-29 00:02 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cusome-by/package.json
> +    "name": "@stdlib/iter/cusome-by",
Indentation in this file is off.

2024-07-29 00:03 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cusome-by/package.json
> +  }
EditorConfig.

2024-07-29 00:03 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cusome-by/test/test.js
> +	// t.equal( typeof it.return, 'function', 'has return method' );
Don't leave commented code.

2024-07-29 00:03 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cusome-by/test/test.js
> +	// t.equal( typeof it.return, 'function', 'has return method' );
Same thing.

2024-07-29 00:03 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cusome-by/test/test.js
> +	// r = it.return();
Why did you do this? Now the test does not test what it is supposed to.

2024-07-29 00:04 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cusome-by/test/test.js
> +	// r = it.return( 'finished' );
Same thing.

2024-07-29 00:04 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cusome-by/test/test.js
> +});
EditorConfig.

2024-07-29 00:05 UTC, kgryte commented on yarn.lock
Why did you include this file? Remove.

2024-07-29 00:06 UTC, kgryte requested changes
This PR needs significant changes before it can be considered for further review. Please study existing packages in `@stdlib/iter/*` and emulate the style and conventions as closely as possible and as appropriate. And further, please be sure to setup your local dev environment for contributing to stdlib as discussed in the contributing guidelines. It is clear that linting was not setup locally.

2024-07-29 00:07 UTC, kgryte commented
@vivek-anand-singh Also, in your OP, you removed the checkbox indicating that you have read the contributing guidelines. Without that checkbox, we cannot accept your PR. Please be sure to include that before any further review.

2024-08-13 12:09 UTC, closed without merging