feat(iter): add cuevery function
stdlib-js/stdlib pull request #2664
Opened 2024-07-26 08:38 UTC by Dipti0704

Resolves #2332.

## Description

> What is the purpose of this pull request?

This pull request:

-  Implements a new iterator function `iterCuevery`
- Adds functionality to cumulatively test whether every iterated value is truthy
- Enhances the @stdlib/iter module ecosystem

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #2332 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

- Input Iterator: The function takes an input iterator.
- Output Iterator: Returns a new iterator that yields boolean values.
- Yielding True: Continues yielding true while all values are falsy.
- Yielding False: Yields false once a truthy value is encountered and for all subsequent iterations.
- Handling Input: Handles both iterable and non-iterable input iterators.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-07-26 12:49 UTC, Dipti0704 commented
@kgryte can you review this?

2024-07-28 23:34 UTC, kgryte commented on lib/node_modules/@stdlib/_tools/repl-txt/rules/interface-spacing/lib/main.js
This file should not be modified.

2024-07-28 23:34 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cuevery/README.md
This file is empty.

2024-07-28 23:35 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cuevery/docs/repl.txt
This file does not conform to our REPL text conventions. Please read the REPL text guide.

2024-07-28 23:35 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cuevery/docs/types/index.d.ts
Missing license header.

2024-07-28 23:36 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cuevery/docs/types/index.d.ts
> +declare function iterCuEvery( iterator: Iterator ): Iterator;
You can improve return value specificity by using the `TypedIterator` interface.

2024-07-28 23:36 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cuevery/docs/types/test.ts
> +//import isIteratorLike from '@stdlib/assert/is-iterator-like';
Why is this here?

2024-07-28 23:36 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cuevery/docs/types/test.ts
> +    iterCuEvery(iterator()); // $ExpectType Iterator
Incorrect spacing and indentation throughout this file.

2024-07-28 23:37 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cuevery/docs/types/test.ts
> +    iterCuEvery(5 as any); // $ExpectError
Why are you casting?

2024-07-28 23:37 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cuevery/docs/types/test.ts
> +    //iterCuEvery((x: number): number => x as any as Iterator); // $ExpectError
Why is this commented out?

2024-07-28 23:37 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cuevery/docs/types/test.ts
> +}
This should be removed.

2024-07-28 23:37 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cuevery/examples/index.js
> +var it = iterMap( rand, function threshold( r ) {
Do not use function expressions.

2024-07-28 23:38 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cuevery/examples/index.js
> +    'iter': 100
This file has incorrect indentation.

2024-07-28 23:38 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cuevery/index.js
This file is empty.

2024-07-28 23:38 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cuevery/index.js
Actually, this file should be removed.

2024-07-28 23:38 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cuevery/lib/index.js
> +* var iterCuEvery = require( '@stdlib/iter-cuevery' );
Incorrect module names. See other packages within the monorepo.

2024-07-28 23:39 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cuevery/lib/main.js
> +
Why are these spaces here?

2024-07-28 23:39 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cuevery/lib/main.js
> +    }
Incorrect spacing and indentation. It is clear that you failed to setup your local development environment, as our linting would have caught these errors. Please read our contributing guidelines.

2024-07-28 23:40 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cuevery/lib/main.js
> +            done = true; // Short-circuit once a falsy value is found
This is not correct behavior. This is a cumulative iterator and should have the same length as the source iterator.

2024-07-28 23:40 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cuevery/lib/main.js
> +    function next() {
You're missing JSDoc comments.

2024-07-28 23:40 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cuevery/lib/main.js
> +    var iter = {
This isn't how we do variable declarations in source files.

2024-07-28 23:40 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cuevery/lib/main.js
> +    function finish(value) {
JSDoc comments.

2024-07-28 23:40 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cuevery/lib/main.js
> +    function factory() {
JSDoc comments.

2024-07-28 23:41 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cuevery/lib/main.js
> +module.exports = iterCuEvery;
You did not setup EditorConfig per the contributing guidelines.

2024-07-28 23:41 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cuevery/package-lock.json
Why is this file here? Remove.

2024-07-28 23:41 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cuevery/package.json
> +  "license": "ISC",
What is this? This `package.json` is not how we do things. See other packages.

2024-07-28 23:42 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cuevery/test/test.js
> +
Why are you commenting out our license header?

2024-07-28 23:42 UTC, kgryte commented on lib/node_modules/@stdlib/iter/cuevery/test/test.js
> +
This file does not follow project conventions.

2024-07-28 23:42 UTC, kgryte commented on lib/node_modules/@stdlib/iter/package.json
Why did you delete this file?

2024-07-28 23:43 UTC, kgryte requested changes
This PR needs significant modifications before it can be reviewed again and considered for inclusion in the project.

2024-10-13 20:45 UTC, closed without merging