feat: add `math/base/special/acotdf`
stdlib-js/stdlib pull request #2799
Opened 2024-08-16 04:44 UTC by gunjjoshi

## Description

> What is the purpose of this pull request?

This pull request:

-   adds `math/base/special/acotdf`, which would be the single-precision variant for [`math/base/special/acotd`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/acotd).

```c
float stdlib_base_acotdf( const float x );
```

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves a part of #649.

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-08-18 15:40 UTC, Planeshifter approved these changes
LGTM!

2024-08-23 07:50 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/acotdf/benchmark/benchmark.js
> +		x = ( randu() * 2.0 ) - 1.0;
@gunjjoshi Would you mind updating this and the other benchmark file?

2024-08-23 07:50 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/acotdf/benchmark/c/native/benchmark.c
> +		x = ( 2.0f * rand_float() ) - 1.0f;
Same comment.

2024-08-23 07:54 UTC, kgryte requested changes
Looks good. Once the benchmarks are updated, I'll approve and merge.

2024-08-23 08:08 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/acotdf/benchmark/benchmark.js
> +		x = ( randu() * 2.0 ) - 1.0;
Done!

2024-08-23 08:08 UTC, kgryte approved these changes
LGTM.

2024-08-23 08:13 UTC, merged