feat: add `array/base/cuevery-by` package
stdlib-js/stdlib pull request #2831
Opened 2024-08-24 16:52 UTC by Kaif987

This commit adds `base/cuevery-by` package

Resolves #2324

## Description

> What is the purpose of this pull request?
The purpose of this pull request is to add the `@stdlib/base/cuevery-by` package which cumulatively tests whether every array element in a provided array passes a test implemented by a predicate function. 

## Related Issues

> Does this pull request have any related issues?
#2324 

This pull request:

-   resolves #2324 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-08-25 12:27 UTC, Kaif987 commented
Hey @kgryte can you review this? let me know if any further changes are needed,

2024-09-07 16:35 UTC, Planeshifter requested changes
Thanks for the contribution!

Left a few comments; PR looks good overall.

2024-09-07 16:35 UTC, Planeshifter commented on lib/node_modules/@stdlib/array/base/cuevery-by/README.md
> +# cuevery-by
```suggestion
# cueveryBy
```

2024-09-07 16:35 UTC, Planeshifter commented on lib/node_modules/@stdlib/array/base/cuevery-by/README.md
> +Cumulatively test whether every array element in a provided array passes a test implemented by a predicate function.
```suggestion
Cumulatively tests whether every array element in a provided array passes a test implemented by a predicate function.
```

2024-09-07 16:35 UTC, Planeshifter commented on lib/node_modules/@stdlib/array/base/cuevery-by/lib/index.js
> +setReadOnly(main, 'assign', assign);
```suggestion
setReadOnly( main, 'assign', assign );
```

2024-09-07 16:35 UTC, Planeshifter commented on lib/node_modules/@stdlib/array/base/cuevery-by/lib/index.js
> +* Cumulatively tests whether every array element in a provided array passes a test implemented by a predicate function.
```suggestion
* Cumulatively test whether every array element in a provided array passes a test implemented by a predicate function.
```

2024-09-07 16:35 UTC, Planeshifter commented on lib/node_modules/@stdlib/array/base/cuevery-by/package.json
> +  "description": "cumulatively tests whether every array element in a provided array passes a test implemented by a predicate function",
```suggestion
  "description": "Cumulatively test whether every array element in a provided array passes a test implemented by a predicate function.",
```

2024-09-07 16:35 UTC, Planeshifter commented on lib/node_modules/@stdlib/array/base/cuevery-by/README.md
> +Cumulatively test whether every array element in a provided array passes a test implemented by a predicate function.
```suggestion
Cumulatively tests whether every array element in a provided array passes a test implemented by a predicate function and assigns the results to a provided output array.
```

2024-09-07 16:35 UTC, Planeshifter commented on lib/node_modules/@stdlib/array/base/cuevery-by/README.md
> +The invoked `predicate` function is provided three arguments:
We should move L67-L92 to before the `assign` documentation given it's applicable to both functions.

2024-09-07 16:35 UTC, Planeshifter commented on lib/node_modules/@stdlib/array/base/cuevery-by/docs/repl.txt
> +{{alias}}.assign( x, out, stride, offset, predicate[, thisArg])
```suggestion
{{alias}}.assign( x, out, stride, offset, predicate[, thisArg] )
```

2024-09-08 06:36 UTC, Kaif987 commented
Hey @Planeshifter  I just added the changes mentioned.

2024-09-23 14:09 UTC, Planeshifter approved these changes
Thank you, @Kaif987! Will merge shortly after CI has cleared.

2024-09-23 14:12 UTC, merged