add(base): `@stdlib/array/base/cunone-by` package
stdlib-js/stdlib pull request #2835
Opened 2024-08-26 12:38 UTC by Kaif987

Resolves #2325

## Description

> What is the purpose of this pull request?

This pull request:

-   This pull request adds the `@stdlib/array/base/cunone-by` package that cumulatively tests whether no array element in a provided array passes a test implemented by a predicate function

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #2325  

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-09-07 00:17 UTC, Planeshifter requested changes
Thank you for your contribution!

Left a few comments concerning some doc fixes, but overall this looks very good!

2024-09-07 00:17 UTC, Planeshifter commented on lib/node_modules/@stdlib/array/base/cunone-by/README.md
> +# cunone-by
```suggestion
# cunoneBy
```

2024-09-07 00:17 UTC, Planeshifter commented on lib/node_modules/@stdlib/array/base/cunone-by/README.md
> +Cumulatively test whether every array element in a provided array fails a test implemented by a predicate function.
```suggestion
Cumulatively tests whether every array element in a provided array fails a test implemented by a predicate function.
```

2024-09-07 00:17 UTC, Planeshifter commented on lib/node_modules/@stdlib/array/base/cunone-by/README.md
> +Cumulatively test whether every array element in a provided array fails a test implemented by a predicate function.
```suggestion
Cumulatively tests whether every array element in a provided array fails a test implemented by a predicate function and assigns the values to elements in a provided output array.
```

2024-09-07 00:17 UTC, Planeshifter commented on lib/node_modules/@stdlib/array/base/cunone-by/README.md
> +#### cunoneBy.assign( x, out, stride, offset, predicate\[, thisArg ] )
We should move the documentation for the `assign` method to after L92.

2024-09-07 14:45 UTC, Kaif987 commented
Hey @Planeshifter I have made the necessary changes. Is there anything else that I need to add

2024-09-07 16:09 UTC, Planeshifter commented on lib/node_modules/@stdlib/array/base/cunone-by/README.md
> +
```suggestion

```

2024-09-16 13:47 UTC, Planeshifter approved these changes
Let's land this! Thanks again for the PR!

2024-09-16 13:48 UTC, merged