feat: add `math/base/special/lcmf`
stdlib-js/stdlib pull request #3098
Opened 2024-11-11 16:06 UTC by aayush0325

Resolves #649.

## Description

> What is the purpose of this pull request?

This pull request:

-   resolves part of #649 by adding C implementation for `math/base/special/lcmf`

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #649

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

Open to reviews!!

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-11-11 16:15 UTC, aayush0325 commented
ready for review @Planeshifter !

2024-11-18 04:13 UTC, kgryte commented
/stdlib merge

2024-11-18 04:20 UTC, kgryte commented
/stdlib update-copyright-years

2024-11-18 07:55 UTC, gunjjoshi commented
We also have a PR for the same package at #3096.

2024-11-18 08:14 UTC, kgryte commented
@gunjjoshi Hmm...indeed. That other PR seems like it still needs a bit of work. Do you think this one is in better shape?

2024-11-18 08:18 UTC, gunjjoshi commented
@kgryte Yes, I think this one would need only a little changes, as compared to a lot more corrections, still to be pointed out in the other PR.

2024-11-18 09:35 UTC, aayush0325 commented
> We also have a PR for the same package at #3096.

Oh sorry my bad. I had been working on this since my PR for `math/base/special/gcdf` #2997. If the other PR is ready to merge then i can close this.

2024-11-19 14:03 UTC, aayush0325 commented
How should we proceed here then @kgryte ?

2024-11-19 14:07 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/lcmf/README.md
> +var round = require( '@stdlib/math/base/special/round' );
```suggestion
var roundf = require( '@stdlib/math/base/special/roundf' );
```

2024-11-19 14:07 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/lcmf/README.md
> +    a = round( randu()*50 );
```suggestion
    a = roundf( randu() * 50 );
```

2024-11-19 14:08 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/lcmf/README.md
> +    b = round( randu()*50 );
```suggestion
    b = roundf( randu() * 50 );
```

2024-11-19 14:08 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/lcmf/README.md
> +    b = round( randu()*50 );
Similarly, we can make these changes in `examples/index.js` as well.

2024-11-19 14:25 UTC, gunjjoshi requested changes

2024-11-19 14:25 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/lcmf/README.md
> +double v = stdlib_base_lcmf( 48.0f, 18.0f );
`v` must be of float type.

2024-11-19 14:25 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/lcmf/benchmark/benchmark.js
@aayush0325 We can follow https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/gcdf/benchmark/benchmark.js here. Specifically, we want to generate all values outside the loop, in an array.

2024-11-19 14:25 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/lcmf/benchmark/benchmark.native.js
Same comment regarding the pre-computation of values.

2024-11-19 14:25 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/lcmf/benchmark/c/native/benchmark.c
> +#define NAME "lcm"
```suggestion
#define NAME "lcmf"
```

2024-11-19 14:25 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/lcmf/benchmark/c/native/benchmark.c
> +}
Here, too, we can declare `x` and `y` as arrays, and initialize them beforehand. See: https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/gcdf/benchmark/c/native/benchmark.c#L92

2024-11-19 14:25 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/lcmf/docs/repl.txt
> +    single-precision floating-point numbers.
@aayush0325 Let's shift "single-precision" to the above line.

2024-11-19 14:25 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/lcmf/lib/main.js
> +	d = gcdf( a, b );
```suggestion
	}

	// Note: we rely on `gcdf` to perform further argument validation...
	d = gcdf( a, b );
```

2024-11-19 14:25 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/lcmf/lib/main.js
> +	return (a/d) * b;
Spacing is off here.

2024-11-19 14:25 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/lcmf/src/main.c
> +* double out = stdlib_base_lcmf( 21.0f, 6.0f );
This should be float.

2024-11-19 14:25 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/lcmf/src/main.c
> +	// Note: we rely on `gcdf` to perform further argument validation...
```suggestion
	}

	// Note: we rely on `gcdf` to perform further argument validation...
```

2024-11-19 14:25 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/lcmf/test/test.js
We should use "returns expected value" everywhere in this file, instead of using "returns NaN" or "returns [ any number ]".

2024-11-19 14:25 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/lcmf/test/test.js
This can be followed for `test.native.js` as well.

2024-11-19 14:27 UTC, gunjjoshi commented
This PR should be good to go once the comments have been addressed.

2024-11-19 15:34 UTC, aayush0325 commented on lib/node_modules/@stdlib/math/base/special/lcmf/benchmark/c/native/benchmark.c
> +}
Pushed, thanks @gunjjoshi !!

2024-11-19 15:43 UTC, gunjjoshi requested changes

2024-11-19 15:43 UTC, gunjjoshi commented on lib/node_modules/@stdlib/_tools/scripts/publish_packages.js
@aayush0325 This and a few more files, outside of `lcmf` have been pushed, we can remove them.

2024-11-19 15:44 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/lcmf/benchmark/benchmark.js
> +		z = lcmf( x[ i%x.length ], y[ i%y.length ] );
```suggestion
		z = lcmf( x[ i % x.length ], y[ i % y.length ] );
```

2024-11-19 15:44 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/lcmf/benchmark/benchmark.native.js
> +		z = lcmf( x[ i%x.length ], y[ i%y.length ] );
```suggestion
		z = lcmf( x[ i % x.length ], y[ i % y.length ] );
```

2024-11-19 15:45 UTC, aayush0325 commented on lib/node_modules/@stdlib/_tools/scripts/publish_packages.js
My apologies, that must've happened while i was rebasing this branch to include the commits made by the stdlib bot

2024-11-19 16:14 UTC, aayush0325 commented
@gunjjoshi resolved the issues with the commit history of this branch now this only contains the required files, with the requested commits.

2024-11-22 00:58 UTC, kgryte commented
/stdlib merge

2024-11-23 12:56 UTC, aayush0325 commented
any updates on this @gunjjoshi ?

2024-11-28 04:47 UTC, aayush0325 commented
does this need any changes @gunjjoshi ?

2024-12-01 03:05 UTC, Planeshifter approved these changes
PR looks good; thank you @aayush0325 for your contribution and to @gunjjoshi for reviewing.

2024-12-02 02:14 UTC, merged