feat: add `math/base/assert/is-oddf`
stdlib-js/stdlib pull request #3125
Opened 2024-11-17 07:12 UTC by gururaj1512

Resolves None.

## Description

> What is the purpose of this pull request?

- This pull request adds package `math/base/assert/is-oddf`

```c
bool stdlib_base_is_oddf( const float x );
```

## Related Issues

> Does this pull request have any related issues?

No.

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-11-18 04:09 UTC, kgryte commented
/stdlib merge

2024-11-18 18:51 UTC, gunjjoshi requested changes

2024-11-18 18:51 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-oddf/README.md
> +    x = roundf( randu()*100.0 );
```suggestion
    x = roundf( randu() * 100.0 );
```

2024-11-18 18:51 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-oddf/README.md
> +    const float x[] = { 5.0, -5.0, 3.14, -3.14, 0.0, 0.0/0.0 };
```suggestion
    const float x[] = { 5.0, -5.0, 3.14, -3.14, 0.0, 0.0 / 0.0 };
```

2024-11-18 18:51 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-oddf/README.md
> +    const float x[] = { 5.0, -5.0, 3.14, -3.14, 0.0, 0.0/0.0 };
Also, these numbers should have `f` suffix.

2024-11-18 18:51 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-oddf/README.md
> +</section>
This section must be kept empty, as it is filled automatically.

2024-11-18 18:51 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-oddf/README.md
> +[@stdlib/math/base/assert/is-even]: https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/assert/is-even
```suggestion
```

2024-11-18 18:51 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-oddf/README.md
> +[@stdlib/math/base/assert/is-even]: https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/assert/is-even
This too, can be removed.

2024-11-18 18:51 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-oddf/benchmark/benchmark.js
> +		y = isOddf( x );
We should use `random/array/discrete-uniform` here, and precompute the values, outside the loop. You can refer: https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/assert/is-evenf/benchmark/benchmark.js

2024-11-18 18:51 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-oddf/benchmark/benchmark.native.js
> +		y = isOddf( x );
Similar thing can be followed here as well.

2024-11-18 18:51 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-oddf/benchmark/c/native/benchmark.c
> +		b = stdlib_base_is_oddf( x );
We can initialize `x` as an array, and fill values in it outside the loop here as well. See: https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/assert/is-evenf/benchmark/c/native/benchmark.c

2024-11-18 18:51 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-oddf/docs/repl.txt
> +    number is an odd number.
We can place this whole sentence in a single line, as it would be less than 80 characters.

2024-11-18 18:51 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-oddf/examples/c/example.c
> +	const float x[] = { 5.0, -5.0, 3.14, -3.14, 0.0, 0.0/0.0 };
```suggestion
	const float x[] = { 5.0, -5.0, 3.14, -3.14, 0.0, 0.0 / 0.0 };
```

2024-11-18 18:51 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-oddf/examples/c/example.c
> +	const float x[] = { 5.0, -5.0, 3.14, -3.14, 0.0, 0.0/0.0 };
As these are single-precision values, we should use the `f` suffix here.

2024-11-18 18:51 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-oddf/README.md
> +}
You can use `random/array/discrete-uniform` here. See: https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/assert/is-evenf/examples/index.js

2024-11-18 18:51 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-oddf/README.md
> +}
And in `examples/index.js` as well.

2024-11-18 18:51 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-oddf/lib/main.js
We can use `float64ToFloat32` here, and wrap it around `x` and other arithmetic operations. Refer: https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/assert/is-evenf/lib/main.js

2024-11-18 18:51 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-oddf/lib/main.js
> +	return isEvenf( x+1.0 );
Spacing is off here.

2024-11-18 18:51 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-oddf/manifest.json
We can use the new format of `manifest.json` here, as we have used in https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/assert/is-evenf/manifest.json

2024-11-18 18:51 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-oddf/package.json
> +  "description": "Test if a finite single-precision floating-point numeric value is an odd number.",
```suggestion
  "description": "Test if a finite single-precision floating-point number is an odd number.",
```

2024-11-18 18:51 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-oddf/package.json
> +  "description": "Test if a finite single-precision floating-point numeric value is an odd number.",
This description should match with what we have used elsewhere.

2024-11-18 18:51 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-oddf/src/addon.c
We can replace this whole logic by using our macros. See: https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/assert/is-evenf/src/addon.c

2024-11-18 18:51 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-oddf/src/main.c
> +* @return	  output value
Mix of a tab and spaces.

2024-11-18 18:51 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-oddf/src/main.c
> +	if ( x > 0.0 ) {
```suggestion
	if ( x > 0.0f ) {
```

2024-11-18 18:51 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-oddf/src/main.c
> +		return stdlib_base_is_evenf( x - 1.0 );
```suggestion
		return stdlib_base_is_evenf( x - 1.0f );
```

2024-11-18 18:51 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-oddf/src/main.c
> +	return stdlib_base_is_evenf( x + 1.0 );
```suggestion
	return stdlib_base_is_evenf( x + 1.0f );
```

2024-11-18 18:51 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-oddf/test/test.js
> +		x = roundf( randu()*1.0e6 ) - 5.0e5;
```suggestion
		x = roundf( randu() * 1.0e6 ) - 5.0e5;
```

2024-11-18 18:51 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-oddf/test/test.js
> +		t.equal( bool, false, 'returns false when provided '+x );
```suggestion
		t.equal( bool, false, 'returns expected value when provided '+x );
```

2024-11-18 18:51 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-oddf/test/test.js
> +		x = roundf( randu()*1.0e6 ) - 5.0e5;
```suggestion
		x = roundf( randu() * 1.0e6 ) - 5.0e5;
```

2024-11-18 18:51 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-oddf/test/test.js
> +		if ( x%2 === 0 ) {
```suggestion
		if ( x % 2 === 0 ) {
```

2024-11-18 18:51 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-oddf/test/test.js
> +		t.equal( bool, true, 'returns true when provided '+x );
```suggestion
		t.equal( bool, true, 'returns expected value when provided '+x );
```

2024-11-18 18:51 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-oddf/test/test.js
> +	t.equal( isOddf( +0.0 ), false, 'returns false' );
```suggestion
	t.equal( isOddf( +0.0 ), false, 'returns expected value' );
```

2024-11-18 18:51 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-oddf/test/test.js
> +	t.equal( isOddf( +0.0 ), false, 'returns false' );
We can replace "true"/"false" by "expected value" below and in `test.native.js` as well.

2024-11-18 18:51 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-oddf/test/test.js
> +	t.equal( isOddf( 0.0/0.0 ), false, 'returns false' );
```suggestion
	t.equal( isOddf( 0.0 / 0.0 ), false, 'returns false' );
```

2024-11-18 18:51 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-oddf/test/test.native.js
> +		x = roundf( randu()*1.0e6 ) - 5.0e5;
```suggestion
		x = roundf( randu() * 1.0e6 ) - 5.0e5;
```

2024-11-18 18:51 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-oddf/test/test.native.js
> +		x = roundf( randu()*1.0e6 ) - 5.0e5;
```suggestion
		x = roundf( randu() * 1.0e6 ) - 5.0e5;
```

2024-11-18 18:51 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-oddf/test/test.native.js
> +		if ( x%2 === 0 ) {
```suggestion
		if ( x % 2 === 0 ) {
```

2024-11-18 18:51 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-oddf/test/test.native.js
> +	t.equal( isOddf( 0.0/0.0 ), false, 'returns false' );
```suggestion
	t.equal( isOddf( 0.0 / 0.0 ), false, 'returns false' );
```

2024-11-25 11:28 UTC, gururaj1512 commented
/stdlib merge

2024-12-04 04:24 UTC, gunjjoshi commented
@kgryte We can proceed with this PR, rather than its duplicate at #3316, given that the changes in this PR look good, and as it was opened earlier.

2024-12-04 04:48 UTC, gunjjoshi approved these changes

2024-12-10 13:30 UTC, Planeshifter approved these changes
Let's land this PR; thanks @gururaj1512!

2024-12-10 13:33 UTC, merged