feat: add `at` method to `array/fixed-endian-factory`
stdlib-js/stdlib pull request #3184
Opened 2024-11-19 19:52 UTC by aayush0325

Resolves #3135 .

## Description

> What is the purpose of this pull request?

This pull request:

-   adds `at` method to `array/fixed-endian-factory`
-   adds the respective benchmarks and tests
-   updates README

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #3135  

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

the `at` method in `@stdlib/array/bool` had all the benchmarks written in a single file so i followed that convention. kindly let me know if we need any changes.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-11-19 19:55 UTC, aayush0325 commented
kindly give this a review @kgryte !

2024-11-19 21:22 UTC, kgryte commented on lib/node_modules/@stdlib/array/fixed-endian-factory/README.md
> +#### TypedArrayFE.prototype.at( i )
@aayush0325 Would you mind moving this method so that the prototype methods are in alphabetical order?

2024-11-19 21:24 UTC, kgryte commented on lib/node_modules/@stdlib/array/fixed-endian-factory/benchmark/benchmark.at.js
> +bench( pkg+':at:endianness=little-endian', function benchmark( b ) {
```suggestion
bench( pkg+'::nonnegative_indices:at:endianness=little-endian', function benchmark( b ) {
```

2024-11-19 21:24 UTC, kgryte commented on lib/node_modules/@stdlib/array/fixed-endian-factory/benchmark/benchmark.at.js
> +bench( pkg+':at:endianness=little-endian', function benchmark( b ) {
```suggestion
bench( pkg+'::negative_indices:at:endianness=little-endian', function benchmark( b ) {
```

2024-11-19 21:25 UTC, kgryte commented on lib/node_modules/@stdlib/array/fixed-endian-factory/benchmark/benchmark.at.js
> +bench( pkg+':at:endianness=big-endian', function benchmark( b ) {
```suggestion
bench( pkg+'::nonnegative_indices:at:endianness=big-endian', function benchmark( b ) {
```

2024-11-19 21:25 UTC, kgryte commented on lib/node_modules/@stdlib/array/fixed-endian-factory/benchmark/benchmark.at.js
> +bench( pkg+':at:endianness=big-endian', function benchmark( b ) {
```suggestion
bench( pkg+'::negative_indices:at:endianness=big-endian', function benchmark( b ) {
```

2024-11-19 21:26 UTC, kgryte commented on lib/node_modules/@stdlib/array/fixed-endian-factory/lib/main.js
> +	* Takes an integer value and returns the data at that index.
@aayush0325 Would you mind moving this so that methods are defined in alphabetical order? You'll want to move to L461.

2024-11-19 21:26 UTC, kgryte commented on lib/node_modules/@stdlib/array/fixed-endian-factory/lib/main.js
> +	* Takes an integer value and returns the data at that index.
```suggestion
	* Returns an array element located at integer position (index) `i`, with support for both nonnegative and negative integer indices.
```

2024-11-19 21:27 UTC, kgryte commented on lib/node_modules/@stdlib/array/fixed-endian-factory/lib/main.js
> +	* @param {integer} idx - required index
```suggestion
	* @param {integer} idx - element index
```

2024-11-19 21:27 UTC, kgryte commented on lib/node_modules/@stdlib/array/fixed-endian-factory/lib/main.js
> +	* @throws {TypeError} first argument must be an integer
```suggestion
	* @throws {TypeError} must provide an integer
```

2024-11-19 21:28 UTC, kgryte commented on lib/node_modules/@stdlib/array/fixed-endian-factory/lib/main.js
> +			throw new TypeError( format( 'invalid argument. Must provide a nonnegative integer. Value: `%s`.', idx ) );
```suggestion
			throw new TypeError( format( 'invalid argument. Must provide an integer. Value: `%s`.', idx ) );
```

2024-11-19 21:28 UTC, kgryte commented on lib/node_modules/@stdlib/array/fixed-endian-factory/lib/main.js
> +		if ( idx >= this._length || idx < 0 ) {
```suggestion
		if ( idx < 0 || idx >= len ) {
```

2024-11-19 21:32 UTC, kgryte commented on lib/node_modules/@stdlib/array/fixed-endian-factory/lib/main.js
> +	/**
@aayush0325 Re-adding the comment: namely, this should be moved to L461 so that methods are defined in alphabetical order.

2024-11-19 21:33 UTC, kgryte commented on lib/node_modules/@stdlib/array/fixed-endian-factory/lib/main.js
> +	* @param {*} [thisArg] function invocation context
```suggestion
```

2024-11-19 21:34 UTC, kgryte requested changes
Thanks for working on this, @aayush0325. Two minor comments. Once resolved, this should be ready for merge.

2024-11-19 21:35 UTC, kgryte commented
> benchmarks written in a single file so i followed that convention. 

Yes, for `at` that makes sense, as element access should not be length-dependent.

2024-11-20 00:38 UTC, aayush0325 commented
I've moved the stuff in `main.js` to where you requested and I've placed it alphabetically among the `non static` methods in
`README.md`. I hope that's okay

2024-11-20 02:55 UTC, kgryte approved these changes
LGTM. Thanks, @aayush0325!

2024-11-20 02:56 UTC, merged