feat: add `every` method to `array/fixed-endian-factory`
stdlib-js/stdlib pull request #3200
Opened 2024-11-20 10:42 UTC by aayush0325

Resolves #3138

## Description

> What is the purpose of this pull request?

This pull request:

-   adds `every` method to `array/fixed-endian-factory` with required docs, tests and benchmarks

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #3138 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-11-20 10:47 UTC, aayush0325 commented
kindly give this a review @kgryte!

2024-11-21 20:59 UTC, kgryte commented on lib/node_modules/@stdlib/array/fixed-endian-factory/README.md
> +
```suggestion
```

2024-11-21 21:01 UTC, kgryte commented on lib/node_modules/@stdlib/array/fixed-endian-factory/benchmark/benchmark.every.length.js
> +	return value > 0;
```suggestion
	return value >= 0;
```

Given that `zeroTo` returns an array whose first element is `0`, you need to ensure that the predicate function passes for all values in order to actually measure perf as a function of array length.

2024-11-21 21:01 UTC, kgryte commented on lib/node_modules/@stdlib/array/fixed-endian-factory/benchmark/benchmark.every.length.js
> +		bench( pkg+':forEach:len='+len, f );
```suggestion
		bench( pkg+':every:len='+len, f );
```

2024-11-21 21:02 UTC, kgryte commented on lib/node_modules/@stdlib/array/fixed-endian-factory/lib/main.js
> +	/**
This needs to be moved to before `forEach`. Currently, this is not inserted in alphabetical order.

2024-11-21 21:04 UTC, kgryte commented on lib/node_modules/@stdlib/array/fixed-endian-factory/test/test.every.js
> +tape( 'the method returns `true` if operating on an empty boolean array', function test( t ) {
```suggestion
tape( 'the method returns `true` if operating on an empty array', function test( t ) {
```

2024-11-21 21:06 UTC, kgryte requested changes
Apart from reordering declared methods, this PR is looking good.

2024-11-22 01:30 UTC, aayush0325 commented
I've changed the position of `every` method to be before the `forEach` method.

2024-11-22 01:45 UTC, kgryte approved these changes
LGTM. Thanks, @aayush0325!

2024-11-22 01:45 UTC, merged