feat: add C implementation for `math/base/special/minmax`
stdlib-js/stdlib pull request #3206
Opened 2024-11-21 06:50 UTC by AbhijitRaut04

Resolves #2106 .

## Description

> This PR contains the C implementation for minmax function

This pull request:

-   C implementation with benchmarks added in this PR.

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #2106 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other
Benchmarks
![image](https://github.com/user-attachments/assets/18e9b49d-980a-4573-9afb-85d2cd3430bd)

Examples
![image](https://github.com/user-attachments/assets/269232e5-b265-480d-8f89-c22740288b55)

Tests
![image](https://github.com/user-attachments/assets/0adc1ff5-5a3b-485d-b615-46fa24cacb17)

addon.c
![image](https://github.com/user-attachments/assets/49afada3-8d61-434b-92bd-e9ec2f9650b1)

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-11-21 06:58 UTC, AbhijitRaut04 commented
@gunjjoshi Please take a review of this PR.

2024-11-21 08:04 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/minmax/README.md
> +Copyright (c) 2024 The Stdlib Authors.
```suggestion
Copyright (c) 2018 The Stdlib Authors.
```

We do not change copyright year when a pre-existing file is updated.

2024-11-21 08:04 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/minmax/README.md
> +double stdlib_base_minmax( const double x, const double y );
@AbhijitRaut04  This is different from the function signature that you've used in `main.c`. You might want to update this accordingly here and everywhere else.

2024-11-21 09:09 UTC, AbhijitRaut04 commented
@gunjjoshi I have applied suggested changes. 
I request you to review #3181 this similar PR also.

2024-11-21 10:22 UTC, gunjjoshi requested changes

2024-11-21 10:22 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/minmax/README.md
> +Gives the minimum and maximum value.
This doesn't match with what we have in `main.js`.

2024-11-21 10:22 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/minmax/README.md
> +// min = -0.0, max = 0.0
```suggestion
double min;
double max;

stdlib_base_minmax( 4.2, 3.14, &min, &max );
```

Let's follow what we we have in https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/rempio2/README.md?plain=1#L146 here.

2024-11-21 10:22 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/minmax/README.md
> +-   **y**: `[in] double` input value.
Missing `min` and `max`.

2024-11-21 10:22 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/minmax/README.md
> +double stdlib_base_minmax( const double x, const double y, double* min, double* max );
This must be `void` instead of `double`.

2024-11-21 10:22 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/minmax/README.md
> +    int i;
These variables should be listed based on decreasing order of their lengths.

2024-11-21 10:22 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/minmax/benchmark/benchmark.native.js
> +var randu = require( '@stdlib/random/base/randu' );
```suggestion
var randu = require( '@stdlib/random/array/uniform' );
```

2024-11-21 10:22 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/minmax/benchmark/benchmark.native.js
> +		}
We should update this to use generate values outside the loop. See: https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/csch/benchmark/benchmark.js#L32

2024-11-21 10:22 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/minmax/benchmark/benchmark.native.js
> +	if ( isnan( v[0] ) || isnan( v[1] ) ) {
```suggestion
	if ( isnan( v[ 0 ] ) || isnan( v[ 1 ] ) ) {
```

2024-11-21 10:22 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/minmax/benchmark/benchmark.native.js
> +		}
You can make similar changes in `benchmark.js` as well.

2024-11-21 10:22 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/minmax/benchmark/c/native/benchmark.c
> +	double x2[100];
```suggestion
	double x1[ 100 ];
	double x2[ 100 ];
```

2024-11-21 10:22 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/minmax/benchmark/c/native/benchmark.c
> +		if ( min != min && max != max ) {
You can use `||` instead of `&&` here.
Ref: https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/modf/benchmark/c/native/benchmark.c#L104

2024-11-21 10:22 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/minmax/benchmark/c/native/benchmark.c
> +	if ( min != min && max != max ) {
Same comment regarding the use of `||`.

2024-11-21 10:22 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/minmax/examples/c/example.c
> +
```suggestion
```

2024-11-21 10:22 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/minmax/examples/c/example.c
> +	const double x2[] = { -0.22, 0.66, 0.0, -0.55, 0.33, 1.0, 0.0 / 0.0, 0.11, 0.45, -0.78 };
```suggestion
    const double x1[] = { 1.0, 0.45, -0.89, 0.0 / 0.0, -0.78, -0.22, 0.66, 0.11, -0.55, 0.0 };
	const double x2[] = { -0.22, 0.66, 0.0, -0.55, 0.33, 1.0, 0.0 / 0.0, 0.11, 0.45, -0.78 };
```

The indentation is off here.

2024-11-21 10:22 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/minmax/examples/c/example.c
> +		double max;
We should declare these outside the loop.

2024-11-21 10:22 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/minmax/include/stdlib/math/base/special/minmax.h
> +* Evaluates the min and max of two values.
This should match with what we have in `main.js`.

2024-11-21 10:22 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/minmax/include/stdlib/math/base/special/minmax.h
> +* @param max   double to store maximum value
We can remove these annotations from here.

2024-11-21 10:22 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/minmax/include/stdlib/math/base/special/minmax.h
> +void stdlib_base_minmax(const double x, const double y, double* min, double* max );
```suggestion
void stdlib_base_minmax( const double x, const double y, double* min, double* max );
```

2024-11-21 10:22 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/minmax/lib/native.js
> +* Returns the minimum and maximum value, ignoring NaN.
Same comment regarding the descriptions here and elsewhere.

2024-11-21 10:22 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/minmax/manifest.json
This file should have an empty line at the end.

2024-11-21 10:22 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/minmax/package.json
This is not necessary. You can revert this change.

2024-11-21 10:22 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/minmax/src/addon.c
> +
Same thing must be done for the third argument as well.

2024-11-21 10:22 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/minmax/src/main.c
> +* @param max   to store maximum value
Indentation is off here.

2024-11-21 10:22 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/minmax/src/main.c
> +* @param max   to store maximum value
Also, you can use `destination to store minimum value` and `destination to store maximum value` here.

2024-11-21 10:22 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/minmax/src/main.c
> +*/
We can follow https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/rempio2/src/main.c#L450 here.

2024-11-21 10:22 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/minmax/src/main.c
> +
```suggestion
```

2024-11-21 10:22 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/minmax/src/main.c
> +
```suggestion
```

2024-11-21 10:22 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/minmax/src/main.c
> +}
This should follow our JS implementation. We are missing the https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/minmax/lib/assign.js#L64 block here.

2024-11-21 10:22 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/minmax/test/test.native.js
> +	t.strictEqual( isnan( v[ 1 ] ), true, 'returns NaN' );
You can replace `returns NaN` by `returns expected value here.`

2024-11-21 10:22 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/minmax/test/test.native.js
> +	t.strictEqual( v[ 1 ], +0.0, 'returns +0' );
Same comment here as well.

2024-11-21 10:22 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/minmax/test/test.native.js
> +	t.strictEqual( v[ 1 ], 3.14, 'returns max value' );
And, here too.

2024-11-22 01:00 UTC, kgryte commented
/stdlib merge

2024-11-22 01:03 UTC, kgryte commented
/stdlib lint-autofix

2024-11-23 12:13 UTC, AbhijitRaut04 commented
@gunjjoshi I have added the changes reviewed. Any other updates required ?

2024-11-27 10:07 UTC, AbhijitRaut04 commented
@kgryte @gunjjoshi I have added the changes reviewed. Kindly review this PR ?

2024-12-20 16:06 UTC, gunjjoshi requested changes

2024-12-20 16:06 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/minmax/README.md
> +> Returns the minimum and maximum values.
```suggestion
> Return the minimum and maximum values.
```

2024-12-20 16:06 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/minmax/README.md
> -
@AbhijitRaut04 We should not remove these, as the JS implementation of this package already exists. "related" sections are kept empty only when a new package is added.

2024-12-20 16:06 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/minmax/README.md
> -
Same comment here, we should keep these as well.

2024-12-20 16:06 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/minmax/benchmark/benchmark.native.js
> +var randu = require( '@stdlib/random/base/uniform' );
@AbhijitRaut04 We should use `@stdlib/random/array/uniform` here, and declare `x` and `y` below as arrays. Then, we can can initialize them with values using `randu`.

2024-12-20 16:06 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/minmax/benchmark/benchmark.native.js
> +var randu = require( '@stdlib/random/base/uniform' );
Same goes for `benchmark.js` as well.

2024-12-20 16:06 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/minmax/benchmark/c/native/benchmark.c
> +		stdlib_base_minmax( x1[ i % 100 ], x2[ i % 100 ], &min, &max );
@AbhijitRaut04 Let's keep the names of the variables as `x` and `y` instead of `x1` and `x2`. That would match with what we have in the JS benchmarks.

2025-05-19 22:05 UTC, closed without merging

2025-05-19 22:05 UTC, anandkaranubc commented
Closed via https://github.com/stdlib-js/stdlib/pull/6296