add `includes()` method to `array/fixed-endian-factory`
stdlib-js/stdlib pull request #3283
Opened 2024-11-27 14:09 UTC by ahmad-kashkoush

Resolves #3145 .

## Description

> What is the purpose of this pull request?

This pull request:

-   support includes method to [@stdlib/array/fixed-endian-factory](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/array/fixed-endian-factory).

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #3145 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-11-27 15:39 UTC, headlessNode commented
@ahmad-kashkoush the title should start with "feat:"

2024-11-27 17:22 UTC, ahmad-kashkoush commented
> @ahmad-kashkoush the title should start with "feat:"

Done, may you review PR?

2024-11-27 20:34 UTC, headlessNode requested changes
A few suggestions regarding the documentation, otherwise looks good. A more thorough review will be done by the maintainers.

2024-11-27 20:34 UTC, headlessNode commented on lib/node_modules/@stdlib/array/fixed-endian-factory/README.md
> +Returns `true` if element can be found.
```suggestion
Returns `true` if the specified `searchElement` is present in the array.
```

2024-11-27 20:34 UTC, headlessNode commented on lib/node_modules/@stdlib/array/fixed-endian-factory/README.md
> +If `searchElement` is not present in the array, the method returns `false`.
```suggestion
If the specified `searchElement` is not present in the array, the method returns `false`.
```

2024-11-27 20:34 UTC, headlessNode commented on lib/node_modules/@stdlib/array/fixed-endian-factory/lib/main.js
> +	* A boolean value which is true if the value `searchElement` is found.
```suggestion
	* Returns `true` if the specified `searchElement` is present in the array.
```

2024-11-27 20:34 UTC, headlessNode commented on lib/node_modules/@stdlib/array/fixed-endian-factory/lib/main.js
> +	* @returns {boolean} boolean indicating that `searchElement` is found
```suggestion
	* @returns {boolean} boolean indicating whether the `searchElement` is present in the array
```

2024-11-27 20:38 UTC, ahmad-kashkoush commented on lib/node_modules/@stdlib/array/fixed-endian-factory/lib/main.js
> +	* @returns {boolean} boolean indicating that `searchElement` is found
ok,  thanks

2024-12-01 17:17 UTC, ahmad-kashkoush commented
Good evening, @kgryte may you this a review

2024-12-03 22:51 UTC, kgryte commented on lib/node_modules/@stdlib/array/fixed-endian-factory/README.md
> +Returns `true` if the specified `searchElement` is present in the array.
```suggestion
Returns a boolean indicating whether an array includes a provided value.
```

2024-12-03 22:52 UTC, kgryte commented on lib/node_modules/@stdlib/array/fixed-endian-factory/README.md
> +var idx = arr.includes( 5.0 );
```suggestion

idx = arr.includes( 5.0 );
```

2024-12-03 22:53 UTC, kgryte commented on lib/node_modules/@stdlib/array/fixed-endian-factory/lib/main.js
> +	/**
```suggestion

	/**
```

2024-12-03 22:53 UTC, kgryte commented on lib/node_modules/@stdlib/array/fixed-endian-factory/lib/main.js
> +	* Returns `true` if the specified `searchElement` is present in the array.
```suggestion
	* Returns a boolean indicating whether an array includes a provided value.
```

2024-12-03 22:54 UTC, kgryte commented on lib/node_modules/@stdlib/array/fixed-endian-factory/lib/main.js
> +	* @param {*} searchElement - element to search for
```suggestion
	* @param {*} searchElement - search element
```

2024-12-03 22:54 UTC, kgryte commented on lib/node_modules/@stdlib/array/fixed-endian-factory/lib/main.js
> +	* @returns {boolean} boolean indicating that `searchElement` is found
```suggestion
	* @returns {boolean} boolean indicating whether an array includes a provided value
```

2024-12-03 22:58 UTC, kgryte approved these changes
LGTM. Thanks, @ahmad-kashkoush!

2024-12-03 22:59 UTC, kgryte commented
@ahmad-kashkoush Would you mind resolving the merge conflicts? Once those are resolved, we can merge. Also, so that methods are listed in alphabetical order, `includes` should come before `indexOf` in both the README and `main.js` file.

2024-12-04 13:53 UTC, merged