feat: add `constants/float32/sqrt-two`
stdlib-js/stdlib pull request #3328
Opened 2024-12-04 21:26 UTC by gururaj1512

Resolves #3327.

## Description

> What is the purpose of this pull request?

This pull request:

-   This RFC proposes adding the package @stdlib/constants/float32/sqrt-two returning square root of single-precision floating-point number 2.

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   None

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-12-05 10:29 UTC, gunjjoshi requested changes

2024-12-05 10:29 UTC, gunjjoshi commented on lib/node_modules/@stdlib/constants/float32/sqrt-two/README.md
> +> [Square root][@stdlib/math/base/special/sqrt] of single-precision floating-point number `2`.
We should point to the single-precision package of `sqrt` here and everywhere else in this file, i.e., `sqrtf`.

2024-12-05 10:29 UTC, gunjjoshi commented on lib/node_modules/@stdlib/constants/float32/sqrt-two/lib/index.js
> +* Square root of single-precision floating-point number `2`.
```suggestion
* Square root of `2` as a single-precision floating-point number.
```

2024-12-05 10:29 UTC, gunjjoshi commented on lib/node_modules/@stdlib/constants/float32/sqrt-two/lib/index.js
> +* Square root of single-precision floating-point number `2`.
@gururaj1512 Would you mind updating the description everywhere else in this package?

2024-12-07 11:31 UTC, gunjjoshi approved these changes

2024-12-07 13:19 UTC, Planeshifter approved these changes

2024-12-07 13:24 UTC, merged