feat: add `math/base/special/lucasf`
stdlib-js/stdlib pull request #3348
Opened 2024-12-06 10:57 UTC by aayush0325

Progresses #649

## Description

> What is the purpose of this pull request?

This pull request:

-   adds `math/base/special/lucasf`

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   Progresses #649

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

This branch can further be rebased to include `constants/float32/max-safe-nth-lucas` macro from #3337 instead of using just 34 as it is.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-12-06 10:58 UTC, aayush0325 commented
/stdlib help

2024-12-06 10:59 UTC, aayush0325 commented
/stdlib update-copyright-years

2024-12-06 11:00 UTC, aayush0325 commented
/stdlib update-copyright-years

2024-12-06 11:13 UTC, gunjjoshi commented
@aayush0325 Thanks for working on this. Can you please update both JS and C benchmarks to pre-compute the values, outside the loop?

2024-12-06 11:15 UTC, aayush0325 commented
got it, pushing soon.

2024-12-06 11:31 UTC, aayush0325 commented
pushed

2024-12-13 10:59 UTC, aayush0325 commented
/stdlib merge

2024-12-14 16:34 UTC, aayush0325 commented
/stdlib merge

2024-12-14 17:07 UTC, aayush0325 commented
good evening @gunjjoshi, this branch has been rebased to make use of `STDLIB_CONSTANT_FLOAT32_MAX_SAFE_NTH_LUCAS` macros in js and C files instead of defining them as a variable, can you please give this a look.

2024-12-17 05:10 UTC, gunjjoshi requested changes

2024-12-17 05:10 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/lucasf/benchmark/c/native/benchmark.c
The indentation of this file is off. It must use tabs, not spaces.

2024-12-17 05:10 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/lucasf/benchmark/benchmark.js
@aayush0325 Can you update this file to use `@stdlib/random/array/uniform` to generate random numbers beforehand, instead of using `@stdlib/random/base/randu`?

2024-12-17 05:10 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/lucasf/README.md
> +> Compute the nth [Lucas number][lucas-number] in single-precision floating-point format.
```suggestion
> Compute the nth [Lucas number][lucas-number] in single-precision floating-point format.
```

@aayush0325 Can you update this here and everywhere else in this PR, to use:

```
Compute/Computes the nth [Lucas number][lucas-number] as a single-precision floating-point number.
```

2024-12-17 05:10 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/lucasf/src/main.c
> +    return lucas_value[ n ];
We should use tabs here, not spaces.

2024-12-17 05:10 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/lucasf/test/test.js
> +	t.strictEqual( isnanf( lucasf( -3.14 ) ), true, 'returns NaN' );
```suggestion
	t.strictEqual( isnanf( lucasf( -3.14 ) ), true, 'returns expected value' );
```
We can change this here and below too.

2024-12-17 05:10 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/lucasf/test/test.js
> +	t.strictEqual( isnanf( lucasf( -3.14 ) ), true, 'returns NaN' );
This applies in `test.native.js` as well.

2024-12-17 05:10 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/lucasf/examples/c/example.c
> +    }
Indentation is off.

2024-12-17 08:53 UTC, aayush0325 commented
good afternoon @gunjjoshi. I've pushed the requested changes. However a linting error was stopping me from updating the description in `lib/index.js` to "Compute/Computes the nth Lucas number as a single-precision floating-point number." Please let me know how to proceed there.

2024-12-17 10:19 UTC, gunjjoshi commented
@aayush0325 You don't have to use `Compute/Computes` everywhere. What I was trying to say was,
For files such as `index.js`, `package.json`, etc. we should use:

```
Compute the nth [Lucas number][lucas-number] as a single-precision floating-point number.
```

while, for the rest files, we should use:

```
Computes the nth [Lucas number][lucas-number] as a single-precision floating-point number.
```

2024-12-17 10:22 UTC, aayush0325 commented
Ah, my bad. pushing the needed changes soon.

2024-12-17 10:31 UTC, aayush0325 commented
Pushed, sorry for the misunderstanding.

2024-12-17 10:53 UTC, aayush0325 commented
I don't get why this is failing the linting tests this seems to run fine locally on the dev container @gunjjoshi

2024-12-18 05:08 UTC, aayush0325 commented
/stdlib merge

2024-12-19 01:08 UTC, kgryte commented
/stdlib merge

2024-12-19 01:20 UTC, kgryte commented
/stdlib merge

2024-12-20 14:54 UTC, gunjjoshi requested changes

2024-12-20 14:54 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/lucasf/src/addon.c
> +STDLIB_MATH_BASE_NAPI_MODULE_I_F( stdlib_base_lucasf )
Although we have used `STDLIB_MATH_BASE_NAPI_MODULE_I_D` in [`math/base/special/lucas`](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/lucas/src/addon.c#L22), we can use [`STDLIB_MATH_BASE_NAPI_MODULE_I_I`](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/napi/unary/src/main.c#L521) here and modify the function signature accordingly, as we have the API ready which accepts and returns an `int32` value, but we don't have an API to accept `int32` and return an `int64` value, as in the case of `lucas`.

2024-12-20 14:55 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/lucasf/src/addon.c
> +STDLIB_MATH_BASE_NAPI_MODULE_I_F( stdlib_base_lucasf )
cc: @kgryte

2025-02-16 09:13 UTC, kgryte commented
@aayush0325 Did you mean to delete the `lucasf` branch?

2025-02-16 09:19 UTC, aayush0325 commented
> @aayush0325 Did you mean to delete the `lucasf` branch?

was getting rid of the merged branches, this was a mistake :sweat_smile:

2025-04-17 17:20 UTC, anandkaranubc commented
This RFC has been completed via https://github.com/stdlib-js/stdlib/pull/6223.

2025-04-17 17:20 UTC, closed without merging