feat: add `math/base/special/exp2f`
stdlib-js/stdlib pull request #3366
Opened 2024-12-07 17:40 UTC by aayush0325

Resolves #649

## Description

> What is the purpose of this pull request?

This pull request:

-   adds `math/base/special/exp2f`

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #649

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-12-07 17:40 UTC, aayush0325 commented
/stdlib update-copyright-years

2024-12-15 03:08 UTC, Planeshifter requested changes
Thanks for your work on this PR! Looks great overall, but some changes will be needed for the JavaScript implementation.

In `main.js`, we need to use the helper function

```js
var float64ToFloat32 = require( '@stdlib/number/float64/base/to-float32' );
```

in order to ensure that all operations are done in a manner consistent with single-precision arithmetic. Recall that in JavaScript, all numbers are double-precision by default, so to emulate single-precision we must, in addition to using the single-precision variants of math functions, explicitly cast intermediate results and constants to single-precision floats.

2024-12-15 03:44 UTC, aayush0325 commented
good morning @Planeshifter! I've wrapped the intermediate results and final answers in `float64ToFloat32()`. If there's anything else that needs to be changed here please let me know.

2024-12-15 03:53 UTC, aayush0325 commented
Also, as mentioned in the questions section of the PR, what should i do about `benchmark/c/cephes` since it doesn't seem to compile locally and it fails on CI as well. Is there something that I'm missing from my side.

2025-03-19 17:30 UTC, gunjjoshi commented
/stdlib update-copyright-years

2025-03-20 17:07 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/exp2f/package.json
> +    "natural",
```suggestion
```

2025-03-20 17:07 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/exp2f/package.json
> +    "natural",
"natural" is for base-e, i.e., `exp`. But, `exp2f` is base-2.

2025-03-20 17:07 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/exp2f/package.json
> +    "euler",
```suggestion
```

2025-03-20 17:07 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/exp2f/package.json
> +    "euler",
For the same reason as above, we can remove this too, as this is base 2, not base `e`.

2025-03-20 17:10 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/exp2f/README.md
> +}
@aayush0325 We can use `@stdlib/random/array/uniform` here.

2025-03-20 17:13 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/exp2f/benchmark/benchmark.native.js
> +var exp2 = tryRequire( resolve( __dirname, './../lib/native.js' ) );
```suggestion
var exp2f = tryRequire( resolve( __dirname, './../lib/native.js' ) );
```

2025-03-20 17:14 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/exp2f/benchmark/benchmark.native.js
> +	'skip': ( exp2 instanceof Error )
```suggestion
	'skip': ( exp2f instanceof Error )
```

2025-03-20 17:14 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/exp2f/benchmark/benchmark.native.js
> +		y = exp2( x[ i%x.length ] );
```suggestion
		y = exp2f( x[ i%x.length ] );
```

2025-03-20 17:15 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/exp2f/benchmark/benchmark.native.js
> +		if ( isnan( y ) ) {
```suggestion
		if ( isnanf( y ) ) {
```

2025-03-20 17:15 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/exp2f/benchmark/benchmark.native.js
> +	if ( isnan( y ) ) {
```suggestion
	if ( isnanf( y ) ) {
```

2025-03-20 17:15 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/exp2f/benchmark/benchmark.native.js
> +var isnan = require( '@stdlib/math/base/assert/is-nan' );
```suggestion
var isnanf = require( '@stdlib/math/base/assert/is-nan'f );
```

2025-03-21 02:12 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/exp2f/README.md
> +}
Same can be followed in `examples/index.js` too.

2025-03-21 02:14 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/exp2f/benchmark/c/native/benchmark.c
> +	double t;
```suggestion
	double t;
	float y;
```

2025-03-21 02:15 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/exp2f/benchmark/c/benchmark.c
> +static double rand_float( void ) {
```suggestion
static float rand_float( void ) {
```

2025-03-21 02:16 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/exp2f/benchmark/c/benchmark.c
> +static double rand_float( void ) {
We are returning a `float` here.

2025-03-21 02:16 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/exp2f/benchmark/c/benchmark.c
> +	double t;
```suggestion
	double t;
	float y;
```

2025-03-21 02:17 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/exp2f/benchmark/c/benchmark.c
> +	double t;
`y` must be a `float`, as `exp2f` returns a `float`, in L103.

2025-03-21 02:19 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/exp2f/benchmark/c/benchmark.c
> +		x[ i ] = ( 240.0 * rand_float() ) - 120.0;
Missing `f` suffixes.

2025-03-21 03:41 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/exp2f/docs/repl.txt
> +    single-precision floating-point format.
```suggestion
    Evaluates the base 2 exponential function in single-precision
    floating-point format.
```

2025-03-21 03:43 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/exp2f/examples/c/example.c
> +    }
@aayush0325 We should be using tabs here, not spaces.

2025-03-21 03:58 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/exp2f/lib/main.js
> +*     | IEEE       | -1022,+1024 | 30000    | 1.8e-16 | 5.4e-17 |
@aayush0325 These values for domain, number of trials, peak and rms are for the double-precision implementation, i.e., `exp2`. You'll need to check the single-precision implementation and update these.

2025-03-21 03:59 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/exp2f/lib/main.js
> +*     | IEEE       | -1022,+1024 | 30000    | 1.8e-16 | 5.4e-17 |
For instance, the domain for `exp2f` will be restricted to `-127,+127`, and not `-1022,+1024`.

2025-03-21 04:03 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/exp2f/lib/main.js
> +	// Separate into integer and fractional parts...
```suggestion
	}

	// Separate into integer and fractional parts...
```

2025-03-21 04:03 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/exp2f/lib/main.js
> +	// Separate into integer and fractional parts...
Empty line before a comment.

2025-03-21 04:03 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/exp2f/lib/main.js
> +		return float64ToFloat32( 0.0 );
```suggestion
		return 0.0;
```

2025-03-21 04:04 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/exp2f/lib/main.js
> +		return float64ToFloat32( 0.0 );
`0.0` can be returned directly here.

2025-03-21 04:07 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/exp2f/lib/main.js
> +		return float64ToFloat32( 0.0 );
@aayush0325 After L110, you'll need to add a conditional statement to return `1.0` if x is `0.0`. You might want to refer to the single-precision implementation (`exp2f`) from cephes, as it is a bit different from porting `exp2` directly to single-precision.

2025-04-02 23:41 UTC, kgryte commented
@aayush0325 You still interested in pushing this PR forward?

2025-04-02 23:55 UTC, aayush0325 commented
/stdlib merge

2025-04-03 00:22 UTC, aayush0325 commented on lib/node_modules/@stdlib/math/base/special/exp2f/lib/main.js
> +*     | IEEE       | -1022,+1024 | 30000    | 1.8e-16 | 5.4e-17 |
https://www.netlib.org/cephes/singldoc.html#exp2 i hope this is what you're looking for!


![image](https://github.com/user-attachments/assets/3a3de061-eb83-45d0-b4df-4a222cfe1f04)

2025-04-03 00:29 UTC, aayush0325 commented on lib/node_modules/@stdlib/math/base/special/exp2f/lib/main.js
> +		return float64ToFloat32( 0.0 );
https://github.com/jeremybarnes/cephes/blob/master/single/exp2f.c


using this as a reference here
![image](https://github.com/user-attachments/assets/4f3da97c-f103-4646-a595-776b195b3667)

2025-04-03 01:07 UTC, aayush0325 commented
good morning @gunjjoshi! sorry for the delay, I've linked to all the references for your ease, kindly let me know if i have to make any other changes

2025-08-12 07:43 UTC, kgryte commented
@anandkaranubc Would you mind taking over this PR?

2025-08-26 07:50 UTC, anandkaranubc commented
/stdlib merge

2025-08-26 07:57 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/exp2f/lib/main.js
> +// TODO: replace with TOMS (Openlibm) algo (updating license header and long comment)
@kgryte Does this comment (originally present in `exp2`) mean following https://github.com/freebsd/freebsd-src/blob/main/lib/msun/src/s_exp2f.c implementation instead?

2025-08-26 09:43 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/exp2f/lib/main.js
> +// TODO: replace with TOMS (Openlibm) algo (updating license header and long comment)
Yes, I believe so. The original implementation looks to be based on Cephes, and, generally, we have preferred to use libm over Cephes given that libm is more actively maintained.

2026-08-10 07:29 UTC, anandkaranubc commented
/stdlib help

2026-08-10 07:29 UTC, anandkaranubc commented
/stdlib update-copyright-years

2026-08-15 03:08 UTC, anandkaranubc approved these changes, later dismissed
I think we can merge this now. Maybe if I can get a verification pass on if the License headers and everything around that is correct, that'd be great.

cc: @kgryte

2026-08-15 03:09 UTC, anandkaranubc commented
Also once this is merged, I will also migrate the `exp2` implementation wrt to FreeBSD.

2026-08-15 03:41 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/exp2f/package.json
> +    "lib": "./lib",
```suggestion
    "lib": "./lib",
    "scripts": "./scripts",
```

2026-08-15 03:52 UTC, kgryte approved these changes
LGTM

2026-08-15 04:08 UTC, merged