feat: add `math/base/special/nonfibonaccif`
stdlib-js/stdlib pull request #3391
Opened 2024-12-10 06:36 UTC by aayush0325

Resolves #649

## Description

> What is the purpose of this pull request?

This pull request:

-   adds C implementation for `math/base/special/nonfibonaccif` with relevant tests, docs, benchmarks and examples.

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #649

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-12-10 06:36 UTC, aayush0325 commented
/stdlib update-copyright-years

2024-12-24 19:15 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/nonfibonaccif/README.md
> +        printf( "x: %i => result: %lf", i , result );
```suggestion
        printf( "x: %i => result: %f", i , result );
```

2024-12-24 19:16 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/nonfibonaccif/benchmark/c/native/Makefile
> +.PHONY: clean
```suggestion
.PHONY: clean

```

2024-12-24 19:18 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/nonfibonaccif/benchmark/c/native/benchmark.c
> +static double rand_float( void ) {
```suggestion
static float rand_float( void ) {
```

2024-12-24 19:19 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/nonfibonaccif/benchmark/c/native/benchmark.c
> +	int x[ 100 ];
```suggestion
	double elapsed;
	int x[ 100 ];
	double t;
	float y;
```

Let's arrange these variables in decreasing order of their lengths.

2024-12-24 19:21 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/nonfibonaccif/docs/repl.txt
> +    single-precision floating-point format.
```suggestion
    Computes the nth non-Fibonacci number in single-precision floating-point
    format.
```

2024-12-24 19:23 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/nonfibonaccif/examples/c/example.c
> +		double result = stdlib_base_nonfibonaccif( i );
```suggestion
		float result = stdlib_base_nonfibonaccif( i );
```

2024-12-24 19:39 UTC, gunjjoshi requested changes

2024-12-24 19:39 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/nonfibonaccif/lib/main.js
> +* Computes the nth non-Fibonacci number.
```suggestion
* Computes the nth non-Fibonacci number in single-precision floating-point format.
```

2024-12-24 19:39 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/nonfibonaccif/lib/native.js
> +* Computes the nth non-Fibonacci number.
```suggestion
* Computes the nth non-Fibonacci number in single-precision floating-point format.
```

2024-12-24 19:39 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/nonfibonaccif/src/Makefile
> +.PHONY: clean
```suggestion
.PHONY: clean

```

2024-12-24 19:39 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/nonfibonaccif/src/main.c
> +#include "stdlib/math/base/special/lnf.h"
```suggestion
#include "stdlib/math/base/special/nonfibonaccif.h"
#include "stdlib/constants/float32/nan.h"
#include "stdlib/constants/float32/phi.h"
#include "stdlib/constants/float32/pinf.h"
#include "stdlib/math/base/assert/is_integerf.h"
#include "stdlib/math/base/assert/is_nanf.h"
#include "stdlib/math/base/special/floorf.h"
#include "stdlib/math/base/special/lnf.h"
#include <stdint.h>
```

2024-12-24 19:39 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/nonfibonaccif/src/main.c
> +#define LN_PHI 0.48121182506
@aayush0325 Can you please declare these two as constants, rather than using `#define`? That would match with what we have in other packages.

2024-12-24 19:39 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/nonfibonaccif/src/main.c
> +* @return	  output value
Mix of tabs and spaces.

2024-12-24 19:39 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/nonfibonaccif/src/main.c
> +* float y = stdlib_base_nonfibonaccif( 3.14 );
```suggestion
* float y = stdlib_base_nonfibonaccif( 3.14f );
```

2024-12-24 19:39 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/nonfibonaccif/src/main.c
> +	b = stdlib_base_lnf( (SQRT5 * ( mut_n + a ) ) - 5.0f + ( 3.0f / mut_n ) ) / LN_PHI;
```suggestion
	b = stdlib_base_lnf( ( SQRT5 * ( mut_n + a ) ) - 5.0f + ( 3.0f / mut_n ) ) / LN_PHI;
```

2024-12-24 19:39 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/nonfibonaccif/test/test.js
@aayush0325 Can you please replace all the instances of `returns NaN` by `returns expected value` in this file?

2024-12-24 19:39 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/nonfibonaccif/test/test.native.js
Same comment for this file too.

2024-12-24 20:03 UTC, aayush0325 commented
pushed the requested changes @gunjjoshi!

2024-12-25 04:04 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/nonfibonaccif/src/main.c
> +const float SQRT5 = 2.23606797749979;
```suggestion
static const float SQRT5 = 2.23606797749979f;
```

2024-12-25 04:04 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/nonfibonaccif/src/main.c
> +const float LN_PHI = 0.48121182506;
```suggestion
static const float LN_PHI = 0.48121182506f;
```

2024-12-25 04:04 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/nonfibonaccif/test/test.js
> +		t.strictEqual( v, expected[ i-1 ], 'returns the '+i+'th non-Fibonacci number' );
```suggestion
		t.strictEqual( v, expected[ i - 1 ], 'returns the '+i+'th non-Fibonacci number' );
```

2024-12-25 04:04 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/nonfibonaccif/test/test.native.js
> +		t.strictEqual( v, expected[ i-1 ], 'returns the '+i+'th non-Fibonacci number' );
```suggestion
		t.strictEqual( v, expected[ i - 1 ], 'returns the '+i+'th non-Fibonacci number' );
```

2024-12-25 04:14 UTC, gunjjoshi approved these changes

2024-12-25 09:59 UTC, kgryte approved these changes
This now LGTM. Thanks, @gunjjoshi, for doing an initial review. @aayush0325 You'll want to review the various changes we needed to make and update your other `math/base/special/*` PRs accordingly and where applicable.

2024-12-25 10:06 UTC, merged