feat: add C implementation for `@stdlib/stats/base/dists/betaprime/stdev`
stdlib-js/stdlib pull request #3461
Opened 2024-12-11 20:16 UTC by aayush0325

Resolves #3446

## Description

> What is the purpose of this pull request?

This pull request:

-   adds C implementation for `@stdlib/stats/base/dists/betaprime/stdev` along with relevant tests, docs, examples and benchmarks.

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #3446

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-12-11 20:16 UTC, aayush0325 commented
/stdlib update-copyright-years

2024-12-12 03:38 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/betaprime/stdev/README.md
> +-   **alpha**: `[in] double` first shape parameter
@aayush0325 Please see https://github.com/stdlib-js/stdlib/pull/3354. Descriptions should end with periods.

2024-12-12 03:38 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/betaprime/stdev/README.md
> +        alpha = ( (double)rand() / (double)RAND_MAX ) * 20.0;
See https://github.com/stdlib-js/stdlib/pull/3354 for random value generation.

2024-12-12 03:39 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/betaprime/stdev/benchmark/benchmark.native.js
> +		alpha = ( randu() * 10.0 ) + EPS;
See https://github.com/stdlib-js/stdlib/pull/3354 for value generation.

2024-12-12 03:39 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/betaprime/stdev/benchmark/c/benchmark.c
> +		alpha = 20.0 * rand_double();
See https://github.com/stdlib-js/stdlib/pull/3354 for random value generation.

2024-12-12 03:40 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/betaprime/stdev/examples/c/example.c
> +		alpha = ( (double)rand() / (double)RAND_MAX ) * 20.0;
See https://github.com/stdlib-js/stdlib/pull/3354 for an example of random value generation.

2024-12-12 03:40 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/betaprime/stdev/lib/native.js
> +* @param {PositiveNumber} alpha - first shape parameter
Missing `@private`

2024-12-12 03:41 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/betaprime/stdev/src/main.c
> +* Returns the standard deviation of an beta prime distribution.
```suggestion
* Returns the standard deviation of a beta prime distribution.
```

2024-12-12 03:41 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/betaprime/stdev/src/main.c
> +* @return     stdandard deviation
Description is not aligned.

2024-12-12 03:42 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/betaprime/stdev/benchmark/benchmark.native.js
> +		alpha = ( randu() * 10.0 ) + EPS;
You should make similar changes to the other JS benchmark file.

2024-12-12 03:44 UTC, kgryte requested changes
Thanks for working on this, @aayush0325. Spot checking your other PRs, it looks like you need to make similar changes across all of them. Please see https://github.com/stdlib-js/stdlib/pull/3354 for an idea of what we are looking for.

2024-12-12 14:54 UTC, aayush0325 commented
good evening @kgryte, ive pushed the requested changes in this and all other PRs. thanks for your time!

2024-12-13 13:57 UTC, Planeshifter approved these changes
Thank you, @aayush0325! Let's get this one in.

2024-12-13 13:57 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/betaprime/stdev/README.md
> +}
```suggestion

static double random_uniform( const double min, const double max ) {
    double v = (double)rand() / ( (double)RAND_MAX + 1.0 );
    return min + ( v * ( max - min ) );
}

int main( void ) {
    double alpha;
    double beta;
    double y;
    int i;

    for ( i = 0; i < 25; i++ ) {
        alpha = random_uniform( 0, 20 );
        beta = random_uniform( 0, 20 ) + 2.0;
        y = stdlib_base_dists_betaprime_stdev( alpha, beta );
        printf( "α: %lf, β: %lf, SD(X;α,β): %lf\n", alpha, beta, y );
    }
}
```

2024-12-13 13:57 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/betaprime/stdev/README.md
> +Returns the standard deviation of a betaprime distribution.
```suggestion
Returns the standard deviation of a beta prime distribution.
```

2024-12-13 14:05 UTC, merged