feat: add `stats/base/dists/planck`
stdlib-js/stdlib pull request #3896
Opened 2024-12-13 19:23 UTC by Jaysukh-409

## Description

> What is the purpose of this pull request?

This pull request:

-   Adds the `Planck` descrete exponential random variable.

-   Task List:
- [ ] cdf
- [ ] ctor
- [ ] docs/dtypes
- [ ] entropy
- [ ] examples
- [ ] kurtosis
- [ ] lib
- [ ] logcdf
- [ ] logpmf
- [ ] mean
- [ ] median
- [ ] mgf
- [ ] mode
- [ ] pmf
- [ ] quantile
- [ ] skewness
- [ ] stdev
- [ ] test
- [ ] variance

## Related Issues

> Does this pull request have any related issues?

This pull request:

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-12-13 19:27 UTC, Jaysukh-409 commented
I searched for the `Planck Distribution` in the Julia, but I wasn't able to find much. And due to that currently test seems to be incomplete. 
Should we use another language for the same task ? Like Python using SciPy to generate tests to check accuracy.

2024-12-13 20:06 UTC, Planeshifter commented
@Jaysukh-409 Yes, SciPy is a good reference and we should test against it when the distribution is not available in R or Julia.

2024-12-15 15:11 UTC, Jaysukh-409 commented
@Planeshifter I tried to test against the scipy but some of my tests are failing. Is there anything which I missed in implementation?

2024-12-16 04:32 UTC, Jaysukh-409 commented
@kgryte @Planeshifter PR is ready for review.

2024-12-18 10:01 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/planck/pmf/README.md
> +The [probability mass function][pmf] (PMF) for a planck random variable is defined as
As `Planck` is a proper noun, it should be capitalized in all descriptions here and elsewhere.

2024-12-18 10:02 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/planck/pmf/README.md
> +The [probability mass function][pmf] (PMF) for a planck random variable is defined as
s/planck/Planck/

2024-12-18 10:03 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/planck/pmf/README.md
> +var round = require( '@stdlib/math/base/special/round' );
Let's go ahead and generate an array of random numbers using `@stdlib/random/array/discrete-uniform`. This ensures consistency with some of the recent work we've been doing when updating various dists packages.

2024-12-18 10:04 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/planck/pmf/benchmark/benchmark.js
> +		x = round( randu()*40.0 );
Same thing. Pre-generate an array of random values, rather than individually within a loop.

2024-12-18 10:04 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/planck/pmf/benchmark/benchmark.js
> +		x = randu() * 40.0;
Same thing.

2024-12-18 10:05 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/planck/pmf/examples/index.js
> +var randu = require( '@stdlib/random/base/randu' );
Same comment as README.

2024-12-18 10:07 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/planck/pmf/test/fixtures/python/REQUIRE
> +python 3.10.12
Missing trailing newline.

2024-12-18 10:10 UTC, kgryte requested changes
Thanks for working on this @Jaysukh-409. Left a few minor niggles, but overall looking good.

2024-12-18 14:25 UTC, Jaysukh-409 commented
@kgryte This PR is now ready to merge.

2024-12-19 01:07 UTC, kgryte commented
/stdlib merge

2024-12-19 01:10 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/planck/pmf/README.md
> +var randu = require( '@stdlib/random/base/randu' );
@Jaysukh-409 Use `random/array/uniform` for generating `lambda`, as well. Meaning, move RV generation out of the loop.

2024-12-19 01:11 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/planck/pmf/benchmark/benchmark.js
> +	x = discreteUniform( b.iterations, 0, 40 );
Don't use `b.iterations`. Just `100`. `b.iterations` could be enormous and you'll cause the process to run out of memory.

2024-12-19 01:11 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/planck/pmf/benchmark/benchmark.js
> +	x = discreteUniform( b.iterations, 0, 40 );
Same comment.

2024-12-19 01:12 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/planck/pmf/benchmark/benchmark.js
> +		lambda = ( randu()*10.0 );
You need to move this out of the loop. Then use modulo arithmetic below (e.g., `i % x.length`, etc). As I mentioned elsewhere, see other recent changes to base stats dists packages where we've already been doing this work.

2024-12-19 01:12 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/planck/pmf/benchmark/benchmark.js
> +	mypmf = pmf.factory( lambda );
Just provide `0.3` directly. No need to have a separate `lambda` variable.

2024-12-19 01:14 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/planck/pmf/examples/index.js
> +x = discreteUniform( 10, 0, 5 );
Same comments as README.

2024-12-19 01:14 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/planck/pmf/lib/factory.js
> +* @param {number} lambda - shape parameter
```suggestion
* @param {NonNegativeNumber} lambda - shape parameter
```

Yes, we handle `lambda < 0.0`, but the intent is that users should provide a nonnegative number.

2024-12-19 01:15 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/planck/pmf/lib/main.js
> +* @param {number} lambda - shape parameter
```suggestion
* @param {NonNegativeNumber} lambda - shape parameter
```

2024-12-19 01:16 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/planck/pmf/test/fixtures/python/REQUIRE
> +numpy 2.2.0
What is this file? This should be removed. `REQUIRE` is a Julia thing, not Python. When in doubt, consult our snippets: https://github.com/stdlib-js/stdlib/tree/develop/tools/snippets/test/fixtures

2024-12-19 01:16 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/planck/pmf/test/fixtures/python/runner.py
> +# !/usr/bin/env python
This file does not match our snippet runner: https://github.com/stdlib-js/stdlib/blob/develop/tools/snippets/test/fixtures/python/runner.py.

2024-12-19 01:18 UTC, kgryte requested changes
Left another round of comments.

2024-12-19 01:20 UTC, kgryte commented
/stdlib merge

2024-12-26 09:52 UTC, kgryte approved these changes
LGTM. @Jaysukh-409 I made a few small changes. Would be worth checking whether they are applicable to your other PRs for `cdf`, `logcdf`, etc. Cheers!

2024-12-26 09:54 UTC, merged