feat: Add C implementation for @stdlib/stats/base/dists/binomial/variance
stdlib-js/stdlib pull request #3929
Opened 2024-12-15 16:13 UTC by 0PrashantYadav0

Resolves #3477

## Description

> What is the purpose of this pull request?

This pull request:

-   Adds C implementation for binomial Variance
-   Includes benchmarks for the C implementation.
-   Provides examples demonstrating the usage of the binomial Variance in C.

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #3477

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [X] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-12-15 16:56 UTC, 0PrashantYadav0 commented
/stdlib update-copyright-years

2024-12-16 16:03 UTC, 0PrashantYadav0 commented
/stdlib update-copyright-years

2024-12-20 02:33 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/binomial/variance/benchmark/benchmark.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2018 The Stdlib Authors.
```

2024-12-20 02:34 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/binomial/variance/benchmark/benchmark.js
> +var variance = require( '@stdlib/stats/base/dists/binomial/median/lib' );
```suggestion
var pkg = require( './../package.json' ).name;
var variance = require( './../lib' );
```

2024-12-20 02:34 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/binomial/variance/benchmark/benchmark.native.js
> +var pkg = require( '@stdlib/stats/base/dists/binomial/median/package.json' ).name;
```suggestion
var pkg = require( './../package.json' ).name;
```

2024-12-20 02:35 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/binomial/variance/src/Makefile
> +.PHONY: clean
```suggestion
.PHONY: clean

```

2024-12-20 02:35 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/binomial/variance/lib/native.js
> +* Returns the variance of a beta prime distribution.
```suggestion
* Returns the variance of a binomial distribution.
```

2024-12-20 02:36 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/binomial/variance/examples/c/Makefile
> +.PHONY: clean
```suggestion
.PHONY: clean

```

2024-12-20 02:37 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/binomial/variance/lib/native.js
> +* var v = variance( 1.0, 3.0 );
Examples here need to be updates to be for binomial distribution

2024-12-20 02:37 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/binomial/variance/src/main.c
> +* @param n	number of trials
Horizontal alignment should use spaces here.

2024-12-20 02:37 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/binomial/variance/manifest.json
> +}
```suggestion
}

```

2024-12-20 02:38 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/binomial/variance/benchmark/c/benchmark.c
> +* @param min	minimum value (inclusive)
Horizontal alignment should use spaces here.

2024-12-20 02:39 UTC, Planeshifter requested changes
This PR has a bunch of problems that will have to be addressed before it can be merged.

2024-12-21 16:39 UTC, 0PrashantYadav0 commented
@Planeshifter Make all the changes. Please review all the changes.

2025-01-06 14:34 UTC, 0PrashantYadav0 commented
@Planeshifter Please review this, i have implemented ID_D as mention earlier.

2025-01-08 01:40 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/binomial/variance/src/main.c
> +/**
```suggestion
#include <stdint.h>

/**
```

2025-01-08 01:42 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/binomial/variance/manifest.json
> +        "@stdlib/math/base/special/ceil"
```suggestion
        "@stdlib/math/base/assert/is-nonnegative-integer"
```

2025-01-08 01:44 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/binomial/variance/src/main.c
> +* // returns 0.9
```suggestion
* // returns 9.0
```

2025-01-08 01:44 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/binomial/variance/README.md
> +// returns 0.9
```suggestion
double out = stdlib_base_dists_binomial_variance( 100, 0.1 );
// returns 9.0
```

2025-01-08 01:45 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/binomial/variance/src/main.c
> +* // returns 0.9
```suggestion
* double y = stdlib_base_dists_binomial_variance( 100, 0.1 );
* // returns 9.0
```

2025-01-08 01:45 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/binomial/variance/README.md
> +// returns 0.9
```suggestion
// returns 9.0
```

2025-01-08 01:49 UTC, Planeshifter approved these changes
Let's land it, thanks!

2025-01-08 03:21 UTC, merged