feat: add C implementation for `stats/base/dists/uniform/mean`
stdlib-js/stdlib pull request #3964
Opened 2024-12-16 15:59 UTC by 0PrashantYadav0

Resolves #3830 

## Description

> What is the purpose of this pull request?

This pull request:

-   adds C implementation for @stdlib/stats/base/dists/uniform/mean along with relevant tests, benchmarks and examples

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #3830

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-12-20 03:54 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/uniform/mean/README.md
> +        printf( "a: %lf, b: %lf, Mean(X;a,b): %lf\n", a, b, y );
```suggestion
        printf( "a: %lf, b: %lf, E(X;a,b): %lf\n", a, b, y );
```

2024-12-20 03:54 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/uniform/mean/benchmark/benchmark.js
> +* Copyright (c) 2024 The Stdlib Authors.
```suggestion
* Copyright (c) 2018 The Stdlib Authors.
```

2024-12-20 03:55 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/uniform/mean/README.md
> +Copyright (c) 2024 The Stdlib Authors.
```suggestion
Copyright (c) 2018 The Stdlib Authors.
```

2024-12-20 03:58 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/uniform/mean/README.md
> +
You mind adding

```
static double random_uniform( const double min, const double max ) {
    double v = (double)rand() / ( (double)RAND_MAX + 1.0 );
    return min + ( v*(max-min) );
}
```

here and using it to draw the random numbers here, please? Applies to the example and benchmark C files, too.

2024-12-20 03:59 UTC, Planeshifter requested changes
Thanks for the PR!

Left a bunch of comments we should address.

I believe the slash commands didn't work for you because any workflows for new contributors have to initially be approved. I will look into us making this clearer...

2024-12-21 16:37 UTC, 0PrashantYadav0 commented
@Planeshifter Make all the changes. Please review all the changes.

2024-12-25 21:27 UTC, Planeshifter reviewed
Thanks for the PR!

Made a bunch of fixes, but should be ready for landing soon.

2024-12-25 21:27 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/uniform/mean/src/main.c
> +* @param b    upper bound
```suggestion
* @param a    minimum support
* @param b    maximum support
```

2024-12-25 21:27 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/uniform/mean/include/stdlib/stats/base/dists/uniform/mean.h
> +* Returns the mean of a uniform distribution with lower bound `a` and upper bound `b`.
```suggestion
* Returns the mean of a uniform distribution with minimum support `a` and maximum support `b`.
```

2024-12-25 21:27 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/uniform/mean/benchmark/c/benchmark.c
> +	int i;
```suggestion
	double a[ 100 ];
	double b[ 100 ];
	double elapsed;
	double y;
	double t;
	int i;
```

2024-12-25 21:27 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/uniform/mean/README.md
> +Returns the [mean][mean] of a [uniform][uniform-distribution] distribution with minimum value \( a \) and maximum value \( b \).
```suggestion
Returns the [expected value][expected-value] of a [uniform][uniform-distribution] distribution with parameters `a` (minimum support) and `b` (maximum support).
```

2024-12-25 21:27 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/uniform/mean/README.md
> +-   **b**: `[in] double` maximum value.
```suggestion
-   **a**: `[in] double` minimum support.
-   **b**: `[in] double` maximum support.
```

2024-12-25 21:27 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/uniform/mean/README.md
> +}
```suggestion
static double random_uniform( const double min, const double max ) {
    double v = (double)rand() / ( (double)RAND_MAX + 1.0 );
    return min + ( v*(max-min) );
}

int main( void ) {
    double a;
    double b;
    double y;
    int i;

    for ( i = 0; i < 25; i++ ) {
        a = random_uniform( 0.0, 10.0 );
        b = random_uniform( a, 20.0 ); // ensure b > a
        y = stdlib_base_dists_uniform_mean( a, b );
        printf( "a: %lf, b: %lf, E(X;a,b): %lf\n", a, b, y );
    }
}
```

2024-12-25 21:27 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/uniform/mean/examples/c/example.c
> +		printf( "a: %lf , b: %lf , Mean: %lf\n", a, b, y );
```suggestion
		printf( "a: %lf , b: %lf , E(X;a,b): %lf\n", a, b, y );
```

2024-12-25 21:27 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/uniform/mean/lib/native.js
> +* @param {number} b - upper bound
```suggestion
* @param {number} a - minimum support
* @param {number} b - maximum support
```

2024-12-25 21:29 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/uniform/mean/README.md
> +
```suggestion
```

2024-12-25 21:30 UTC, Planeshifter approved these changes

2024-12-25 21:36 UTC, merged