feat: add C implementation for `stats/base/dists/uniform/median`
stdlib-js/stdlib pull request #3970
Opened 2024-12-16 18:00 UTC by 0PrashantYadav0

Resolves #3831

## Description

> What is the purpose of this pull request?

This pull request:

-   adds C implementation for stats/base/dists/uniform/median along with relevant tests, docs, examples and benchmarks.

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #3831

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-12-17 02:18 UTC, Planeshifter requested changes
Thanks for your efforts!

The PR currently has a bunch of errors and does not compile. Please test the commands in the linked issue to confirm things work as expected. You also want to make sure you have EditorConfig setup.

2024-12-17 02:18 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/uniform/median/README.md
These changes should be reverted.

2024-12-17 02:18 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/uniform/median/include/stdlib/stats/base/dists/uniform/median.h
> +* Returns the median of a Uniform distribution with lower bound `a` and upper bound `b`.
```suggestion
* Returns the median of a uniform distribution with lower bound `a` and upper bound `b`.
```

2024-12-17 02:18 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/uniform/median/lib/native.js
> +* Returns the median of a Uniform distribution.
```suggestion
* Returns the median of a uniform distribution.
```

2024-12-17 02:18 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/uniform/median/examples/c/Makefile
> +c_targets := benchmark.out
The Makefiles in `benchmark/c`, `exampkes/c`, and `src` all have different targets. Please check the reference PR.

2024-12-17 02:18 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/uniform/median/manifest.json
> +    "options": {
Should have two-space indentation.

2024-12-17 02:18 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/uniform/median/src/main.c
> +* Returns the median of a Uniform distribution.
```suggestion
* Returns the median of a uniform distribution.
```

2024-12-17 02:18 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/uniform/median/src/main.c
> +		return 0.0 / 0.0; // Return NaN for invalid inputs
```suggestion
		return 0.0 / 0.0; // NaN
```

2024-12-17 02:18 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/uniform/median/test/test.native.js
> +tape( 'the function returns the median of a Uniform distribution', opts, function test( t ) {
```suggestion
tape( 'the function returns the median of a uniform distribution', opts, function test( t ) {
```

2024-12-17 02:18 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/uniform/median/benchmark/benchmark.js
> +* Copyright (c) 2024 The Stdlib Authors.
We don't update copyright years when changing existing files.

```suggestion
* Copyright (c) 2018 The Stdlib Authors.
```

2024-12-21 16:37 UTC, 0PrashantYadav0 commented
@Planeshifter Make all the changes. Please review all the changes.

2024-12-25 21:36 UTC, Planeshifter commented
/stdlib lint-autofix

2024-12-25 21:47 UTC, Planeshifter reviewed
Thanks! 

Made a few edits and fixes. Specifically, we want to be consistent with existing terminology (e.g., use "minimum support" and "maximum support" for parameters of continuous uniform distribution) and use the custom `random_uniform` to draw randon numbers in the example and benchmark code.

2024-12-25 21:47 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/uniform/median/README.md
> +Returns the [median][median] of a [uniform][uniform-distribution] distribution with minimum value \( a \) and maximum value \( b \).
```suggestion
Returns the [median][median] of a [uniform][uniform-distribution] distribution with parameters `a` (minimum support) and `b` (maximum support).
```

2024-12-25 21:47 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/uniform/median/README.md
> +-   **b**: `[in] double` maximum value.
```suggestion
-   **a**: `[in] double` minimum support.
-   **b**: `[in] double` maximum support.
```

2024-12-25 21:47 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/uniform/median/src/main.c
> +* @param b    upper bound
```suggestion
* @param a    minimum support
* @param b    maximum support
```

2024-12-25 21:47 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/uniform/median/lib/native.js
> +* @param {number} b - upper bound
```suggestion
* @param {number} a - minimum support
* @param {number} b - maximum support
```

2024-12-25 21:47 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/uniform/median/include/stdlib/stats/base/dists/uniform/median.h
> +* Returns the median of a uniform distribution with lower bound `a` and upper bound `b`.
```suggestion
* Returns the median of a uniform distribution.
```

2024-12-25 21:47 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/uniform/median/examples/c/example.c
> +		printf( "a: %lf , b: %lf , Median: %lf\n", a, b, y );
```suggestion
		printf( "a: %lf , b: %lf , Median(X;a,b): %lf\n", a, b, y );
```

2024-12-25 21:47 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/uniform/median/README.md
> +}
```suggestion
static double random_uniform( const double min, const double max ) {
    double v = (double)rand() / ( (double)RAND_MAX + 1.0 );
    return min + ( v*(max-min) );
}

int main( void ) {
    double a;
    double b;
    double y;
    int i;

    for ( i = 0; i < 25; i++ ) {
        a = random_uniform( 0.0, 10.0 );
        b = random_uniform( a, 20.0 ); // ensure b > a
        y = stdlib_base_dists_uniform_median( a, b );
        printf( "a: %lf, b: %lf, Median(X;a,b): %lf\n", a, b, y );
    }
}
```

2024-12-25 21:47 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/uniform/median/benchmark/c/benchmark.c
> +}
```suggestion

/**
* Generates a random number on the interval [min,max).
*
* @param min    minimum value (inclusive)
* @param max    maximum value (exclusive)
* @return       random number
*/
static double random_uniform( const double min, const double max ) {
	double v = (double)rand() / ( (double)RAND_MAX + 1.0 );
	return min + ( v*(max-min) );
}

/**
* Runs a benchmark.
*
* @return elapsed time in seconds
*/
static double benchmark( void ) {
	double elapsed;
	double a, b;
	double y;
	double t;
	int i;

	t = tic();
	for ( i = 0; i < ITERATIONS; i++ ) {
		a = random_uniform( 0.0, 100.0 );
		b = random_uniform( a, 200.0 );
		y = stdlib_base_dists_uniform_median( a, b );
		if ( y != y ) {
			printf( "should not return NaN\n" );
			break;
		}
	}
	elapsed = tic() - t;
	if ( y != y ) {
		printf( "should not return NaN\n" );
	}
	return elapsed;
}
```

2024-12-25 21:47 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/uniform/median/examples/c/example.c
> +		b = a + ( (double)rand() / ( (double)RAND_MAX + 1.0 ) * 50.0 );
```suggestion
static double random_uniform( const double min, const double max ) {
	double v = (double)rand() / ( (double)RAND_MAX + 1.0 );
	return min + ( v*(max-min) );
}

int main( void ) {
	double a;
	double b;
	double y;
	int i;

	for ( i = 0; i < 25; i++ ) {
		a = random_uniform( 0.0, 10.0 );
		b = random_uniform( a, 20.0 );
```

2024-12-25 21:50 UTC, Planeshifter approved these changes

2024-12-25 21:56 UTC, merged