feat: add C implementation for `stats/base/dists/bernoulli/pmf`
stdlib-js/stdlib pull request #3974
Opened 2024-12-16 20:25 UTC by Neerajpathak07

Resolves #3418 
## Description

> What is the purpose of this pull request?

This pull request:

-   adds C implementation for `stats/base/dists/bernoulli/pmf`

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #3418  

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-  [x] Read, understood, and followed the [contributing guidelines](https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md)

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-12-16 20:29 UTC, Neerajpathak07 commented
/stdlib update-copyright-years

2025-01-16 14:54 UTC, Neerajpathak07 commented
/stdlib update-copyright-years

2025-02-11 01:50 UTC, Planeshifter requested changes
Left a bunch of comments that should be addressed before this PR can land.

2025-02-11 01:50 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/bernoulli/pmf/README.md
> +#include "stdlib/stats/base/dists/bernoulli/cdf.h"
```suggestion
#include "stdlib/stats/base/dists/bernoulli/pmf.h"
```

2025-02-11 01:50 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/bernoulli/pmf/README.md
> +Returns a function for evaluating the [probability mass function][pmf] (PMF) of a [Bernoulli][bernoulli-distribution] distribution with success probability `0 <= p <= 1`.
This description is incorrect.

2025-02-11 01:50 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/bernoulli/pmf/benchmark/benchmark.js
> +		x[ i ] = round( uniform( 0.0, 3.0 ) );
This change should be reverted.

2025-02-11 01:50 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/bernoulli/pmf/benchmark/benchmark.js
> +		x[ i ] = round( uniform( 0.0, 3.0 ) );
Should be reverted.

2025-02-11 01:50 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/bernoulli/pmf/benchmark/benchmark.native.js
> +		x[ i ] = round( uniform( 0.0, 3.0 ) );
Can use `discreteUniform` here.

2025-02-11 01:50 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/bernoulli/pmf/docs/repl.txt
> +    with success probability `0 <= p <= 1`.
This change is not needed. Below we already specify the range of valid values for `p`.

2025-02-11 01:50 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/bernoulli/pmf/docs/types/index.d.ts
> +	* Evaluates the probability mass function (PMF) for a Bernoulli distribution with success probability `0 <= p <= 1`.
Should be reverted.

2025-02-11 01:50 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/bernoulli/pmf/include/stdlib/stats/base/dists/bernoulli/pmf.h
> +* Evaluates the probability mass function (PMF) for a Bernoulli distribution with success probability `0 <= p <= 1`.
```suggestion
* Evaluates the probability mass function (PMF) for a Bernoulli distribution with success probability `p` at value `x`.
```

2025-02-11 01:50 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/bernoulli/pmf/lib/main.js
> +* Evaluates the moment-generating function (MGF) for a Bernoulli distribution with success probability `p` at a value `t`.
This is wrong and needs to be reverted.

2025-02-11 01:50 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/bernoulli/pmf/lib/native.js
> +* Evaluates the moment-generating function (MGF) for a Bernoulli distribution with success probability `p` at a value `t`.
Incorrect description.

2025-02-11 01:50 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/bernoulli/pmf/src/main.c
> +*/
This example has to be incorrect, as the PMF can only have non-zero values for `0` and `1`.

2025-02-11 01:50 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/bernoulli/pmf/src/main.c
> +* Evaluates the probability mass function (PMF) for a Bernoulli distribution with success probability `0 <= p <= 1`.
```suggestion
* Evaluates the probability mass function (PMF) for a Bernoulli distribution with success probability `p` at value `x`.
```

2025-02-11 01:50 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/bernoulli/pmf/src/main.c
> +	return 0.0 ;
```suggestion
	return 0.0;
```

2025-02-11 01:50 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/bernoulli/pmf/test/test.native.js
> +		}
Should check whether the non-exact check is necessary. There are no calculations that would suggest it's needed. If also present in `test.js`, would be good to remove from that as well.

2025-02-19 13:39 UTC, Neerajpathak07 commented
@Planeshifter Updated the changes here and elsewhere!!

2025-04-05 00:06 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/bernoulli/pmf/README.md
> +Returns a function for evaluating the [probability mass function][pmf] (PMF) of a [Bernoulli][bernoulli-distribution] distribution with success probability `0 <= p <= 1`.
```suggestion
Evaluates the [probability mass function][pmf] (PMF) of a [Bernoulli][bernoulli-distribution] distribution with success probability `0 <= p <= 1`.
```

2025-04-05 00:07 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/bernoulli/pmf/benchmark/benchmark.js
> +		x[ i ] = discreteUniform( 0.0, 3.0 );
```suggestion
		x[ i ] = discreteUniform( 0, 3 );
```

2025-04-05 00:07 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/bernoulli/pmf/benchmark/benchmark.js
> +		x[ i ] = discreteUniform( 0.0, 3.0 );
```suggestion
		x[ i ] = discreteUniform( 0, 3 );
```

2025-04-05 00:08 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/bernoulli/pmf/benchmark/benchmark.native.js
> +		x[ i ] = discreteUniform( 0.0, 3.0 );
```suggestion
		x[ i ] = discreteUniform( 0, 3 );
```

2025-04-05 00:09 UTC, Planeshifter approved these changes
Let's get this PR finally in. Thanks, @Neerajpathak07!

2025-04-05 00:16 UTC, merged