feat: add c implementation for dist/triangular/median
stdlib-js/stdlib pull request #4004
Opened 2024-12-17 15:44 UTC by sethdivyansh

Resolves #3817

## Description

- adds C implementation for @stdlib/stats/base/dists/triangular/median along with relevant tests, benchmarks and examples

This pull request:

-  progresses: #3817 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-12-18 02:45 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/triangular/median/README.md
> +#### stdlib_base_dists_triangular_median( a, b, c)
```suggestion
#### stdlib_base_dists_triangular_median( a, b, c )
```

2024-12-18 02:47 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/triangular/median/README.md
> +
Please define the below here 

```c
static double random_uniform( const double min, const double max ) {
    double v = (double)rand() / ( (double)RAND_MAX + 1.0 );
    return min + ( v*(max-min) );
}
```

and use it to draw the random values for `a`, `b`, and `c` similar to the changes made in https://github.com/stdlib-js/stdlib/pull/3354/commits/da14b77af9c95ec5185a6aced49030f53d97fdee.

2024-12-18 02:48 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/triangular/median/src/main.c
> +* @param {number} a - minimum support
This is not how we do our C documentation comments. Please consult the reference implementation or other merged PRs.

2024-12-18 02:49 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/triangular/median/lib/native.js
> +* @param {number} a - minimum support
```suggestion
*
* @private
* @param {number} a - minimum support
```

2024-12-18 02:49 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/triangular/median/examples/c/example.c
> +
Same comment as in the `README.md`.

2024-12-18 02:50 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/triangular/median/benchmark/c/benchmark.c
> +		min[ i ] = 10.0*(double)rand() / ( (double)RAND_MAX + 1.0 );
Same comment as in the `README.md`.

2024-12-18 02:50 UTC, Planeshifter requested changes
Thanks for your work!

Left a few comments that will need to be addressed before this PR can be merged; hopefully should be quick to rectify.

2024-12-18 07:27 UTC, sethdivyansh commented
> Thanks for your work!
> 
> Left a few comments that will need to be addressed before this PR can be merged; hopefully should be quick to rectify.

Done with the changes. Please review.

2024-12-20 01:09 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/triangular/median/examples/c/example.c
> +    return min + ( v*(max-min) );
```suggestion
	double v = (double)rand() / ( (double)RAND_MAX + 1.0 );
	return min + ( v*(max-min) );
```

2024-12-20 01:10 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/triangular/median/src/main.c
> +* Returns the median of a Triangular distribution.
```suggestion
* Returns the median of a triangular distribution.
```

2024-12-20 01:12 UTC, Planeshifter approved these changes
Thanks for making the edits! Will merge shortly after CI is all green.

2024-12-20 02:05 UTC, merged