feat: add C implementation for `stats/base/dists/kumaraswamy/median`
stdlib-js/stdlib pull request #4020
Opened 2024-12-18 12:55 UTC by DeshDeepakKant

Resolves #3701 

## Description

> What is the purpose of this pull request?

This pull request:

-  adds C implementation for stats/base/dists/kumaraswamy/median along with relevant tests, docs, examples and benchmarks.

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #3701 
## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines](https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md)

* * *

@stdlib-js/reviewers

2024-12-19 00:06 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/kumaraswamy/median.h
> +/**
This file needs to be removed.

2024-12-19 00:07 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/kumaraswamy/median/README.md
> +Copyright (c) 2014 The Stdlib Authors.
```suggestion
Copyright (c) 2018 The Stdlib Authors.
```

2024-12-19 00:08 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/kumaraswamy/median/README.md
> +```
````suggestion

```c
double stdlib_base_dists_kumaraswamy_median( const double a, const double b );
```
````

2024-12-19 00:08 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/kumaraswamy/median/README.md
> +
We don't want to inline the implementation here.
```suggestion
```

2024-12-19 00:09 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/kumaraswamy/median/src/main.c
> +/**
```suggestion
#include <math.h>

/**
```

2024-12-19 00:10 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/kumaraswamy/median/package.json
> +  "description": "Kumaraswamy distribution median.",
These changes need to be reverted.

2024-12-19 00:10 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/kumaraswamy/median/package.json
> +  "main": "./lib/main.js",
This shouldn't be changed.

2024-12-19 00:11 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/kumaraswamy/median/manifest.json
> +    "options": {
Indentation should be two spaces here.

2024-12-19 00:11 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/kumaraswamy/median/manifest.json
> +
Ensure you have EditorConfig setup. Should have a trailing newline here.

2024-12-19 00:11 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/kumaraswamy/median/lib/native.js
> +* @param {number} a - shape parameter
```suggestion
*
* @private
* @param {number} a - shape parameter
```

2024-12-19 00:12 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/kumaraswamy/median/benchmark/c/benchmark.c
> +		// Ensure parameters are positive and within reasonable ranges
```suggestion
```

2024-12-19 00:13 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/kumaraswamy/median/test/test.native.js
> +tape( 'the function returns the median of a Cauchy distribution', opts, function test( t ) {
```suggestion
tape( 'the function returns the median of a Kumaraswamy distribution', opts, function test( t ) {
```

2024-12-19 00:13 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/kumaraswamy/median/test/fixtures/julia/runner.jl
> +		z[ i ] = var( Geometric( p[ i ] ) );
This is not the correct distribution.

2024-12-19 00:14 UTC, Planeshifter requested changes
Thanks for opening a PR!

Unfortunately, it right now contains a large number of errors that will have to be addressed before it can move forward.

2024-12-19 11:01 UTC, DeshDeepakKant commented
Thanks for the review,

This is my first time contributing to open source,
I will fix it asap.

2024-12-20 00:01 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/kumaraswamy/median/README.md
> +```
````suggestion
```
````

2024-12-20 00:01 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/kumaraswamy/median/README.md
> +
```suggestion
}
```

2024-12-20 00:02 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/kumaraswamy/median/README.md
> +```
````suggestion
}
```
````

2024-12-20 00:02 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/kumaraswamy/median/examples/c/example.c
> +		// Ensure parameters are positive and within reasonable ranges
```suggestion
```

2024-12-20 00:04 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/kumaraswamy/median/examples/c/example.c
> +}
```suggestion
}

```

2024-12-20 00:05 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/kumaraswamy/median/src/main.c
> +#include <math.h>
```suggestion
#include "stdlib/stats/base/dists/kumaraswamy/median.h"
#include "stdlib/math/base/assert/is_nan.h"
#include "stdlib/math/base/special/pow.h"
```

2024-12-20 00:06 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/kumaraswamy/median/src/main.c
> +    return 1.0 - pow( 0.5, 1.0 / b );
```suggestion
    return 1.0 - stdlib_base_pow( 0.5, 1.0 / b );
```

2024-12-20 00:07 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/kumaraswamy/median/manifest.json
> +        "@stdlib/constants/float64/eps"
```suggestion
        "@stdlib/math/base/assert/is-nan",
        "@stdlib/math/base/special/pow",
        "@stdlib/constants/float64/eps"
```

2024-12-20 00:07 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/kumaraswamy/median/manifest.json
> +        "@stdlib/constants/float64/eps"
```suggestion
        "@stdlib/math/base/assert/is-nan",
        "@stdlib/math/base/special/pow",
        "@stdlib/constants/float64/eps"
```

2024-12-20 00:07 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/kumaraswamy/median/manifest.json
> +        "@stdlib/constants/float64/eps"
```suggestion
        "@stdlib/math/base/assert/is-nan",
        "@stdlib/math/base/special/pow",
        "@stdlib/constants/float64/eps"
```

2024-12-20 00:11 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/kumaraswamy/median/test/fixtures/julia/runner.jl
> +# Copyright (c) 2018 The Stdlib Authors.
```suggestion
# Copyright (c) 2024 The Stdlib Authors.
```

2024-12-20 00:16 UTC, Planeshifter commented
@DeshDeepakKant Thanks for all the changes! Did another review and, after a few more edits, I believe your PR should be ready to land now. This is an exciting milestone, as it marks your first contribution to open-source development. Let's go ahead and merge your contribution. 🚀

2024-12-20 00:17 UTC, Planeshifter approved these changes

2024-12-20 01:13 UTC, merged