refactor: update `stats/base/dmax` to follow latest project conventions
stdlib-js/stdlib pull request #4051
Opened 2024-12-19 09:50 UTC by aayush0325

Resolves None.

## Description

> What is the purpose of this pull request?

This pull request:

-   Refactors the native addon of `stats/base/dmax` to follow latest conventions.
-   I browsed through some old PRs ( following #1807 here ) to get an idea of what should be done here. 
-   **So far, the only change made here is migration from C++ to C addons**
-   However for refrence say #1807 has some other changes related to tests, benchmarks and documentation as well. Please let me know if we need to do the same here

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves None. 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-12-19 10:49 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dmax/manifest.json
> +      "task": "examples",
You also need a configuration for benchmarks.

2024-12-19 10:50 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dmax/src/addon.c
> +	napi_value v;
Use `STDLIB_NAPI_CREATE_DOUBLE`.

2024-12-19 10:50 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dmax/src/addon.c
> +	napi_value v;
You should be able to search `blas/ext/base/*` for an example usage.

2024-12-19 10:51 UTC, kgryte requested changes
This is looking good. Just two minor comments.

2024-12-19 10:52 UTC, kgryte commented
/stdlib merge

2024-12-19 10:54 UTC, kgryte commented
Let's hold off on additional changes for future PRs.

2024-12-19 10:56 UTC, aayush0325 commented
Noted, pushing the requested changes soon!

2024-12-19 21:26 UTC, aayush0325 commented
is this good to go @kgryte?

2024-12-21 02:35 UTC, kgryte approved these changes
LGTM. Thanks, @aayush0325!

2024-12-21 02:36 UTC, merged