feat: add C implementation for `stats/base/dists/geometric/quantile`
stdlib-js/stdlib pull request #4094
Opened 2024-12-20 13:54 UTC by 0PrashantYadav0

Resolves #3640

## Description

> What is the purpose of this pull request?

This pull request:

-   adds C implementation for `@stdlib/stats/base/dists/geometric/quantile` along with relevant tests, benchmarks and examples.

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #3640

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2025-01-03 12:20 UTC, 0PrashantYadav0 commented
/stdlib update-copyright-years

2025-02-11 01:56 UTC, Planeshifter requested changes
Looks mostly fine, but there are some mismatches with respect to the parameter names that need to be cleaned up. Thanks!

2025-02-11 01:56 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/geometric/quantile/README.md
> +#### stdlib_base_dists_geometric_quantile( p, p_success )
It would be better to use the same parameter names as we do for the JS implementation.

As-is, this also doesn't match the description in the following line.

2025-02-11 01:56 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/geometric/quantile/benchmark/benchmark.js
> +		p[ i ] = ( randu() * 1.0 );
```suggestion
		p[ i ] = randu();
```

2025-02-11 01:56 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/geometric/quantile/benchmark/benchmark.native.js
> +		p[ i ] = ( randu() * 1.0 );
```suggestion
		p[ i ] = randu();
```

2025-02-11 01:56 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/geometric/quantile/benchmark/c/benchmark.c
> +		p[ i ] = random_uniform( 0.0, 1.0 );
Should create another array `r` and also pre-fill before the benchmark loop.

2025-02-11 01:56 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/geometric/quantile/src/main.c
> +* @param p_success  success probability
Use r and p here to match function signature.

2025-03-06 06:46 UTC, 0PrashantYadav0 commented
@Planeshifter Made all the changes please review and merge.

2025-03-07 03:23 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/geometric/quantile/README.md
> +<!-- /.examples -->
```suggestion
<!-- /.examples -->

</section>

<!-- /.c -->
```

2025-03-07 03:26 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/geometric/quantile/src/main.c
> +		r <= 0.0 ||
Let's match what we have in the JS implementation:

```suggestion
		r < 0.0 ||
```

2025-03-07 03:27 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/geometric/quantile/lib/native.js
> +* @param {Probability} r - input value
```suggestion
*
* @private
* @param {Probability} r - input value
```

2025-03-07 03:28 UTC, Planeshifter approved these changes
Let's get it in. 💪

2025-03-07 03:35 UTC, merged