feat: add `math/base/special/log2f`
stdlib-js/stdlib pull request #4179
Opened 2024-12-23 14:43 UTC by Neerajpathak07

Resolves #649 .

## Description

> What is the purpose of this pull request?

This pull request:

-   adds `math/base/special/log2f`

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #649 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-  [x]  Read, understood, and followed the [contributing guidelines](https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md)

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2025-01-09 13:37 UTC, Neerajpathak07 commented on lib/node_modules/@stdlib/math/base/special/log2f/src/main.c
> +	R = stdlib_base_kernel_log1p( f );
will be need to add implementations for `kernel-log1pf`.

2025-12-12 13:20 UTC, Neerajpathak07 commented
/stdlib update-copyright-years

2025-12-31 06:36 UTC, anandkaranubc requested changes

2025-12-31 06:36 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/log2f/lib/main.js
> +var IVLN2HI = f32( 1.4428710938e+00 ); /* 0x3fb8b000 */
```suggestion
var IVLN2HI = f32( 1.4428710938e+00 );  // 0x3fb8b000
```

2025-12-31 06:36 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/log2f/lib/main.js
> +var IVLN2LO = f32( -1.7605285393e-04 ); // 0x3de705fc, 0x2eefa200
```suggestion
var IVLN2LO = f32( -1.7605285393e-04 ); // 0xb9389ad4
```

2025-12-31 06:36 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/log2f/lib/main.js
> +var HIGH_MAX_NORMAL_EXP = 0x7f800000|0; // asm type annotation
You can use `@stdlib/constants/float32/exponent-mask` instead.

2025-12-31 06:36 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/log2f/lib/main.js
> +var HIGH_MIN_NORMAL_EXP = 0x00800000|0; // asm type annotation
```suggestion
// 1.1754943508222875e-38 => 0 00000001 00000000000000000000000 => 0x00800000 = 8388608
var MIN_NORM_WORD = 0x00800000|0; // asm type annotation
```

Can we use this commenting style here, following the project conventions while defining words?

2025-12-31 06:36 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/log2f/lib/main.js
> +var HIGH_BIASED_EXP_0 = 0x3f800000|0; // asm type annotation
```suggestion
// 1 => 0 01111111 00000000000000000000000 => 0x3f800000 = 1065353216
var ONE_WORD = 0x3f800000|0; // asm type annotation
```

2025-12-31 06:36 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/log2f/lib/main.js
> +var HIGH_MIN_NORMAL_EXP = 0x00800000|0; // asm type annotation
Applies to `main.c` as well.

2025-12-31 06:36 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/log2f/lib/main.js
> +* Evaluates the binary logarithm (base two) for single-precision floating point values.
```suggestion
* Evaluates the binary logarithm (base two) of a single-precision floating-point number.
```

Applies here and elsewhere.

2025-12-31 06:36 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/log2f/lib/main.js
> +	hx = toWordf( x ) | 0;
```suggestion
	hx = toWordf( f32( x ) ) |0; // asm type annotation
```

2025-12-31 06:36 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/log2f/lib/main.js
> +	}
You don't need this condition as you are already checking for `+-0` down below at line 112.

2025-12-31 06:36 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/log2f/lib/main.js
> +	k = f32( k + f32( ( ( hx >> 23 ) - FLOAT32_EXPONENT_BIAS ) | 0 ) );
We don't need `f32` emulation here as `k` is an integer.

2025-12-31 06:36 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/log2f/lib/main.js
> +	k = f32( k + f32( ( ( hx >> 23 ) - FLOAT32_EXPONENT_BIAS ) | 0 ) );
Same applies below.

2025-12-31 06:36 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/log2f/lib/main.js
> +	i = f32( ( ( hx+0x4afb0d ) & HIGH_MIN_NORMAL_EXP )|0 ); // asm type annotation
Same for `i`. This is also an integer.

2025-12-31 06:36 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/log2f/lib/main.js
> +	x = fromWordf( hx | ( i ^ HIGH_BIASED_EXP_0) );
```suggestion
	x = fromWordf( hx | ( i^ONE_WORD ) );
```

2025-12-31 06:36 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/log2f/lib/main.js
> +	f = f32( x - 1.0 );
```suggestion
	f = f32( x - f32( 1.0 ) );
```

Same applies for `0.5` in the next line.

2025-12-31 06:36 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/log2f/lib/main.js
> +	hx = toWordf( hi ) | 0;
```suggestion
	hx = toWordf( hi ) | 0; // asm type annotation
```

2025-12-31 06:36 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/log2f/lib/main.js
> +	hi = fromWordf( hx & 0xfffff000);
You can also define `0xfffff000` as a separate variable:

```js
// Mask to clear lower 12 mantissa bits:
var TRUNC_MASK = 0xfffff000|0; // asm type annotation
```

2025-12-31 06:36 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/log2f/lib/main.js
> +	lo = f32( f32( f - hi ) - f32( hfsq ) + f32( R ) );
```suggestion
	lo = f32( f32( f32( f-hi ) - hfsq ) + R );
```

2025-12-31 06:36 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/log2f/lib/main.js
> +	lo = f32( f32( f - hi ) - f32( hfsq ) + f32( R ) );
`hfsq` and `R` are already `float32`

2025-12-31 06:36 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/log2f/lib/main.js
> +	return f32( f32( f32( lo + hi ) * IVLN2LO ) + f32( lo * IVLN2HI ) + f32( hi * IVLN2HI ) + f32( y ) ); // eslint-disable-line max-len
The `f32` emulation is off here too, especially the addition, which also needs to be casted. One solution is to use two variables `valHi` and `valLo` as done in https://github.com/stdlib-js/stdlib/blob/93fa3eb4ae84a02ec231d778c6e543a83a86bc45/lib/node_modules/%40stdlib/math/base/special/log2/lib/main.js#L164-L171

2025-12-31 06:39 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/log2f/lib/main.js
> +	hi = f32( f - hfsq );
Before this, I was thinking about whether to include the comment in the [reference implementation](https://svnweb.freebsd.org/base/release/12.2.0/lib/msun/src/e_log2f.c?view=markup#l60). I don't think this is an issue with the modern C/JS compilers, but just getting a second opinion. Thanks!

cc: @kgryte

2025-12-31 06:41 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/log2f/benchmark/c/benchmark.c
Any reason why we don't have the native C benchmark file?

2025-12-31 06:41 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/log2f/benchmark/c/benchmark.c
> +}
This needs to be updated as per the current project conventions.

```
/**
* Generates a random number on the interval [min,max).
*
* @param min    minimum value (inclusive)
* @param max    maximum value (exclusive)
* @return       random number
*/
static float random_uniform( const float min, const float max ) {
	float v = (float)rand() / ( (float)RAND_MAX + 1.0f );
	return min + ( v*(max-min) );
}
```

2025-12-31 06:42 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/log2f/benchmark/benchmark.js
> +};
No need for this. There is no built-in `Math.log2f`

2025-12-31 06:43 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/log2f/benchmark/benchmark.js
> +bench( pkg+'::built-in', opts, function benchmark( b ) {
This will be removed accordingly.

2025-12-31 06:44 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/log2f/src/addon.c
> +STDLIB_MATH_BASE_NAPI_MODULE_F_F( stdlib_base_log2f )
```suggestion
STDLIB_MATH_BASE_NAPI_MODULE_F_F( stdlib_base_log2f )
```

2025-12-31 06:46 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/log2f/test/fixtures/julia/runner.jl
> +gen( x, out );
All these values should be casted to `Float32`. See https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/sinf/test/fixtures/julia/runner.jl for reference

2025-12-31 06:48 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/log2f/test/fixtures/julia/runner.jl
> +gen( x, out );
It's fine to just use `stop = 1.0e-45` here

2025-12-31 06:54 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/log2f/test/test.js
> +		y = log2f( x[i] );
Instead of declaring a new variable `e`, you can do:

```js
x[ i ] = f32( x[ i ] );
expected[ i ] = f32( expected[ i ] );
```

as being done in https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/sinf/test/test.js

2025-12-31 06:54 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/log2f/test/test.js
> +		t.strictEqual( ulpdiff( y, e ) <= 152, true, 'returns expected value' );
Any reason why such a big number. I think this can be lowered.

2025-12-31 06:54 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/log2f/test/test.js
> +		t.strictEqual( ulpdiff( y, e ) <= 8, true, 'returns expected value' );
Same comment here.

2025-12-31 06:54 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/log2f/test/test.js
> +		t.strictEqual( ulpdiff( y, e ) <= 9, true, 'returns expected value' );
Same.

2025-12-31 06:54 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/log2f/test/test.js
> +		t.strictEqual( ulpdiff( y, e ) <= 9, true, 'returns expected value' );
Ideally, this should be the minimum possible value.

2025-12-31 06:55 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/log2f/package.json
> +  "description": "Binary logarithm (base 2).",
`description` needs to be updated

2025-12-31 06:57 UTC, anandkaranubc commented
@Neerajpathak07 This PR needs a bit of cleanup. I think you’ll need to go through each file, cross-check it with the corresponding double-precision files, and make the necessary changes.

2025-12-31 07:25 UTC, Neerajpathak07 commented
Ahh alright I'll review the implementation closely again.

2025-12-31 07:25 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/log2f/lib/main.js
> +	hi = f32( f - hfsq );
We don't need that comment from FreeBSD, as it doesn't apply here.

2025-12-31 07:26 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/log2f/lib/main.js
> +	hi = f32( f - hfsq );
Cool, thanks!

2025-12-31 09:53 UTC, Neerajpathak07 commented on lib/node_modules/@stdlib/math/base/special/log2f/lib/main.js
> +	return f32( f32( f32( lo + hi ) * IVLN2LO ) + f32( lo * IVLN2HI ) + f32( hi * IVLN2HI ) + f32( y ) ); // eslint-disable-line max-len
LM try this!!

2025-12-31 16:21 UTC, Neerajpathak07 commented
Updated the PR followed by the suggested changes. Will take a final look in the morning and open for review!!

2026-03-01 16:02 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/log2f/lib/main.js
> +	hx = toWordf( f32( x ) ) | 0; // asm type annotation
```suggestion
	x = f32( x );
	hx = toWordf( x ) | 0; // asm type annotation
```

We already converted `x` to `float32` in L114. So, no need to have a redundant conversion here.

2026-03-02 03:12 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/log2f/lib/main.js
> +		hx = toWordf( x ) | 0;
```suggestion
		hx = toWordf( x ) | 0; // asm type annotation
```

2026-03-02 05:18 UTC, Neerajpathak07 commented on lib/node_modules/@stdlib/math/base/special/log2f/src/main.c
Have streamlined the C implementation w.r.t the newest version of `msun` implementation.
Reference:- https://github.com/freebsd/freebsd-src/blob/main/lib/msun/src/e_log2f.c

2026-03-02 06:10 UTC, Neerajpathak07 commented
/stdlib update-copyright-years

2026-03-02 13:47 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/log2f/lib/main.js
> +	k += ( ( hx >> 23 ) - FLOAT32_EXPONENT_BIAS ) | 0; // asm type annotation
We can use [`@stdlib/constants/float32/num-significand-bits`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/constants/float32/num-significand-bits) here instead of directly having `23`. This would make it clearer that we are stripping the significand field to expose the exponent.

2026-03-02 13:48 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/log2f/lib/main.js
> +	k += ( ( i >> 23 ) | 0 ); // asm type annotation
Similarly, here too.

2026-03-02 17:32 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/log2f/lib/main.js
> +	k += ( ( i >> 23 ) | 0 ); // asm type annotation
```suggestion
	k += ( i >> 23 ) | 0; // asm type annotation
```

2026-03-02 17:32 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/log2f/lib/main.js
> +	return valLo + valHi;
@Neerajpathak07 We will need to update this part. This is similar how we do it for the double-precision implementation, but you might want to refer again to the reference and also wrap the arithmetic operations here with `f32()`.

2026-08-16 23:56 UTC, anandkaranubc submitted a review, later dismissed
This PR is ready to be merged. Thanks @Neerajpathak07 for working on it! 🚀 

cc: @kgryte

2026-08-17 06:44 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/log2f/src/main.c
> +	return ( lo + hi ) * IVLN2LO + lo * IVLN2HI + hi * IVLN2HI + y;
```suggestion
	return ( (lo+hi)*IVLN2LO ) + ( lo*IVLN2HI ) + ( hi*IVLN2HI ) + y;
```

2026-08-17 06:48 UTC, kgryte approved these changes
LGTM

2026-08-17 06:55 UTC, merged