refactor: update `math/base/assert/is-even` to follow latest project conventions
stdlib-js/stdlib pull request #4183
Opened 2024-12-23 18:35 UTC by vivekmaurya001

Resolves None.

## Description

- refactoring addon.c to follow latest project conventions for  `math/base/assert/is-even` 
- updating benchmark calculations

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

 - [x] Read, understood, and followed the [contributing guidelines](https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md)

* * *

@stdlib-js/reviewers 

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-12-25 15:10 UTC, vivekmaurya001 commented
good afternoon, please give this a reveiw @kgryte!

2025-01-02 22:28 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/assert/is-even/benchmark/benchmark.js
>  var round = require( '@stdlib/math/base/special/round' );
@vivekmaurya001 Instead of using a manual loop to generate random values, would you mind using `random/array/discrete-uniform`?

2025-01-02 22:28 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/assert/is-even/benchmark/benchmark.native.js
>  var round = require( '@stdlib/math/base/special/round' );
Same comment.

2025-01-02 22:29 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/assert/is-even/benchmark/c/native/benchmark.c
> +		x[ i ] = ( rand_double() * 200.0 ) - 100.0;
@vivekmaurya001 Would you mind rounding this values? Using the built-in C99 `round` function should be fine.

2025-01-02 22:31 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/assert/is-even/src/addon.c
> +	STDLIB_NAPI_CREATE_DOUBLE( env, stdlib_base_is_even( x ), out );
@vivekmaurya001 You should use `STDLIB_NAPI_CREATE_INT32` as done in the original bindings.

2025-01-02 22:31 UTC, kgryte requested changes
Left an initial round of comments.

2025-01-03 06:52 UTC, vivekmaurya001 commented on lib/node_modules/@stdlib/math/base/assert/is-even/benchmark/benchmark.js
>  var round = require( '@stdlib/math/base/special/round' );
done !

2025-01-03 06:52 UTC, vivekmaurya001 commented on lib/node_modules/@stdlib/math/base/assert/is-even/benchmark/benchmark.native.js
>  var round = require( '@stdlib/math/base/special/round' );
done

2025-01-03 06:52 UTC, vivekmaurya001 commented on lib/node_modules/@stdlib/math/base/assert/is-even/benchmark/c/native/benchmark.c
> +		x[ i ] = ( rand_double() * 200.0 ) - 100.0;
yeah sorry i forgot to add it , now corrected !

2025-01-03 06:53 UTC, vivekmaurya001 commented on lib/node_modules/@stdlib/math/base/assert/is-even/src/addon.c
> +	STDLIB_NAPI_CREATE_DOUBLE( env, stdlib_base_is_even( x ), out );
okay !

2025-01-03 07:29 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/assert/is-even/benchmark/c/native/benchmark.c
> +		x[ i ] = round(( rand_double() * 200.0 ) - 100.0);
```suggestion
		x[ i ] = round( (rand_double()*200.0) - 100.0 );
```

2025-01-03 07:30 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/assert/is-even/src/addon.c
>  #include <stdint.h>
```suggestion
```

No longer used.

2025-01-03 07:31 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/assert/is-even/src/addon.c
>  #include <node_api.h>
```suggestion
#include <node_api.h>
#include <stdint.h>
```

Correction, it should be used below.

2025-01-03 07:31 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/assert/is-even/src/addon.c
> +	STDLIB_NAPI_CREATE_INT32( env, stdlib_base_is_even( x ), out );
```suggestion
	STDLIB_NAPI_CREATE_INT32( env, (int32_t)stdlib_base_is_even( x ), out );
```

2025-01-03 07:33 UTC, kgryte approved these changes
LGTM

2025-01-03 07:38 UTC, merged