feat: add `math/base/assert/is-probabilityf`
stdlib-js/stdlib pull request #4214
Opened 2024-12-25 07:34 UTC by vivekmaurya001

Progresses None

## Description

- adds math/base/assert/is-probabilityf, which would be the single-precision equivalent for [math/base/assert/is-probability](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/assert/is-probability).

This pull request:

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

 - [x] Read, understood, and followed the [contributing guidelines](https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md)

* * *

@stdlib-js/reviewers 

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-12-25 07:48 UTC, vivekmaurya001 commented
/stdlib update-copyright-years

2024-12-25 08:37 UTC, vivekmaurya001 commented
@kgryte , please give some reveiw

2025-01-08 07:31 UTC, vivekmaurya001 commented
/stdlib update-copyright-years

2025-01-08 16:37 UTC, gunjjoshi requested changes

2025-01-08 16:37 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-probabilityf/README.md
> +    bool = isProbabilityf( x );
@vivekmaurya001 We can use `@stdlib/random/array/uniform` here, and initialize `x` as an array.

2025-01-08 16:37 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-probabilityf/README.md
> +bool out = stdlib_base_is_probabilityf( 0.5 );
```suggestion
bool out = stdlib_base_is_probabilityf( 0.5f );
```

2025-01-08 16:37 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-probabilityf/README.md
> +out = stdlib_base_is_probabilityf( 3.14 );
```suggestion
out = stdlib_base_is_probabilityf( 3.14f );
```

2025-01-08 16:37 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-probabilityf/benchmark/benchmark.js
> +var randu = require( '@stdlib/random/base/randu' );
@vivekmaurya001 Can you please change this and the code below accordingly, to use `@stdlib/random/array/uniform`?

2025-01-08 16:37 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-probabilityf/benchmark/benchmark.js
> +var randu = require( '@stdlib/random/base/randu' );
Same can be done for `benchmark.native.js` as well.

2025-01-08 16:37 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-probabilityf/benchmark/c/native/benchmark.c
> +		b = stdlib_base_is_probabilityf( x[ i%100 ] );
```suggestion
		b = stdlib_base_is_probabilityf( x[ i % 100 ] );
```

2025-01-08 16:37 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-probabilityf/README.md
> +    bool = isProbabilityf( x );
This can be done in `examples/index.js` too.

2025-01-08 16:37 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-probabilityf/package.json
> +    "dbl",
```suggestion
```

2025-01-08 16:37 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-probabilityf/src/main.c
> +* bool out = stdlib_base_is_probabilityf( 0.5 );
```suggestion
* bool out = stdlib_base_is_probabilityf( 0.5f );
```

2025-01-08 16:37 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-probabilityf/src/main.c
> +* out = stdlib_base_is_probabilityf( 1.5 );
```suggestion
* out = stdlib_base_is_probabilityf( 1.5f );
```

2025-01-08 16:37 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-probabilityf/src/main.c
> +	return ( x >= 0.0 && x <= 1.0 );
```suggestion
	return ( x >= 0.0f && x <= 1.0f );
```

2025-01-08 16:37 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-probabilityf/test/test.js
> +		x = -1.0 - ( randu()*1000.0 );
```suggestion
		x = -1.0 - ( randu() * 1000.0 );
```

2025-01-08 16:37 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-probabilityf/test/test.js
> +		x = ( randu()*1000.0 ) + 2.0;
```suggestion
		x = ( randu() * 1000.0 ) + 2.0;
```

2025-01-08 16:37 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-probabilityf/test/test.js
> +	t.equal( isProbabilityf( 0.0/0.0 ), false, 'returns false' );
```suggestion
	t.equal( isProbabilityf( 0.0 / 0.0 ), false, 'returns false' );
```

2025-01-08 16:37 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-probabilityf/test/test.native.js
> +		x = -1.0 - ( randu()*1000.0 );
```suggestion
		x = -1.0 - ( randu() * 1000.0 );
```

2025-01-08 16:37 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-probabilityf/test/test.native.js
> +		x = ( randu()*1000.0 ) + 2.0;
```suggestion
		x = ( randu() * 1000.0 ) + 2.0;
```

2025-01-08 16:37 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-probabilityf/test/test.native.js
> +	t.equal( isProbabilityf( 0.0/0.0 ), false, 'returns false' );
```suggestion
	t.equal( isProbabilityf( 0.0 / 0.0 ), false, 'returns false' );
```

2025-01-08 16:41 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-probabilityf/test/test.js
> +		t.equal( bool, false, 'returns false when provided '+x );
```suggestion
		t.equal( bool, false, 'returns expected value when provided '+x );
```

2025-01-08 16:42 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-probabilityf/test/test.js
> +		t.equal( bool, false, 'returns false when provided '+x );
@vivekmaurya001 Can you please change this everywhere else in this file and in `test.native.js`?

2025-01-08 17:40 UTC, vivekmaurya001 commented on lib/node_modules/@stdlib/math/base/assert/is-probabilityf/README.md
> +    bool = isProbabilityf( x );
done the changes !

2025-01-08 17:40 UTC, vivekmaurya001 commented on lib/node_modules/@stdlib/math/base/assert/is-probabilityf/benchmark/benchmark.js
> +var randu = require( '@stdlib/random/base/randu' );
done

2025-01-08 17:41 UTC, vivekmaurya001 commented on lib/node_modules/@stdlib/math/base/assert/is-probabilityf/test/test.js
> +		t.equal( bool, false, 'returns false when provided '+x );
should i replace the return true also ? , for now i have done with false

2025-01-08 18:54 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-probabilityf/test/test.js
> +		t.equal( bool, false, 'returns false when provided '+x );
Yes, @vivekmaurya001 .

2025-01-08 18:55 UTC, vivekmaurya001 commented on lib/node_modules/@stdlib/math/base/assert/is-probabilityf/test/test.js
> +		t.equal( bool, false, 'returns false when provided '+x );
ook

2025-01-08 19:04 UTC, vivekmaurya001 commented on lib/node_modules/@stdlib/math/base/assert/is-probabilityf/test/test.js
> +		t.equal( bool, false, 'returns false when provided '+x );
done

2025-01-08 19:15 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/assert/is-probabilityf/test/test.js
> +	t.equal( isProbabilityf( 0.0/0.0 ), false, 'returns expected value' );
```suggestion
	t.equal( isProbabilityf( 0.0 / 0.0 ), false, 'returns expected value' );
```

2025-01-08 19:18 UTC, gunjjoshi approved these changes

2025-01-11 13:37 UTC, vivekmaurya001 commented
Good morning , @kgryte  please take a look

2025-01-11 14:24 UTC, Planeshifter approved these changes

2025-01-11 14:27 UTC, merged