feat: add C implementation for `stats/base/dists/geometric/pmf`
stdlib-js/stdlib pull request #4220
Opened 2024-12-25 11:43 UTC by 0PrashantYadav0

Resolves #3639

## Description

> What is the purpose of this pull request?

This pull request:

-   adds C implementation for @stdlib/stats/base/dists/geometric/pmf along with relevant tests, benchmarks and examples.

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #3639

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-12-25 21:06 UTC, Planeshifter requested changes
Did an initial review and left comments that should be addressed. Thanks!

2024-12-25 21:06 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/geometric/pmf/benchmark/benchmark.js
> +		p[ i ] = ( randu()*1.0 ) + EPS;
Let's not add `EPS` here because `p` should be a number in `[0,1]`.

2024-12-25 21:06 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/geometric/pmf/README.md
> +Evaluates evaluating the [probability mass function][pmf] (PMF) of a [geometric][geometric-distribution] distribution with success probability `0 <= p <= 1`.
```suggestion
Evaluates the [probability mass function][pmf] (PMF) of a [geometric][geometric-distribution] distribution with success probability `0 <= p <= 1`.
```

2024-12-25 21:06 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/geometric/pmf/README.md
> +        p = random_uniform( 0.0, 1.0 ) + STDLIB_CONSTANT_FLOAT64_EPS;
Let's not add `EPS` here because `p` should be a number in `[0,1]`.

2024-12-25 21:06 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/geometric/pmf/benchmark/benchmark.native.js
> +		p[ i ] = ( randu()*1.0 ) + EPS;
Let's not add `EPS` here because `p` should be a number in `[0,1]`.

2024-12-25 21:06 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/geometric/pmf/benchmark/c/benchmark.c
> +		p[ i ] = random_uniform( 0.0, 1.0 ) + STDLIB_CONSTANT_FLOAT64_EPS;
Let's not add `EPS` here because `p` should be a number in `[0,1]`.

2024-12-25 21:06 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/geometric/pmf/include/stdlib/stats/base/dists/geometric/pmf.h
> +* Evaluates the probability mass function (PMF) for the geometric distribution with probability parameter p.
```suggestion
* Evaluates the probability mass function (PMF) for a geometric distribution with success probability `p` at a value `x`.
```

2024-12-25 21:06 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/geometric/pmf/manifest.json
> +    "options": {
Two-space indentation needed here.

2024-12-25 21:06 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/geometric/pmf/src/main.c
> +    if (
Should be tab-indented.

2024-12-25 21:06 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/geometric/pmf/src/main.c
> +* @param {number} x - input value
Shouldn't have JSDoc comments in C files. No type annotations and descriptions should be vertically aligned.

2024-12-25 21:06 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/geometric/pmf/src/main.c
> +#include <math.h>
Not used:

```suggestion
```

2024-12-25 21:06 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/geometric/pmf/src/main.c
> +* // returns NaN
Let's just keep one example; also needs to be updated for C (no `var`):

```suggestion
* @example
* double y = pmf( 4.0, 0.3 );
* // returns ~0.072
```

2024-12-26 07:08 UTC, 0PrashantYadav0 commented
@Planeshifter I made changes in this pr as well as in all the pr related to geometric distribution. Please look into all of these.

2024-12-26 17:05 UTC, Planeshifter commented
/stdlib lint-autofix

2024-12-28 18:03 UTC, Planeshifter approved these changes
Thanks! Let's land this PR shortly.

2024-12-28 18:03 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/geometric/pmf/src/main.c
> +	if( stdlib_base_is_nonnegative_integer( x ) ){
```suggestion
	if ( stdlib_base_is_nonnegative_integer( x ) ) {
```

2024-12-28 18:12 UTC, merged