[RFC]: Add C implementation for @stdlib/stats/base/dists/arcsine/mode
stdlib-js/stdlib pull request #4236
Opened 2024-12-25 20:04 UTC by anandkaranubc

### Type: pre_push_report

**Description:** Results of running various checks prior to pushing changes.  
**Report:**

- **Task:** run_javascript_examples **Status:** Success
- **Task:** run_c_examples **Status:** Success
- **Task:** run_cpp_examples **Status:** Not Applicable
- **Task:** run_javascript_readme_examples **Status:** Success
- **Task:** run_c_benchmarks **Status:** Success
- **Task:** run_cpp_benchmarks **Status:** Not Applicable
- **Task:** run_fortran_benchmarks **Status:** Not Applicable
- **Task:** run_javascript_benchmarks **Status:** Success
- **Task:** run_julia_benchmarks **Status:** Not Applicable
- **Task:** run_python_benchmarks **Status:** Not Applicable
- **Task:** run_r_benchmarks **Status:** Not Applicable
- **Task:** run_javascript_tests **Status:** Success

---

**Resolves** #{{3355}}.

## Description

**What is the purpose of this pull request?**

This pull request:

- Adds a C implementation of the `@stdlib/stats/base/dists/arcsine/mode` package, including a Node.js native addon.
- Includes a C source implementation within the `src` directory of the package.
- Provides a native add-on interface for calling the C implementation from JavaScript.
- Adds a JavaScript file in the `lib` folder to enable benchmarking and unit testing for the native implementation.
- Creates unit tests to validate expected behavior.
- Includes C benchmarks to measure the performance of the implementation.
- Supplies C examples to demonstrate usage.
- Adds JavaScript benchmarks for measuring the performance of the native add-on.
- Updates the README to document the added C API.
- Provides build and configuration files for compiling and running the C source implementation using project `make` commands.

## Related Issues

**Does this pull request have any related issues?**

This pull request:

- Resolves #3355

## Questions

**Any questions for reviewers of this pull request?**

No.

## Other

**Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.**

No.

## Checklist

**Please ensure the following tasks are completed before submitting this pull request:**

- [x] Read, understood, and followed the [contributing guidelines][contributing].

---

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

---

2024-12-25 20:23 UTC, anandkaranubc commented
Can i get some suggestion on why it says `#include "stdlib/math/base/napi/binary.h"` even though the file exists?

2024-12-29 05:14 UTC, anandkaranubc commented
@Planeshifter Can you give this a quick review please? Thanks!

2024-12-29 16:09 UTC, Planeshifter requested changes
Thank you for your first PR, which is much appreciated!

Left a few comments. You will also need to update the `README.md` file to document the new C implementation.

2024-12-29 16:09 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/arcsine/mode/src/main.c
> +#include <stdbool.h>
Not needed:

```suggestion

```

2024-12-29 16:09 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/arcsine/mode/manifest.json
> +        "@stdlib/math/base/special/asin",
These dependencies here are not used. Please update and only list what is included in the respective C files (so for examples and benchmark you also want to include the ones in the C benchmark and example files).

2024-12-29 16:09 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/arcsine/mode/examples/c/example.c
> +        } else {
Let's remove this if-block to simplify.

2024-12-29 22:57 UTC, anandkaranubc commented
Thanks @Planeshifter for feedback. I have made the necessary changes as you suggested over here and also in a similar feature request in https://github.com/stdlib-js/stdlib/pull/4241

2024-12-30 03:37 UTC, Planeshifter commented
/stdlib lint-autofix

2025-01-02 19:42 UTC, anandkaranubc commented
/stdlib update-copyright-years

2025-01-02 20:42 UTC, anandkaranubc commented
@Planeshifter 

Sorry for the ping. Just wanted to get your feedback on whether I should change something now?

PS: Happy New Year!

2025-01-04 21:21 UTC, anandkaranubc commented
/stdlib update-copyright-years
/stdlib lint-autofix

2025-01-04 21:24 UTC, anandkaranubc commented
/stdlib lint-autofix

2025-01-08 04:12 UTC, anandkaranubc commented
/stdlib lint-autofix

2025-01-15 02:55 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/arcsine/mode/include/stdlib/stats/base/dists/arcsine/mode.h
> +*/
We don't include parameter and return descriptions in header files to keep them concise.

```suggestion
/**
* Returns the mode of an arcsine distribution with minimum support `a` and maximum support `b`.
*/
```

2025-01-15 02:56 UTC, Planeshifter approved these changes
Thanks, @anandkaranubc, for the edits and PR! Let's get it in...

2025-01-15 03:15 UTC, merged