feat: add C ndarray interface and refactor implementation for `stats/base/dnanmeanors`
stdlib-js/stdlib pull request #4248
Opened 2024-12-26 05:27 UTC by Neerajpathak07

Resolves none

## Description

> What is the purpose of this pull request?

This pull request:

-   adds C ndarray interface for stats/base/dnanmean
-   refactor JavaScript implementation
-   refactor examples, tests, docs and benchmarks in manifest.json

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves none

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-  [x] Read, understood, and followed the [contributing guidelines](https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md)

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2025-01-18 13:09 UTC, Neerajpathak07 commented
/stdlib update-copyright-years

2025-02-01 12:18 UTC, aayush0325 requested changes
this is looking good, a couple of minor changes and we should be good to go here!

2025-02-01 12:18 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/dnanmeanors/benchmark/benchmark.js
> +	if ( bernoulli( 0.2 ) ) {
```suggestion
	if ( bernoulli( 0.8 < 1 ) ) {
```
just a minor change here, we'll try to keep things explicit to show what is being returned etc...

2025-02-01 12:18 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/dnanmeanors/benchmark/benchmark.native.js
> +	if ( bernoulli( 0.2 ) ) {
same comment here and for the other files

2025-02-01 12:18 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/dnanmeanors/src/addon.c
> +* Copyright (c) 2020 The Stdlib Authors.
```suggestion
* Copyright (c) 2024 The Stdlib Authors.
```
no need to change this

2025-02-01 12:18 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/dnanmeanors/src/addon.c
> -#include <node_api.h>
we shouldn't remove the `<node_api.h>` header as we're using napi_value, napi_env etc in this file

2025-02-01 12:31 UTC, Neerajpathak07 commented
@aayush0325 Updated the PR do take a look!

2025-02-01 13:03 UTC, aayush0325 requested changes
lgtm, just one missing change

some of the examples in `README.md`, `lib/index.js`, `docs/repl.txt` don't properly represent how we're handling the `NaN` elements can you please update them?

here is a [sample PR](https://github.com/stdlib-js/stdlib/pull/4994) for you to get an idea of what I'm talking about

2025-02-01 13:05 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/dnanmeanors/README.md
> +var v = dnanmeanors( 4, x, 2 );
here for example, we'll only be traversing through 1.0 --> 2.0 --> -2.0 --> 4.0, which gives us the same result but we should also explicitly traverse over the `NaN` element to show how we're handling that

2025-02-01 13:06 UTC, Neerajpathak07 commented
Alright got it I'll update these changes as well.

2025-02-01 13:07 UTC, Neerajpathak07 commented on lib/node_modules/@stdlib/stats/base/dnanmeanors/README.md
> +var v = dnanmeanors( 4, x, 2 );
Oh got it as we would generally ignore the NaN val so didn't think of it.

2025-02-01 13:46 UTC, aayush0325 approved these changes
lgtm

2025-02-01 13:49 UTC, Neerajpathak07 commented
Made the changes in all the other PR's where necessary.

2025-02-02 17:50 UTC, Neerajpathak07 commented
/stdlib update-copyright-years

2025-02-03 04:59 UTC, aayush0325 approved these changes

2025-02-03 08:38 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dnanmeanors/README.md
> +// returns 4.6667
```suggestion
// returns ~4.6667
```

2025-02-03 08:39 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dnanmeanors/README.md
> +// returns 4.6667
The displayed return value is approximate. Hence, use a tilde.

2025-02-03 08:40 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dnanmeanors/README.md
> +-   **N**:       `[in] CBLAS_INT` number of indexed elements.
```suggestion
-   **N**: `[in] CBLAS_INT` number of indexed elements.
```

Don't align this in READMEs. This needs to be fixed here and elsewhere in this file.

2025-02-03 08:40 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dnanmeanors/README.md
> +// returns 4.6667
```suggestion
// returns ~4.6667
```

2025-02-03 08:41 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dnanmeanors/README.md
> +-   **N**:       `[in] CBLAS_INT` number of indexed elements.
Same comments as below.

2025-02-03 08:41 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dnanmeanors/README.md
> +    const double x[] = { 1.0, 2.0, 0.0/0.0, 3.0, 0.0/0.0, 4.0, 5.0, 6.0, 0.0/0.0,   7.0, 8.0, 0.0/0.0 };
```suggestion
    const double x[] = { 1.0, 2.0, 0.0/0.0, 3.0, 0.0/0.0, 4.0, 5.0, 6.0, 0.0/0.0, 7.0, 8.0, 0.0/0.0 };
```

2025-02-03 08:43 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dnanmeanors/benchmark/benchmark.js
> +}
```suggestion
/**
* Returns a random number.
*
* @private
* @returns {number} random number 
*/
function rand() {
	if ( bernoulli( 0.5 < 1 ) ) {
		return NaN;
	}
	return uniform( -10.0, 10.0 );
}
```

These same changes should be applied in other benchmark files. `p = 0.8` means that, on avg, 80% of the values will be `NaN`. That is not super realistic.

2025-02-03 08:43 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dnanmeanors/benchmark/benchmark.native.js
> +* Returns a random value or `NaN`.
Same comments.

2025-02-03 08:43 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dnanmeanors/benchmark/benchmark.ndarray.js
> +* Returns a random value or `NaN`.
Same comments.

2025-02-03 08:44 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dnanmeanors/benchmark/benchmark.ndarray.native.js
> +* Returns a random value or `NaN`.
Same comments.

2025-02-03 08:48 UTC, kgryte requested changes
Left an initial round of comments.

2025-02-03 09:53 UTC, Neerajpathak07 commented on lib/node_modules/@stdlib/stats/base/dnanmeanors/benchmark/benchmark.js
> +}
ok then I'll make these changes where ever necessary!

2025-02-03 11:18 UTC, aayush0325 commented
@Neerajpathak07 sorry for the confusion from my side, you should use `bernoulli( 0.8 ) < 1` in your `rand()` function in JS benchmarks, i had suggested `bernoulli ( 0.8 < 1 )` which is not correct (notice the brackets).

2025-02-03 11:18 UTC, aayush0325 requested changes

2025-02-03 11:18 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/dnanmeanors/benchmark/benchmark.js
> +	if ( bernoulli( 0.5 < 1 ) ) {
```suggestion
	if ( bernoulli( 0.8 ) < 1 ) {
```

2025-02-03 11:19 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/dnanmeanors/benchmark/benchmark.js
> +	if ( bernoulli( 0.5 < 1 ) ) {
that is my bad :disappointed: sorry for the inconvenience

2025-02-03 12:51 UTC, Neerajpathak07 commented on lib/node_modules/@stdlib/stats/base/dnanmeanors/benchmark/benchmark.js
> +	if ( bernoulli( 0.5 < 1 ) ) {
According to this [review](https://github.com/stdlib-js/stdlib/pull/4248#discussion_r1938989291) have kept the avg 50% rather than 80%.

2025-02-03 12:52 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/dnanmeanors/benchmark/benchmark.js
> +	if ( bernoulli( 0.5 < 1 ) ) {
yes im telling you this only after discussing it with him!

2025-02-03 12:54 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/dnanmeanors/benchmark/benchmark.js
> +	if ( bernoulli( 0.5 < 1 ) ) {
the suggested change keeps 20% `NaN` values

2025-02-03 13:00 UTC, Neerajpathak07 commented on lib/node_modules/@stdlib/stats/base/dnanmeanors/benchmark/benchmark.js
> +	if ( bernoulli( 0.5 < 1 ) ) {
alright the n I'll make the changes here and on other PR's

2025-02-03 13:02 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/dnanmeanors/benchmark/benchmark.js
> +	if ( bernoulli( 0.5 < 1 ) ) {
refer to the comments in #4781 for your reference

2025-02-03 13:02 UTC, Neerajpathak07 commented on lib/node_modules/@stdlib/stats/base/dnanmeanors/benchmark/benchmark.js
> +	if ( bernoulli( 0.5 < 1 ) ) {
also should I update the `benchmark.length.c` to accumulate the avg for `NaN`

2025-02-03 13:07 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/dnanmeanors/benchmark/benchmark.js
> +	if ( bernoulli( 0.5 < 1 ) ) {
`benchmark.length.c` is okay

2025-02-03 13:39 UTC, Neerajpathak07 commented
@aayush0325 @kgryte Should this be good to go and if there are any changes remaining do let me know!!

2025-02-08 16:25 UTC, aayush0325 approved these changes
thank you!

2025-02-09 08:28 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dnanmeanors/README.md
> +double v = stdlib_strided_dnanmeanors( 6, x, 2, 0 );
```suggestion
double v = stdlib_strided_dnanmeanors_ndarray( 6, x, 2, 0 );
```

2025-02-09 08:30 UTC, kgryte approved these changes
LGTM

2025-02-09 08:41 UTC, merged