feat: add C implementation for `stats/base/dists/levy/cdf`
stdlib-js/stdlib pull request #4288
Opened 2024-12-27 12:18 UTC by AadishJ

Resolves #3722.

## Description

> What is the purpose of this pull request?

This pull request:

- Adds a C implementation of the levy cdf.
- Includes benchmarks for the C implementation.
- Provides examples demonstrating the usage of the levy cdf in C.

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #3722

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

- [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-12-28 17:48 UTC, Planeshifter requested changes
Thanks for your PR!

Looking good overall, but please fix the example in README.

2024-12-28 17:48 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/levy/cdf/README.md
> +#include "stdlib/stats/base/dists/arcsine/cdf.h"
Copy-paste error with examole being for arcsine dsitribution.

2024-12-28 17:54 UTC, AadishJ commented
Made the changes please check

2025-03-25 08:37 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/levy/cdf/benchmark/benchmark.js
> +		x[ i ] = ( randu() * 20.0 ) - 10.0;
@AadishJ We can directly draw the random numbers from `uniform` here for better clarity, e.g. `uniform( -10.0, 10.0 )` instead of `( randu() * 20.0 ) - 10.0`.

2025-03-25 08:38 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/levy/cdf/benchmark/benchmark.native.js
> +		x[ i ] = ( randu() * 20.0 ) - 10.0;
@AadishJ We can directly create arrays of random numbers from the desired distribution via `uniform` here for better clarity and to avoid the for-loop.

2025-03-25 09:13 UTC, AadishJ commented
Hey I have made the changes please check

2025-04-05 00:39 UTC, Planeshifter commented
/stdlib update-copyright-years

2025-04-05 00:42 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/levy/cdf/src/main.c
> +#include "stdlib/stats/base/dists/levy/cdf.h"
```suggestion
#include "stdlib/stats/base/dists/levy/cdf.h"
#include "stdlib/math/base/assert/is_nan.h"
#include "stdlib/math/base/special/erfc.h"
#include "stdlib/math/base/special/sqrt.h"
```

2025-04-05 00:43 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/levy/cdf/src/main.c
> +double stdlib_base_levy_cdf( const double x, const double mu, const double c ) {
```suggestion
* double y = stdlib_base_dists_levy_cdf( 9.0, 0.0, 1.0 );
* // returns ~0.999
*/
double stdlib_base_dists_levy_cdf( const double x, const double mu, const double c ) {
```

2025-04-05 00:43 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/levy/cdf/include/stdlib/stats/base/dists/levy/cdf.h
> +double stdlib_base_levy_cdf( const double x, const double mu, const double c );
```suggestion
double stdlib_base_dists_levy_cdf( const double x, const double mu, const double c );
```

2025-04-05 00:44 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/levy/cdf/README.md
> +        y = stdlib_base_levy_cdf( x, mu, c );
```suggestion
        y = stdlib_base_dists_levy_cdf( x, mu, c );
```

2025-04-05 00:44 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/levy/cdf/examples/c/example.c
> +		y = stdlib_base_levy_cdf( x, mu, c );
```suggestion
		y = stdlib_base_dists_levy_cdf( x, mu, c );
```

2025-04-05 00:46 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/levy/cdf/benchmark/c/benchmark.c
> +#include <time.h>
```suggestion
#include "stdlib/stats/base/dists/levy/cdf.h"
#include <sys/time.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
```

2025-04-05 00:47 UTC, Planeshifter approved these changes, later dismissed
Thanks, @AadishJ!

2025-04-05 00:51 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/levy/cdf/src/addon.c
> +STDLIB_MATH_BASE_NAPI_MODULE_DDD_D( stdlib_base_levy_cdf )
```suggestion
STDLIB_MATH_BASE_NAPI_MODULE_DDD_D( stdlib_base_dists_levy_cdf )
```

2025-04-05 00:54 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/levy/cdf/benchmark/c/benchmark.c
> +		y = stdlib_base_levy_cdf( x[ i % 100 ], mu[ i % 100 ], c[ i % 100 ] );
```suggestion
		y = stdlib_base_dists_levy_cdf( x[ i % 100 ], mu[ i % 100 ], c[ i % 100 ] );
```

2025-04-05 00:57 UTC, Planeshifter approved these changes

2025-04-05 00:59 UTC, merged