feat: add C implementation for `stats/base/dists/erlang/kurtosis`
stdlib-js/stdlib pull request #4289
Opened 2024-12-27 12:48 UTC by Neerajpathak07

Resolves #3570 .

## Description

> What is the purpose of this pull request?

This pull request:

-  adds C implementation for `stats/base/dists/erlang/kurtosis`

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #3570  

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-  [x] Read, understood, and followed the [contributing guidelines](https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md)

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2025-01-17 19:28 UTC, Neerajpathak07 commented
/stdlib update-copyright-years

2025-03-01 03:17 UTC, Planeshifter requested changes
Thanks for your PR, Neeraj!

For the Erlang packages, it would be good to type the `k` parameter as a `int32_t` given the parameter has to be an integer.. This will require some slight refactoring, but hopefully won't be too burdensome.

If people need the larger range afforded by `double`, they can use the gamma distribution instead.

2025-03-01 09:11 UTC, Neerajpathak07 commented
@Planeshifter Sure let me get back to you with the refactored code.

2025-03-02 17:08 UTC, Neerajpathak07 commented on lib/node_modules/@stdlib/stats/base/dists/erlang/kurtosis/test/test.native.js
> +	t.equal( isnan( y ), true, 'returns NaN' );
@Planeshifter I have made the necessary changes but Idk why only these two test cases are failing whereas it runs clean when I run them locally.

2025-03-02 17:43 UTC, Neerajpathak07 commented on lib/node_modules/@stdlib/stats/base/dists/erlang/kurtosis/test/test.native.js
> +	t.equal( isnan( y ), true, 'returns NaN' );
similar thing happens with other erlang packages as well is there something I'm missing?

2025-03-07 02:34 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/erlang/kurtosis/src/main.c
> +* Returns the excess kurtosis for a erlang distribution with shape parameter `k` and rate parameter `lambda`.
```suggestion
#include <stdint.h>

/**
* Returns the excess kurtosis for an Erlang distribution with shape parameter `k` and rate parameter `lambda`.
```

2025-03-07 02:34 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/erlang/kurtosis/src/main.c
> +* double y = stdlib_base_dists_beta_kurtosis( 1.0, 1.0 );
```suggestion
* double y = stdlib_base_dists_beta_kurtosis( 1, 1.0 );
```

2025-03-07 02:35 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/erlang/kurtosis/include/stdlib/stats/base/dists/erlang/kurtosis.h
> +* Returns the excess kurtosis for a erlang distribution with shape parameter `k` and rate parameter `lambda`.
```suggestion
* Returns the excess kurtosis for an Erlang distribution with shape parameter `k` and rate parameter `lambda`.
```

2025-03-07 02:36 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/erlang/kurtosis/examples/c/example.c
> +	double lambda;
```suggestion
	double lambda;
	int32_t k;
```

2025-03-07 02:36 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/erlang/kurtosis/README.md
> +    int i;
```suggestion
    double lambda;
    int32_t k;
    double y;
    int i;
```

2025-03-07 02:38 UTC, Planeshifter reviewed
Looks very good overall; left a few comments that should be addressed. However, I am not sure about the failing test cases right now. 

Any ideas on what is going on here, @kgryte?

2025-03-07 02:39 UTC, Planeshifter commented
/stdlib help

2025-03-15 19:06 UTC, Neerajpathak07 commented on lib/node_modules/@stdlib/stats/base/dists/erlang/kurtosis/test/test.native.js
> +	y = kurtosis( 0.0, 2.0 );
@Planeshifter removed the tests for int values like `3.9` and `1.5` for `var k`

2025-04-03 13:07 UTC, Planeshifter approved these changes
Thanks for your PR and getting it into great shape, @Neerajpathak07! 

As time permits, it would be great to similarly refactor the other Erlang PRs to have an integer-typed `k` parameter.

2025-04-03 13:13 UTC, merged

2025-04-03 15:39 UTC, Neerajpathak07 commented
@Planeshifter Will wrap all of them by tonight. little heads up you'll be pretty attested with some load on reviewing them but dw I'll make sure to bring them in great shape.