feat: add C `ndarray` API and refactor `blas/ext/base/dsumors`
stdlib-js/stdlib pull request #4320
Opened 2024-12-28 14:12 UTC by headlessNode

## Description

> What is the purpose of this pull request?

This pull request:

-   add C `ndarray` API and refactor/cleanup `blas/ext/base/dsumors`

## Related Issues

> Does this pull request have any related issues?

No. 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-12-28 17:27 UTC, headlessNode commented on lib/node_modules/@stdlib/blas/ext/base/dsumors/README.md
> +Computes the sum of double-precision floating-point strided array elements using ordinary recursivev summation and alternative indexing semantics.
```suggestion
Computes the sum of double-precision floating-point strided array elements using ordinary recursive summation and alternative indexing semantics.
```

2024-12-28 17:27 UTC, headlessNode commented on lib/node_modules/@stdlib/blas/ext/base/dsumors/benchmark/c/benchmark.length.c
> +		//cppcheck-suppress uninitvar
```suggestion
		// cppcheck-suppress uninitvar
```

2024-12-28 17:27 UTC, headlessNode commented on lib/node_modules/@stdlib/blas/ext/base/dsumors/benchmark/c/benchmark.length.c
> +		//cppcheck-suppress uninitvar
```suggestion
		// cppcheck-suppress uninitvar
```

2024-12-28 17:27 UTC, headlessNode commented on lib/node_modules/@stdlib/blas/ext/base/dsumors/src/main.c
>  */
JSDoc missing `alternative indexing semantics`

2025-01-02 03:21 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/dsumors/README.md
> +var x = discreteUniform( 10.0, -100, 100, {
```suggestion
var x = discreteUniform( 10, -100, 100, {
```

2025-01-02 03:23 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/dsumors/examples/index.js
> +var x = discreteUniform( 10.0, -100, 100, {
```suggestion
var x = discreteUniform( 10, -100, 100, {
```

2025-01-02 03:25 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/dsumors/src/main.c
>  * @param N       number of indexed elements
@headlessNode The descriptions need to be realigned.

2025-01-02 03:25 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/dsumors/test/test.dsumors.js
> +tape( 'if provided a `stride` parameter equal to `0`, the function returns the sum of first element repeated N times', function test( t ) {
```suggestion
tape( 'if provided a `stride` parameter equal to `0`, the function returns the sum of the first element repeated N times', function test( t ) {
```

2025-01-02 03:25 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/dsumors/test/test.dsumors.native.js
> +tape( 'if provided a `stride` parameter equal to `0`, the function returns the sum of first element repeated N times', opts, function test( t ) {
```suggestion
tape( 'if provided a `stride` parameter equal to `0`, the function returns the sum of the first element repeated N times', opts, function test( t ) {
```

2025-01-02 03:26 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/dsumors/test/test.ndarray.js
> +tape( 'if provided a `stride` parameter equal to `0`, the function returns the sum of first element repeated N times', function test( t ) {
```suggestion
tape( 'if provided a `stride` parameter equal to `0`, the function returns the sum of the first element repeated N times', function test( t ) {
```

2025-01-02 03:26 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/dsumors/test/test.ndarray.native.js
> +tape( 'if provided a `stride` parameter equal to `0`, the function returns the sum of first element repeated N times', opts, function test( t ) {
```suggestion
tape( 'if provided a `stride` parameter equal to `0`, the function returns the sum of the first element repeated N times', opts, function test( t ) {
```

2025-01-02 03:27 UTC, kgryte requested changes
Other than the description alignment, this LGTM.

2025-01-05 06:04 UTC, headlessNode commented on lib/node_modules/@stdlib/blas/ext/base/dsumors/src/main.c
> +}
```suggestion
double API_SUFFIX(stdlib_strided_dsumors)( const CBLAS_INT N, const double *X, const CBLAS_INT strideX ) {
	CBLAS_INT ox = stdlib_strided_stride2offset( N, strideX );
	return API_SUFFIX(stdlib_strided_dsumors_ndarray)( N, X, strideX, ox );
}
```

2025-01-05 06:08 UTC, headlessNode commented on lib/node_modules/@stdlib/blas/ext/base/dsumors/src/main.c
>  * @param N       number of indexed elements
@kgryte Sorry, I'm not sure I understand. What do you mean by "realigned"?

2025-01-06 07:33 UTC, kgryte commented on lib/node_modules/@stdlib/blas/ext/base/dsumors/src/main.c
>  * @param N       number of indexed elements
@headlessNode They don't all start at the same character column. See L26-29. Compare L40-43 where the descriptions for strideX and offsetX now start one column farther to the right.

2025-01-06 15:23 UTC, headlessNode commented
@kgryte Changes applied.

2025-01-08 04:22 UTC, kgryte approved these changes
LGTM

2025-01-08 04:23 UTC, merged