feat: add C `ndarray` API and refactor `blas/ext/base/dsumpw`
stdlib-js/stdlib pull request #4329
Opened 2024-12-28 18:36 UTC by headlessNode

## Description

> What is the purpose of this pull request?

This pull request:

-   add C `ndarray` API and refactor/cleanup `blas/ext/base/dsumpw`

## Related Issues

> Does this pull request have any related issues?

No.

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2025-01-02 03:29 UTC, kgryte requested changes
Taking a quick look at this PR and it seems that it needs the same small changes as the other similar PRs. Would you mind addressing?

2025-01-05 06:10 UTC, headlessNode commented on lib/node_modules/@stdlib/blas/ext/base/dsumpw/README.md
> +var x = discreteUniform( 10.0, -100, 100, {
```suggestion
var x = discreteUniform( 10, -100, 100, {
```

2025-01-05 06:14 UTC, headlessNode commented on lib/node_modules/@stdlib/blas/ext/base/dsumpw/examples/index.js
> +var x = discreteUniform( 10.0, -100, 100, {
```suggestion
var x = discreteUniform( 10, -100, 100, {
```

2025-01-05 06:14 UTC, headlessNode commented on lib/node_modules/@stdlib/blas/ext/base/dsumpw/test/test.dsumpw.js
> +tape( 'if provided a `stride` parameter equal to `0`, the function returns the sum of first element repeated N times', function test( t ) {
```suggestion
tape( 'if provided a `stride` parameter equal to `0`, the function returns the sum of the first element repeated N times', function test( t ) {
```

2025-01-05 06:14 UTC, headlessNode commented on lib/node_modules/@stdlib/blas/ext/base/dsumpw/test/test.dsumpw.native.js
> +tape( 'if provided a `stride` parameter equal to `0`, the function returns the sum of first element repeated N times', opts, function test( t ) {
```suggestion
tape( 'if provided a `stride` parameter equal to `0`, the function returns the sum of the first element repeated N times', opts, function test( t ) {
```

2025-01-05 06:14 UTC, headlessNode commented on lib/node_modules/@stdlib/blas/ext/base/dsumpw/test/test.ndarray.js
> +tape( 'if provided a `stride` parameter equal to `0`, the function returns the sum of first element repeated N times', function test( t ) {
```suggestion
tape( 'if provided a `stride` parameter equal to `0`, the function returns the sum of the first element repeated N times', function test( t ) {
```

2025-01-05 06:14 UTC, headlessNode commented on lib/node_modules/@stdlib/blas/ext/base/dsumpw/test/test.ndarray.native.js
> +tape( 'if provided a `stride` parameter equal to `0`, the function returns the sum of first element repeated N times', opts, function test( t ) {
```suggestion
tape( 'if provided a `stride` parameter equal to `0`, the function returns the sum of the first element repeated N times', opts, function test( t ) {
```

2025-01-05 06:16 UTC, headlessNode commented
@kgryte changes addressed.

2025-01-08 09:19 UTC, kgryte approved these changes
LGTM

2025-01-08 09:20 UTC, merged