feat: add C `ndarray` interface and refactor implementation for `stats/base/dsmeanpw`
stdlib-js/stdlib pull request #4338
Opened 2024-12-29 06:59 UTC by Neerajpathak07

Resolves none

## Description

> What is the purpose of this pull request?

This pull request:

-  adds C `ndarray` interface for `stats/base/dsmeanpw`
-  refactors JavaScript implementation
-  refactors tests, docs, benchmarks and examples.

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves none

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-  [x] Read, understood, and followed the [contributing guidelines](https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md)

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2025-01-18 13:37 UTC, Neerajpathak07 commented
/stdlib update-copyright-years

2025-01-18 21:58 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsmeanpw/manifest.json
>          "@stdlib/blas/ext/base/dssum",
Would you mind updating this dep to explicitly be `dssumpw`, rather than `dssum`? Applies here and below.

2025-01-18 21:59 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsmeanpw/src/main.c
> +#include "stdlib/blas/ext/base/dssum.h"
```suggestion
#include "stdlib/blas/ext/base/dssumpw.h"
```

2025-01-18 21:59 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsmeanpw/src/main.c
> +	return stdlib_strided_dssum_ndarray( N, X, strideX, offsetX ) / (double)N;
```suggestion
	return stdlib_strided_dssumpw_ndarray( N, X, strideX, offsetX ) / (double)N;
```

2025-01-18 22:00 UTC, kgryte requested changes
Other than updating to use `dssumpw` explicitly, this PR looks good.

2025-01-19 05:05 UTC, Neerajpathak07 commented on lib/node_modules/@stdlib/stats/base/dsmeanpw/src/main.c
> +	return stdlib_strided_dssum_ndarray( N, X, strideX, offsetX ) / (double)N;
sure I'll make the changes and make this PR ready!

2025-01-19 08:17 UTC, kgryte approved these changes
LGTM

2025-01-19 08:18 UTC, merged