feat: add C `ndarray` interface and refactor implementation for `stats/base/dsmeanwd`
stdlib-js/stdlib pull request #4339
Opened 2024-12-29 07:53 UTC by Neerajpathak07

Resolves none

## Description

> What is the purpose of this pull request?

This pull request:

-  adds C `ndarray` interface for `stats/base/dsmeanwd`
-  refactors JavaScript implementation
-  refactors tests, docs, benchmarks and examples.

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves none

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-  [x] Read, understood, and followed the [contributing guidelines](https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md)

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-12-29 16:35 UTC, Neerajpathak07 commented
@Planeshifter I have created a few PR's would really appreciate a review cheers!

2024-12-31 08:33 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsmeanwd/README.md
> +-   **strideX**: Stride Length for `x`.
```suggestion
-   **strideX**: stride Length for `x`.
```

2024-12-31 08:34 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsmeanwd/README.md
> +Calculate the mean value of a single-precision floating-point strided array, ignoring `NaN` values.
```suggestion
Computes the mean value of a single-precision floating-point strided array, ignoring `NaN` values.
```

2024-12-31 08:34 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsmeanwd/README.md
> +Calculate the mean value of a single-precision floating-point strided array, ignoring `NaN` values.
@Neerajpathak07 Also, this description is incorrect. Copy-paste error.

2024-12-31 08:34 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsmeanwd/README.md
> +float v = stdlib_strided_dsmeanwd( 4, x, 2 );
```suggestion
double v = stdlib_strided_dsmeanwd( 4, x, 2 );
```

2024-12-31 08:35 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsmeanwd/README.md
> +Computes the mean value of a single-precision floating-point strided array, ignoring `NaN` values and using alternative indexing semantics.
This isn't the correct description.

2024-12-31 08:35 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsmeanwd/README.md
> +float v = stdlib_strided_dsmeanwd_ndarray( 4, x, 2, 0 );
```suggestion
double v = stdlib_strided_dsmeanwd_ndarray( 4, x, 2, 0 );
```

2024-12-31 08:35 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsmeanwd/README.md
> +    float v = stdlib_strided_dsmeanwd( N, x, strideX );
```suggestion
    double v = stdlib_strided_dsmeanwd( N, x, strideX );
```

2024-12-31 08:36 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsmeanwd/benchmark/c/benchmark.length.c
> +	float v;
This change is incorrect. The function returns an extended precision result.

2024-12-31 08:36 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsmeanwd/benchmark/c/benchmark.length.c
> +	v = 0.0f;
Incorrect.

2024-12-31 08:37 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsmeanwd/benchmark/c/benchmark.length.c
> +	float v;
```suggestion
	double v;
```

2024-12-31 08:37 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsmeanwd/benchmark/c/benchmark.length.c
> +	v = 0.0f;
```suggestion
	v = 0.0;
```

2024-12-31 08:38 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsmeanwd/docs/repl.txt
> +    NaN
This result does not look correct. The reason is the first argument should be `2`, not `4`.

2024-12-31 08:38 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsmeanwd/docs/repl.txt
> +    NaN
Incorrect. Consider what the original example was doing.

2024-12-31 08:38 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsmeanwd/docs/repl.txt
> +    > {{alias}}( 4, x1, 2 )
Incorrect.
```suggestion
    > {{alias}}( 2, x1, 2 )
```

2024-12-31 08:39 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsmeanwd/docs/repl.txt
> +    NaN
Incorrect. Pause to consider whether returning `NaN` when we originally returned `0.33` makes sense?

2024-12-31 08:39 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsmeanwd/examples/c/example.c
> +	float v = stdlib_strided_dsmeanwd( N, x, strideX );
```suggestion
	double v = stdlib_strided_dsmeanwd( N, x, strideX );
```

Incorrect.

2024-12-31 08:40 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsmeanwd/include/stdlib/stats/base/dsmeanwd.h
> +* Computes the mean absolute value of a single-precision floating-point strided array, ignoring `NaN` values and using alternative indexing semantics .
This description is incorrect.

2024-12-31 08:42 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsmeanwd/manifest.json
> +        "@stdlib/math/base/assert/is-positive-zero"
Why are these dependencies included? They are not used.

2024-12-31 08:43 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsmeanwd/src/main.c
>  * @return        output value
You need to realign the descriptions.

2024-12-31 08:44 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsmeanwd/src/main.c
> +* Computes the arithmetic mean of a single-precision floating-point strided array, ignoring `NaN` values and using alternative indexing semantics.
The description should be similar to the description above.

2024-12-31 08:44 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsmeanwd/src/main.c
>  	}
This is incorrect.

2024-12-31 08:45 UTC, kgryte requested changes
Left several comments. This PR needs clean-up before it can move forward.

2024-12-31 17:56 UTC, Neerajpathak07 commented
@kgryte Made all the suggested changes and a few more in this PR and the following PR's:- #4330 , #4317, #4331 & #4338.
And I am also working on fixing the issues for `dsnanmean` and related packages.

2025-01-03 09:39 UTC, Neerajpathak07 commented
@kgryte I have made the essential changes to all the PR's related to the similar packages. Do let me know for changes is any!

2025-01-18 11:53 UTC, kgryte commented
@aayush0325 Would you mind taking a look at this PR?

2025-01-18 12:34 UTC, aayush0325 requested changes
looking good, only a few minor comments. thanks!!

2025-01-18 12:34 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/dsmeanwd/README.md
> +-   **strideX**: stride Length for `x`.
```suggestion
-   **strideX**: stride length for `x`.
```

2025-01-18 12:34 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/dsmeanwd/README.md
> +Computes the arithmetic mean of a single-precision floating-point strided array `x` using Welford's algorithm with extended accumulation and returning an extended precision result.
```suggestion
Computes the arithmetic mean of a single-precision floating-point strided array using Welford's algorithm with extended accumulation and returning an extended precision result.
```

2025-01-18 12:34 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/dsmeanwd/README.md
> +Computes the arithmetic mean of a single-precision floating-point strided array `x` using Welford's algorithm with extended accumulation and returning an extended precision result.
we could do either that or show ``X`` (not `x`) there to match the headings, just suggesting what we've been doing in other packages.

2025-01-18 12:34 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/dsmeanwd/README.md
> +Computes the arithmetic mean of a single-precision floating-point strided array `x` using Welford's algorithm with extended accumulation and alternative indexing semantics and returning an extended p
```suggestion
Computes the arithmetic mean of a single-precision floating-point strided array using Welford's algorithm with extended accumulation and alternative indexing semantics and returning an extended precision result.
```

2025-01-18 12:34 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/dsmeanwd/src/addon.c
> +	STDLIB_NAPI_CREATE_DOUBLE( env, stdlib_strided_dsmeanwd( N, X, strideX ), v );
```suggestion
	STDLIB_NAPI_CREATE_DOUBLE( env, API_SUFFIX(stdlib_strided_dsmeanwd)( N, X, strideX ), v );
```
all function calls where `CBLAS_INT` is a parameter should be wrapped in `API_SUFFIX`

2025-01-18 12:34 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/dsmeanwd/src/addon.c
> +	STDLIB_NAPI_CREATE_DOUBLE( env, stdlib_strided_dsmeanwd_ndarray( N, X, strideX, offsetX ), v );
```suggestion
	STDLIB_NAPI_CREATE_DOUBLE( env, API_SUFFIX(stdlib_strided_dsmeanwd_ndarray)( N, X, strideX, offsetX ), v );
```

2025-01-18 12:34 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/dsmeanwd/src/main.c
> +* Copyright (c) 2025 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```
git isn't counting this as a new file like it does in some of the other PRs so no need to update the copyright year here

2025-01-18 12:46 UTC, Neerajpathak07 commented
@aayush0325 
I have addressed the changes I'll try and make the necessary changes to other PR's related to this as well.

2025-01-18 13:37 UTC, Neerajpathak07 commented
Throws this error for some PR's :-
![image](https://github.com/user-attachments/assets/a825c324-80ab-44b1-a675-9dfa6b95b7f8)
so for those I have kept it 2025

2025-01-18 13:49 UTC, Neerajpathak07 commented
Made the necessary changes through out other PR's as well!

2025-01-18 15:03 UTC, aayush0325 commented
> Throws this error for some PR's :- ![image](https://private-user-images.githubusercontent.com/171167348/404537628-a825c324-80ab-44b1-a675-9dfa6b95b7f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcyMTI4OTUsIm5iZiI6MTczNzIxMjU5NSwicGF0aCI6Ii8xNzExNjczNDgvNDA0NTM3NjI4LWE4MjVjMzI0LTgwYWItNDRiMS1hNjc1LTlkZmE2Yjk1YjdmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExOFQxNTAzMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kY2Y3M2NiNWE4NzQ3Mzg4MTljYTgyZjdiZDNkOGRkZGQxNWIyMjliODczN2VjNmFkNzNjM2IwZmE3NmNiZmIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.iJuRmZr7m0GSTOREBzQ5SuLlnyCeekAfiyrtPeOnImc) so for those I have kept it 2025

yes that's okay!

2025-01-18 15:07 UTC, aayush0325 requested changes
left some very minor comments, once resolved this will be good to go

2025-01-18 15:07 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/dsmeanwd/src/addon.c
> +#include <node_api.h>
kindly also include `stdlib/blas/base/shared.h` explicitly since `API_SUFFIX` is being used.

2025-01-18 15:07 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/dsmeanwd/src/addon.c
> +	STDLIB_NAPI_CREATE_DOUBLE( env, API_SUFFIX( stdlib_strided_dsmeanwd_ndarray )( N, X, strideX, offsetX ), v );
```suggestion
	STDLIB_NAPI_CREATE_DOUBLE( env, API_SUFFIX(stdlib_strided_dsmeanwd_ndarray)( N, X, strideX, offsetX ), v );
```
no need to add spacing here, just a matter of convention

2025-01-18 15:07 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/dsmeanwd/src/addon.c
> +	STDLIB_NAPI_CREATE_DOUBLE( env, API_SUFFIX( stdlib_strided_dsmeanwd_ndarray )( N, X, strideX, offsetX ), v );
kindly check for this everywhere else please

2025-01-18 16:44 UTC, Neerajpathak07 commented on lib/node_modules/@stdlib/stats/base/dsmeanwd/src/addon.c
> +	STDLIB_NAPI_CREATE_DOUBLE( env, API_SUFFIX( stdlib_strided_dsmeanwd_ndarray )( N, X, strideX, offsetX ), v );
I'll make sure of it.

2025-01-18 21:44 UTC, kgryte approved these changes
LGTM

2025-01-18 21:45 UTC, merged