feat: add C ndarray interface and refactor implementation for `stats/base/svariancewd`
stdlib-js/stdlib pull request #4370
Opened 2024-12-30 06:29 UTC by MeastroZI

Resolves None

## Description

> What is the purpose of this pull request?

This pull request:

-   {{TODO: add description describing what this pull request does}}

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves None

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-12-30 06:37 UTC, MeastroZI commented on lib/node_modules/@stdlib/stats/base/svariancewd/examples/c/example.c
> +	float x[] = { 1.0f, 2.0f, 3.0f, 4.0f, 5.0f, 6.0f, 7.0f, 8.0f };
```suggestion
	const float x[] = { 1.0f, 2.0f, 3.0f, 4.0f, 5.0f, 6.0f, 7.0f, 8.0f };
```

2024-12-30 06:46 UTC, MeastroZI commented on lib/node_modules/@stdlib/stats/base/svariancewd/README.md
> +The `N` and stride parameters determine which elements in `x` are accessed at runtime. For example, to compute the [variance][variance] of every other element in `x`,
```suggestion
The `N` and `stride` parameters determine which elements in `x` are accessed at runtime. For example, to compute the [variance][variance] of every other element in `x`,
```

2024-12-30 06:46 UTC, MeastroZI commented on lib/node_modules/@stdlib/stats/base/svariancewd/README.md
> +While [`typed array`][mdn-typed-array] views mandate a view offset based on the underlying `buffer`, the offset parameter supports indexing semantics based on a starting index. For example, to calcul
```suggestion
While [`typed array`][mdn-typed-array] views mandate a view offset based on the underlying buffer, the offset parameter supports indexing semantics based on a starting index. For example, to calculate the [variance][variance] for every other element in `x` starting from the second element
```

2024-12-30 06:46 UTC, MeastroZI commented on lib/node_modules/@stdlib/stats/base/svariancewd/README.md
> +-   **strideX**: `[in] CBLAS_INT` stride length for `X`.
```suggestion
-   **N**: `[in] CBLAS_INT` number of indexed elements.
-   **correction**: `[in] FLOAT` degrees of freedom adjustment. Setting this parameter to a value other than `0` has the effect of adjusting the divisor during the calculation of the [variance][variance] according to `N-c` where `c` corresponds to the provided degrees of freedom adjustment. When computing the [variance][variance] of a population, setting this parameter to `0` is the standard choice (i.e., the provided array contains data constituting an entire population). When computing the unbiased sample [variance][variance], setting this parameter to `1` is the standard choice (i.e., the provided array contains data sampled from a larger population; this is commonly referred to as Bessel's correction).
-   **X**: `[in] float*` input array.
-   **strideX**: `[in] CBLAS_INT` stride length for `X`.
```

2024-12-31 12:06 UTC, MeastroZI commented
/stdlib update-copyright-years

2025-01-03 07:07 UTC, aayush0325 requested changes
left an initial round of comments

2025-01-03 07:07 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svariancewd/README.md
>  The `N` and `stride` parameters determine which elements in `x` are accessed at runtime. For example, to compute the [variance][variance] of every other element in `x`,
```suggestion
The `N` and stride parameters determine which elements in the strided array are accessed at runtime. For example, to compute the [variance][variance] of every other element in `x`,
```

2025-01-03 07:07 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svariancewd/README.md
>  var floor = require( '@stdlib/math/base/special/floor' );
```suggestion

```

2025-01-03 07:07 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svariancewd/README.md
>  var floor = require( '@stdlib/math/base/special/floor' );
we don't need this import anymore

2025-01-03 07:07 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svariancewd/README.md
> +The `N` and stride parameters determine which elements in `x` are accessed at runtime. For example, to compute the [variance][variance] of every other element in `x`,
```suggestion
```

2025-01-03 07:07 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svariancewd/README.md
> +The `N` and stride parameters determine which elements in `x` are accessed at runtime. For example, to compute the [variance][variance] of every other element in `x`,
we don't need this in the C interface documentation

2025-01-03 07:07 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svariancewd/benchmark/benchmark.ndarray.js
> +};
```suggestion
var options = {
	'dtype': 'float32'
};
```
just updating this as a matter of convention

2025-01-03 07:07 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svariancewd/benchmark/benchmark.ndarray.js
> +};
same comment for all other javascript benchmarks

2025-01-03 07:07 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svariancewd/examples/index.js
> +x = discreteUniform( 10, -50, 50, {
```suggestion
var x = discreteUniform( 10, -50, 50, {
```

2025-01-03 07:07 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svariancewd/examples/index.js
> +x = discreteUniform( 10, -50, 50, {
we can declare and assign here

2025-01-03 07:07 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svariancewd/include/stdlib/stats/base/svariancewd.h
> +* Computes the variance of a single-precision floating-point strided array using Welford's algorithm and using alternative indexing semantics..
```suggestion
* Computes the variance of a single-precision floating-point strided array using Welford's algorithm and using alternative indexing semantics.
```

2025-01-03 07:07 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svariancewd/src/main.c
>  	float delta;
this implementation is not what we are looking for, see #4240, notice how in main.c we're getting the offset according to `N` and `strideX` using `stdlib/strided/base/stride2offset` and then making a call to the ndarray interface, you'll need to include `stdlib/strided/base/stride2offset.h` and hence add it in manifest.json too

2025-01-03 07:07 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svariancewd/src/addon.c
> +float API_SUFFIX(stdlib_strided_svariancewd)( const CBLAS_INT N, const float correction, const float *X, const CBLAS_INT strideX );
```suggestion
```
we don't need this here

2025-01-03 07:07 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svariancewd/src/main.c
>  #include <stdint.h>
```suggestion
```

we dont need to include this header anymore as `int64_t` is not being used

2025-01-03 07:07 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svariancewd/manifest.json
> +      ],
```suggestion
      "libraries": [],
```
we don't need this anymore, same for all other instances in this file

2025-01-03 07:07 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svariancewd/lib/ndarray.native.js
>  * var floor = require( '@stdlib/math/base/special/floor' );
```suggestion
```
we don't need to import this module anymore

2025-01-03 07:07 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svariancewd/lib/ndarray.js
>  * var floor = require( '@stdlib/math/base/special/floor' );
```suggestion
```
we don't need to import this module anymore

2025-01-03 07:07 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svariancewd/lib/index.js
>  *
we don't need to import `floor` here

2025-01-03 07:09 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svariancewd/src/main.c
>  	float delta;
the function should look like 

```c
const CBLAS_INT ox = stdlib_base_stride2offset( N, strideX );
return API_SUFFIX(stdlib_strided_svariancewd_ndarray)( N, correction, X, strideX, ox ); 
```

2025-01-03 07:26 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svariancewd/lib/svariancewd.js
please refer to an existing implementation to get an idea of what we're looking for here! similar to C implementation we need to use `stride2offset` here

2025-01-03 07:28 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svariancewd/lib/svariancewd.js
your function should look like 
```javascript
return ndarray( N, x, strideX, stride2offset( N, strideX );
```
and you need to import ndarray and stride2offset by
```javascript
var stride2offset = require( '@stdlib/strided/base/stride2offset' );
var ndarray = require( './ndarray.js' );
```

2025-01-03 07:31 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svariancewd/lib/svariancewd.js
you can refer to [this](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/stats/base/dmin/lib/dmin.js)

2025-01-03 07:58 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svariancewd/src/main.c
> +* Computes the variance of a single-precision floating-point strided array using Welford's algorithm.
```suggestion
* Computes the variance of a single-precision floating-point strided array using Welford's algorithm using alternative indexing semantics.
```

2025-01-03 08:43 UTC, MeastroZI commented
Thank You @aayush0325 for your review ,  one more question is where i can find all the latest convention of project , means is it is written somewhere ?  or just have to look other updated pacakges to get idea of all this updates we are making ?

2025-01-03 08:45 UTC, aayush0325 commented
@MeastroZI check stats/base/dmax!

2025-01-03 09:42 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svariancewd/docs/repl.txt
>          Index increment.
```suggestion
        Stride Length.
```
same for all other instances in this file

2025-01-04 06:46 UTC, MeastroZI commented on lib/node_modules/@stdlib/stats/base/svariancewd/examples/index.js
>  var x;
```suggestion
```

2025-01-04 07:00 UTC, MeastroZI commented on lib/node_modules/@stdlib/stats/base/svariancewd/examples/index.js
```suggestion
```

2025-01-04 16:06 UTC, aayush0325 requested changes
minor changes needed, this PR will be in good shape once these are implemented!

2025-01-04 16:06 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svariancewd/README.md
> +x = discreteUniform( 10, -50, 50 );
please set the datatype to be float32 explicitly

2025-01-04 16:06 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svariancewd/benchmark/benchmark.native.js
> +	x = uniform( len, -10, 10, options);
```suggestion
	var x = uniform( len, -10, 10, options);
```
we can simply declare and assign here, same comment for all other javascript benchmark files

2025-01-04 16:07 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svariancewd/README.md
> +x = discreteUniform( 10, -50, 50 );
this example should match `examples/index.js`

2025-01-04 16:27 UTC, MeastroZI commented on lib/node_modules/@stdlib/stats/base/svariancewd/README.md
> +x = discreteUniform( 10, -50, 50 );
```suggestion
x = discreteUniform( 10, -50, 50, {
	'dtype': 'float32'
});
```

2025-01-04 16:29 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svariancewd/README.md
> +x = discreteUniform( 10, -50, 50 );
can you please do something like 
```javascript
var x = discreteUniform( 10, -50, 50, {
	'dtype': 'float32'
});
```
i.e. declare and assign at the same time

2025-01-04 16:31 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svariancewd/README.md
> +x = discreteUniform( 10, -50, 50 );
in cases where the calculation is **not complex** we can declare and assign
```javascript
var x = someFunction();
```

is better than

```javascript
var x;

x = someFunction();
```

2025-01-04 16:33 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svariancewd/benchmark/benchmark.native.js
> +	x = uniform( len, -10, 10, options);
```suggestion
	var x = uniform( len, -10, 10, options );
```
spacing is also off here, please check for this in other JavaScript benchmarks too!

2025-01-04 18:12 UTC, aayush0325 approved these changes
lgtm

2025-01-06 09:10 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/svariancewd/README.md
> +Computes the [variance][variance] of a single-precision floating-point strided array `x` using Welford's algorithm.
```suggestion
Computes the [variance][variance] of a single-precision floating-point strided array using Welford's algorithm.
```

2025-01-06 09:10 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/svariancewd/README.md
> +-   **correction**: `[in] FLOAT` degrees of freedom adjustment. Setting this parameter to a value other than `0` has the effect of adjusting the divisor during the calculation of the [variance][varia
```suggestion
-   **correction**: `[in] float` degrees of freedom adjustment. Setting this parameter to a value other than `0` has the effect of adjusting the divisor during the calculation of the [variance][variance] according to `N-c` where `c` corresponds to the provided degrees of freedom adjustment. When computing the [variance][variance] of a population, setting this parameter to `0` is the standard choice (i.e., the provided array contains data constituting an entire population). When computing the unbiased sample [variance][variance], setting this parameter to `1` is the standard choice (i.e., the provided array contains data sampled from a larger population; this is commonly referred to as Bessel's correction).
```

2025-01-06 09:13 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/svariancewd/docs/repl.txt
> +    The `N` and stride parameters determine which elements in x are accessed
```suggestion
    The `N` and stride parameters determine which elements in the strided array are accessed
```

You will likely need to rewrap the lines. The point of removing references to `x` to avoid copy-paste errors in future packages.

2025-01-06 09:14 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/svariancewd/include/stdlib/stats/base/svariancewd.h
> +* Computes the variance of a single-precision floating-point strided array using Welford's algorithm and using alternative indexing semantics.
```suggestion
* Computes the variance of a single-precision floating-point strided array using Welford's algorithm and alternative indexing semantics.
```

2025-01-06 09:15 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/svariancewd/src/main.c
> +
```suggestion
```

2025-01-06 09:16 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/svariancewd/src/main.c
> +* Computes the variance of a single-precision floating-point strided array using Welford's algorithm using alternative indexing semantics.
```suggestion
* Computes the variance of a single-precision floating-point strided array using Welford's algorithm and alternative indexing semantics.
```

2025-01-06 09:18 UTC, kgryte requested changes
Apart from reflowing the text in the REPL text file, this is looking good to me.

2025-01-06 09:20 UTC, kgryte commented
/stdlib merge

2025-02-01 12:57 UTC, aayush0325 approved these changes
LGTM

2025-06-08 09:05 UTC, kgryte approved these changes

2025-06-08 09:06 UTC, merged