feat: add C ndarray interface and refactor implementation for `stats/base/dmskmin`
stdlib-js/stdlib pull request #4371
Opened 2024-12-30 06:33 UTC by aayush0325

Resolves None

## Description

> What is the purpose of this pull request?

This pull request:

-   adds C ndarray interface for `stats/base/dmskmin`
-   refactors JavaScript implementation 
-   updates tests, docs, examples and benchmarks

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves None

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-12-30 06:38 UTC, aayush0325 commented
same comment regarding max line length exceeding in `lib/ndarray.native.js` @ reviewer

2025-01-01 03:35 UTC, aayush0325 commented
/stdlib update-copyright-years

2025-01-01 03:58 UTC, aayush0325 commented
js benchmarks to be updated here

2025-01-02 08:03 UTC, aayush0325 commented
this one's ready for review @Planeshifter!

2025-01-02 10:01 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dmskmin/lib/ndarray.native.js
>  *
@aayush0325 You need to remove the `floor` import at L43.

2025-01-02 10:02 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dmskmin/src/addon.c
> +    STDLIB_NAPI_ARGV_INT64( env, strideMask, argv, 5 );
@aayush0325 Mixed tab and space indentation here and L59.

2025-01-02 10:04 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dmskmin/test/test.ndarray.native.js
> +	v = dmskmin( -1, x, 1, 0, mask, 1, 0 );
Thanks for catching this!

2025-01-02 10:04 UTC, kgryte requested changes
This is looking good apart from two minor nits.

2025-01-02 12:08 UTC, aayush0325 commented
pushed a fix, thanks @kgryte!

2025-01-02 18:03 UTC, kgryte approved these changes
LGTM

2025-01-02 18:04 UTC, merged