feat: add C ndarray interface and refactor implementation for `stats/base/svarianceyc`
stdlib-js/stdlib pull request #4372
Opened 2024-12-30 06:40 UTC by MeastroZI

Resolves None

## Description

> What is the purpose of this pull request?

This pull request:

-   add C ndarray interface and refactor implementation for `stats/base/svarianceyc`

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves None

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-12-31 12:06 UTC, MeastroZI commented
/stdlib update-copyright-years

2025-01-04 18:18 UTC, MeastroZI commented on lib/node_modules/@stdlib/stats/base/svarianceyc/docs/repl.txt
> +
```suggestion
```

2025-01-06 11:47 UTC, MeastroZI commented on lib/node_modules/@stdlib/stats/base/svarianceyc/docs/repl.txt
>      // Using `N` and `stride` parameters:
```suggestion
    // Using `N` and stride parameters:
```

2025-01-06 11:49 UTC, MeastroZI commented on lib/node_modules/@stdlib/stats/base/svarianceyc/lib/index.js
> +* var v = svarianceyc.ndarray( x.length, 1, x, 2, 1 );
```suggestion
* var v = svarianceyc.ndarray( 4, 1, x, 2, 1 );
```

2025-01-06 16:23 UTC, aayush0325 requested changes
left a round of comments

2025-01-06 16:23 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svarianceyc/benchmark/benchmark.js
> +	x = uniform( len, -10, 10, options );
```suggestion
	var x = uniform( len, -10, 10, options );
```

2025-01-06 16:23 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svarianceyc/benchmark/benchmark.js
> +	x = uniform( len, -10, 10, options );
same comment for all other JavaScript benchmark files

2025-01-06 16:23 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svarianceyc/examples/index.js
> +});
```suggestion
var x = discreteUniform( 10, -50, 50, {
	'dtype': 'float32'
});
```
kindly make this change in the `README.md` examples too if applicable

2025-01-06 16:23 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svarianceyc/include/stdlib/stats/base/svarianceyc.h
> +* Computes the variance of a single-precision floating-point strided array using a one-pass algorithm proposed by Youngs and Cramer, using alternative indexing semantics.
```suggestion
* Computes the variance of a single-precision floating-point strided array using a one-pass algorithm proposed by Youngs and Cramer and alternative indexing semantics.
```

this is the convention that we're following across the `stats/base` namespace for now

2025-01-06 16:23 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svarianceyc/src/main.c
> +* Computes the variance of a single-precision floating-point strided array using a one-pass algorithm proposed by Youngs and Cramer, using alternative indexing semantics.
```suggestion
* Computes the variance of a single-precision floating-point strided array using a one-pass algorithm proposed by Youngs and Cramer and alternative indexing semantics
```

2025-01-06 16:23 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svarianceyc/src/main.c
>  		S += (float)(1.0/(di*(di-1.0))) * d * d;
indentation is off

2025-01-06 16:25 UTC, aayush0325 requested changes

2025-01-06 16:25 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svarianceyc/src/main.c
> +        return 0.0f / 0.0f; // Nan
```suggestion
        return 0.0f / 0.0f; // NaN
```

2025-01-06 16:29 UTC, MeastroZI commented on lib/node_modules/@stdlib/stats/base/svarianceyc/src/main.c
>  		S += (float)(1.0/(di*(di-1.0))) * d * d;
```suggestion
		d = (float)( di * (double) v ) - sum;
		S += (float)( 1.0 / ( di * ( di-1.0 ) ) ) * d * d;
```

2025-01-06 16:29 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svarianceyc/benchmark/benchmark.js
> +	x = uniform( len, -10, 10, options );
it is better to declare and assign at the same time when the calculation is **not complex** i.e.
```javascript
var x = someFunction(); // this is better
```
we prefer this over
```javascript
var x;

x = someFunction(); // this is also okay but not preferred
```

2025-01-06 16:29 UTC, MeastroZI commented on lib/node_modules/@stdlib/stats/base/svarianceyc/benchmark/benchmark.js
>  	var x;
```suggestion
```

2025-01-06 16:30 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svarianceyc/src/main.c
>  		S += (float)(1.0/(di*(di-1.0))) * d * d;
we don't need this change here

2025-01-06 16:30 UTC, MeastroZI commented on lib/node_modules/@stdlib/stats/base/svarianceyc/benchmark/benchmark.js
```suggestion
```

2025-01-06 16:32 UTC, MeastroZI commented on lib/node_modules/@stdlib/stats/base/svarianceyc/examples/index.js
>  var x;
```suggestion
```

2025-01-06 16:55 UTC, aayush0325 requested changes

2025-01-06 16:55 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svarianceyc/src/main.c
> +		S += (float)( 1.0 / ( di * ( di-1.0 ) ) ) * d * d;
we don't need this change, this can be reverted back
```suggestion
		d = (float)(di*(double)v) - sum;
		S += (float)(1.0/(di*(di-1.0))) * d * d;
```

2025-01-06 18:07 UTC, aayush0325 requested changes

2025-01-06 18:07 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/svarianceyc/README.md
> +Computes the [variance][variance] of a single-precision floating-point strided array using a one-pass algorithm proposed by Youngs and Cramer and using alternative indexing semantics.
```suggestion
Computes the [variance][variance] of a single-precision floating-point strided array using a one-pass algorithm proposed by Youngs and Cramer and alternative indexing semantics.
```

2025-01-06 18:10 UTC, aayush0325 approved these changes
lgtm

2025-01-15 17:47 UTC, MeastroZI commented on lib/node_modules/@stdlib/stats/base/svarianceyc/docs/repl.txt
>      --------
```suggestion
    --------
    
```

2025-01-15 17:59 UTC, Vinit-Pandit commented on lib/node_modules/@stdlib/stats/base/svarianceyc/docs/repl.txt
> +
```suggestion

```

2025-01-17 23:02 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/svarianceyc/README.md
> +Computes the [variance][variance] of a single-precision floating-point strided array `x` using a one-pass algorithm proposed by Youngs and Cramer.
```suggestion
Computes the [variance][variance] of a single-precision floating-point strided array using a one-pass algorithm proposed by Youngs and Cramer.
```

2025-01-17 23:06 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/svarianceyc/src/addon.c
> +	STDLIB_NAPI_CREATE_DOUBLE( env, (double)stdlib_strided_svarianceyc_ndarray( N, correction, X, strideX, offesetX ), v );
```suggestion
	STDLIB_NAPI_ARGV_INT64( env, offsetX, argv, 4 );
	STDLIB_NAPI_CREATE_DOUBLE( env, (double)stdlib_strided_svarianceyc_ndarray( N, correction, X, strideX, offsetX ), v );
```

2025-01-17 23:06 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/svarianceyc/src/addon.c
> +STDLIB_NAPI_MODULE_EXPORT_FCN_WITH_METHOD( addon, "ndarray", addon_method )
```suggestion

STDLIB_NAPI_MODULE_EXPORT_FCN_WITH_METHOD( addon, "ndarray", addon_method )
```

2025-01-17 23:07 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/svarianceyc/src/main.c
> +    if ( N ==1 || strideX == 0 ) {
```suggestion
    if ( N == 1 || strideX == 0 ) {
```

2025-01-17 23:09 UTC, kgryte approved these changes
LGTM after minor clean-up.

2025-01-17 23:25 UTC, merged