feat: add C `ndarray` interface and refactor implementation for `stats/base/dsnanmean`
stdlib-js/stdlib pull request #4395
Opened 2024-12-30 19:12 UTC by Neerajpathak07

Resolves none.

## Description

> What is the purpose of this pull request?

This pull request:

-  adds C `ndarray` interface for `stats/base/dsnanmean`
-   refactor JavaScript implementation
-   refactor examples, tests, docs and benchmarks.

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves none

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-  [x] Read, understood, and followed the [contributing guidelines](https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md)

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-12-31 08:53 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsnanmean/README.md
> +Calculate the Arithmetic Mean value of a double-precision floating-point strided array, ignoring `NaN` values.
This description should more closely match that of the JS APIs above.

2024-12-31 08:53 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsnanmean/README.md
> +Computes the Arithmetic Mean value of a double-precision floating-point strided array, ignoring `NaN` values and using alternative indexing semantics.
Same comment. I am also not sure why "arithmetic mean" is capitalized.

2024-12-31 08:54 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsnanmean/README.md
> +Computes the Arithmetic Mean value of a double-precision floating-point strided array, ignoring `NaN` values and using alternative indexing semantics.
The description is also incorrect. `X` is not double-precision, but single-precision.

2024-12-31 08:54 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsnanmean/README.md
> +    const float x[] = { 1.0f, 2.0f, 0.0f/0.0f, 3.0f, 0.0f/0.0f, 4.0f, 5.0f, 6.0f,   0.0f/0.0f, 7.0f, 8.0f, 0.0f/0.0f };
```suggestion
    const float x[] = { 1.0f, 2.0f, 0.0f/0.0f, 3.0f, 0.0f/0.0f, 4.0f, 5.0f, 6.0f, 0.0f/0.0f, 7.0f, 8.0f, 0.0f/0.0f };
```

2024-12-31 08:55 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsnanmean/benchmark/benchmark.js
> +	var x = uniform( len, -10.0, 10.0, options );
This doesn't match the original random value generation. Need to use `filledarrayBy` and a custom random function.

2024-12-31 08:56 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsnanmean/benchmark/benchmark.ndarray.js
> +	var x = uniform( len, -10.0, 10.0, options );
Same comment.

2024-12-31 08:56 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsnanmean/benchmark/benchmark.ndarray.native.js
> +	var x = uniform( len, -10.0, 10.0, options );
Same comment.

2024-12-31 08:56 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsnanmean/benchmark/c/benchmark.length.c
> +	float v;
This is incorrect.

2024-12-31 08:56 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsnanmean/benchmark/c/benchmark.length.c
> +	v = 0.0f;
Incorrect.

2024-12-31 08:56 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsnanmean/benchmark/c/benchmark.length.c
> +	float v;
Incorrect.

2024-12-31 08:56 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsnanmean/benchmark/c/benchmark.length.c
> +	v = 0.0f;
```suggestion
	v = 0.0;
```

2024-12-31 08:57 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsnanmean/docs/repl.txt
> +        Stride Length.
```suggestion
        Stride length.
```

2024-12-31 08:57 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsnanmean/docs/repl.txt
> +    NaN
Incorrect.

2024-12-31 08:57 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsnanmean/docs/repl.txt
> +    NaN
Incorrect.

2024-12-31 08:57 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsnanmean/docs/repl.txt
> +        Stride Length.
```suggestion
        Stride length.
```

2024-12-31 08:57 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsnanmean/docs/repl.txt
> +    NaN
Incorrect.

2024-12-31 08:58 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsnanmean/examples/index.js
> +var x = discreteUniform( 10, -50, 50, {
This doesn't match the original random value generation logic.

2024-12-31 08:59 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsnanmean/include/stdlib/stats/base/dsnanmean.h
> +* Computes the mean absolute value of a double-precision floating-point strided array, ignoring `NaN` values and using alternative indexing semantics .
Doesn't agree with description above.

2024-12-31 08:59 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsnanmean/include/stdlib/stats/base/dsnanmean.h
> +* Computes the mean absolute value of a double-precision floating-point strided array, ignoring `NaN` values and using alternative indexing semantics .
The description is also wrong.

2024-12-31 09:00 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsnanmean/lib/index.js
> +* var v = dsnanmean.ndarray( 5, x, 2, 1 );
This isn't correct. What was the computed value of `N` previously?

2024-12-31 09:01 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsnanmean/lib/ndarray.js
> -* // returns 1.25
Why was this removed? Don't remove inconvenient code (e.g., if lint errors are happening, fix the lint errors; don't just delete it).

2024-12-31 09:01 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsnanmean/lib/ndarray.native.js
> -* // returns 1.25
Again. Why was this deleted?

2024-12-31 09:02 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsnanmean/manifest.json
> +        "@stdlib/math/base/assert/is-positive-zero",
TMK, neither of these dependencies are used. Please don't just blindly copy-paste things from other packages. Think about what you are doing and whether something is applicable to the specific logic/implementation at hand.

2024-12-31 09:03 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsnanmean/src/main.c
> +* Computes the maximum value of a double-precision floating-point strided array, ignoring `NaN` values and using alternative indexing semantics.
How does this description make sense?

2024-12-31 09:04 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsnanmean/test/test.ndarray.js
> -tape( 'the function supports a negative `stride` parameter', function test( t ) {
Why was this test removed?

2024-12-31 09:05 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsnanmean/test/test.ndarray.native.js
> -tape( 'the function supports a negative `stride` parameter', opts, function test( t ) {
Why was this test removed?

2024-12-31 09:05 UTC, kgryte requested changes
Left comments. Please do a very thorough review of all your open PRs implementing similar changes. They are currently inundated with copy-paste mistakes.

2024-12-31 11:26 UTC, Neerajpathak07 commented
@kgryte Thank you for you review. Extremely sorry for the errors. I'll fix these mistakes for other PR's as well.

2025-01-02 20:50 UTC, Neerajpathak07 commented
@kgryte 
I have made all the essential changes to all the packages requiring similar implementations.
This time I was able to understand what the package was demanding for and how to go about it.

2025-01-04 08:13 UTC, Neerajpathak07 commented
@kgryte I'm awaiting the PR with `dsnanmeanpn` to be merged then I'll be able to reference this implementation.

2025-01-08 18:17 UTC, Neerajpathak07 commented
@kgryte I have made the suggested changes throughout all my other PR's would really appreciate a review

2025-01-08 18:17 UTC, Neerajpathak07 commented on lib/node_modules/@stdlib/stats/base/dsnanmean/src/main.c
> +	return stdlib_strided_dsnanmeanpn_ndarray( N, X, strideX, offsetX );
@kgryte I'm awaiting the PR with dsnanmeanpn to be merged then I'll be able to reference this implementation.

2025-02-10 14:54 UTC, Neerajpathak07 commented on lib/node_modules/@stdlib/stats/base/dsnanmean/src/main.c
> +	return stdlib_strided_dsnanmeanpn_ndarray( N, X, strideX, offsetX );
PR with `dsnanmeanpn` has been merged! #4405

2025-02-13 15:36 UTC, aayush0325 requested changes

2025-02-13 15:36 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/dsnanmean/README.md
readme structure is incorrect

2025-02-13 15:36 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/dsnanmean/docs/repl.txt
> +    > {{alias}}( 4, x1,2 )
spacing
```suggestion
    > {{alias}}( 4, x1, 2 )
```

2025-02-13 15:36 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/dsnanmean/include/stdlib/stats/base/dsnanmean.h
> +* Copyright (c) 2025 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2025-02-13 15:36 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/dsnanmean/src/main.c
> +	return stdlib_strided_dsnanmeanpn_ndarray( N, X, strideX, offsetX );
wrap in `API_SUFFIX`

2025-02-13 15:46 UTC, aayush0325 submitted a review, later dismissed
this should be clear of any errors now

2025-02-23 04:47 UTC, Neerajpathak07 commented
@kgryte could we land this in.

2025-03-12 06:58 UTC, Neerajpathak07 commented
@kgryte pls take a look at this as well!!

2025-03-12 09:22 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsnanmean/README.md
> +    printf( "mean: %f\n", v );
```suggestion
    printf( "mean: %lf\n", v );
```

`v` is a double.

2025-03-12 09:27 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsnanmean/manifest.json
> +      "task": "",
```suggestion
      "task": "build",
```

2025-03-12 09:28 UTC, kgryte approved these changes
LGTM

2025-03-12 09:37 UTC, merged