feat: add `math/base/special/bessely1`
stdlib-js/stdlib pull request #4396
Opened 2024-12-30 19:57 UTC by ShabiShett07

Resolves #{{TODO: add issue number}}.

## Description

> What is the purpose of this pull request?

This pull request:

-   Resolves part of #649  https://github.com/stdlib-js/stdlib/issues/649 by adding math/base/special/bessely1
## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #649 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.
Open to reviews!!

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2024-12-31 10:41 UTC, ShabiShett07 commented
Errors have been fixed

2025-01-02 16:14 UTC, ShabiShett07 commented
/stdlib check-files

2025-01-02 16:37 UTC, ShabiShett07 commented
/stdlib update-copyright-years

2025-01-02 16:39 UTC, ShabiShett07 commented
/stdlib lint-autofix

2025-01-03 07:14 UTC, ShabiShett07 commented
I have fixed the errors in package.json

2025-02-22 13:34 UTC, ShabiShett07 commented
@Neerajpathak07, need your assistance in this!

2025-02-22 13:38 UTC, Neerajpathak07 commented on lib/node_modules/@stdlib/math/base/special/bessely1/README.md
> +```
```suggestion
```c
double out = stdlib_base_bessely1( 0.0 );
// returns -Infinity
```
```

2025-02-22 13:38 UTC, Neerajpathak07 commented on lib/node_modules/@stdlib/math/base/special/bessely1/README.md
> -[@stdlib/math/base/special/besselj0]: https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/besselj0
Kindly revert this change

2025-02-22 13:39 UTC, Neerajpathak07 commented on lib/node_modules/@stdlib/math/base/special/bessely1/README.md
> --   <span class="package-name">[`@stdlib/math/base/special/besselj0`][@stdlib/math/base/special/besselj0]</span><span class="delimiter">: </span><span class="description">compute the Bessel function
revert this change in L211.

2025-02-22 13:41 UTC, Neerajpathak07 commented on lib/node_modules/@stdlib/math/base/special/bessely1/README.md
> --   <span class="package-name">[`@stdlib/math/base/special/besselj0`][@stdlib/math/base/special/besselj0]</span><span class="delimiter">: </span><span class="description">compute the Bessel function
## See Also tag should be lined up above this while respecting the one line space between them.

2025-02-22 13:45 UTC, Neerajpathak07 commented on lib/node_modules/@stdlib/math/base/special/bessely1/benchmark/benchmark.native.js
> +};
```suggestion
var y1 = tryRequire( resolve( __dirname, './../lib/native.js' ) );
var opts = {
	'skip': ( y1 instanceof Error )
};
```
According to `benchmark.js`

2025-02-22 13:51 UTC, Neerajpathak07 commented on lib/node_modules/@stdlib/math/base/special/bessely1/benchmark/benchmark.native.js
> +};
Copy paste error from `bessely0`

2025-02-22 14:06 UTC, Neerajpathak07 commented on lib/node_modules/@stdlib/math/base/special/bessely1/benchmark/benchmark.native.js
> +		y = y0( x );
```suggestion
		y = y1( x );
```
since it is of order 1.

2025-02-22 14:07 UTC, Neerajpathak07 commented on lib/node_modules/@stdlib/math/base/special/bessely1/src/main.c
> +* @returns evaluated Bessel function
I believe the C doxygen are incorrect

2025-02-22 14:08 UTC, Neerajpathak07 commented on lib/node_modules/@stdlib/math/base/special/bessely1/src/main.c
> +* @returns evaluated Bessel function
```suggestion
* @param x    input value
* @return     evaluated Bessel function
```

2025-02-22 14:16 UTC, Neerajpathak07 commented
@ShabiShett07 all in all the PR is in great shape few changes and some additional points:-
- Were the rational functions automatically generated upon running the the corresponding JS file if yes then there's no reason to worry.
- Since this PR aimed at adding C implementation for the existing JS implementation change the PR tittle to:-
 feat: add C implementation for `math/base/special/bessely1`

2025-02-22 16:10 UTC, ShabiShett07 commented
Thank you @Neerajpathak07 for recognizing the errors, actually this was a PR made by me in initial stages on Stdlib, surely gonna make all the necessary changes.

2025-02-22 18:47 UTC, ShabiShett07 commented
@Neerajpathak07, made all necessary changes as per your suggestion, is there any other errors I need to fix?

2025-02-23 04:56 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/bessely1/examples/c/example.c
> +#include "stdlib/math/base/special/bessely1.h"
```suggestion
#include "stdlib/math/base/special/bessely1.h"
#include <stdio.h>
```

2025-02-23 04:57 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/bessely1/examples/c/example.c
> +#include "stdlib/math/base/special/bessely1.h"
Let's reorder this so that it matches with the C example in `README.md`.

2025-02-23 05:13 UTC, gunjjoshi requested changes

2025-02-23 05:13 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/bessely1/README.md
> +-   <span class="package-name">[`@stdlib/math/base/special/bessely1`][@stdlib/math/base/special/bessely1]</span><span class="delimiter">: </span><span class="description">compute the Bessel function
You can revert this change. We shouldn't modify the `related` sections manually.

2025-02-23 05:13 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/bessely1/README.md
> +[@stdlib/math/base/special/bessely1]: https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/bessely1
Similarly, you can revert this too.

2025-02-23 05:13 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/bessely1/benchmark/benchmark.native.js
> +var randu = require( '@stdlib/random/base/randu' );
@ShabiShett07 Can you please use [`@stdlib/random/array/uniform`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/random/array/uniform) here?
For reference use, see: https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/acsc/benchmark/benchmark.native.js

2025-02-23 05:13 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/bessely1/benchmark/benchmark.native.js
> +var randu = require( '@stdlib/random/base/randu' );
Would be great if we can reflect this change in `benchmark.js` too.

2025-02-23 05:17 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/bessely1/lib/native.js
> +* ```
```suggestion
```

2025-02-23 05:18 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/bessely1/lib/native.js
> +* ```
As `native.js` doesn't contain any implementation, we can refrain from adding the reference copyright license.

2025-02-23 05:21 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/bessely1/src/main.c
> +#include "stdlib/math/base/special/bessely1.h"
```suggestion
#include "stdlib/math/base/special/bessely1.h"
#include "stdlib/math/base/special/besselj1.h"
```

2025-02-23 05:23 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/bessely1/src/main.c
> +#include "stdlib/math/base/special/bessely1.h"
As this is `bessely1`, let's keep its include path at the top.

2025-02-23 20:20 UTC, gunjjoshi commented
@ShabiShett07 You'll have to update `evalrational.js`, and then run it to generate the rational functions, rather than copying and pasting them in `main.js`. You can refer: https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/bessely0/scripts/evalrational.js

2025-02-23 20:30 UTC, gunjjoshi requested changes

2025-02-23 20:30 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/bessely1/src/main.c
> +*
```suggestion
*
* ## Notes
*
* -   Accuracy for subnormal `x` is very poor. Full accuracy is achieved at `1.0e-308` but trends progressively to zero at `5e-324`. This suggests that underflow (or overflow, perhaps due to a reciprocal) is effectively cutting off digits of precision until the computation loses all accuracy at `5e-324`.
*
```

2025-02-23 20:30 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/bessely1/src/main.c
> +* double v = y1(0.0);
```suggestion
* double v = y1( 0.0 );
```

2025-02-23 20:30 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/bessely1/src/main.c
> +// Main function to compute the Bessel function of the second kind of order one
```suggestion
```
This doesn't seem necessary.

2025-02-23 20:30 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/bessely1/src/main.c
> +double stdlib_base_bessely1(double x) {
```suggestion
double stdlib_base_bessely1( double x ) {
```

2025-02-23 20:30 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/bessely1/src/main.c
> +double stdlib_base_bessely1(double x) {
Missing spaces here and elsewhere in this file.

2025-02-23 20:30 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/bessely1/src/main.c
> +double stdlib_base_bessely1(double x) {
Also, there is a mix of spaces and tabs in this file. Can you please reiterate it once again, @ShabiShett07?

2025-02-23 20:30 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/bessely1/test/test.native.js
> +		t.equal( y, NINF, 'returns -Infinity' );
```suggestion
		t.equal( y, NINF, 'returns expected value' );
```

2025-02-23 20:30 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/bessely1/test/test.native.js
> +		t.equal( isnan( v ), true, 'returns NaN' );
```suggestion
		t.equal( isnan( v ), true, 'returns expected value' );
```

2025-02-23 20:30 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/bessely1/test/test.native.js
> +	t.equal( v, NINF, 'returns -Infinity' );
```suggestion
	t.equal( v, NINF, 'returns expected value' );
```

2025-02-23 20:30 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/bessely1/test/test.native.js
> +	t.equal( isnan( v ), true, 'returns NaN' );
```suggestion
	t.equal( isnan( v ), true, 'returns expected value' );
```

2025-02-23 20:30 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/bessely1/test/test.native.js
> +	t.equal( v, 0.0, 'returns 0.0' );
```suggestion
	t.equal( v, 0.0, 'returns expected value' );
```

2025-02-23 20:30 UTC, gunjjoshi commented on lib/node_modules/@stdlib/math/base/special/bessely1/test/test.native.js
> +	t.equal( isnan( v ), true, 'returns NaN' );
```suggestion
	t.equal( isnan( v ), true, 'returns expected value' );
```

2025-02-28 04:43 UTC, ShabiShett07 commented
Hey, @gunjjoshi sir, Thank you for reviewing and I have tried to solve the errors which you have have pointed out, please do check

2025-03-16 20:23 UTC, Planeshifter commented
<!-- stdlib-bot-tracking-issue-closure-check -->
:warning: **Tracking Issue Closure Warning** :warning:

I noticed your PR description contains closing keywords ("Resolves", "Closes", or "Fixes") referencing a "Tracking Issue".

**Why this matters:**
Tracking issues should typically remain open until all related sub-issues are completed. GitHub automatically closes issues with such closing keywords when the PR is merged.

**Required action:**
Use "Progresses:" or "Ref:" instead to reference the tracking issue without automatically closing it.

Thank you for your contribution to the project!

2025-05-09 03:51 UTC, anandkaranubc commented
/stdlib merge

2025-05-09 05:23 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/bessely1/test/test.native.js
> +tape( 'main export is a function', function test( t ) {
```suggestion
tape( 'main export is a function', opts, function test( t ) {
```

Missing `opts`

2025-05-09 05:24 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/bessely1/test/test.native.js
> +
```suggestion
// VARIABLES //

var y1 = tryRequire( resolve( __dirname, './../lib/native.js' ) );
var opts = {
	'skip': ( y1 instanceof Error )
};
```

This is missing.

2025-05-09 05:26 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/bessely1/src/main.c
> +	xc = x;
@ShabiShett07, is there a reason why a copy of `x` is present? I don’t see either `x` or `xc` being modified in the code below.

2025-05-09 05:27 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/bessely1/src/main.c
> +		return -INFINITY;
```suggestion
		return STDLIB_CONSTANT_FLOAT64_NINF;
```

2025-05-09 05:27 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/bessely1/src/main.c
> +	if (x == INFINITY) {
```suggestion
	if ( x == STDLIB_CONSTANT_FLOAT64_PINF ) {
```

2025-05-09 05:28 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/bessely1/src/main.c
> +		return NAN;
```suggestion
	if ( x < 0.0 ) {
```

Negative spacing.

2025-05-09 05:28 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/bessely1/src/main.c
> +		return NAN;
```suggestion
		return 0.0 / 0.0; // NaN
```

2025-05-09 05:59 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/bessely1/src/main.c
> +/* Begin auto-generated functions. The following functions are auto-generated. Do not edit directly. */
These seem to have been written manually.

2025-05-09 06:42 UTC, anandkaranubc approved these changes, later dismissed
Good to go!

2025-05-09 07:02 UTC, anandkaranubc commented on lib/node_modules/@stdlib/math/base/special/bessely1/lib/native.js
> +* var v = y1( 1.0 );
```suggestion
* var v = y1( 1.0 );
```

2025-05-09 07:02 UTC, anandkaranubc approved these changes

2025-06-01 05:51 UTC, kgryte approved these changes

2025-06-01 05:53 UTC, merged