feat: add C `ndarray` interface and refactor implementation for `stats/base/dsnanmeanors`
stdlib-js/stdlib pull request #4397
Opened 2024-12-30 19:59 UTC by Neerajpathak07

Resolves none.

## Description

> What is the purpose of this pull request?

This pull request:

-  adds C `ndarray` interface for `stats/base/dsnanmeanors`
-   refactor JavaScript implementation
-   refactor examples, tests, docs and benchmarks.

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves none.

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-  [x] Read, understood, and followed the [contributing guidelines](https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md)

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2025-02-13 15:51 UTC, aayush0325 requested changes

2025-02-13 15:51 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/dsnanmeanors/README.md
> +<!-- C usage documentation. -->
incorrect README structure

2025-02-13 15:51 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/dsnanmeanors/benchmark/c/benchmark.length.c
> +* @return elapsed time in seconds
align these

2025-02-13 15:51 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/dsnanmeanors/src/addon.c
> +* Copyright (c) 2020 The Stdlib Authors.
```suggestion
* Copyright (c) 2025 The Stdlib Authors.
```

2025-02-13 15:51 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/dsnanmeanors/src/main.c
> +	CBLAS_INT n;
align by length

2025-02-13 15:54 UTC, aayush0325 approved these changes

2025-02-14 02:42 UTC, Planeshifter approved these changes

2025-02-14 02:47 UTC, Planeshifter commented
Thanks @Neerajpathak07 for PR and @aayush0325 for review!

2025-02-14 02:47 UTC, merged