feat: add C `ndarray` interface and refactor implementation for `stats/base/dsnanmeanpn`
stdlib-js/stdlib pull request #4405
Opened 2024-12-31 07:49 UTC by Neerajpathak07

Resolves none.

## Description

> What is the purpose of this pull request?

This pull request:

-  adds C `ndarray` interface for `stats/base/dsnanmeanpn`
-   refactor JavaScript implementation
-   refactor examples, tests, docs and benchmarks.

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves none

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-  [x] Read, understood, and followed the [contributing guidelines](https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md)

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2025-02-02 09:44 UTC, aayush0325 requested changes

2025-02-02 09:44 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/dsnanmeanpn/README.md
> +Copyright (c) 2024 The Stdlib Authors.
```suggestion
Copyright (c) 2020 The Stdlib Authors.
```

2025-02-02 09:44 UTC, aayush0325 commented on lib/node_modules/@stdlib/stats/base/dsnanmeanpn/src/main.c
> +* Copyright (c) 2025 The Stdlib Authors.
```suggestion
* Copyright (c) 2020 The Stdlib Authors.
```

2025-02-08 16:24 UTC, aayush0325 approved these changes
thank you!

2025-02-09 08:33 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsnanmeanpn/benchmark/benchmark.js
> +* @returns {number} random number or `NaN`
```suggestion
* Returns a random number.
*
* @private
* @returns {number} random number
```

2025-02-09 08:33 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsnanmeanpn/benchmark/benchmark.native.js
> +* @returns {number} random number or `NaN`
```suggestion
* Returns a random number.
*
* @private
* @returns {number} random number
```

2025-02-09 08:34 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsnanmeanpn/benchmark/benchmark.ndarray.js
> +* @returns {number} random number or `NaN`
```suggestion
* Returns a random number.
*
* @private
* @returns {number} random number
```

2025-02-09 08:34 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dsnanmeanpn/benchmark/benchmark.ndarray.native.js
> +* @returns {number} random number or `NaN`
```suggestion
* Returns a random number.
*
* @private
* @returns {number} random number
```

2025-02-09 08:40 UTC, kgryte approved these changes
LGTM

2025-02-09 08:52 UTC, merged