feat:  add C implementation for `stats/base/dists/binomial/kurtosis`
stdlib-js/stdlib pull request #4411
Opened 2024-12-31 12:13 UTC by 0PrashantYadav0

Resolves #3467

## Description

> What is the purpose of this pull request?

This pull request:

-   adds C implementation for @stdlib/stats/base/dists/binomial/kurtosis along with relevant tests, docs, examples and benchmarks.

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #3467

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2025-01-03 02:16 UTC, Planeshifter requested changes
Instead of `int`, can we please type `n` as `int32_t`? The latter is part of the C standard library's `<stdint.h>` header and ensures portability across different systems by defining exact-width integer types. See e.g. https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/fibonacci for a package with a `int32_t` parameter.

Notice that this PR also contains instances such as in `kurtosis.h` where `n` is still `double`-typed, too, so these will have to be updated as well.

Would you be able to please update all your `binomial/*` PRs accordingly?

2025-01-03 08:23 UTC, 0PrashantYadav0 commented
@Planeshifter i am having trouble in doing so as i have to use `STDLIB_MATH_BASE_NAPI_MODULE_ID_D` which is not implemented in `stdlib/math/base/napi/binary.h` . Do i have to implement this as my own, if so then how can i do this ?

2025-01-03 11:27 UTC, 0PrashantYadav0 commented
@Planeshifter By changing the double into int32_t i have remove some test cases as it will provide undefined answer.

2025-01-03 11:43 UTC, 0PrashantYadav0 commented
@Planeshifter I have made the required changes in this pr please review and if its ok i will make similar changes in all my prs.

2025-01-03 12:33 UTC, 0PrashantYadav0 commented
/stdlib update-copyright-years

2025-01-03 21:47 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/README.md
> +#### STDLIB_MATH_BASE_NAPI_MODULE_ID_D( fcn )
@0PrashantYadav0 Would you mind submitting the changes to `math/base/napi/binary` as a separate PR? This will help us ensure clean commits and an accurate changelog.

2025-01-03 21:48 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/binomial/kurtosis/README.md
> +Returns the kurtosis of a binomial distribution.
```suggestion
Returns the [excess kurtosis][kurtosis] of a [binomial][binomial-distribution] distribution with number of trials `n` and success probability `p`.
```

2025-01-03 21:49 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/binomial/kurtosis/README.md
> +-   **n**: `[in] int` number of trials.
```suggestion
-   **n**: `[in] int32_t` number of trials.
```

2025-01-03 21:49 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/binomial/kurtosis/README.md
> +double stdlib_base_dists_binomial_kurtosis( const int n, const double p );
```suggestion
double stdlib_base_dists_binomial_kurtosis( const int32_t n, const double p );
```

2025-01-03 21:52 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/binomial/kurtosis/benchmark/c/benchmark.c
> +		p[ i ] = random_uniform( 0, 1 );
```suggestion
		n[ i ] = stdlib_base_ceil( random_uniform( 0.0, 100.0 ) );
		p[ i ] = random_uniform( 0.0, 1.0 );
```

`random_uniform` expects doubles, so we add the decimal points.

2025-01-03 21:52 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/binomial/kurtosis/README.md
> +        p = random_uniform( 0, 1 );
```suggestion
        n = stdlib_base_ceil( random_uniform( 0.0, 100.0 ) );
        p = random_uniform( 0.0, 1.0 );
```

2025-01-03 21:53 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/binomial/kurtosis/examples/c/example.c
> +		p = random_uniform( 0, 1 );
```suggestion
		n = stdlib_base_ceil( random_uniform( 0.0, 100.0 ) );
		p = random_uniform( 0.0, 1.0 );
```

2025-01-03 21:54 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/binomial/kurtosis/include/stdlib/stats/base/dists/binomial/kurtosis.h
> +* Returns the kurtosis of a binomial distribution.
```suggestion
* Returns the excess kurtosis of a binomial distribution with number of trials `n` and success probability `p`.
```

2025-01-03 21:54 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/binomial/kurtosis/lib/native.js
> +* Returns the kurtosis of a binomial distribution.
```suggestion
* Returns the excess kurtosis of a binomial distribution with number of trials `n` and success probability `p`.
```

2025-01-03 21:55 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/binomial/kurtosis/src/main.c
> +* Returns the kurtosis of a binomial distribution.
```suggestion
* Returns the excess kurtosis of a binomial distribution with number of trials `n` and success probability `p`.
```

2025-01-03 21:55 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/binomial/kurtosis/src/main.c
> +		n < 0.0 ||
```suggestion
		n < 0 ||
```

`n` is an integer.

2025-01-03 21:56 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/binomial/kurtosis/src/main.c
> +		stdlib_base_is_nan( n ) ||
```suggestion
```

`n` is an integer.

2025-01-03 21:57 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/binomial/kurtosis/src/main.c
> +#include "stdlib/constants/float64/pinf.h"
This constant is not used. The `manifest.json` file should also be updated accordingly.

2025-01-03 21:57 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/binomial/kurtosis/src/main.c
> +		n >= INT32_MAX ||
If `n` is `int32_t`, in what circumstance could it ever exceed the max `int32`?

2025-01-03 21:57 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/binomial/kurtosis/src/main.c
> +	return ( 1.0 - (6.0 * pq ) ) / ( n * pq );
```suggestion
	return ( 1.0 - ( 6.0 * pq ) ) / ( n * pq );
```

Use consistent spacing.

2025-01-03 21:58 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/binomial/kurtosis/manifest.json
> +        "@stdlib/math/base/special/ceil"
This dep is not used in the implementation.

2025-01-03 21:58 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/binomial/kurtosis/manifest.json
> +        "@stdlib/constants/float64/pinf",
This dep is not used.

2025-01-03 21:58 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/binomial/kurtosis/src/main.c
> +#include "stdlib/math/base/assert/is_nonnegative_integer.h"
This dep is not used.

2025-01-03 21:58 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/binomial/kurtosis/manifest.json
> +        "@stdlib/math/base/assert/is-nonnegative-integer",
This dep is not used.

2025-01-03 22:00 UTC, kgryte commented on lib/node_modules/@stdlib/stats/base/dists/binomial/kurtosis/test/test.native.js
> +			tol = 100.0 * EPS * abs( expected[i] );
Why is this tolerance so high? The implementation is simple arithmetic and does not involve transcendentals.

2025-01-03 22:01 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/README.md
> +#### STDLIB_MATH_BASE_NAPI_MODULE_ID_D( fcn )
We can first merge that PR before merging this one after merging in the latest changes on `develop`.

2025-01-04 05:16 UTC, 0PrashantYadav0 commented on lib/node_modules/@stdlib/stats/base/dists/binomial/kurtosis/test/test.native.js
> +			tol = 100.0 * EPS * abs( expected[i] );
This is due point precision error. It shows error upto 2 decimal points thats why it has high tolerance.

2025-01-04 05:16 UTC, 0PrashantYadav0 commented on lib/node_modules/@stdlib/math/base/napi/binary/README.md
> +#### STDLIB_MATH_BASE_NAPI_MODULE_ID_D( fcn )
sure i will open new pr for this

2025-01-04 05:56 UTC, 0PrashantYadav0 commented
@kgryte I open pr for binary as well as for ternary implementation, #4522 and #4523 . Please review and merge them asap so that i can move forward and implement these in all the prs of binomial/* .

2025-01-06 14:36 UTC, 0PrashantYadav0 commented
@Planeshifter @kgryte  Please review this, i have implemented ID_D as mention earlier.

2025-02-15 18:06 UTC, Planeshifter reviewed
@0PrashantYadav0 Would you mind resolving the merge conflicts in this PR. please?

2025-02-15 19:11 UTC, 0PrashantYadav0 commented
/stdlib merge

2025-02-16 18:26 UTC, 0PrashantYadav0 commented
@Planeshifter Done please review and merge. Thank you.

2025-02-16 20:01 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/binomial/kurtosis/src/main.c
> +* Returns the kurtosis of a binomial distribution.
```suggestion
* Returns the excess kurtosis of a binomial distribution with number of trials `n` and success probability `p`.
```

2025-02-16 20:04 UTC, Planeshifter commented on lib/node_modules/@stdlib/stats/base/dists/binomial/kurtosis/manifest.json
> +        "@stdlib/math/base/special/ceil"
```suggestion
        "@stdlib/math/base/assert/is-nan"
```

2025-02-16 20:07 UTC, Planeshifter approved these changes
Great, thanks for resolving the merge conflicts! 

Did a review pass and PR looks to be in good shape overall now. Had to apply to edits that @kgryte initially flagged but which were not resolved; please ensure to only resolve comments once addressed.

I will go ahead and merge your PR shortly. Thanks again for all your contributions!

2025-02-16 20:28 UTC, merged