PR: Add sqrtpi package
stdlib-js/stdlib pull request #507
Opened 2022-08-25 21:59 UTC by steff456

Resolves #1185

## Description

> What is the purpose of this pull request?

This pull request adds `sqrtpi` package

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #1185

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2022-08-26 19:42 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrtpi/README.md
> +> Compute the positive [square root][square-root] of the product of pi and a provided positive number.
```suggestion
> Compute the positive [square root][square-root] of the product of pi and a positive number.
```

2022-08-26 20:07 UTC, kgryte requested changes
@steff456 Thanks for working on this! Only small changes before this is ready for merge.

2022-08-26 20:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrtpi/README.md
> +Computes the positive [square root][square-root] of the product of pi and a provided positive number.
```suggestion
Computes the principal [square root][@stdlib/math/base/special/sqrt] of the product of 𝛑 and a positive number.
```

We can refer to the documentation for `sqrt` within stdlib, rather than to an external source.

2022-08-26 20:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrtpi/README.md
> +// returns 3.5449
```suggestion
// returns ~3.5449
```

2022-08-26 20:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrtpi/README.md
> +// returns 5.6049
```suggestion
// returns ~5.6049
```

My guess is that these are approximate values, correct? Not exact? If the former, then we always include a `~` character to indicate that exact values may deviate from what is displayed.

2022-08-26 20:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrtpi/README.md
> +For negative numbers, the positive [square root][square-root] of the product of pi and a provided positive number is **not** defined.
```suggestion
For negative numbers, the principal [square root][@stdlib/math/base/special/sqrt] is **not** defined.
```

2022-08-26 20:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrtpi/README.md
> +var v = sqrt( -4.0 );
```suggestion
var v = sqrtpi( -4.0 );
```

2022-08-26 20:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrtpi/README.md
> +<!-- </related-links> -->
```suggestion
[@stdlib/math/base/special/sqrt]: https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/sqrt

<!-- <related-links> -->

[@stdlib/math/base/special/rsqrt]: https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/rsqrt

<!-- </related-links> -->
```

2022-08-26 20:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrtpi/docs/repl.txt
> +    positive number.
```suggestion
    Computes the principal square root of the product of 𝛑 and a positive
    number.
```

2022-08-26 20:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrtpi/docs/repl.txt
> +        Positive square root of the product of pi and the input number.
```suggestion
        Principal square root of the product of 𝛑 and the input number.
```

2022-08-26 20:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrtpi/docs/repl.txt
> +    3.5449
```suggestion
    ~3.5449
```

2022-08-26 20:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrtpi/docs/repl.txt
> +    5.6049
```suggestion
    ~5.6049
```

2022-08-26 20:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrtpi/docs/types/index.d.ts
> +* Computes the positive square root of the product of pi and a provided positive number.
```suggestion
* Computes the principal square root of the product of pi and a positive number.
```

2022-08-26 20:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrtpi/docs/types/index.d.ts
> +* -   For `x < 0`, the positive square root of the product of pi and a provided positive number is not defined.
```suggestion
* -   For `x < 0`, the principal square root is not defined.
```

2022-08-26 20:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrtpi/docs/types/index.d.ts
> +* @returns positive square root of the product of pi and `x`
```suggestion
* @returns results
```

2022-08-26 20:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrtpi/docs/types/index.d.ts
> +* // returns 3.5449
```suggestion
* // returns ~3.5449
```

2022-08-26 20:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrtpi/docs/types/index.d.ts
> +* // returns 5.6049
```suggestion
* // returns ~5.6049
```

2022-08-26 20:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrtpi/lib/index.js
> +* Computes the positive square root of the product of pi and a provided positive number.
```suggestion
* Compute the principal square root of the product of 𝛑 and a positive number.
```

2022-08-26 20:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrtpi/lib/index.js
> +* Computes the positive square root of the product of pi and a provided positive number.
For the entry file `index.js`, the description should match the top-level README description and the `package.json` description and be a command to the user, rather than a description of function behavior. E.g., "Compute this" vs "Computes this".

2022-08-26 20:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrtpi/lib/index.js
> +* // returns 3.5449
```suggestion
* // returns ~3.5449
```

2022-08-26 20:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrtpi/lib/index.js
> +* // returns 5.6049
```suggestion
* // returns ~5.6049
```

2022-08-26 20:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrtpi/lib/main.js
> +* Computes the positive square root of the product of pi and a provided positive number.
```suggestion
* Computes the principal square root of the product of 𝛑 and a positive number.
```

2022-08-26 20:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrtpi/lib/main.js
> +* @param {number} x - input value
```suggestion
* @param {number} x - input value
```

The type annotation is not necessary here, as the type can be inferred from the `function foo() {}` signature.

2022-08-26 20:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrtpi/lib/main.js
> +* @returns {number} positive square root of the product of pi and the input number.
```suggestion
* @returns {number} results
```

2022-08-26 20:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrtpi/lib/main.js
> +* // returns 3.5449
```suggestion
* // returns ~3.5449
```

2022-08-26 20:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrtpi/lib/main.js
> +* // returns 5.6049
```suggestion
* // returns ~5.6049
```

2022-08-26 20:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrtpi/package.json
> +  "description": "Compute the positive square root of the product of pi and a provided positive number.",
```suggestion
  "description": "Compute the principal square root of the product of 𝛑 and a positive number.",
```

2022-08-26 20:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrtpi/package.json
> +    "test": "./test"
```suggestion
    "benchmark": "./benchmark",
    "doc": "./docs",
    "example": "./examples",
    "lib": "./lib",
    "test": "./test"
```

List of directories should match what is in the package.

2022-08-26 20:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrtpi/package.json
> +  "directories": {
```suggestion
  "directories": {
```

No native implementation, and thus no `binding.gyp` file is present in the package.

2022-08-26 20:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrtpi/test/fixtures/julia/runner.jl
> +# Copyright (c) 2018 The Stdlib Authors.
```suggestion
# Copyright (c) 2022 The Stdlib Authors.
```

2022-08-26 20:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrtpi/test/test.js
> +tape( 'the function evaluates the principal square root of `x` on the interval `[50,500]`', function test( t ) {
```suggestion
tape( 'the function evaluates the principal square root when `x` is on the interval `[50,500]`', function test( t ) {
```

2022-08-26 20:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrtpi/test/test.js
> +tape( 'the function evaluates the principal square root of `x` on the interval `[20,50]`', function test( t ) {
```suggestion
tape( 'the function evaluates the principal square root of when `x` is on the interval `[20,50]`', function test( t ) {
```

Changing the description to better match function behavior.

2022-08-26 20:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrtpi/test/test.js
> +tape( 'the function evaluates the principal square root of `x` on the interval `[3,20]`', function test( t ) {
```suggestion
tape( 'the function evaluates the principal square root of when `x` is on the interval `[3,20]`', function test( t ) {
```

2022-08-26 20:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrtpi/test/test.js
> +tape( 'the function evaluates the principal square root of `x` on the interval `[0.8,3]`', function test( t ) {
```suggestion
tape( 'the function evaluates the principal square root of when `x` is on the interval `[0.8,3]`', function test( t ) {
```

2022-08-26 20:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrtpi/test/test.js
> +tape( 'the function evaluates principal square root of `x` on the interval `[0.0,0.8]`', function test( t ) {
```suggestion
tape( 'the function evaluates principal square root of when `x` is on the interval `[0.0,0.8]`', function test( t ) {
```

2022-08-26 20:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrtpi/test/test.js
> +tape( 'the function evaluates the principal square root of `x` on the interval `[1e-300,1e-308]`', function test( t ) {
```suggestion
tape( 'the function evaluates the principal square root of when `x` is on the interval `[1e-300,1e-308]`', function test( t ) {
```

2022-08-26 20:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrtpi/test/test.js
> +tape( 'the function evaluates the principal square root of subnormal `x`', function test( t ) {
```suggestion
tape( 'the function evaluates the principal square root when `x` is subnormal', function test( t ) {
```

2022-08-26 20:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrtpi/test/test.js
> +tape( 'the function evaluates the principal square root of `x` (huge positive)', function test( t ) {
```suggestion
tape( 'the function evaluates the principal square root for huge positive numbers', function test( t ) {
```

2022-08-26 20:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrtpi/test/test.js
> +});
```suggestion
```

This is a duplicate of L244.

2022-08-26 20:12 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrtpi/docs/repl.txt
> +        Principal square root of the product of 𝛑 and the input number.
```suggestion
        Principal square root of the product of 𝛑 and the input value.
```

2022-08-26 20:14 UTC, kgryte commented
@steff456 Went ahead and applied the requested changes. If you could do another review to ensure that I did not miss anything, that would be great!

2022-08-29 16:46 UTC, steff456 commented
I think the PR is ready! I don't see anymore changes that are needed from your review. Thanks a lot :)

2022-08-29 16:47 UTC, kgryte approved these changes

2022-08-29 16:48 UTC, merged