PR: Add gammasgn
stdlib-js/stdlib pull request #513
Opened 2022-08-30 22:26 UTC by steff456

Resolves https://github.com/stdlib-js/todo/issues/588.

## Description

> What is the purpose of this pull request?

This pull request:

Adds `gammasgn` package to compute the sign of the `gamma` function in the given input value.

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #https://github.com/stdlib-js/todo/issues/588

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2022-08-31 00:20 UTC, kgryte requested changes
@steff456 Thanks for working on this! Most of the requested changes are minor nits. I did make suggestions for the equation, which would need to be regenerated along with the src URL.

2022-08-31 00:20 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/README.md
> +Defined as,
```suggestion
The sign of the [gamma-function][@stdlib/math/base/special/gamma] is defined as
```

2022-08-31 00:20 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/README.md
> +> Sign of the [gamma function][gamma-function].
```suggestion
> Sign of the [gamma function][@stdlib/math/base/special/gamma].
```

We can point to the `stdlib` package here.

2022-08-31 00:20 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/README.md
> +<!-- <equation class="equation" label="eq:gamma_sign_function" align="center" raw="gammasgn ( x ) = \begin{cases} 1 & \textrm{if}\ \Gamma > 1 \\ -1 & \textrm{if}\ \Gamma < 1 \\ 0 & \textrm{otherwise}
```suggestion
<!-- <equation class="equation" label="eq:gamma_sign_function" align="center" raw="\operatorname{gammasgn} ( x ) = \begin{cases} 1 & \textrm{if}\ \Gamma > 1 \\ -1 & \textrm{if}\ \Gamma < 1 \\ 0 & \textrm{otherwise}\ \end{cases}" alt="Sign of the gamma function"> -->
```

We want to use `\operatorname` to achieve desired font style rendering.

2022-08-31 00:20 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/README.md
> +<div class="equation" align="center" data-raw-text="gammasgn ( x ) = \begin{cases} 1 &amp; \textrm{if}\ \Gamma &gt; 1 \\ -1 &amp; \textrm{if}\ \Gamma &lt; 1 \\ 0 &amp; \textrm{otherwise}\ \end{cases}
This should be regenerated due to changes above.

2022-08-31 00:20 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/README.md
> +The [gamma function][gamma-function] can be computed as the product of `gammasgn` and `gammaln`.
```suggestion
The [gamma function][@stdlib/math/base/special/gamma] can be computed as the product of `gammasgn(x)` and `exp(gammaln(x))`.
```

2022-08-31 00:20 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/README.md
> +Returns the sign of the [gamma function][gamma-function] evaluated in the given `x` value.
```suggestion
Returns the sign of the [gamma function][@stdlib/math/base/special/gamma].
```

2022-08-31 00:20 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/README.md
> +[gamma-function]: https://en.wikipedia.org/wiki/Gamma_function
```suggestion
[@stdlib/math/base/special/gamma]: https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/gamma
```

2022-08-31 00:20 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/README.md
> +
```suggestion
```

Included above.

2022-08-31 00:20 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/benchmark/benchmark.js
> +		x = ( randu()*100000.0 ) - 0.0;
```suggestion
		x = ( randu()*171.0 ) - 0.0;
```

Matching the SciPy benchmarks. The values don't matter here, given the implementation, but I suppose we should be realistic and so `171` seems reasonable.

2022-08-31 00:20 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/docs/repl.txt
> +        Sign of the gamma function evaluated in the input value.
```suggestion
        Sign of the gamma function.
```

We can be less verbose here.

2022-08-31 00:20 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/docs/repl.txt
> +    -1
```suggestion
    -1.0
```

Missing decimal.

2022-08-31 00:20 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/docs/types/test.ts
> +// The function does not compile if provided a value other than a number...
```suggestion
// The compiler throws an error if the function is provided a value other than a number...
```

At some point, we should standardize these comments across the project.

2022-08-31 00:20 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/docs/types/test.ts
> +// The function does not compile if provided insufficient arguments...
```suggestion
// The compiler throws an error if the function is provided insufficient arguments...
```

2022-08-31 00:20 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/lib/main.js
> +* Computes the principal square root of the product of 𝛑 and a positive number.
```suggestion
* Computes the sign of the gamma function.
```

2022-08-31 00:20 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/lib/main.js
> +* @returns {number} results
```suggestion
* @returns {number} sign of the gamma function
```

2022-08-31 00:20 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/lib/main.js
> +	return 1.0;
```suggestion
	var fx;
	if ( isnan( x ) ) {
		return x;
	}
	if ( x > 0 ) {
		return 1.0;
	}
	fx = floor( x );
	if ( x === fx ) {
		return 0.0;
	}
	fx /= 2.0;
	if ( fx === floor( fx ) ) {
		return -1.0;
	}
	return 1.0;
```

The `x - fx === 0` check can be simplified to an equality check. An optimizing compiler could simplify and rearrange on its own, but I'd rather not leave it to chance.

`parseInt` is not necessary here. True, a native implementation might cast to int and then use the modulus. However, the modulus can be a slower operation. The basic goal of the line in question is checking whether the value is even. We can do that with a division (still slower) and a `floor`. Still a bit slow, but follows https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/assert/is-even/lib/is_even.js.

2022-08-31 00:20 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/README.md
> +
We should add a notes section here to explain why the `gammasgn` function can return `0.0` and why that makes sense.

Namely, the gamma function is not defined for negative integer values (i.e., `gamma(x) === NaN` when `x` is a negative integer). The natural logarithm of the gamma function is defined for negative integer values (e.g., `gammaln(x) === Infinity` when `x` is a negative integer). Accordingly, in order for the equality `gamma(x) === gammasgn(x) * exp(gammaln(x))` to hold (i.e., return `NaN`), `gammasgn` needs to either return `NaN` or `0`. By convention, this function returns `0`.

2022-08-31 00:20 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/package.json
> +  "description": "Sign of the gamma function",
```suggestion
  "description": "Sign of the gamma function.",
```

Descriptions in `package.json` files always end in a period.

2022-08-31 00:20 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/test/fixtures/python/runner.py
> +#!/usr/bin/env julia
The shebang is incorrect here.

2022-08-31 00:20 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/test/test.js
> +var mediumNegative = require( './fixtures/python/medium_negative.json' );
```suggestion
var mediumNegative = require( './fixtures/python/medium_negative.json' );
```

2022-08-31 00:20 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/test/test.js
> +tape( 'the function computes the sign of `gamma` evaluated in `x`', function test( t ) {
```suggestion
tape( 'the function computes the sign of the gamma function', function test( t ) {
```

2022-08-31 00:20 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/test/test.js
> +		delta = abs( v - expected[ i ] );
None of this should be needed. The value comparison should be exact, as the function can only return `1.0`, `-1.0`, or `0.0`.

2022-08-31 00:20 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/test/test.js
> +tape( 'the function computes the sign of `gamma` for small positive numbers', function test( t ) {
```suggestion
tape( 'the function computes the sign of the gamma function for small positive numbers', function test( t ) {
```

2022-08-31 00:20 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/test/test.js
> +		delta = abs( v - expected[ i ] );
Same comment as above.

2022-08-31 00:20 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/test/test.js
> +tape( 'the function computes the sign of `gamma` for medium positive numbers', function test( t ) {
```suggestion
tape( 'the function computes the sign of the gamma function for medium positive numbers', function test( t ) {
```

2022-08-31 00:20 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/test/test.js
> +		delta = abs( v - expected[ i ] );
Same comment as above.

2022-08-31 00:20 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/test/test.js
> +tape( 'the function computes the sign of `gamma` for small negative numbers', function test( t ) {
```suggestion
tape( 'the function computes the sign of the gamma function for small negative numbers', function test( t ) {
```

2022-08-31 00:20 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/test/test.js
> +		v = gammasgn( x[ i ] );
Same comment as above.

We only need to perform approx floating-point comparison when values are subject to floating-point rounding error.

2022-08-31 00:20 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/test/test.js
> +tape( 'the function computes the sign of `gamma` for medium negative numbers', function test( t ) {
```suggestion
tape( 'the function computes the sign of the gamma function for medium negative numbers', function test( t ) {
```

2022-08-31 00:20 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/test/test.js
> +		v = gammasgn( x[ i ] );
Same as above.

2022-08-31 00:20 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/test/test.js
> +tape( 'the function returns `-0` if provided `+0`', function test( t ) {
```suggestion
tape( 'the function returns `+0` if provided `-0`', function test( t ) {
```

2022-08-31 00:20 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/test/test.js
> +});
We should add tests for negative integers. (i.e., we should return `0.0`). No need to use additional fixtures. Just create a `for` loop which tests against the first `100` negative integers.

2022-08-31 17:55 UTC, steff456 commented on lib/node_modules/@stdlib/math/base/special/gammasgn/lib/main.js
> +	return 1.0;
In fact it is reviewing that the floor of the given number is odd, I added a call to the function in stdlib, let me know if we don't want that dependency so I can change it again

2022-08-31 18:00 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/lib/main.js
> +	return 1.0;
No need to use the dependency. Just do `fx !== floor( fx )`.

2022-08-31 18:01 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/lib/main.js
> +	return 1.0;
Thanks for catching that. You're right regarding the "is odd" check.

Although, we should just do this instead:

```
if ( fx === floor( fx ) ) {
    return 1.0;
}
return -1.0;
```

meaning just swap the return values.

2022-09-01 01:24 UTC, kgryte requested changes

2022-09-01 01:24 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/README.md
> +
```suggestion
<section class="intro">

The sign of the [gamma-function][@stdlib/math/base/special/gamma] is defined as

```

2022-09-01 01:24 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/README.md
> +
Should be inside intro `section`.

2022-09-01 01:24 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/README.md
> +Returns the sign of the [gamma function][@stdlib/math/base/special/gamma]
```suggestion
Returns the sign of the [gamma function][@stdlib/math/base/special/gamma].
```

2022-09-01 01:24 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/README.md
> +The [gamma function][@stdlib/math/base/special/gamma] is not defined for negative integer values (i.e., `gamma(x) === NaN` when `x` is a negative integer). The [natural logarithm of the gamma functio
```suggestion
-    The [gamma function][@stdlib/math/base/special/gamma] is not defined for negative integer values (i.e., `gamma(x) === NaN` when `x` is a negative integer). The [natural logarithm of the gamma function][@stdlib/math/base/special/gammaln] is defined for negative integer values (i.e., `gammaln(x) === Infinity` when `x` is a negative integer). Accordingly, in order for the equality `gamma(x) === gammasgn(x) * exp(gammaln(x))` to hold (i.e., return `NaN`), `gammasgn` needs to either return `NaN` or `0`. By convention, this function returns `0`.
```

2022-09-01 01:24 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/README.md
> +
```suggestion
```

Related section content can just be removed when creating new packages. We auto-populate this section using an external database which maps a package to its related packages.

We need only retain the `<section>` tags.

2022-09-01 01:24 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/docs/repl.txt
> +    Sign of the gamma function.
```suggestion
    Computes the sign of the gamma function.
```

2022-09-01 01:24 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/docs/types/index.d.ts
> +* Sign of the gamma function.
```suggestion
* Computes the sign of the gamma function.
```

2022-09-01 01:24 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/docs/types/index.d.ts
> +* @returns results
```suggestion
* @returns sign of the gamma function
```

2022-09-01 01:24 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/lib/index.js
> +* Sign of the gamma function.
```suggestion
* Compute the sign of the gamma function.
```

2022-09-01 01:24 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/lib/main.js
> +	if ( fx === floor(fx) ) {
```suggestion
	if ( fx === floor( fx ) ) {
```

2022-09-01 01:24 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/test/test.js
> +		t.ok( v === expected[ i ], 'x: ' + x[ i ] + '. Value: ' + v + '. Expected: ' + expected[ i ] + '.' );
```suggestion
		t.equal( v, expected[ i ], 'x: ' + x[ i ] + '. Value: ' + v + '. Expected: ' + expected[ i ] + '.' );
```

2022-09-01 01:24 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/test/test.js
> +		t.ok( v === expected[ i ], 'x: ' + x[ i ] + '. Value: ' + v + '. Expected: ' + expected[ i ] + '.' );
We typically use the `equal`/`strictEqual` method for asserting that two values are equal.

2022-09-01 01:24 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/test/test.js
> +		t.ok( v === expected[ i ], 'x: ' + x[ i ] + '. Value: ' + v + '. Expected: ' + expected[ i ] + '.' );
```suggestion
		t.equal( v, expected[ i ], 'x: ' + x[ i ] + '. Value: ' + v + '. Expected: ' + expected[ i ] + '.' );
```

2022-09-01 01:24 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/test/test.js
> +		t.ok( v === expected[ i ], 'x: ' + x[ i ] + '. Value: ' + v + '. Expected: ' + expected[ i ] + '.' );
```suggestion
		t.equal( v, expected[ i ], 'x: ' + x[ i ] + '. Value: ' + v + '. Expected: ' + expected[ i ] + '.' );
```

2022-09-01 01:24 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/test/test.js
> +		t.ok( v === expected[ i ], 'x: ' + x[ i ] + '. Value: ' + v + '. Expected: ' + expected[ i ] + '.' );
```suggestion
		t.equal( v, expected[ i ], 'x: ' + x[ i ] + '. Value: ' + v + '. Expected: ' + expected[ i ] + '.' );
```

2022-09-01 01:24 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/test/test.js
> +		t.ok( v === expected[ i ], 'x: ' + x[ i ] + '. Value: ' + v + '. Expected: ' + expected[ i ] + '.' );
```suggestion
		t.equal( v, expected[ i ], 'x: ' + x[ i ] + '. Value: ' + v + '. Expected: ' + expected[ i ] + '.' );
```

2022-09-01 01:24 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/test/test.js
> +tape( 'the function returns `+0` if provided a negative integer number', function test( t ) {
```suggestion
tape( 'the function returns `+0` if provided a negative integer', function test( t ) {
```

2022-09-01 01:24 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/test/test.js
> +	var v;
```suggestion
	var v;
```

2022-09-01 01:24 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/gammasgn/test/test.js
> +	for ( i = 0; i >= end; i-- ) {
```suggestion
	for ( i = 0; i >= -100; i-- ) {
```

The extra variable assignment is not necessary.

2022-09-01 01:27 UTC, kgryte approved these changes
Thanks, @steff456!

2022-09-01 01:27 UTC, merged