Feature/logit
stdlib-js/stdlib pull request #52
Opened 2016-12-08 04:13 UTC by Planeshifter

Resolves #26 .

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

* [x] Read, understood, and followed the [contributing guidelines][contributing], including the relevant style guides.
* [x] Read and understand the [Code of Conduct][code-of-conduct].
* [x] Read and understood the [licensing terms][license].
* [x] Searched for existing issues and pull requests __before__ submitting this pull request.
* [x] Filed an issue (or an issue already existed) __prior to__ submitting this pull request.
* [x] Rebased onto latest `develop`.
* [x] Submitted against `develop` branch.

## Description

> What is the purpose of this pull request?

This pull request:

* Contains an implementation of the logit function
* Exports the logit function to the special functions namespace

## Related Issues

> Does this pull request have any related issues?

This pull request:

* resolves 
* fixes

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

---

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/master/CONTRIBUTING.md
[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/master/CODE_OF_CONDUCT.md
[license]: https://github.com/stdlib-js/stdlib/blob/master/LICENSE

2016-12-08 05:30 UTC, kgryte requested changes

2016-12-08 05:30 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/logit/README.md
> +> Compute the [logit][logit] of a proportion.
> Compute the logit function.

2016-12-08 05:30 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/logit/README.md
> +> Compute the [logit][logit] of a proportion.
Perhaps include a quick intro, explaining what the logit function is; e.g., the inverse of the logistic function, as well as its functional (equation) definition.

2016-12-08 05:30 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/logit/README.md
> +Computes the [logit][logit] of a proportion `p`.
> Computes the logit function.

2016-12-08 05:30 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/logit/README.md
> +If `p < 0` or `p > 1`, the function will return `NaN`.
> the function returns `NaN`.

2016-12-08 05:30 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/logit/package.json
> +{
This `package.json` is out-of-date. Various fields now have default values.

2016-12-09 05:03 UTC, Planeshifter commented
Thanks for the review! Made the requested changes.

2016-12-09 23:00 UTC, kgryte requested changes

2016-12-09 23:00 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/logit/README.md
> +The [logit][logit] function is the inverse of the [standard logistic] function, sometimes also called the sigmoid function.
Broken link => `[standard logistic]`

2016-12-10 04:25 UTC, Planeshifter commented
Thanks. Link is fixed.

2016-12-10 07:58 UTC, kgryte requested changes

2016-12-10 07:58 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/logit/test/test.js
> +function almostEqual( a, b, tol ) {
We have discussed this before. This definition of "almost equal" is wanting. For instance, if `a < 1` and `b < 1`, the tolerance will be too large. Recall that `eps` is the delta between `1` and the __next__ number greater than `1`. As a reminder, this delta is not constant. For smaller values, the delta is less than `eps`.

So, as a reminder, we should __not__ be using this definition. This is particularly the case where, in this definition, `a` and `b` are treated equivalently. Here, this is not true. One value is the reference value and should be the basis for determining the neighborhood of accuracy.

If this definition was used somewhere else, that is a bug.

2016-12-10 07:58 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/logit/README.md
> +The [logit][logit] function is defined as the logarithm of the odds `p / (1-p)`, i.e.
Punctuation:

> ...the odds `p / (1-p)`; i.e.,

2016-12-10 07:58 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/logit/test/test.js
> +			t.ok( bool, 'within tolerance. x: '+x[i]+'. y: '+y+'. Expected: '+expected[i]+'. Tolerance: '+tol+'.' );
This is not the actual tolerance. The actual tolerance is scaled. Another reason we should not be using a functional definition for "almost equal".

 Should also include the `delta`.

2016-12-10 07:58 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/logit/test/test.js
> +			t.ok( bool, 'within tolerance. x: '+x[i]+'. y: '+y+'. Expected: '+expected[i]+'. Tolerance: '+tol+'.' );
Not the actual tolerance. Should also include the `delta`.

2016-12-10 07:58 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/logit/test/test.js
> +			t.ok( bool, 'within tolerance. x: '+x[i]+'. y: '+y+'. Expected: '+expected[i]+'. Tolerance: '+tol+'.' );
Not the actual tolerance.  Should also include the `delta`.

2016-12-10 07:58 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/logit/test/fixtures/python/runner.py
> +    python> x = linspace(-1000, 1000, 2001);
Not a realistic range for this particular test. Instead,

```
python> x = linspace(0.0, 1.0, 2001);
```

2016-12-10 18:47 UTC, Planeshifter commented
Replaced the `almostEqual` function call by our inline check. There are quite a few instances of the wrong check still in our `develop` branch; I will fix them over the weekend.

2016-12-10 21:24 UTC, kgryte approved these changes

2016-12-10 21:25 UTC, merged