Add support for pretty printing collections of the same length
stdlib-js/stdlib pull request #526
Opened 2022-09-22 22:58 UTC by steff456

## Description

> What is the purpose of this pull request?

This pull request:

-   Adds the `log` package that allows pretty printing collections of the same length
- If a scalar value and a collection are provided, it will broadcast to each item in the collection.

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   is part of https://github.com/stdlib-js/todo/issues/1425

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2022-09-22 23:02 UTC, kgryte commented on lib/node_modules/@stdlib/array/log/examples/index.js
> +var log = require( '@stdlib/array/log' );
Use the relative path here. Apart from doctests, this should be the only difference between the example as shown in the README and the example as included in this file.

2022-09-22 23:02 UTC, kgryte commented on lib/node_modules/@stdlib/array/log/examples/index.js
> +var log = require( '@stdlib/array/log' );
```suggestion
var log = require( './../lib' );
```

2022-09-22 23:03 UTC, kgryte commented on lib/node_modules/@stdlib/array/log/lib/logger.js
> +* @param {string} str - format string
Missing a private declaration here. This module/function is not part of the package's public API.

```suggestion
* @private
* @param {string} str - format string
```

2022-09-22 23:04 UTC, kgryte commented on lib/node_modules/@stdlib/array/log/lib/logger.js
> +* Prints the string given by parameter.
```suggestion
* Outputs a provided message to a web console (or stdout).
```

2022-09-22 23:07 UTC, kgryte commented on lib/node_modules/@stdlib/array/log/test/test.js
> +tape( 'the function prints the correct result when provided 1 array', function test( t ) {
```suggestion
tape( 'the function prints the correct result when provided one array', function test( t ) {
```

2022-09-22 23:08 UTC, kgryte commented on lib/node_modules/@stdlib/array/log/test/test.js
> +tape( 'the function prints the correct result when provided 2 arrays with the same length', function test( t ) {
```suggestion
tape( 'the function prints the correct result when provided two arrays', function test( t ) {
```

Given the assertion test above, it's assumed that provided arrays must be the same length.

2022-09-22 23:11 UTC, kgryte commented on lib/node_modules/@stdlib/array/log/test/test.js
> +tape( 'the function prints the correct result when provided 3 arrays with the same length', function test( t ) {
```suggestion
tape( 'the function repeatedly prints a formatted message (three arrays)', function test( t ) {
```

2022-09-22 23:12 UTC, kgryte commented on lib/node_modules/@stdlib/array/log/test/test.js
> +tape( 'the function prints the correct result when provided 4 arrays with the same length', function test( t ) {
```suggestion
tape( 'the function repeatedly prints a formatted message (four arrays)', function test( t ) {
```

2022-09-22 23:13 UTC, kgryte commented on lib/node_modules/@stdlib/array/log/test/test.js
> +tape( 'the function prints the correct result when provided 1 array and 1 scalar', function test( t ) {
```suggestion
tape( 'the function broadcasts non-array arguments (one array, one scalar)', function test( t ) {
```

2022-09-22 23:14 UTC, kgryte commented on lib/node_modules/@stdlib/array/log/test/test.js
> +tape( 'the function prints the correct result when provided 1 scalar and 1 array', function test( t ) {
```suggestion
tape( 'the function broadcasts non-array arguments (one scalar, one array)', function test( t ) {
```

2022-09-22 23:14 UTC, kgryte commented on lib/node_modules/@stdlib/array/log/test/test.js
> +tape( 'the function prints the correct result when provided 2 arrays and 1 scalar', function test( t ) {
```suggestion
tape( 'the function broadcasts non-array elements (two arrays, one scalar)', function test( t ) {
```

2022-09-22 23:15 UTC, kgryte commented on lib/node_modules/@stdlib/array/log/test/test.js
> +tape( 'the function prints the correct result when provided 1 scalar and 2 arrays', function test( t ) {
```suggestion
tape( 'the function broadcasts non-array arguments (one scalar, two arrays)', function test( t ) {
```

2022-09-22 23:16 UTC, kgryte commented on lib/node_modules/@stdlib/array/log/test/test.js
> +tape( 'the function prints the correct result when provided 1 scalar', function test( t ) {
```suggestion
tape( 'the function prints a formatted message when provided only a scalar argument', function test( t ) {
```

2022-09-22 23:16 UTC, kgryte commented on lib/node_modules/@stdlib/array/log/test/test.js
> +tape( 'the function prints the correct result when provided 2 scalars', function test( t ) {
```suggestion
tape( 'the function prints a formatted message when only provided two scalar arguments', function test( t ) {
```

2022-09-22 23:18 UTC, kgryte requested changes
@steff456 Thanks for submitting this PR! I believe we still need to add `repl.txt` and TypeScript declarations. Once those are added, this PR should be ready for merge.

2022-09-29 18:06 UTC, kgryte commented on lib/node_modules/@stdlib/array/log/docs/repl.txt
> +{{alias}}( str[, ...args] )
Add empty line.

2022-09-29 18:07 UTC, kgryte commented on lib/node_modules/@stdlib/array/log/docs/repl.txt
> +    str: str
dtype

2022-09-29 18:07 UTC, kgryte commented on lib/node_modules/@stdlib/array/log/docs/repl.txt
> +    ...args: Collection|*
Need to update how variadic args are documented and use `any`. See https://github.com/stdlib-js/stdlib/blob/develop/docs/repl_text.md.

2022-09-29 18:07 UTC, kgryte commented on lib/node_modules/@stdlib/array/log/docs/repl.txt
> +    --------
Trailing newline.

2022-09-29 18:08 UTC, kgryte commented on lib/node_modules/@stdlib/array/log/docs/repl.txt
> +    > var log = require( '@stdlib/array/log' );
This line should be removed.

2022-09-29 18:08 UTC, kgryte commented on lib/node_modules/@stdlib/array/log/docs/repl.txt
> +    > log( '%d < %d ', x, y );
Instead of `log`, we use `{{alias}}`.

2022-09-29 18:08 UTC, kgryte commented on lib/node_modules/@stdlib/array/log/docs/repl.txt
> +    // e.g., => '1 < 4\n2 < 5\n3 < 6\n'
This line should be removed, as we don't doctest console log.

2022-09-29 18:11 UTC, kgryte commented on lib/node_modules/@stdlib/array/log/docs/types/index.d.ts
> +declare function log( str: String, ...args: any ): any;
Return type should be `void`.

2022-09-29 18:11 UTC, kgryte commented on lib/node_modules/@stdlib/array/log/docs/types/index.d.ts
> +declare function log( str: String, ...args: any ): any;
I believe `args` is optional, so want `args?: any`.

2022-09-29 18:12 UTC, kgryte commented on lib/node_modules/@stdlib/array/log/docs/types/index.d.ts
> +* var log = require( '@stdlib/array/log' );
In TypeScript declarations, we need to use backticks around import statements. E.g.,

```
var log = require( `@stdlib/array/log` );
```

2022-09-29 18:13 UTC, kgryte commented on lib/node_modules/@stdlib/array/log/docs/types/index.d.ts
> +* @throws {TypeError} first argument must be a string
This line is not needed, as passing a non-string value is not allowed in TypeScript. Meaning, there will be a compiler error. We only document errors that a compiler would not catch, such as L27.

2022-09-29 18:15 UTC, kgryte commented on lib/node_modules/@stdlib/array/log/docs/types/index.d.ts
> +* Insert array element values into a format string and print the result.
Should be `Inserts`. Notice the `s`.

2022-09-29 18:16 UTC, kgryte commented
@Planeshifter Any thoughts on the package name, here?

2022-09-30 20:02 UTC, Planeshifter commented
`@stdlib/array/log` with variable name `log` seems fine with me. Could use `logArray`. If we were concerned about `log` being confused with logarithm, another alternative may be `print`?

2022-09-30 20:05 UTC, kgryte commented
@planeshifter another question is whether this package belongs in `@stdlib/array`.

2022-10-02 10:01 UTC, kgryte commented on lib/node_modules/@stdlib/array/log/docs/repl.txt
> +    --------
```suggestion
    --------

```

2022-10-02 10:02 UTC, kgryte commented on lib/node_modules/@stdlib/array/log/docs/types/index.d.ts
> +declare function log( str: String, ...args: any ): void;
```suggestion
declare function log( str: string, ...args: any ): void;
```

2022-10-02 10:03 UTC, kgryte commented on lib/node_modules/@stdlib/array/log/docs/types/test.ts
> +// The function doesn't throw an error
```suggestion
// The function returns undefined...
```

2022-12-11 10:21 UTC, kgryte commented
After thinking about this a bit more, I am thinking that we should create a new top-level `console` namespace (i.e., `@stdlib/console`) for housing this and other [`console`](https://developer.mozilla.org/en-US/docs/Web/API/console) related packages. In which case, this package could be moved to `@stdlib/console/log-array` (or `@stdlib/console/log-each`; I think this name is better).

Having a `console` namespace could be useful, as there is enough variation among `console` implementations in JS engines that having consistent behavior (i.e., a set of standard APIs) could be useful. These APIs would largely be independent of our planned `printf` set of APIs.

## Prior art

-   [console-browserify](https://github.com/browserify/console-browserify): especially among older engines, having a consistent `console` API motivated Browserify and other bundlers to ship an interface consistent with what existed in Node.js.

Thoughts, @Planeshifter?

2022-12-14 01:43 UTC, Planeshifter commented
@kgryte I think we should go ahead and create a top-level `console` namespace!

2022-12-14 03:38 UTC, kgryte commented
Cool. I'll add the top-level namespace. @steff456 Once I do, we'll want to rename the package in this PR. I'll circle back once we have everything in place.

2022-12-14 13:04 UTC, steff456 commented
Ok! I'll wait for the signal 😉

2022-12-15 22:47 UTC, kgryte commented
@steff456 The `console` namespace has now been created. Would you mind renaming this package to

```
@stdlib/console/log-each
```

and updating the alias from `log` to `logEach`?

2022-12-15 22:48 UTC, kgryte commented
You'll need to merge in the latest commits from `develop`.

2022-12-28 06:27 UTC, kgryte commented on lib/node_modules/@stdlib/console/log-each/README.md
> +var logEach = require( '@stdlib/array/log-each' );
```suggestion
var logEach = require( '@stdlib/console/log-each' );
```

2022-12-28 06:31 UTC, kgryte commented on lib/node_modules/@stdlib/console/log-each/lib/logger.js
> +/**
```suggestion
// MODULES //

var log = require( '@stdlib/console/log' );


// MAIN //

/**
```

2022-12-28 06:31 UTC, kgryte commented on lib/node_modules/@stdlib/console/log-each/lib/logger.js
> +	console.log( str );
```suggestion
	log( str );
```

2022-12-28 06:35 UTC, kgryte commented on lib/node_modules/@stdlib/console/log-each/package.json
> +    "name": "@stdlib/array/log-each",
```suggestion
    "name": "@stdlib/console/log-each",
```

2022-12-28 06:38 UTC, kgryte commented on lib/node_modules/@stdlib/console/log-each/README.md
> +var logEach = require( '@stdlib/array/log-each' );
```suggestion
var logEach = require( '@stdlib/console/log-each' );
```

2022-12-28 06:39 UTC, kgryte approved these changes
LGTM! Thanks, @steff456!

2022-12-28 06:44 UTC, merged