Refactor frexp API
stdlib-js/stdlib pull request #558
Opened 2022-10-20 23:56 UTC by steff456

## Description

> What is the purpose of this pull request?

This pull request:

-   Refactors `frexp` package to support `assign` when the result needs to be overwrite a given array

## Related Issues

> Does this pull request have any related issues?

This PR is part of https://github.com/stdlib-js/todo/issues/1435

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2022-10-25 22:07 UTC, kgryte requested changes

2022-10-25 22:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/frexp/benchmark/benchmark.js
> +bench( pkg+'::assign', function benchmark( b ) {
```suggestion
bench( pkg+':assign', function benchmark( b ) {
```

2022-10-25 22:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/frexp/docs/repl.txt
>      > out = new {{alias:@stdlib/array/float64}}( 2 );
```suggestion
    > var out = new {{alias:@stdlib/array/float64}}( 2 );
```

New example block, so need to freshly declare any variables.

2022-10-25 22:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/frexp/docs/repl.txt
> +{{alias}}.assign( x, out, stride, offset )
L26 should be:

```
out: Array<number>
```

No longer can the output array be an Object or typed array.

2022-10-25 22:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/frexp/docs/types/index.d.ts
> +	( x: number ): Collection;
```suggestion
	( x: number ): Array<number>;
```

For the main export, only an `Array` containing numbers is returned.

2022-10-25 22:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/frexp/docs/types/test.ts
>  // The compiler throws an error if the function is provided a last argument other than a number...
```suggestion
// The compiler throws an error if the function is provided an argument which is not a number...
```

2022-10-25 22:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/frexp/docs/types/test.ts
> +}
```suggestion
```

These tests are no longer needed.

2022-10-25 22:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/frexp/lib/main.js
> +	return fcn( x, [0.0, 0.0], 1, 0 );
```suggestion
	return fcn( x, [ 0.0, 0 ], 1, 0 );
```

2022-10-25 22:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/frexp/lib/main.js
>  * @returns {(Array|TypedArray|Object)} output array
```suggestion
* @returns {Array<number>} output array
```

2022-10-25 22:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/frexp/test/test.assign.js
> +tape( 'the function supports provided an output array', function test( t ) {
```suggestion
tape( 'the function supports providing an output array', function test( t ) {
```

2022-10-25 22:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/frexp/test/test.assign.js
> +tape( 'the function supports provided an output typed array', function test( t ) {
```suggestion
tape( 'the function supports providing an output typed array', function test( t ) {
```

2022-10-25 22:10 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/frexp/docs/repl.txt
> +{{alias}}.assign( x, out, stride, offset )
@steff456 I think this is the main thing to be changed.

2022-10-25 22:11 UTC, kgryte commented
@steff456 As part of this refactor, did you identify any dependents (i.e., packages using `frexp`) that would need to be updated as a result of refactoring to an `assign` API?

2022-10-25 22:13 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/frexp/lib/assign.js
> +	normalize( x, X, stride, offset );
```suggestion
	normalize( x, X, 1, 0 );
```

The stride and offset should remain `1` and `0`, as these arguments refer to `X`, the workspace, not `out`.

2022-10-25 22:14 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/frexp/lib/assign.js
> +	exp = floatExp( X[ offset ] ) + X[ offset + stride ] + 1;
```suggestion
	exp = floatExp( X[ 0 ] ) + X[ 1 ] + 1;
```

The workspace is distinct from the output array.

2022-10-25 22:14 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/frexp/lib/assign.js
> +	toWords( WORDS, X[ offset ] );
```suggestion
	toWords( WORDS, X[ 0 ] );
```

2022-10-25 22:15 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/frexp/lib/assign.js
> +	high = WORDS[ offset + stride ];
```suggestion
	high = WORDS[ 1 ];
```

The workspace is distinct from the output array.

2022-10-25 22:15 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/frexp/lib/assign.js
> +	x = fromWords( high, WORDS[ offset + stride ] );
```suggestion
	x = fromWords( high, WORDS[ 1 ] );
```

Workspace is distinct from the output array.

2022-10-25 22:16 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/frexp/lib/assign.js
> +	high = WORDS[ 1 ];
```suggestion
	high = WORDS[ 0 ];
```

2022-10-25 22:16 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/frexp/lib/assign.js
> +	exp = floatExp( X[ 0 ] ) + X[ 1 ] + 1;
```suggestion
	exp = floatExp( X[0] ) + X[ 1 ] + 1;
```

2022-10-25 22:26 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/frexp/test/test.assign.js
> +		f = frexp( x[i], out, 1, 0 );
```suggestion
		f = frexp( x, out, 1, 0 );
```

2022-10-25 22:26 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/frexp/test/test.assign.js
> +		f = frexp( x[i], out, 1, 0 );
```suggestion
		f = frexp( x, out, 1, 0 );
```

2022-10-25 22:28 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/frexp/test/test.assign.js
> +		t.equal( f, out, 'returns output array' );
```suggestion
		t.equal( f, out, 'returns output array' );

		// Compute the absolute value of the normalized fraction:
		f = abs( f[ 0 ] );
```

2022-10-25 22:29 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/frexp/test/test.assign.js
> +		t.equal( f, x, 'frac * 2^exp equals ' + x );
```suggestion
		t.equal( f, out, 'returns output array' );

		if ( f[ 1 ] > BIAS ) {
			f = f[ 0 ] * pow( 2.0, BIAS ) * pow( 2.0, f[1]-BIAS );
		} else {
			f = f[ 0 ] * pow( 2.0, f[ 1 ] );
		}
		t.equal( f, x, 'frac * 2^exp equals ' + x );
```

2022-10-25 22:30 UTC, steff456 commented
> @steff456 As part of this refactor, did you identify any dependents (i.e., packages using frexp) that would need to be updated as a result of refactoring to an assign API?

I need to double check!

2022-10-26 20:09 UTC, steff456 commented
Update: there's no dependents that need to be updated 😉

2022-10-26 20:23 UTC, kgryte commented
@steff456 Thanks for checking!

2022-10-26 20:28 UTC, kgryte commented
@steff456 Aren't `@stdlib/stats/incr/prod` and `@stdlib/stats/incr/mprod` affected by the changes introduced in this PR?

2022-10-26 20:45 UTC, steff456 commented
You are right! I'm not sure why my editor was excluding files in the search, but now it is fixed! Thanks for double checking on your side @kgryte :)

2022-10-26 20:49 UTC, Planeshifter commented
@steff456 I think any `node_modules` folders are being ignored by default in most code editors. I remember having had to configure my workspace to make sure that the `lib/node_modules/@stdlib` folder and its sub-folders are not ignored.

2022-10-26 21:17 UTC, kgryte commented on lib/node_modules/@stdlib/stats/incr/mprod/lib/main.js
> +	frexp.assign( x, workspace );
```suggestion
	frexp.assign( x, workspace, 1, 0 );
```

Missing stride and offset.

2022-10-26 21:18 UTC, kgryte commented on lib/node_modules/@stdlib/stats/incr/mprod/lib/main.js
> +		frexp( acc.frac, workspace );
```suggestion
		frexp( acc.frac, workspace, 1, 0 );
```

Missing stride and offset.

2022-10-26 21:18 UTC, kgryte commented on lib/node_modules/@stdlib/stats/incr/prod/lib/main.js
> +		frexp.assign( x, PARTS );
```suggestion
		frexp.assign( x, PARTS, 1, 0 );
```

Missing stride and offset.

2022-10-26 21:18 UTC, kgryte commented on lib/node_modules/@stdlib/stats/incr/prod/lib/main.js
> +			frexp.assign( frac, PARTS );
```suggestion
			frexp.assign( frac, PARTS, 1, 0 );
```

Missing stride and offset.

2022-10-26 21:22 UTC, kgryte approved these changes
LGTM. Thanks, @steff456!

2022-10-26 21:34 UTC, Planeshifter approved these changes

2022-10-26 21:34 UTC, merged