Refactor sincos API
stdlib-js/stdlib pull request #598
Opened 2022-10-31 22:25 UTC by steff456

## Description

> What is the purpose of this pull request?

This pull request:

- Refactors `sincos` package to support assign when the result needs to be overwrite a given array

## Related Issues

> Does this pull request have any related issues?

This PR is part of https://github.com/stdlib-js/todo/issues/1435

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2022-11-02 06:36 UTC, kgryte requested changes

2022-11-02 06:36 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sincos/README.md
> +Simultaneously computes the [sine][@stdlib/math/base/special/sin] and [cosine][@stdlib/math/base/special/cos] of a `number` (in radians), and assigns results to a provided output array.
```suggestion
Simultaneously computes the [sine][@stdlib/math/base/special/sin] and [cosine][@stdlib/math/base/special/cos] of a `number` (in radians) and assigns results to a provided output array.
```

2022-11-02 06:36 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sincos/benchmark/benchmark.js
> +bench( pkg+'::assign', function benchmark( b ) {
```suggestion
bench( pkg+':assign', function benchmark( b ) {
```

2022-11-02 06:36 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sincos/docs/repl.txt
> +    Simultaneously computes the sine and cosine of a number, and assigns
```suggestion
    Simultaneously computes the sine and cosine of a number and assigns
```

2022-11-02 06:36 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sincos/docs/types/index.d.ts
> +	* @param out - destination array
```suggestion
	* @param out - output array
```

2022-11-02 06:36 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sincos/docs/types/test.ts
>  // The function returns a collection...
```suggestion
// The function returns an array of numbers...
```

2022-11-02 06:36 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sincos/lib/assign.js
> +* Simultaneously computes the sine and cosine of a number, and assigns results to a provided output array.
```suggestion
* Simultaneously computes the sine and cosine of a number and assigns results to a provided output array.
```

2022-11-02 06:36 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sincos/lib/assign.js
> +* @param {Collection} out - destination array
```suggestion
* @param {Collection} out - output array
```

2022-11-02 06:36 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sincos/lib/kernel_sincos.js
> +* @param {Collection} out - destination array
```suggestion
* @param {Collection} out - output array
```

2022-11-02 06:36 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sincos/lib/main.js
> +var computeSincos = require( './assign.js' );
```suggestion
var assign = require( './assign.js' );
```

2022-11-02 06:36 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sincos/lib/main.js
> +	return computeSincos( x, [ 0.0, 0.0 ], 1, 0 );
```suggestion
	return assign( x, [ 0.0, 0.0 ], 1, 0 );
```

2022-11-02 06:36 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sincos/test/test.assign.js
> +tape( 'the function computes in-place the sine and cosine (for -256*pi < x < 0)', function test( t ) {
```suggestion
tape( 'the function computes the sine and cosine (for -256*pi < x < 0)', function test( t ) {
```

2022-11-02 06:36 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sincos/test/test.assign.js
> +	t.equal( v, z, 'returns a reference to out' );
```suggestion
	t.equal( v, z, 'returns output array' );
```

2022-11-02 06:36 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sincos/test/test.assign.js
> +	t.equal( v, z, 'returns a reference to out' );
```suggestion
	t.equal( v, z, 'returns output array' );
```

2022-11-02 06:36 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sincos/test/test.assign.js
> +		t.equal( y, z, 'returns a reference to out' );
```suggestion
		t.equal( y, z, 'returns output array' );
```

2022-11-02 06:36 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sincos/test/test.assign.js
> +		t.equal( y, z, 'returns a reference to out' );
```suggestion
		t.equal( y, z, 'returns output array' );
```

2022-11-02 06:36 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sincos/test/test.assign.js
> +		t.equal( y, z, 'returns a reference to out' );
```suggestion
		t.equal( y, z, 'returns output array' );
```

2022-11-02 06:36 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sincos/test/test.assign.js
> +		t.equal( y, z, 'returns a reference to out' );
```suggestion
		t.equal( y, z, 'returns output array' );
```

2022-11-02 06:36 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sincos/test/test.assign.js
> +		t.equal( y, z, 'returns a reference to out' );
```suggestion
		t.equal( y, z, 'returns output array' );
```

2022-11-02 06:36 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sincos/test/test.assign.js
> +		t.equal( y, z, 'returns a reference to out' );
```suggestion
		t.equal( y, z, 'returns output array' );
```

2022-11-02 06:36 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sincos/test/test.assign.js
> +		t.equal( y, z, 'returns a reference to out' );
```suggestion
		t.equal( y, z, 'returns output array' );
```

2022-11-02 06:36 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sincos/test/test.assign.js
> +	t.equal( v, z, 'returns a reference to out' );
```suggestion
	t.equal( v, z, 'returns output array' );
```

2022-11-02 06:36 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sincos/test/test.assign.js
> +	t.strictEqual( parts, out, 'returns output typed array' );
```suggestion
	t.strictEqual( parts, out, 'returns output array' );
```

2022-11-02 06:39 UTC, kgryte approved these changes

2022-11-02 06:39 UTC, kgryte commented
LGTM. Thanks, @steff456!

2022-11-02 06:51 UTC, kgryte commented
Test failures do not seem to originate from the tests in this PR. Instead, they are coming from `besselj0`. These tests seem to be failing due to flushing subnormals to zero. Locally, `besselj0` tests pass for me.

2022-11-02 06:51 UTC, merged

2022-11-03 00:41 UTC, kgryte commented
**Update**: discovered that test failures did originate from this PR. Bessel function implementations depend on `@stdlib/math/base/special/sincos`, and, in particular, the implementations depended on the refactored assignment API. However, this PR did not update dependents based on the changes in this PR.

@steff456 When performing these types of refactorings, we need to ensure that all downstream dependents are migrated to the new APIs.

Test failures should be addressed in https://github.com/stdlib-js/stdlib/commit/f2d99e153034f5953dfda019a81b4c3f81c7854b and https://github.com/stdlib-js/stdlib/commit/4e77dbfb3dfbf644b320364972b88875d33aee1c.

2022-11-03 17:33 UTC, steff456 commented
Thanks for fixing it so quickly! I'll take more care of reviewing dependents for my next PRs 😅