Add C implementation for `@stdlib/math/base/special/kernel-sin`
stdlib-js/stdlib pull request #655
Opened 2022-12-06 05:06 UTC by Pranavchiku

Resolves #644 .

## Checklist

- [x] update readme.md
- [ ] include.gypi
- [ ] binding.gyp
- [ ] include/stdlib/math/base/special/
- [ ] src
- [ ] manifest.json
- [ ] lib
- [ ] examples
- [ ] benchmark
- [ ] test
* * *

@kgryte

2022-12-06 06:02 UTC, Pranavchiku commented
All tests and benchmarks passed.

2022-12-06 07:03 UTC, kgryte requested changes

2022-12-06 07:03 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/kernel-sin/README.md
> +stdlib_base_kernel_sin( 0.0, 0.0 ) // returns ~0.0
```suggestion
var v = stdlib_base_kernel_sin( 0.0, 0.0 );
// returns ~0.0

v = stdlib_base_kernel_sin( 0.619, 9.279e-18 );
// returns ~0.58
```

We use `// returns` doctest annotations for C examples just as we do for JS examples.

2022-12-06 07:03 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/kernel-sin/README.md
> +-   **y**: `[in] double` input value.
```suggestion
-   **x**: `[in] double` input value (in radians, assumed to be bounded by `~pi/4` in magnitude).
-   **y**: `[in] double` tail of `x`.
```

2022-12-06 07:03 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/kernel-sin/README.md
> +        y = (double)rand() / (double)RAND_MAX;
This example is not representative of how this function would be used. See the JS example and the note included in the README regarding `x` and `y`. Otherwise, the results won't make sense.

For `x`, hardcode a list of values between -pi/4 and pi/4 and set `y` to `0`. This is what we do in the JS example.

2022-12-06 07:03 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/kernel-sin/README.md
> +int main() {
```suggestion

int main() {
```

Always include a blank line after includes. This is true for both C and JS according to project conventions.

2022-12-06 07:03 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/kernel-sin/README.md
> +    double out;
Order according to char length.

2022-12-06 07:03 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/kernel-sin/benchmark/benchmark.native.js
> +		x = ( randu()*8.0/PI ) - ( 4.0/PI );
These values are wrong, based on the expectations of the function. Would you mind correcting and also fixing the `benchmark.js` file?

2022-12-06 07:03 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/kernel-sin/benchmark/c/benchmark.c
> +#define NAME "kernel-sin"
```suggestion
* Benchmark `kernel_sin`.
*/
#include "stdlib/math/base/special/kernel_sin.h"
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include <time.h>
#include <sys/time.h>

#define NAME "kernel_sin"
```

2022-12-06 07:03 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/kernel-sin/benchmark/c/benchmark.c
> +		y = rand_double();
These values are not correct, based on expected usage. Once the JS benchmarks are fixed, use similar values here.

2022-12-06 07:03 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/kernel-sin/examples/c/example.c
> +		x = (double)rand() / (double)RAND_MAX;
Same comments as in README.

2022-12-06 07:03 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/kernel-sin/lib/native.js
> +* @param {number} x - input value (in radians, assumed to be bounded by `~pi/4` in magnitude)
```suggestion
* @private
* @param {number} x - input value (in radians, assumed to be bounded by `~pi/4` in magnitude)
```

2022-12-06 07:03 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/kernel-sin/src/main.c
> +#include <math.h>
```suggestion
```

Why are these necessary?

2022-12-06 07:03 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/kernel-sin/src/main.c
> +*
```suggestion
```

Only include headers when they are needed.

2022-12-06 07:03 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/kernel-sin/src/main.c
> +* @param y    input value
These should be updated to match JS descriptions.

2022-12-08 04:27 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/kernel-sin/README.md
> +        y = (double)rand() / (double)RAND_MAX;
On it.

2022-12-08 04:44 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/kernel-sin/src/main.c
> +#include <math.h>
Sorry for that, I forgot to remove these.

2022-12-08 04:57 UTC, Pranavchiku commented
@kgryte this PR can have a review :)

2022-12-08 05:00 UTC, kgryte commented
@Pranavchiku Awesome. Will try to review in a day or so.

2022-12-08 06:03 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/kernel-sin/README.md
> +var v = stdlib_base_kernel_sin( 0.0, 0.0 );
```suggestion
double v = stdlib_base_kernel_sin( 0.0, 0.0 );
```

2022-12-08 06:05 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/kernel-sin/README.md
> +// returns ~0.58
```suggestion
double out = stdlib_base_kernel_sin( 0.0, 0.0 );
// returns ~0.0

out = stdlib_base_kernel_sin( 0.619, 9.279e-18 );
// returns ~0.58
```

2022-12-09 09:57 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/kernel-sin/README.md
> +#include <math.h>
```suggestion
```

2022-12-09 09:57 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/kernel-sin/README.md
> +#include <stdint.h>
```suggestion
```

2022-12-09 09:58 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/kernel-sin/README.md
> +#include <inttypes.h>
```suggestion
```

2022-12-09 09:58 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/kernel-sin/README.md
> +
```suggestion
    double x[] = { -0.7853981633974483, -0.6108652381980153, -0.4363323129985824, -0.26179938779914946, -0.08726646259971649, 0.08726646259971649,
    0.26179938779914935, 0.43633231299858233, 0.6108652381980153, 0.7853981633974483 };
   
    double out;
    int i;

```

2022-12-09 09:59 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/kernel-sin/README.md
> +        printf ( "x[ i ]: %lf, y: %lf, out: %lf\n", x[ i ], y, out );
```suggestion
        out = stdlib_base_kernel_sin( x[ i ], 0.0 );
        printf ( "x[ i ]: %lf, y: %lf, out: %lf\n", x[ i ], 0.0, out );
```

2022-12-09 10:00 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/kernel-sin/benchmark/c/benchmark.c
> +		printf( "# c::%s\n", NAME );
```suggestion
		printf( "# c::native::%s\n", NAME );
```

2022-12-09 10:01 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/kernel-sin/examples/c/example.c
> +        printf ( "x[ i ]: %lf, y: %lf, out: %lf\n", x[ i ], y, out );
```suggestion
#include <stdlib.h>
#include <stdio.h>

int main() {
    double x[] = { -0.7853981633974483, -0.6108652381980153, -0.4363323129985824, -0.26179938779914946, -0.08726646259971649, 0.08726646259971649, 0.26179938779914935, 0.43633231299858233, 0.6108652381980153, 0.7853981633974483 };
    
    double out;
    int i;
    for ( i = 0; i < 10; i++ ) {
        out = stdlib_base_kernel_sin( x[ i ], 0.0 );
        printf ( "x[ i ]: %lf, y: %lf, out: %lf\n", x[ i ], 0.0, out );
```

2022-12-09 10:02 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/kernel-sin/src/addon.c
> +#include <stdbool.h>
```suggestion
```

2022-12-09 10:02 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/kernel-sin/src/main.c
> +* double out = stdlib_base_kernel_sin( x, y );
```suggestion
* double out = stdlib_base_kernel_sin( 0.5, 0.0 );
```

2022-12-09 10:03 UTC, kgryte approved these changes

2022-12-09 10:04 UTC, kgryte commented
LGTM. Thanks, @Pranavchiku!

2022-12-09 10:04 UTC, merged