Add utility to retrieve user-specific configuration file directory
stdlib-js/stdlib pull request #68
Opened 2016-12-13 04:47 UTC by Planeshifter

Resolves #61.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

* [x] Read, understood, and followed the [contributing guidelines][contributing], including the relevant style guides.
* [x] Read and understand the [Code of Conduct][code-of-conduct].
* [x] Read and understood the [licensing terms][license].
* [x] Searched for existing issues and pull requests __before__ submitting this pull request.
* [x] Filed an issue (or an issue already existed) __prior to__ submitting this pull request.
* [x] Rebased onto latest `develop`.
* [x] Submitted against `develop` branch.

## Description

> What is the purpose of this pull request?

This pull request:

* contains a straight-forward port of [utils-configdir](https://github.com/kgryte/utils-configdir)

## Related Issues

> Does this pull request have any related issues?

This pull request:

* resolves #
* fixes #

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

---

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/master/CONTRIBUTING.md
[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/master/CODE_OF_CONDUCT.md
[license]: https://github.com/stdlib-js/stdlib/blob/master/LICENSE

2016-12-13 05:04 UTC, kgryte requested changes

2016-12-13 05:04 UTC, kgryte commented on lib/node_modules/@stdlib/utils/configdir/lib/configdir.js
> +* @returns {(string|null)} directory
Add `throws` annotation.

2016-12-13 05:04 UTC, kgryte commented on lib/node_modules/@stdlib/utils/configdir/lib/configdir.js
> +var path = require( 'path' );
`var join = require( 'path' ).join;`

This change will affect subsequent usage below.

2016-12-13 05:04 UTC, kgryte commented on lib/node_modules/@stdlib/utils/configdir/README.md
> +On non-windows platforms, if the function is unable to locate the current user's [`home`][@stdlib/utils/homedir] directory, the function returns `null`.
We should probably capitalize Windows here => `non-Windows`. Same goes for similar usage in `./test/test.js`.

2016-12-13 05:04 UTC, kgryte commented on lib/node_modules/@stdlib/utils/configdir/README.md
> +On non-windows platforms, if the function is unable to locate the current user's [`home`][@stdlib/utils/homedir] directory, the function returns `null`.
Should also add

> Similarly, on Windows platforms, if the function is unable to locate an application data directory, the function also returns `null`.

2016-12-13 15:39 UTC, Planeshifter commented
Thanks! Made the requested changes.

2016-12-14 02:25 UTC, kgryte approved these changes

2016-12-14 02:25 UTC, merged