Feature/factorial2
stdlib-js/stdlib pull request #72
Opened 2016-12-17 13:29 UTC by chrisdamba

Resolves # .

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

* [ ] Read, understood, and followed the [contributing guidelines][contributing], including the relevant style guides.
* [ ] Read and understand the [Code of Conduct][code-of-conduct].
* [ ] Read and understood the [licensing terms][license].
* [ ] Searched for existing issues and pull requests __before__ submitting this pull request.
* [ ] Filed an issue (or an issue already existed) __prior to__ submitting this pull request.
* [ ] Rebased onto latest `develop`.
* [ ] Submitted against `develop` branch.

## Description

> What is the purpose of this pull request?

This pull request:

* a
* b
* c

## Related Issues

> Does this pull request have any related issues?

This pull request:

* resolves #
* fixes #

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

---

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/master/CONTRIBUTING.md
[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/master/CODE_OF_CONDUCT.md
[license]: https://github.com/stdlib-js/stdlib/blob/master/LICENSE

2016-12-17 17:46 UTC, Planeshifter requested changes
Thank you very much for this pull request! I left some comments.

2016-12-17 17:46 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/factorial2/README.md
> +The [double factorial][double-factorial-function] is implemented for integer values in terms of the [Factorial][@stdlib/math/base/special/factorial] function using the relation:
Missing `[@stdlib/math/base/special/factorial]: https://github.com/stdlib-js/stdlib` in the link section at the end of the file.

2016-12-17 17:46 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/factorial2/examples/index.js
> +var factorial = require( './../lib' );
`factorial` should be replaced by `factorial2` in this file.

2016-12-17 17:46 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/factorial2/lib/factorial2.js
> +		(isInteger( x ) && x < 0) ||
Use `isNegativeInteger` module instead.

2016-12-17 17:46 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/factorial2/package.json
> +{
The contents of the `package.json` files have changed, take a look at the [snippet](https://github.com/stdlib-js/stdlib/blob/develop/tools/snippets/package.json). Fields that need to be updated: `author`, `contributors`, `repository`,  `homepage`, `bugs`, and `license`.

2016-12-17 17:46 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/factorial2/test/test.js
> +
Add empty line before `// TESTS //`.

2016-12-17 17:46 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/factorial2/test/test.js
> +			t.ok( delta <= tol, 'within tolerance. x: ' + x[ i ] + '. Value: ' + v + '. Expected: ' + expected[ i ] + '. Tolerance: ' + tol + '.' );
Can you replace the last two lines with 

``` javascript
tol = EPS * abs( expected[ i ] );
t.ok( delta <= tol, 'within tolerance. x: '+x[i]+'. Value: '+v+'. E: '+expected[i]+'. Δ: '+delta+'. tol: '+tol );
```

and check whether the tests still pass?

2016-12-17 17:46 UTC, Planeshifter commented on lib/node_modules/@stdlib/math/base/special/factorial2/test/test.js
> +		t.ok( delta <= tol, 'within tolerance. x: ' + x[ i ] + '. Value: ' + v + '. Expected: ' + expected[ i ] + '. Tolerance: ' + tol + '.' );
Can you replace the last two lines with 

``` javascript
tol = 2.0e-14 * abs( expected[ i ] );
t.ok( delta <= tol, 'within tolerance. x: '+x[i]+'. Value: '+v+'. E: '+expected[i]+'. Δ: '+delta+'. tol: '+tol );
```

and check whether the tests still pass?

2016-12-17 17:54 UTC, kgryte commented
Awesome. @chrisdamba Can you also complete the PR template checklist and update the description section.

2016-12-17 17:57 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/factorial2/README.md
> +The double factorial should not be confused with the factorial function iterated twice, written as (n!)! and not n!!
> Note that the double factorial should not...

2016-12-17 17:57 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/factorial2/README.md
> +The [Gamma][@stdlib/math/base/special/gamma] function extends the [double factorial][double-factorial-function] function for non-integer values.
> function to non-integer values.

2016-12-17 18:00 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/factorial2/lib/factorial2.js
> +
Add another newline.

2016-12-17 18:01 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/factorial2/lib/factorial2.js
> +var DOUBLE_FACTORIALS = require( './doublefactorials.json' );
This should be the last `require` statement. Order of `requires`:

* Builtins; e.g., `path`, `Buffer`, etc.
* External packages; e.g., `@stdlib/math/base/special/sqrt`.
* Relative modules; e.g., `./doublefactorials.json`.

2016-12-17 18:03 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/factorial2/lib/factorial2.js
> +		(isInteger( x ) && x < 0) ||
Alternatively, keep `isInteger`, but cache the result so you can use the `boolean` later at line `66`.

``` javascript
var isInt;

isInt = isInteger( x );
if ( isInt && x < 0 ) {
   return NaN;
}
...
if ( isInt ) {
  ...
}
```

2016-12-17 18:09 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/factorial2/test/fixtures/julia/runner.jl
> +#!/usr/bin/env julia
Might be better to use Python and SciPy for generating test fixtures, as SciPy actually has a `factorial2` implementation against which we can test.

2016-12-17 18:11 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/factorial2/test/test.js
> +		t.ok( delta <= tol, 'within tolerance. x: ' + x[ i ] + '. Value: ' + v + '. Expected: ' + expected[ i ] + '. Tolerance: ' + tol + '.' );
The tolerance should be scaled via `epsilon`.

``` javascript
tol = <scalar> * EPS * abs( expected[ i ] );
```

2016-12-17 19:20 UTC, kgryte commented
@chrisdamba Once you make the requested changes, if you could `squash` the commits into a single commit, that would be awesome! This would make the commit history a bit cleaner for us, so that we can identify when a unit of functionality was initially added.

Thanks again for all your work!

2016-12-18 13:26 UTC, chrisdamba commented on lib/node_modules/@stdlib/math/base/special/factorial2/lib/factorial2.js
> +		(isInteger( x ) && x < 0) ||
Good call :)

2016-12-18 13:42 UTC, chrisdamba commented on lib/node_modules/@stdlib/math/base/special/factorial2/test/test.js
> +		t.ok( delta <= tol, 'within tolerance. x: ' + x[ i ] + '. Value: ' + v + '. Expected: ' + expected[ i ] + '. Tolerance: ' + tol + '.' );
If I scale the tolerance with epsilon, the tests break.

2016-12-18 13:45 UTC, chrisdamba commented on lib/node_modules/@stdlib/math/base/special/factorial2/test/test.js
> +		t.ok( delta <= tol, 'within tolerance. x: ' + x[ i ] + '. Value: ' + v + '. Expected: ' + expected[ i ] + '. Tolerance: ' + tol + '.' );
Can you explain the rationale behind scaling the tolerance with epsilon? Also, why can't we apply the same for the factorial tests?

2016-12-18 15:14 UTC, chrisdamba commented on lib/node_modules/@stdlib/math/base/special/factorial2/test/fixtures/julia/runner.jl
> +#!/usr/bin/env julia
I think so too but I've discovered some errors whilst trying to generate the fixtures, as in the attached screenshot.
![selection_001](https://cloud.githubusercontent.com/assets/2035056/21294454/b08edb26-c534-11e6-9ce9-3f438e5c0ead.png)

2016-12-18 15:44 UTC, chrisdamba commented on lib/node_modules/@stdlib/math/base/special/factorial2/package.json
> +{
Not so sure what values that need to be updated for this.

2016-12-18 15:51 UTC, chrisdamba commented on lib/node_modules/@stdlib/math/base/special/factorial2/test/test.js
> +			t.ok( delta <= tol, 'within tolerance. x: ' + x[ i ] + '. Value: ' + v + '. Expected: ' + expected[ i ] + '. Tolerance: ' + tol + '.' );
This passes.

2016-12-18 18:49 UTC, kgryte requested changes

2016-12-18 18:49 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/factorial2/package.json
> +{
```
{
  "name": "@stdlib/math/base/special/factorial2",
  "version": "0.0.0",
  "description": "Evaluate a double factorial.",
  "author": {
    "name": "The Stdlib Authors",
    "url": "https://github.com/stdlib-js/stdlib/graphs/contributors"
  },
  "contributors": [
    {
      "name": "The Stdlib Authors",
      "url": "https://github.com/stdlib-js/stdlib/graphs/contributors"
    }
  ],
  "scripts": {},
  "main": "./lib",
  "repository": {
    "type": "git",
    "url": "git://github.com/stdlib-js/stdlib.git"
  },
  "homepage": "https://github.com/stdlib-js/stdlib",
  "keywords": [
    "stdlib",
    "stdmath",
    "mathematics",
    "math",
    "special functions",
    "special",
    "function",
    "factorial",
    "double factorial",
    "fact",
    "combinatorics",
    "gamma",
    "number"
  ],
  "bugs": {
    "url": "https://github.com/stdlib-js/stdlib/issues"
  },
  "dependencies": {},
  "devDependencies": {},
  "engines": {
    "node": ">=0.10.0"
  },
  "license": "Apache-2.0"
}
```

2016-12-18 18:49 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/factorial2/README.md
> +The [double factorial][double-factorial-function] is implemented for integer values in terms of the [Factorial][@stdlib/math/base/special/factorial] function using the relation:
Lowercase "factorial":

> ...in terms of the factorial function using the relation:

2016-12-18 18:49 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/factorial2/README.md
> +<!-- <equation class="equation" label="eq:double_factorial_function_and_factorial" align="center" raw="(2n)!! = 2^n * n!" alt="Factorial function extension via the Factorial function"> -->
Lowercase "Factorial"

2016-12-18 18:49 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/factorial2/README.md
> +<!-- <equation class="equation" label="eq:double_factorial_function_and_gamma" align="center" raw="(2n-1)!! = \Gamma \left( \frac{(2n+1)}{2} \right) * \frac{2^n}{\sqrt{\pi}}" alt="Factorial function
I do not believe you need the `*` (asterisk) in your equation. This applies here and immediately below.

2016-12-18 18:49 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/factorial2/README.md
> +<!-- <equation class="equation" label="eq:double_factorial_function_and_factorial" align="center" raw="(2n)!! = 2^n * n!" alt="Factorial function extension via the Factorial function"> -->
`2^n \cdot n!`

2016-12-18 18:49 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/factorial2/README.md
> +<div class="equation" align="center" data-raw-text="(2n)!! = 2^n * n!" data-equation="eq:double_factorial_function_and_factorial">
`2^n \cdot n!`

2016-12-18 18:49 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/factorial2/lib/factorial2.js
> +	var n;
Variables should be listed in order of length.

```
var isInt;
var n;
```

2016-12-18 18:49 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/factorial2/test/fixtures/julia/runner.jl
> +#!/usr/bin/env julia
Will try to reproduce locally.

2016-12-18 18:58 UTC, kgryte requested changes

2016-12-18 18:58 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/factorial2/test/test.js
>  			tol = EPS * Math.max( 1.0, abs( v ), abs( expected[ i ] ) );
This line should be

```
tol = EPS * abs( expected[ i ] );
```

2016-12-18 18:58 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/factorial2/test/test.js
>  		tol = 2.0e-14 * Math.max( 1.0, abs( v ), abs( expected[ i ] ) );
This line should be

```
tol = <num> * EPS * abs( expected[ i ] );
```
For example,
```
tol = 100.0 * EPS * abs( expected[ i ] );
```
The reason why we scale epsilon is that doing so provides more context as to how much results are off by and lessens the presence of so-called "magic" numbers. For instance, if we know that
```
actual = <number>;
expected = 1.0;
tol = 1.0 * EPS * abs( expected );
delta = abs( actual - expected );
bool = ( delta <= tol );
```
we know that actual value differs from the expected by only `1` bit. Similarly for other values, although the correspondence between units epsilon and number of differing bits is not 1:1.

2016-12-18 19:41 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/factorial2/test/fixtures/julia/runner.jl
> +#!/usr/bin/env julia
Did some investigating. Based on the SciPy and Boost implementations, the double factorial is simply not implemented for doubles. In the code above, if you cast `x` to integers, then the fixtures work.

As a result, unlikely to get either of those two reference implementations to provide test fixtures. 

Further, I am willing to hazard a guess that the Gamma relation is not straightforward. Boost only applies a Gamma approximation for odd integers. SciPy applies two different approximations based on whether an input integer is odd or even. While the double factorial __can__ be extended to reals, neither of those two implementations can serve as reference implementations.

2016-12-19 01:27 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/factorial2/lib/factorial2.js
> +var PIO2 = 1.57079632679489661923; // pi/2
This can be replaced by using `@stdlib/math/constants/float64-half-pi`.

2016-12-19 06:40 UTC, chrisdamba commented on lib/node_modules/@stdlib/math/base/special/factorial2/test/test.js
>  		tol = 2.0e-14 * Math.max( 1.0, abs( v ), abs( expected[ i ] ) );
Great explanation, thank you for this!

2016-12-19 06:43 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/factorial2/test/test.js
>  		tol = 2.0e-14 * Math.max( 1.0, abs( v ), abs( expected[ i ] ) );
No problem!

2016-12-19 06:46 UTC, chrisdamba commented on lib/node_modules/@stdlib/math/base/special/factorial2/lib/factorial2.js
> +var PIO2 = 1.57079632679489661923; // pi/2
I can see there are other areas in the library which need to be updated as well to use the constant e.g in `acos`, `asin` and `atan`.

2016-12-19 06:51 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/factorial2/lib/factorial2.js
> +var PIO2 = 1.57079632679489661923; // pi/2
Indeed. We have an internal backlog of various clean-up tasks. :( Currently picking them off as we have time. Thanks for the reminder!

2016-12-19 06:53 UTC, chrisdamba commented on lib/node_modules/@stdlib/math/base/special/factorial2/test/fixtures/julia/runner.jl
> +#!/usr/bin/env julia
So in this case do we leave the fixtures as they are?

2016-12-19 06:55 UTC, chrisdamba commented on lib/node_modules/@stdlib/math/base/special/factorial2/lib/factorial2.js
> +var PIO2 = 1.57079632679489661923; // pi/2
Wouldn't mind picking up this clean-up task if there's an issue not assigned.

2016-12-19 06:59 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/factorial2/test/fixtures/julia/runner.jl
> +#!/usr/bin/env julia
Based on my assessment, looks like the package implementation needs refactoring. Notably, unless we know of some implementation which actually does extend the double factorial function to all reals, we should stick to Boost and Scipy and only support integer inputs. For large inputs, similar to Boost, if not covered by the table, we can then apply a Gamma approximation*.

Once that is updated, the fixtures can be updated, and we'll have a better idea of where we stand.

* NOTE: I would be curious to know how the table lookup compares to integer multiplication in terms of performance as done in SciPy. Did you ever investigate this?

2016-12-19 07:01 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/factorial2/lib/factorial2.js
> +var PIO2 = 1.57079632679489661923; // pi/2
We can create an issue to this end, and, if you want to submit a separate PR addressing them, that would be great!

2016-12-19 07:06 UTC, chrisdamba commented on lib/node_modules/@stdlib/math/base/special/factorial2/test/fixtures/julia/runner.jl
> +#!/usr/bin/env julia
Definitely concur, needs some refactoring. I haven't actually done the investigation but I believe it's worth doing the comparison. Will do so and update you the results.

2016-12-19 07:08 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/factorial2/lib/factorial2.js
> +var PIO2 = 1.57079632679489661923; // pi/2
@chrisdamba See issue #74.

2016-12-19 07:09 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/factorial2/test/fixtures/julia/runner.jl
> +#!/usr/bin/env julia
Awesome. Thanks! Really appreciate your tending to this. 👍

2017-05-06 21:41 UTC, rreusser commented
I'd love to help get this merged. Am I to conclude that, at least for a start, restricting the implementation to integers is the right move? Is the function then strictly a lookup table?

2017-05-06 21:46 UTC, Planeshifter commented
Similar to Boost, For large inputs, similar to Boost, if not covered by the table, we can then apply a Gamma approximation*

2017-05-06 21:48 UTC, Planeshifter commented
Yes, restricting to integer inputs should be fine.

A table lookup and for large inputs a Gamma approximation should work, as Athan pointed out. Maybe have a look at how Boost does it.

2023-09-21 21:04 UTC, closed without merging

2023-09-21 21:04 UTC, kgryte commented
Closing this PR due to inactivity.