work on RFC: add constant pi divided by four #76
stdlib-js/stdlib pull request #77
Opened 2016-12-19 21:07 UTC by chrisdamba

Resolves #76 .

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

* [x] Read, understood, and followed the [contributing guidelines][contributing], including the relevant style guides.
* [x] Read and understand the [Code of Conduct][code-of-conduct].
* [x] Read and understood the [licensing terms][license].
* [x] Searched for existing issues and pull requests __before__ submitting this pull request.
* [x] Filed an issue (or an issue already existed) __prior to__ submitting this pull request.
* [x] Rebased onto latest `develop`.
* [x] Submitted against `develop` branch.

## Description

> What is the purpose of this pull request?

This pull request:

* is work on RFC: add constant pi divided by four #76

## Related Issues

> Does this pull request have any related issues?

This pull request:

* resolves #76

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

---

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/master/CONTRIBUTING.md
[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/master/CODE_OF_CONDUCT.md
[license]: https://github.com/stdlib-js/stdlib/blob/master/LICENSE

2016-12-19 23:06 UTC, kgryte requested changes

2016-12-19 23:06 UTC, kgryte commented on lib/node_modules/@stdlib/math/constants/float64-fourth-pi/lib/index.js
> +* @module @stdlib/math/constants/float64-half-pi
Need to fix the pkg path.

> @stdlib/math/constants/float64-fourth-pi

2016-12-19 23:06 UTC, kgryte commented on lib/node_modules/@stdlib/math/constants/float64-fourth-pi/lib/index.js
> +* var FOURTH_PI = require( '@stdlib/math/constants/float64-half-pi' );
Need to fix the require path.

> @stdlib/math/constants/float64-fourth-pi

2016-12-19 23:06 UTC, kgryte commented on lib/node_modules/@stdlib/math/constants/float64-fourth-pi/lib/index.js
> +* One half times the mathematical constant `π`.
> One fourth times the...

2016-12-19 23:06 UTC, kgryte commented on lib/node_modules/@stdlib/math/constants/float64-fourth-pi/README.md
> +One half times the mathematical constant [π][pi].
> One fourth times the...

2016-12-19 23:10 UTC, kgryte commented
Thanks for the PR! After making the requested changes, see the [Git guide](https://github.com/stdlib-js/stdlib/tree/develop/docs/style-guides/git) for `squash` and commit message info. When you `squash`, you should be able to amend the message per the guide.

2016-12-20 06:38 UTC, chrisdamba commented
Thanks @kgryte for the guidance. I apologise for the mess, will get it right eventually :)

2016-12-20 06:41 UTC, kgryte commented
@chrisdamba No worries! This is a valuable experience for us in knowing how to best onboard people into the project. Obviously, we have a fair amount of work to do to make the process smooth and sufficiently informed so that contributors can get up to speed as fast as possible.

2016-12-20 07:45 UTC, chrisdamba commented
Tidying up the PR by deleting and submitting a new one with the requested changes and clean commit based on the guidance.

2016-12-20 07:45 UTC, closed without merging