Add C implementation for `@stdlib/math/base/special/sqrt1pm1`
stdlib-js/stdlib pull request #778
Opened 2022-12-26 04:42 UTC by Pranavchiku

Resolves #773.

## Checklist

- [x] update readme.md
- [ ] include.gypi
- [ ] binding.gyp
- [ ] include/stdlib/math/base/special/
- [ ] src
- [ ] manifest.json
- [ ] lib
- [ ] examples
- [ ] benchmark
- [ ] test
* * *

@kgryte

2022-12-26 05:02 UTC, Pranavchiku commented on lib/node_modules/@stdlib/math/base/special/sqrt1pm1/src/main.c
> +* @return	  output value
```suggestion
* @param x     input value
* @return     output value
```

2022-12-26 05:04 UTC, Pranavchiku commented
All tests and benchmarks cleared, this PR can have a review.

2022-12-27 04:08 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrt1pm1/benchmark/cpp/native/benchmark.c
> +/**
@Pranavchiku I believe this file should be in a `/benchmark/c` folder, rather than `benchmark/cpp`.

2022-12-27 04:11 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrt1pm1/src/main.c
> +* The original C++ code and copyright notice are from the [Boost library]{@link https://github.com/boostorg/math/blob/fa1896fbc4c6fadc167307342ceb20bf2b6c0688/include/boost/math/special_functions/sqr
```suggestion
* The original C++ code and copyright notice are from the [Boost library]{@link https://github.com/boostorg/math/blob/fa1896fbc4c6fadc167307342ceb20bf2b6c0688/include/boost/math/special_functions/sqrt1pm1.hpp}. This implementation follows the original, but has been modified according to project conventions.
```

For C files, saying "modified for JavaScript" does not make sense.

2022-12-27 04:12 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrt1pm1/src/main.c
> +* // returns 0.0
```suggestion
* double out = stdlib_base_sqrt1pm1( 3.0 );
* // returns 1.0
```

Slightly more interesting example.

2022-12-27 04:15 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrt1pm1/test/test.native.js
> +		tol = 390.0 * EPS * abs( expected[ i ] );
This is a relatively high tolerance. Increased relative error due to either `expm1` or `log1p`. Matches JS implementation tests, so fine to use here.

2022-12-27 04:16 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrt1pm1/src/main.c
> +* The original C++ code and copyright notice are from the [Boost library]{@link https://github.com/boostorg/math/blob/fa1896fbc4c6fadc167307342ceb20bf2b6c0688/include/boost/math/special_functions/sqr
```suggestion
* The original C++ code and copyright notice are from the [Boost library]{@link https://github.com/boostorg/math/blob/fb82796a79788dc7f9973c9f0c492f8c1b54aa92/include/boost/math/special_functions/sqrt1pm1.hpp}. This implementation follows the original, but has been modified according to project conventions.
```

2022-12-27 04:17 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/sqrt1pm1/benchmark/cpp/native/Makefile
> +#/
This should be in `/benchmark/c`, not `*/cpp`.

2022-12-27 04:18 UTC, kgryte requested changes
@Pranavchiku LGTM. Just need to rename the benchmark folder for the C benchmarks. The Boost benchmarks should remain in `cpp`. For the plain C benchmarks, we place in a `c` directory.

2022-12-27 04:42 UTC, Pranavchiku commented
Thanks, done :)

2022-12-27 04:45 UTC, kgryte approved these changes
LGTM. Thanks, @Pranavchiku!

2022-12-27 04:46 UTC, kgryte commented
@Pranavchiku Looks like a temporary file was added to this PR.

2022-12-27 04:48 UTC, Pranavchiku commented
Ahh yes, so sorry for that! I am removing it.

2022-12-27 04:49 UTC, kgryte approved these changes

2022-12-27 04:49 UTC, merged