feat: add support for BLAS Level 1 `drotg` routine
stdlib-js/stdlib pull request #929
Opened 2023-02-26 09:37 UTC by Pranavchiku

Fixes #280.

## Checklist

- [x] Add readme.md
- [ ] repl.txt
- [ ] types
- [ ] package.json
- [ ] lib
- [ ] examples
- [ ] benchmark
- [ ] test 
* * *

@kgryte

2023-02-28 17:03 UTC, Pranavchiku commented
I guess, I have a lint error in `test.assign.js` and `test.main.js`, that was some `mixed space and tab indents`, I was unable to fix it hence used `--no-verify` commit, will polish it once all files get in this PR.

2023-02-28 17:40 UTC, Pranavchiku commented
All tests and benchmarks cleared, this PR can have a review.

2023-03-01 00:02 UTC, kgryte commented
@Pranavchiku Would you be willing to update this PR according to the changes made in commit <https://github.com/stdlib-js/stdlib/commit/36b75b3271e9c3ee29c2c4488c3c1420fe48dd2e>?

2023-03-01 23:29 UTC, kgryte commented
@Pranavchiku When getting mixed tabs and spaces lint errors, in Sublime Text, I simply select all text and then use built in IDE tools to convert indentation from spaces to tabs (or vice versa depending on the file type). In short, prefer resolving this locally rather than using `--no-verify`.

2023-03-02 00:46 UTC, kgryte commented on lib/node_modules/@stdlib/blas/base/drotg/benchmark/benchmark.js
> +var Float32Array = require( '@stdlib/array/float32' );
```suggestion
var Float64Array = require( '@stdlib/array/float64' );
```

2023-03-02 00:46 UTC, kgryte commented on lib/node_modules/@stdlib/blas/base/drotg/benchmark/benchmark.js
> +	out = new Float32Array( 4 );
```suggestion
	out = new Float64Array( 4 );
```

2023-03-02 00:48 UTC, kgryte commented on lib/node_modules/@stdlib/blas/base/drotg/lib/assign.js
> +var pow = require( '@stdlib/math/base/special/pow' );
```suggestion
var abs2 = require( '@stdlib/math/base/special/abs2' );
```

2023-03-02 00:48 UTC, kgryte commented on lib/node_modules/@stdlib/blas/base/drotg/lib/assign.js
> +		r = scale * sqrt( pow( a/scale, 2 ) + pow( b/scale, 2 ) );
```suggestion
		r = scale * sqrt( abs2( a/scale ) + abs2( b/scale ) );
```

2023-03-02 00:51 UTC, kgryte commented on lib/node_modules/@stdlib/blas/base/drotg/test/test.assign.js
> +		}
```suggestion
		for ( j = 0; j < out.length; j++ ) {
			if ( out[j] === expected[i][j] ) {
				t.deepEqual( out, expected[i], 'returns expected value' );
			} else {
				delta = abs( out[j] - expected[i][j] );
				tol = 1.5 * EPS * abs( expected[i][j] );
				t.ok( delta <= tol, 'within tolerance. out: '+out[j]+'. expected: '+expected[i][j]+'. delta: '+delta+'. tol: '+tol+'.' );
			}
		}
```

2023-03-02 00:53 UTC, kgryte commented on lib/node_modules/@stdlib/blas/base/drotg/test/test.assign.js
> +	}
These tests do not work as expected. The `out === expected` comparison is comparing references, not values. These tests and below need to be refactored.

2023-03-02 00:54 UTC, kgryte commented on lib/node_modules/@stdlib/blas/base/drotg/test/test.assign.js
> +	var out;
```suggestion
	var out;
	var e;
```

2023-03-02 00:54 UTC, kgryte commented on lib/node_modules/@stdlib/blas/base/drotg/test/test.assign.js
> +		expected[i] = new Float64Array( expected[i] );
```suggestion
		e = new Float64Array( expected[i] );
```

2023-03-02 00:55 UTC, kgryte commented on lib/node_modules/@stdlib/blas/base/drotg/test/test.assign.js
> +	}
See refactoring above.

2023-03-02 00:55 UTC, kgryte commented on lib/node_modules/@stdlib/blas/base/drotg/test/test.main.js
> +		expected[i] = new Float64Array( expected[i] );
Same comments as `test.assign.js`. These tests need to be refactored.

2023-03-02 00:58 UTC, kgryte requested changes
@Pranavchiku This mostly looks good. The tests need some refactoring.

2023-03-02 05:13 UTC, Pranavchiku commented
Updated tests, all tests pass and benchmarks cleared, this PR can have a final review.

2023-03-02 06:34 UTC, kgryte commented on lib/node_modules/@stdlib/blas/base/drotg/test/test.assign.js
> +	}
```suggestion
```

This appears to be duplicated.

2023-03-02 06:35 UTC, kgryte commented on lib/node_modules/@stdlib/blas/base/drotg/test/test.assign.js
> +	}
Ah. Okay, I see what you are doing here. This is unnecessary. We just need to test whether `actual === out`.

2023-03-02 06:36 UTC, kgryte commented on lib/node_modules/@stdlib/blas/base/drotg/test/test.assign.js
> +	for ( i = 0; i < out.length; i++ ) {
```suggestion
	t.strictEqual( actual, out, 'returns expected value' );
	for ( i = 0; i < out.length; i++ ) {
```

2023-03-02 06:36 UTC, kgryte commented on lib/node_modules/@stdlib/blas/base/drotg/test/test.assign.js
> +	for ( i = 0; i < out.length; i++ ) {
```suggestion
	t.strictEqual( actual, out, 'returns expected value' );
	for ( i = 0; i < out.length; i++ ) {
```

2023-03-02 06:36 UTC, kgryte commented on lib/node_modules/@stdlib/blas/base/drotg/test/test.assign.js
> +	}
```suggestion
```

2023-03-02 06:36 UTC, kgryte commented on lib/node_modules/@stdlib/blas/base/drotg/test/test.assign.js
> +	for ( i = 0; i < out.length; i++ ) {
```suggestion
	t.strictEqual( actual, out, 'returns expected value' );
	for ( i = 0; i < out.length; i++ ) {
```

2023-03-02 06:36 UTC, kgryte commented on lib/node_modules/@stdlib/blas/base/drotg/test/test.assign.js
> +	}
```suggestion
```

2023-03-02 06:37 UTC, kgryte commented on lib/node_modules/@stdlib/blas/base/drotg/test/test.assign.js
> +	for ( i = 0; i < out.length; i++ ) {
```suggestion
	t.strictEqual( actual, out, 'returns expected value' );
	for ( i = 0; i < out.length; i++ ) {
```

2023-03-02 06:37 UTC, kgryte commented on lib/node_modules/@stdlib/blas/base/drotg/test/test.assign.js
> +	}
```suggestion
```

2023-03-02 06:39 UTC, kgryte commented on lib/node_modules/@stdlib/blas/base/drotg/test/test.assign.js
> +tape( 'the function supports providing both stride and offset', function test(t) {
```suggestion
tape( 'the function supports providing both a stride and offset', function test(t) {
```

2023-03-02 06:40 UTC, kgryte approved these changes
LGTM. Thanks, @Pranavchiku!

2023-03-02 07:43 UTC, merged