feat: add Node-API macros for binary functions
stdlib-js/stdlib pull request #969
Opened 2023-03-07 16:27 UTC by steff456

## Description

> What is the purpose of this pull request?

This pull request:

-   Adds the following macros to add support for binary math functions that have any type mixed with an integer,

```
/**
* Invokes a binary function accepting double-precision floating-point number with an integer and returning a double-precision floating-point number.
*/
napi_value stdlib_math_base_napi_di_d( napi_env env, napi_callback_info info, double (*fcn)( double, int ) );

/**
* Invokes a binary function accepting single-precision floating-point number with an integer and returning a single-precision floating-point number.
*/
napi_value stdlib_math_base_napi_fi_f( napi_env env, napi_callback_info info, float (*fcn)( float, int ) );

/**
* Invokes a binary function accepting double-precision complex floating-point number with an integer and returning a double-precision complex floating-point number.
*/
napi_value stdlib_math_base_napi_zi_z( napi_env env, napi_callback_info info, stdlib_complex128_t (*fcn)( stdlib_complex128_t, int ) );

/**
* Invokes a binary function accepting single-precision complex floating-point number with an integer and returning a single-precision complex floating-point number.
*/
napi_value stdlib_math_base_napi_ci_c( napi_env env, napi_callback_info info, stdlib_complex64_t (*fcn)( stdlib_complex64_t, int ) );
```

This is needed for some functions that are part of the complex API refactoring.

## Related Issues

> Does this pull request have any related issues?

- Nope.

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2023-03-07 16:55 UTC, kgryte commented
@steff456 Instead of `int`, we should use the fixed width type `int32_t`.

2023-03-07 16:59 UTC, steff456 commented
I'll update it!

2023-03-09 10:09 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/include/stdlib/math/base/napi/binary.h
> +* Macro for registering a Node-API module exporting an interface invoking a binary function accepting a double-precision floating-point number and an integer, returning a double-precision floating-po
```suggestion
* Macro for registering a Node-API module exporting an interface invoking a binary function accepting a double-precision floating-point number and a signed 32-bit integer and returning a double-precision floating-point number.
```

2023-03-09 10:11 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/include/stdlib/math/base/napi/binary.h
> +* Macro for registering a Node-API module exporting an interface invoking a binary function accepting a single-precision floating-point number with an integer and returning single-precision floating-
```suggestion
* Macro for registering a Node-API module exporting an interface invoking a binary function accepting a single-precision floating-point number and a signed 32-bit integer and returning single-precision floating-point number.
```

2023-03-09 10:11 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/include/stdlib/math/base/napi/binary.h
> +*     return x * y;
```suggestion
* static float mulf( const float x, const int32_t n ) {
*     return x * n;
```

2023-03-09 10:12 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/include/stdlib/math/base/napi/binary.h
> +* Macro for registering a Node-API module exporting an interface invoking a binary function accepting a double-precision complex floating-point number with an integer and returning double-precision c
```suggestion
* Macro for registering a Node-API module exporting an interface invoking a binary function accepting a double-precision complex floating-point number and a signed 32-bit and returning double-precision complex floating-point number.
```

2023-03-09 10:12 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/include/stdlib/math/base/napi/binary.h
> +*     im = xim * y;
```suggestion
* static stdlib_complex128_t mul( const stdlib_complex128_t x, const int32_t n ) {
*     double xre;
*     double xim;
*     double re;
*     double im;
*
*     stdlib_reim( x, &xre, &xim );
*
*     re = xre * n;
*     im = xim * n;
```

2023-03-09 10:13 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/include/stdlib/math/base/napi/binary.h
> +* }
```suggestion
* static stdlib_complex128_t mul( const stdlib_complex128_t x, const int32_t n ) {
*     double re;
*     double im;
*
*     stdlib_reim( x, &re, &im );
*     return stdlib_complex128( re*n, im*n );
* }
```

2023-03-09 10:14 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/include/stdlib/math/base/napi/binary.h
> +* Macro for registering a Node-API module exporting an interface invoking a binary function accepting a single-precision complex floating-point number with an integer and returning single-precision c
```suggestion
* Macro for registering a Node-API module exporting an interface invoking a binary function accepting a single-precision complex floating-point number and a signed 32-bit integer and returning single-precision complex floating-point number.
```

2023-03-09 10:14 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/include/stdlib/math/base/napi/binary.h
> +*     return stdlib_complex64( re, im );
```suggestion
* static stdlib_complex64_t add( const stdlib_complex64_t x, const int32_t n ) {
*     float re;
*     float im;
*
*     stdlib_reimf( x, &re, &im );
*     return stdlib_complex64( re*n, im*n );
```

2023-03-09 10:15 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/include/stdlib/math/base/napi/binary.h
> +* Invokes a binary function accepting double-precision floating-point number with an integer and returning a double-precision floating-point number.
```suggestion
* Invokes a binary function accepting a double-precision floating-point number and a signed 32-bit integer and returning a double-precision floating-point number.
```

2023-03-09 10:15 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/include/stdlib/math/base/napi/binary.h
> +* Invokes a binary function accepting single-precision floating-point number with an integer and returning a single-precision floating-point number.
```suggestion
* Invokes a binary function accepting a single-precision floating-point number and a signed 32-bit integer and returning a single-precision floating-point number.
```

2023-03-09 10:16 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/include/stdlib/math/base/napi/binary.h
> +* Invokes a binary function accepting double-precision complex floating-point number with an integer and returning a double-precision complex floating-point number.
```suggestion
* Invokes a binary function accepting a double-precision complex floating-point number and a signed 32-bit integer and returning a double-precision complex floating-point number.
```

2023-03-09 10:16 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/include/stdlib/math/base/napi/binary.h
> +* Invokes a binary function accepting single-precision complex floating-point number with an integer and returning a single-precision complex floating-point number.
```suggestion
* Invokes a binary function accepting a single-precision complex floating-point number and a signed 32-bit integer and returning a single-precision complex floating-point number.
```

2023-03-09 10:17 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/include/stdlib/math/base/napi/binary.h
> +* static double mul( const double x, const int32_t n ) {
```suggestion
* #include <stdint.h>
*
* static double mul( const double x, const int32_t n ) {
```

2023-03-09 10:17 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/include/stdlib/math/base/napi/binary.h
> +* static float mulf( const float x, const int32_t y ) {
```suggestion
* #include <stdint.h>
*
* static float mulf( const float x, const int32_t y ) {
```

2023-03-09 10:17 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/include/stdlib/math/base/napi/binary.h
> +* static float mulf( const float x, const int32_t y ) {
```suggestion
* #include <stdint.h>
*
* static float mulf( const float x, const int32_t y ) {
```

2023-03-09 10:18 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/include/stdlib/math/base/napi/binary.h
> +*
```suggestion
* #include <stdint.h>
*
```

2023-03-09 10:19 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/include/stdlib/math/base/napi/binary.h
> +*
```suggestion
* #include <stdint.h>
*
```

2023-03-09 10:19 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/src/main.c
> +* Invokes a binary function accepting a double-precision floating-point number with an integer and returning double-precision floating-point number.
```suggestion
* Invokes a binary function accepting a double-precision floating-point number and a signed 32-bit integer and returning double-precision floating-point number.
```

2023-03-09 10:20 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/src/main.c
> +	status = napi_get_value_int( env, argv[ 1 ], &y );
```suggestion
	status = napi_get_value_int32( env, argv[ 1 ], &y );
```

2023-03-09 10:20 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/src/main.c
> +* Invokes a binary function accepting a single-precision floating-point numbers with an integer and returning single-precision floating-point number.
```suggestion
* Invokes a binary function accepting a single-precision floating-point number and a signed 32-bit integer and returning single-precision floating-point number.
```

2023-03-09 10:21 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/src/main.c
> +	status = napi_get_value_int( env, argv[ 1 ], &y );
```suggestion
	status = napi_get_value_int32( env, argv[ 1 ], &y );
```

2023-03-09 10:21 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/src/main.c
> +* Invokes a binary function accepting a double-precision complex floating-point number with an integer and returning double-precision complex floating-point number.
```suggestion
* Invokes a binary function accepting a double-precision complex floating-point number and a signed 32-bit integer and returning double-precision complex floating-point number.
```

2023-03-09 10:21 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/src/main.c
> +	status = napi_get_value_int( env, argv[ 1 ], &y );
```suggestion
	status = napi_get_value_int32( env, argv[ 1 ], &y );
```

2023-03-09 10:22 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/src/main.c
> +* Invokes a binary function accepting a single-precision complex floating-point number with an integer and returning single-precision complex floating-point number.
```suggestion
* Invokes a binary function accepting a single-precision complex floating-point number and a signed 32-bit integer and returning single-precision complex floating-point number.
```

2023-03-09 10:22 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/src/main.c
> +	status = napi_get_value_int( env, argv[ 1 ], &y );
```suggestion
	status = napi_get_value_int32( env, argv[ 1 ], &y );
```

2023-03-09 10:22 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/src/main.c
> +	status = napi_get_value_int( env, argv[ 1 ], &y );
See <https://nodejs.org/api/n-api.html#napi_get_value_int32>.

2023-03-09 10:24 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/include/stdlib/math/base/napi/binary.h
> +* Macro for registering a Node-API module exporting an interface invoking a binary function accepting a single-precision floating-point number and a signed 32-bit integer and returning single-precisi
```suggestion
* Macro for registering a Node-API module exporting an interface invoking a binary function accepting a single-precision floating-point number and a signed 32-bit integer and returning a single-precision floating-point number.
```

2023-03-09 10:25 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/include/stdlib/math/base/napi/binary.h
> +* STDLIB_MATH_BASE_NAPI_MODULE_FI_F( addf );
```suggestion
* STDLIB_MATH_BASE_NAPI_MODULE_FI_F( mulf );
```

2023-03-09 10:25 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/include/stdlib/math/base/napi/binary.h
> +* STDLIB_MATH_BASE_NAPI_MODULE_DI_D( add );
```suggestion
* STDLIB_MATH_BASE_NAPI_MODULE_DI_D( mul );
```

2023-03-09 10:25 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/include/stdlib/math/base/napi/binary.h
> +* Macro for registering a Node-API module exporting an interface invoking a binary function accepting a double-precision complex floating-point number and a signed 32-bit and returning double-precisi
```suggestion
* Macro for registering a Node-API module exporting an interface invoking a binary function accepting a double-precision complex floating-point number and a signed 32-bit and returning a double-precision complex floating-point number.
```

2023-03-09 10:25 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/include/stdlib/math/base/napi/binary.h
> +* STDLIB_MATH_BASE_NAPI_MODULE_ZI_Z( add );
```suggestion
* STDLIB_MATH_BASE_NAPI_MODULE_ZI_Z( mul );
```

2023-03-09 10:26 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/include/stdlib/math/base/napi/binary.h
> +* Macro for registering a Node-API module exporting an interface invoking a binary function accepting a single-precision complex floating-point number and a signed 32-bit integer and returning single
```suggestion
* Macro for registering a Node-API module exporting an interface invoking a binary function accepting a single-precision complex floating-point number and a signed 32-bit integer and returning a single-precision complex floating-point number.
```

2023-03-09 10:26 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/include/stdlib/math/base/napi/binary.h
> +* STDLIB_MATH_BASE_NAPI_MODULE_CI_C( add );
```suggestion
* STDLIB_MATH_BASE_NAPI_MODULE_CI_C( mul );
```

2023-03-09 10:26 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/include/stdlib/math/base/napi/binary.h
> +* static stdlib_complex64_t add( const stdlib_complex64_t x, const int32_t n ) {
```suggestion
* static stdlib_complex64_t mul( const stdlib_complex64_t x, const int32_t n ) {
```

2023-03-09 10:27 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/src/main.c
> +* Invokes a binary function accepting a double-precision floating-point number and a signed 32-bit integer and returning double-precision floating-point number.
```suggestion
* Invokes a binary function accepting a double-precision floating-point number and a signed 32-bit integer and returning a double-precision floating-point number.
```

2023-03-09 10:27 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/src/main.c
> +* Invokes a binary function accepting a single-precision floating-point number and a signed 32-bit integer and returning single-precision floating-point number.
```suggestion
* Invokes a binary function accepting a single-precision floating-point number and a signed 32-bit integer and returning a single-precision floating-point number.
```

2023-03-09 10:27 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/src/main.c
> +* Invokes a binary function accepting a double-precision complex floating-point number and a signed 32-bit integer and returning double-precision complex floating-point number.
```suggestion
* Invokes a binary function accepting a double-precision complex floating-point number and a signed 32-bit integer and returning a double-precision complex floating-point number.
```

2023-03-09 10:28 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/src/main.c
> +* Invokes a binary function accepting a single-precision complex floating-point number and a signed 32-bit integer and returning single-precision complex floating-point number.
```suggestion
* Invokes a binary function accepting a single-precision complex floating-point number and a signed 32-bit integer and returning a single-precision complex floating-point number.
```

2023-03-09 10:32 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/src/main.c
> +		status = napi_throw_error( env, NULL, "invalid invocation. Must provide two complex numbers." );
```suggestion
		status = napi_throw_error( env, NULL, "invalid invocation. Must provide two arguments." );
```

2023-03-09 10:32 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/src/main.c
> +		status = napi_throw_error( env, NULL, "invalid invocation. Must provide two numbers." );
```suggestion
		status = napi_throw_error( env, NULL, "invalid invocation. Must provide two arguments." );
```

2023-03-09 10:35 UTC, kgryte requested changes
Looking good thus far. @steff456 would you mind documenting the macros and functions in the README, alongside the other public APIs? See <https://github.com/stdlib-js/stdlib/blob/16fb143aba60e6e1f8ed9370226d169fdb3256c0/lib/node_modules/@stdlib/math/base/napi/binary/README.md#c-apis>.

2023-03-21 21:49 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/README.md
> +#include <node_api.h>
```suggestion
#include <node_api.h>
#include <stdint.h>
```

2023-03-21 21:49 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/README.md
> +#include <node_api.h>
```suggestion
#include <node_api.h>
#include <stdint.h>
```

2023-03-21 21:50 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/README.md
> +#include <node_api.h>
```suggestion
#include <node_api.h>
#include <stdint.h>
```

2023-03-21 21:50 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/README.md
> +#include <node_api.h>
```suggestion
#include <node_api.h>
#include <stdint.h>
```

2023-03-21 21:50 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/README.md
> +#include "stdlib/complex/reim.h"
```suggestion
#include "stdlib/complex/reimf.h"
```

2023-03-21 21:51 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/README.md
> +static double mul( const double x, const int32_t y ) {
```suggestion
#include <stdint.h>

static double mul( const double x, const int32_t y ) {
```

2023-03-21 21:51 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/README.md
> +static float mulf( const float x, const int32_t y ) {
```suggestion
#include <stdint.h>

static float mulf( const float x, const int32_t y ) {
```

2023-03-21 21:51 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/README.md
> +#include "stdlib/complex/reim.h"
```suggestion
#include "stdlib/complex/reim.h"
#include <stdint.h>
```

2023-03-21 21:52 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/README.md
> +#include "stdlib/complex/reimf.h"
```suggestion
#include "stdlib/complex/reimf.h"
#include <stdint.h>
```

2023-03-21 21:56 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/napi/binary/README.md
> +STDLIB_MATH_BASE_NAPI_MODULE_FF_F( mulf );
```suggestion
STDLIB_MATH_BASE_NAPI_MODULE_FI_F( mulf );
```

2023-03-21 21:58 UTC, kgryte approved these changes
LGTM. Thanks, @steff456!

2023-03-21 22:09 UTC, merged