feat: add native addon to `ceiln` and `cceiln`
stdlib-js/stdlib pull request #988
Opened 2023-03-29 15:47 UTC by steff456

Part of https://github.com/stdlib-js/todo/issues/1454

## Description

> What is the purpose of this pull request?

This pull request:

For `ceiln` API:

-   Adds C implementation
-   Adds native addon with benchmark, tests, examples and readme update

For `cceiln` API:

-   Removes out keyword
-   Adds support for Complex128 dtype
-   Adds C implementation
-   Adds native addon with benchmark, tests, examples and readme update

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   Part of https://github.com/stdlib-js/todo/issues/1454

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

2023-08-25 19:47 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cceiln/README.md
> +> Round a double-precision complex floating-point number to the nearest multiple of `10^n` toward positive infinity.
Round each component of a...

2023-08-25 19:47 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cceiln/README.md
> +> Round a double-precision complex floating-point number to the nearest multiple of `10^n` toward positive infinity.
Here and elsewhere throughout `cceiln`.

2023-08-25 19:48 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cceiln/README.md
>      var x = 0.2 + 0.1;
```suggestion

    var x = 0.2 + 0.1;
```

2023-08-25 19:49 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cceiln/README.md
> +var rand = uniform( -50.0, 50.0 );
I'd update similar to `croundn` where we use two separate PRNGs.

2023-08-25 19:50 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cceiln/benchmark/benchmark.native.js
> +	if ( isnan( real( y ) ) ) {
```suggestion
	if ( isnan( imag( y ) ) ) {
```

Need to import the package above.

2023-08-25 19:50 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cceiln/benchmark/c/benchmark.c
> +#include "stdlib/math/base/special/ceiln.h"
```suggestion
#include "stdlib/math/base/special/cceiln.h"
```

2023-08-25 19:52 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cceiln/docs/types/test.ts
> +// The function returns a double-precision complex floating-point number
```suggestion
// The function returns a double-precision complex floating-point number...
```

2023-08-25 19:54 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cceiln/examples/index.js
> +var rand = uniform( -50.0, 50.0 );
Updates as in README.

2023-08-25 19:55 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cceiln/examples/index.js
> +	n = ceil( rand()*5.0 );
Instead of using `ceil`, use the `discrete-uniform` PRNG.

2023-08-25 19:56 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cceiln/lib/main.js
> +* @returns {Complex128} output array
```suggestion
* @returns {Complex128} result
```

2023-08-25 19:56 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cceiln/lib/main.js
> +* var cceiln = require( '@stdlib/math/base/special/cceiln' );
```suggestion
```

2023-08-25 19:57 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cceiln/manifest.json
> +}
```suggestion
}

```

2023-08-25 19:58 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cceiln/test/test.js
> +	t.deepEqual( cceiln( new Complex128( -PI, PI ), -2 ), new Complex128( -3.14, 3.15 ), 'returns expected value' );
We need to compare the real and imag components separately. Deep equal won't work as you expect it here.

2023-08-25 19:59 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cceiln/test/test.native.js
> +	t.deepEqual( cceiln( new Complex128( -PI, PI ), -2 ), new Complex128( -3.14, 3.15 ), 'returns expected value' );
Same as other test file

2023-09-08 07:31 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cceiln/README.md
> +var rand = uniform( -50.0, 50.0 );
```suggestion
var rand1 = uniform( -50.0, 50.0 );
```

2023-09-08 07:32 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cceiln/README.md
> +var randn = discreteUniform( -5.0, 0.0 );
```suggestion
var rand2 = discreteUniform( -5.0, 0.0 );
```

2023-09-08 07:32 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cceiln/README.md
> +    n = randn();
```suggestion
    n = rand2();
```

2023-09-08 07:32 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cceiln/README.md
> +    z = new Complex128( rand(), rand() );
```suggestion
    z = new Complex128( rand1(), rand1() );
```

2023-09-08 07:33 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cceiln/README.md
> +var randn = discreteUniform( -5.0, 0.0 );
`randn` is a commonly used alias for a PRNG generating normally distributed numbers.

2023-09-08 07:36 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cceiln/benchmark/c/benchmark.c
> +		printf( "# c::native::%s\n", NAME );
```suggestion
		printf( "# c::%s\n", NAME );
```

"native" is reserved for a native stdlib implementation, not an implementation based on C99.

2023-09-08 07:38 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cceiln/docs/types/index.d.ts
> +import { Complex128 } from '@stdlib/types/object';
```suggestion
import { Complex128 } from '@stdlib/types/complex';
```

This typedef has moved.

2023-09-08 07:40 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cceiln/examples/index.js
> +var rand = uniform( -50.0, 50.0 );
```suggestion
var rand1 = uniform( -50.0, 50.0 );
```

2023-09-08 07:40 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cceiln/examples/index.js
> +var randn = discreteUniform( -5.0, 0.0 );
```suggestion
var rand2 = discreteUniform( -5.0, 0.0 );
```

2023-09-08 07:40 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cceiln/examples/index.js
> +	n = randn();
```suggestion
	n = rand2();
```

2023-09-08 07:40 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cceiln/examples/index.js
> +	z = new Complex128( rand(), rand() );
```suggestion
	z = new Complex128( rand1(), rand1() );
```

2023-09-08 07:42 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cceiln/lib/main.js
> +	return new Complex128(ceiln( real( z ), n ), ceiln( imag( z ), n ) );
```suggestion
	return new Complex128( ceiln( real( z ), n ), ceiln( imag( z ), n ) );
```

2023-09-08 07:43 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cceiln/lib/native.js
> +* Rounds each component of a double-precision complex floating-point number toward positive infinity.
```suggestion
* Rounds each component of a double-precision complex floating-point number to the nearest multiple of `10^n` toward positive infinity.
```

2023-09-08 07:44 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cceiln/src/main.c
> +* Rounds each component of a double-precision complex floating-point number toward positive infinity.
```suggestion
* Rounds each component of a double-precision complex floating-point number to the nearest multiple of `10^n` toward positive infinity.
```

2023-09-08 07:46 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cceiln/test/test.js
> +		t.strictEqual( imag( v ), x, 'returns components when provided re='+x+', im='+x+', n='+n+'.' );
```suggestion
		t.strictEqual( real( v ), x, 'returns expected value when provided re='+x+', im='+x+', n='+n+'.' );
		t.strictEqual( imag( v ), x, 'returns expected value when provided re='+x+', im='+x+', n='+n+'.' );
```

2023-09-08 07:46 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cceiln/test/test.js
> +		t.strictEqual( imag( v ), x, 'returns components when provided re='+x+', im='+x+', n='+n+'.' );
```suggestion
		t.strictEqual( real( v ), x, 'returns expected value when provided re='+x+', im='+x+', n='+n+'.' );
		t.strictEqual( imag( v ), x, 'returns expected value when provided re='+x+', im='+x+', n='+n+'.' );
```

2023-09-08 07:47 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cceiln/test/test.js
> +		t.strictEqual( imag( v ), PINF, 'returns components when provided re='+x+', im='+x+', n='+n+'.' );
```suggestion
		t.strictEqual( real( v ), PINF, 'returns expected value when provided re='+x+', im='+x+', n='+n+'.' );
		t.strictEqual( imag( v ), PINF, 'returns expected value when provided re='+x+', im='+x+', n='+n+'.' );
```

2023-09-08 07:48 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cceiln/test/test.native.js
> +		t.strictEqual( imag( v ), x, 'returns components when provided re='+x+', im='+x+', n='+n+'.' );
```suggestion
		t.strictEqual( real( v ), x, 'returns expected value when provided re='+x+', im='+x+', n='+n+'.' );
		t.strictEqual( imag( v ), x, 'returns expected value when provided re='+x+', im='+x+', n='+n+'.' );
```

2023-09-08 07:48 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cceiln/test/test.native.js
> +		t.strictEqual( imag( v ), x, 'returns components when provided re='+x+', im='+x+', n='+n+'.' );
```suggestion
		t.strictEqual( real( v ), x, 'returns expected value when provided re='+x+', im='+x+', n='+n+'.' );
		t.strictEqual( imag( v ), x, 'returns expected value when provided re='+x+', im='+x+', n='+n+'.' );
```

2023-09-08 07:49 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/cceiln/test/test.native.js
> +		t.strictEqual( imag( v ), PINF, 'returns components when provided re='+x+', im='+x+', n='+n+'.' );
```suggestion
		t.strictEqual( real( v ), PINF, 'returns expected value when provided re='+x+', im='+x+', n='+n+'.' );
		t.strictEqual( imag( v ), PINF, 'returns expected value when provided re='+x+', im='+x+', n='+n+'.' );
```

2023-09-08 07:50 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/ceiln/README.md
> +Rounds a `numeric` value to the nearest multiple of `10^n` toward positive infinity.
```suggestion
Rounds a double-precision floating-point number to the nearest multiple of `10^n` toward positive infinity.
```

2023-09-08 07:50 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/ceiln/README.md
> +double stdlib_base_ceiln( const double x, const double n );
```suggestion
double stdlib_base_ceiln( const double x, const int32_t n );
```

2023-09-08 07:51 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/ceiln/README.md
> +        y = stdlib_base_ceiln( x[ i ], 0 );
This example is not super illustrative, as `ceiln` behaves like `ceil` when `n = 0`.

2023-09-08 07:51 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/ceiln/README.md
> +    double x[] = { 3.14, -3.14, 0.0, 0.0/0.0 };
```suggestion
    const double x[] = { 3.14, -3.14, 0.0, 0.0/0.0 };
```

2023-09-08 07:52 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/ceiln/README.md
> +        printf( "ceiln(%lf, 0) = %lf\n", x[ i ], y );
This will need to be updated should `n` be changed to a different value.

2023-09-08 07:53 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/ceiln/benchmark/benchmark.native.js
> +		y = ceiln( x, 0 );
```suggestion
		y = ceiln( x, -2 );
```

This should match the other `benchmark.js` file in order to compare apples to apples.

2023-09-08 07:54 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/ceiln/benchmark/benchmark.native.js
> +		x = ( randu()*1000.0 ) - 500.0;
```suggestion
		x = ( randu()*1.0e7 ) - 5.0e6;
```

The value range should match the vanilla `benchmark.js`.

2023-09-08 07:55 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/ceiln/benchmark/c/native/benchmark.c
> +		y = stdlib_base_ceiln( x, 0 );
```suggestion
		y = stdlib_base_ceiln( x, -2 );
```

2023-09-08 07:55 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/ceiln/examples/c/example.c
> +	double x[] = { 3.14, -3.14, 0.0, 0.0/0.0 };
```suggestion
	const double x[] = { 3.14, -3.14, 0.0, 0.0/0.0 };
```

2023-09-08 07:56 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/ceiln/examples/c/example.c
> +		printf( "ceiln(%lf) = %lf\n", x[ i ], y );
```suggestion
		y = stdlib_base_ceiln( x[ i ], -2 );
		printf( "ceiln(%lf, -2) = %lf\n", x[ i ], y );
```

2023-09-08 07:56 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/ceiln/README.md
> +        y = stdlib_base_ceiln( x[ i ], 0 );
```suggestion
        y = stdlib_base_ceiln( x[ i ], -2 );
```

2023-09-08 07:56 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/ceiln/README.md
> +        printf( "ceiln(%lf, 0) = %lf\n", x[ i ], y );
```suggestion
        printf( "ceiln(%lf, -2) = %lf\n", x[ i ], y );
```

2023-09-08 07:57 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/ceiln/include/stdlib/math/base/special/ceiln.h
> +* Rounds a numeric value to the nearest multiple of \\(10^n\\) toward positive infinity.
```suggestion
* Rounds a double-precision floating-point number to the nearest multiple of \\(10^n\\) toward positive infinity.
```

2023-09-08 07:58 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/ceiln/lib/native.js
> +* Rounds a numeric value to the nearest multiple of \\(10^n\\) toward positive infinity.
```suggestion
* Rounds a double-precision floating-point number to the nearest multiple of \\(10^n\\) toward positive infinity.
```

2023-09-08 07:58 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/ceiln/manifest.json
> +}
```suggestion
}

```

2023-09-08 07:59 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/ceiln/src/ceiln.c
> +* Rounds a numeric value to the nearest multiple of \\(10^n\\) toward positive infinity.
```suggestion
* Rounds a double-precision floating-point number to the nearest multiple of \\(10^n\\) toward positive infinity.
```

2023-09-08 07:59 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/ceiln/src/ceiln.c
> +    double s;
Need to convert spaces to TABS.

2023-09-08 08:00 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/ceiln/src/ceiln.c
> +        return NAN;
```suggestion
        return x;
```

2023-09-08 08:00 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/ceiln/src/ceiln.c
> +        return x;
```suggestion
        ( stdlib_base_abs( x ) > STDLIB_CONSTANT_FLOAT64_MAX && n <= 0 ) ) {
        return x;
```

2023-09-08 08:02 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/ceiln/src/ceiln.c
> +        if ( isinf( y ) ) {
Use `@stdlib/math/base/assert/is-infinite` here and below.

2023-09-08 08:02 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/ceiln/src/ceiln.c
> +        return INFINITY;
Use stdlib constant `PINF`.

2023-09-08 08:03 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/ceiln/src/ceiln.c
> +        return ( ceil( y ) / HUGE ) / s;
What do we use for `HUGE` in JavaScript?

2023-09-08 08:07 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/ceiln/README.md
> +-   **n**: `[in] double` integer power of 10.
```suggestion
-   **n**: `[in] int32_t` integer power of 10.
```

2023-09-08 08:10 UTC, kgryte requested changes
Thanks, @steff456. Looks like we need to clean-up the C implementation a touch. Once that is finished, should be ready to merge.

2023-09-08 08:12 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/ceiln/src/ceiln.c
> +        return ( ceil( y ) / HUGE ) / s;
Rather than use C `HUGE`, we should use a static variable in the parent scope, similar to the JavaScript implementation.

2023-09-08 08:14 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/ceiln/src/ceiln.c
> +        ( stdlib_base_abs( x ) > STDLIB_CONSTANT_FLOAT64_MAX && n <= 0 ) ){
This the wrong constant. We want the max safe integer, not the max value.

2023-09-08 08:15 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/ceiln/src/ceiln.c
> +        n < STDLIB_CONSTANT_FLOAT64_MIN_BASE10_EXPONENT ||
Why are we using this constant? In the JS implementation, we use the min subnormal constant?

2023-09-08 08:15 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/ceiln/src/ceiln.c
> +    if ( isnan( x ) ){
Use stdlib function.

2023-09-08 08:15 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/ceiln/src/ceiln.c
> +        isinf( x ) ||
Use stdlib function.

2023-09-08 08:17 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/ceiln/src/ceiln.c
> +    if ( n < STDLIB_CONSTANT_FLOAT64_MAX_BASE10_EXPONENT ) {
This is the wrong constant. Did you test this implementation? This does not appear to be a good port.

2023-09-18 16:44 UTC, steff456 commented on lib/node_modules/@stdlib/math/base/special/ceiln/src/ceiln.c
> +    if ( n < STDLIB_CONSTANT_FLOAT64_MAX_BASE10_EXPONENT ) {
I see it is the wrong constant, but I did test it both locally and in the CI and all the tests where passing 🤨

2023-09-21 20:16 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/ceiln/src/ceiln.c
> +    double s;
@steff456 Looks like this file stills needs to be converted to use TAB indentation.

2023-09-21 20:20 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/ceiln/src/ceiln.c
> +        return ( ceil( y ) / HUGE ) / s;
@steff456 I believe `HUGE` still needs to be defined in the parent scope.

2023-09-21 20:20 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/ceiln/src/ceiln.c
>  	return ceil( y ) / s;
This should be `stdlib_base_ceil`, correct?

2023-09-21 20:21 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/ceiln/src/ceiln.c
>          return ( ceil( y ) / HUGE ) / s;
Same thing. This should be `stdlib_base_ceil`, correct?

2023-09-21 20:21 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/ceiln/src/ceiln.c
>      }
Rather than `INFINITY`, this should be `STDLIB_CONSTANT_FLOAT64_PINF`.

2023-09-21 20:23 UTC, kgryte requested changes
@steff456 Looks like we still need to make some changes in the C implementation. Left comments. This should all be straightforward. Once addressed, I think this should be ready to merge.

2023-09-23 05:01 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/ceiln/src/ceiln.c
> +#include "stdlib/constants/float64/max.h"
```suggestion
```

2023-09-23 05:02 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/ceiln/manifest.json
> +        "@stdlib/constants/float64/max",
```suggestion
```

2023-09-23 05:02 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/ceiln/manifest.json
> +        "@stdlib/constants/float64/max",
```suggestion
```

2023-09-23 05:03 UTC, kgryte commented on lib/node_modules/@stdlib/math/base/special/ceiln/manifest.json
> +        "@stdlib/constants/float64/max",
```suggestion
```

2023-09-23 05:04 UTC, kgryte approved these changes
LGTM. Will merge once CI passes.

2023-09-23 19:17 UTC, merged